### ISSUE TITLE
adding source packages to a solution isn't always reflected in  solution explorer

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#1]
I created a web starter application, and added some source packages using global.json, adding the sources directories and rebuilding.
If I look to the icons in the solution explorer to understand if the source or nuget package I seen this:

first I added **mvc**, rebuilt it, checked in solution explorer, and all looks fine.
second I added **entity framework**, rebuilt it, checked in solution explorer, and all looks fine
after this I added **Identity**,rebuilt it, checked in solution explorer, and found that in the web starter app the **EntityFramework.SqlServer** the sources packages icon is shown, but in the project **Microsoft.AspNet.Identity.EntityFramework** is nuget package icon of EntityFramework.SqlServer is shown.
After this I added the Microsoft.Framework.DependencyInjection package: the project is loaded in the solution, but in all the projects in the solution with the above packages looks like the nuget version is used.

Since this way the projects are not really added to the solution I tried again adding the projects directly, removing them when vs added automatically, and the result is the same.

I tried to run the kpm list from the project directory and seems fine: I find a reference for the version 0.0.0 of the package and is used in all the projects.

I'm using ctp 6 and main feed

**Comment by PradeepKadubandi** [comment]
can you may be share a screen shot of your solution explorer?

It looks like you are referencing a package which references another package and you are expecting that to be a project reference since you have it in solution - did I get that right?

I am not sure if that works ... if you add a reference to "Microsoft.Framework.DependencyInjection" in your project.json directly, it will be treated as a project reference when that project is in the solution (to be precise, when that project is in kre search paths for projects) ...

However when your top level dependency is a package, all it's references would be packages ...

If you make the direct dependency a project reference (by pulling in sources for that project from github) then and when your indirect reference is also in solution, it would be treated as a project reference...

Does that answer your question?

**Comment by lucamorelli** [comment]
![untitled](https://cloud.githubusercontent.com/assets/127777/6509810/1d165a0c-c362-11e4-9979-3d2d6b97f826.png)

Step 1: I added mvc, ef and identity. In the top of the image you can see the references of the web starter app, and here EntityFramework.SqlServer is shown as source package. In the bottom the reference in Microsoft.AspNet.Identity.EntityFramework is shown as nuget package.

the source are the clone of the tag beta 3 from the repos.

**Comment by davidfowl** [comment]
That's because each repository has their own global.json and their own locations for getting sources.

**Comment by lucamorelli** [comment]
![untitled](https://cloud.githubusercontent.com/assets/127777/6509968/354c69bc-c363-11e4-95b2-3f64ef1a4f79.png)
Step 2: this happens if I add the dependency injection repository: I have an error but the application runs

**Comment by davidfowl** [comment]
That's because each repository has their own `global.json` and their own locations for getting sources. To get sources all the way down you'd need to tweak the `global.json` each repository you pull in. There still work to be done here as it's not a great experience. 

You can follow this bug

**Comment by lucamorelli** [comment]
In the global.json I have this:
{
    "sources": [ "src", "test", "c:/beta 3/mvc/src", "c:/beta 3/entityframework/src", "c:/beta 3/identity/src", "c:/beta 3/dependencyinjection/src" ],
    "sdk": {
        "version": "1.0.0-beta3"
    }
}
I suppose that global.json is not included in the sources

**Comment by davidfowl** [comment]
I'm trying to figure out which bug you're getting at. It seems like there's several bugs you're calling out all at once and I'd prefer if I we could identify one thing or several things and file separate bugs.

**Comment by lucamorelli** [comment]
If you need I can give you acces to the vm with the repro. you can ask to sayed hashimi

**Comment by davidfowl** [comment]
I don't need access to any VM. We're aware of several issues, I just want to pin point them here instead of calling them all out at once.

**Comment by sayedihashimi** [comment]
This doesn't work now, we may revisit later.
