### ISSUE TITLE
Defining Multiple Startup Projects doesn't work

### ISSUE THREAD

**Issue by avanderhoorn** [aspnet/Tooling#10]
When I try and run multiple startup projects I get various errors occurring and none of the projects start. To get around this, I have to start each project individual first and then I can run multiple startup projects. This is really annoying when trying to work with client/agent - server scenarios, etc.

**Comment by davidfowl** [comment]
What exception do you get?

**Comment by tommck** [comment]
It works for me right after I've done it.  But, when I reload the Solution, the F5 and Ctrl-F5 will do nothing until I change it to a single project and then switch it back to multiple projects.  Then it works again

**Comment by tommck** [comment]
In the scenario I mention above, the Debug->Start Debugging and Debug->Start Without Debugging menu items actually get disabled.  It's kinda strange

**Comment by BillHiebert** [comment]
I opened a tooling bug to investigate.

**Comment by tommck** [comment]
Great, thanks!

**Comment by avanderhoorn** [comment]
Thanks!

**Comment by sayedihashimi** [comment]
Fixed in Visual Studio 2015 RC
