### ISSUE TITLE
project.json Should Support Full NuGet Metadata

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Tooling#100]
The output of an ASP.NET 5 Class Library Project is a Nuget Package (.nupkg). My project.json file is shown below:

    {
      "version": "1.0.0-*",
      "description": "Provides boilerplate framework code for an ASP.NET MVC project. ASP.NET MVC Boilerplate is a professional template for building secure, fast, robust and adaptable web applications or sites. It provides the minimum amount of code required on top of the default MVC template provided by Microsoft. You can download the ASP.NET MVC Boilerplate project template on the Visual Studio Gallery or download the code on GitHub.",
      "authors": [ "Muhammad Rehan Saeed" ],
      "tags": [ "ASP.NET MVC MVC6 Boilerplate Muhammad Rehan Saeed Framework" ],
      "projectUrl": "https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate",
      "licenseUrl": "https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate/blob/master/LICENSE"
      ...omitted
    }

There does not seem to be properties for the Title, Icon URL, Summary or Release Notes, Copyright or Language. Can these also be added?

**Comment by davidfowl** [comment]
It already does, we may not have updated the schema files.

**Comment by RehanSaeed** [comment]
Excellent! I presume the schema will get updated at RTM.

**Comment by sayedihashimi** [comment]
@davidfowl who owns updating the schema files? I'd like to assign this item.

**Comment by RehanSaeed** [comment]
The schema seems to have been updated with a few more properties. The Release Notes and Language have still not been added.

**Comment by davidfowl** [comment]
The project.json files have been updated since then
