### ISSUE TITLE
VS 2017 RC - Solution Explorer cuts off Publish window

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/Tooling#1000]
From @scottaddie at https://github.com/dotnet/roslyn-project-system/issues/1592

Create a new ASP.NET Core project targeting .NET Core, using the Web Application project template. Right-click the project in Solution Explorer, and select **Publish**. Notice the empty black area to the left of Solution Explorer that cuts off the Publish window's Folder icon/option (outlined in red below).

![image](https://cloud.githubusercontent.com/assets/1414993/23104632/84d97e22-f686-11e6-8e60-041640c8cc67.png)

I'm using VS 2017 RC on Windows 10 (v1607) with a display resolution of 3,200 x 1,800. Dragging the Solution Explorer splitter further to the left indicates that the aforementioned empty black area is attached to the Solution Explorer window.

@morrisjoe

**Comment by mlorbetske** [comment]
TFS Bug#386659

**Comment by mlorbetske** [comment]
@scottaddie could you share what your current DPI/scaling setting is? On Windows 10, you can get the current value from right clicking on the desktop and choosing display settings - the value will be listed above the top slider in the value of "Change the size of text, apps, and other items: xxx%"

**Comment by scottaddie** [comment]
250%

**Comment by scottaddie** [comment]
@mlorbetske I've confirmed that this is also an issue on my Windows 7 work machine with the same build installed. The screen resolution there is 1,920 x 1,200.

**Comment by bzhu94** [comment]
This has been fixed with changeset #1648442

**Comment by bzhu94** [comment]
Fixed with changeset #1648442

**Comment by scottaddie** [comment]
@bzhu94 @mlorbetske Out of curiosity, will this be included in the RTM build for March 7th?

**Comment by AraHaan** [comment]
out of curiosity will the RTM build on March 7th include full C++ 17?

**Comment by bzhu94** [comment]
@scottaddie Unfortunately, this fix will not be included in the RTM build.

**Comment by sayedihashimi** [comment]
@arahaan we don't have the right set of people in this repository to answer your question. I can help route your question by email at sayedha@microsoft.com if you like.

**Comment by mlorbetske** [comment]
@scottaddie this change fixing this will now be included in the RTW release
