### ISSUE TITLE
Why user individual account option is disabled on asp.net core web api and VS2017 RC4?

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/Tooling#1005]
![image](https://cloud.githubusercontent.com/assets/1798510/23339480/abb90b5a-fc23-11e6-93eb-d0db310acf5a.png)

**Comment by mlorbetske** [comment]
Hi @MaherJendoubi, this hasn't been enabled as there'd be some odd experiences around it with the way this works today (there'd have to be a signup experience or the backing database would have to come from another project, etc.). We've been talking through what this should look like for a while & have an idea of what this will look like and have a plan to do something similar in an upcoming release of Visual Studio 2017.

**Comment by MaherJendoubi** [comment]
@mlorbetske Have you an idea if it will be fixed in the RTM release next week?

**Comment by mlorbetske** [comment]
@MaherJendoubi this won't be in the RTM release, but in an update that follows

**Comment by MaherJendoubi** [comment]
@mlorbetske Thank you for the reply!

**Comment by vgpallis** [comment]
What about this issue, 3 months have been passed and no answer at all... If someone wants to build a .net core web api site with facebook auth, how can achieve it without being given the tools?

**Comment by mlorbetske** [comment]
@vgpallis for .NET Core 2.0 (or higher) individual auth for WebAPI is planned. My understanding is that @blowdart has the details on when we'd be planning to add support for more auth pivots for Web API.

**Comment by blowdart** [comment]
If by individual auth you mean there's the ability to have an auth server, which issues bearer tokens, which can be use in authenticating and authorizing an api endpoint it'll be 2.1.

But for facebook, it's just oauth, so acquiring the token is up to you (and facebook has SDKs), and validating it is calling facebook endpoints.
