### ISSUE TITLE
Scaffolding fails with could not load System.Runtime version 4.2.0.0

### ISSUE THREAD

**Issue by twsouthwick** [aspnet/Tooling#1009]
After removing the environment variable in #1008, I'm still getting an error, although a different one.

# Steps to reproduce
- Launch VS (I'm using a clean install of 15.0.26228.0)
- Create an ASP.NET Core application (.NET Core App 1.1)
- In project view, right click Controllers ->Add->New Scaffolded Item and then select MVC Controller - Empty
- First time, select "Full dependencies", then repeat and fill in name

## Expected behavior
New controller should be generated

## Actual behavior
Get an error:

```
Error

There was an error running the selected code generator: 'Could not load file or assembly 'System.RUntime, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f...'. The system cannot find the file specified at...
```

![image](https://cloud.githubusercontent.com/assets/583206/23524034/d38fade2-ff3d-11e6-9d7a-c29a3576e52d.png)

**Comment by mlorbetske** [comment]
Moved to https://github.com/aspnet/Scaffolding/issues/416
