### ISSUE TITLE
Update node to 5.x and npm to 3.x

### ISSUE THREAD

**Issue by giggio** [aspnet/Tooling#101]
Right now Visual Studio is using Node 0.10 and npm 1.4.9. We can't use the latest features on npm because of that, like scoped modules. We always have to `npm install` from the command line because of that.
Update node to at least 0.12.5 and npm to at least 2.10.1 (their latest version).

**Comment by RobertoRodrigues** [comment]
**This is a problem!!!**

**Comment by akamud** [comment]
:+1:

**Comment by alexsandro-xpt** [comment]
+1

**Comment by BillHiebert** [comment]
@madskristensen 

You can change the tools used by Visual Studio using the Tools\Options\Projects and Solutions\External Web Tools  page. The order of the paths listed on that page is the order VS will search for those tools. Install the version of node\npm you want and add it to the top of the list of tools.

![capture](https://cloud.githubusercontent.com/assets/1553785/8502161/6ab06868-2161-11e5-865b-31b41ade2173.PNG)

**Comment by giggio** [comment]
Hey, this is nice! Tks, @BillHiebert for the tip.
And Microsoft should still update the tooling.

**Comment by BillHiebert** [comment]
We will  likely evaluate the tools for every release, but no matter what we do we may not satisfy everyone's needs, and of course there will be gaps between when new tools are available and VS incorporates them. Hopefully the settings dialog will address these needs. 

In case it isn't obvious, note that you can have different versions of tools per project by using a relative path - as the first item in the screenshot I sent has..

**Comment by madskristensen** [comment]
We will be updating Solution Explorer's _Dependency_ node to better support npm 3 for the ASP.NET 5 RC tooling release. For the RTM release we plan on updating npm itself to the latest 3.x release

**Comment by giggio** [comment]
@madskristensen Cool! How about node 4.2? It would be nice to have the LTS version running on VS by default.

**Comment by MartinJohns** [comment]
It would be great if this option (Locations of external tools) could be configured on a per-project base. Having it in the Visual Studio option is not a feasible way when you aim for a "check-out and run" workflow. This would also allow using different NodeJS versions for different projects.

**Comment by madskristensen** [comment]
@giggio We will update both npm and node for either the ASP.NET 5 RC2 release or Visual Studio 2015 Update 2. We'll use the latest LTS release of node. It will hopefully be 5.x but if it isn't ready then it will be 4.2.x

**Comment by giggio** [comment]
@madskristensen Node 5 is out, but it is not going to be an LTS release. Still, [they recommend](https://nodejs.org/en/blog/community/node-v5/) that for tooling we could be using on the stable branch (and LTS, of course).
It makes sense to me. Node 5 also brings npm 3, which helps Windows developers solve the long path problem.

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231277&fullScreen=false&_a=edit">231277</a>
