### ISSUE TITLE
Manage Bower Packages: Update button should disable upon clicking

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#1010]
Here are the steps to reproduce in VS 2017:

1. Use the ASP.NET Core Web Application (.NET Core) project template to create a new ASP.NET Core 1.1 Web Application with No Authentication.
1. Right-click the web project in Solution Explorer, and select **Manage Bower Packages...**.
1. From the **Installed** tab, click the **Update** button for the Bootstrap package. Notice that the button doesn't disable after it's been clicked, yet the update is occurring.

This **Update** button should be disabled while the package update is in progress. Otherwise, the following command is executed each time the button is clicked: `"C:\Users\Scott Addie\AppData\Roaming\npm\Bower.cmd" install bootstrap#v4.0.0-alpha.6 --force-latest --save`.

In the screenshot below, you see what happens when I click the button 3 times in a row:

![bower_update](https://cloud.githubusercontent.com/assets/10702007/23536562/5c5589f6-ff8b-11e6-8c22-7aa322a802d9.png)

**Comment by mlorbetske** [comment]
TFS Bug#406011

**Comment by jodavis** [comment]
This is fixed in the latest release of VS. Controls in the UI will be disabled whenever any commands are executing.
