### ISSUE TITLE
Class Libraries don't support new Razor in VS2017

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Tooling#1013]
Repro:
Clone https://github.com/OrchardCMS/Orchard2 on master
Open VS2017
Edit Orchard2\src\Orchard.Cms.Web\Modules\Orchard.Menu\Views\_ViewImports.cshtml

![image](https://cloud.githubusercontent.com/assets/1165805/23722122/07e4f7c2-03f9-11e7-974d-278b13be92ac.png)

Expected:

![image](https://cloud.githubusercontent.com/assets/1165805/23722128/0fc9cae4-03f9-11e7-803f-0c439d3e42c4.png)

/cc
@NTaylorMullen 
@BillHiebert 
@ToddGrun 
@DamianEdwards

**Comment by BillHiebert** [comment]
This is now tracked in TFS 393058 https://devdiv.visualstudio.com/web/wi.aspx?pcguid=011b8bdf-6d56-4f87-be0d-0092136884d9&id=393058

**Comment by ByteNuts** [comment]
As a temporary workaround, you can change the project Sdk to **Web**.

Edit your .csproj within VS'17 and change
`<Project Sdk="Microsoft.NET.Sdk">`
to
`<Project Sdk="Microsoft.NET.Sdk.Web">`

Maintain your **Target framework** as **.NETStandard 1.6** if you're using it and be sure to set the **Output type** to **Class library**.

You will get tag helpers intellisense, despite no highlight as described in this [known issue](https://github.com/aspnet/Tooling/blob/master/known-issues-vs2017.md#tag-helpers-do-not-work).

**Comment by NTaylorMullen** [comment]
I'd be curious to hear of people's success with @ByteNuts' workaround. I can foresee issues with class libraries that are only desktop but otherwise i'd think it'd work.

**Comment by CoskunSunali** [comment]
@NTaylorMullen, I remember trying @ByteNuts's workaround before I landed on this issue but the compilation broke.

As far as I can recall, it complained that a project using the Web SDK should contain a `Main` entry method.

However, changing the Output Type to Class Library as per @ByteNuts's suggestion seems to have fixed that build-time exception.

Out of curiosity, as you said, the workaround applies to web projects only and could cause issues with desktop-only libraries. Why would you use a library that implements Razor views for a desktop-only library? I am seriously asking to hear if there is a use case for that approach.

**Comment by NTaylorMullen** [comment]
> Why would you use a library that implements Razor views for a desktop-only library? I am seriously asking to hear if there is a use case for that approach.

In new world, not really a reason to have a desktop-only library. However, it happens, usually when migrating an old library to the new world.

**Comment by CoskunSunali** [comment]
I see your point. Thank you.

**Comment by thiennn** [comment]
any update on this? I have update to VS 2017 Preview 15.3 and .NET Core 2.0.0 preview 1. But it doesn't work.

**Comment by rynowak** [comment]
We're looking into this for 15.3 preview2

**Comment by rynowak** [comment]
@NTaylorMullen fixed for preview2 right?

**Comment by NTaylorMullen** [comment]
Yup!

**Comment by rynowak** [comment]
Ok, thanks everyone for reporting this issue. This will be fixed in VS 2017 15.3-preview 2.

If you have further issues with tooling for Razor please report them via VS Feedback or on aspnet/Razor

**Comment by fwitkowski** [comment]
I just have got version 15.3.2 and this is not fixed.

**Comment by fwitkowski** [comment]
The projects are not public. These are company projects and I cannot share
them. I can send you maybe a few screenshots of where the errors show up.

On Aug 23, 2017 6:22 PM, "alexgav" <notifications@github.com> wrote:

Hi Filip,


Do you have a repro project we could take a look at?


Thanks,

Alex


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by alexgav** [comment]
Could you try creating a library project similar to your company ones? And/or taking one of the projects, deleting all files, adding a Razor view, and sharing that? The actual project file is pretty important and would be great to take a look at. The code in the project files doesn't matter that much.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by fwitkowski** [comment]
I still see many errors in views (but no errors on build)
Like this one when specifying model
![image](https://user-images.githubusercontent.com/1815925/29671363-5c3ba2ce-88b7-11e7-9d81-dfea40c76b90.png)

Or viewbag
![image](https://user-images.githubusercontent.com/1815925/29671119-b0369df8-88b6-11e7-83c4-96bfa4bcdf4b.png)

Or Html.Partial
![image](https://user-images.githubusercontent.com/1815925/29671154-c59362a8-88b6-11e7-8df1-0bee93cc2603.png)

Or many more.
The errors are highlighted in every project we have. 
Attaching one of the project files (I did change some names into ***)
[Tmp.TalentBrew.Admin.Site.txt](https://github.com/aspnet/Tooling/files/1249146/Tmp.TalentBrew.Admin.Site.txt)

**Comment by fwitkowski** [comment]
One more issue. VS2017 does not pick up custom Html Helpers.
VS2015: 
![image](https://user-images.githubusercontent.com/1815925/30332060-6c8c8cb6-97a7-11e7-89dc-86cab9b3c7e8.png)

Same page, VS2017 (only limited list):
![image](https://user-images.githubusercontent.com/1815925/30332146-a0d6d06c-97a7-11e7-867f-3ed96f12e29f.png)

This is in version 15.3.3

**Comment by barrytang** [comment]
To report new issues, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool. The GitHub Issue Tracker for the aspnet/Tooling repo is now deprecated in favor of the Report a Problem tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.

**Comment by barrytang** [comment]
@NTaylorMullen @alexgav , is this a known issue?

**Comment by rynowak** [comment]
Looking at the above, my guess is that it's getting the wrong set of namespace imports, possibly because it's falling back to the Razor (non-core) editor.

**Comment by rynowak** [comment]
@fwitkowski could this be your issue? https://github.com/aspnet/Razor/issues/1628

Are tag helpers working?
