### ISSUE TITLE
PrepublishScript can't find npm install

### ISSUE THREAD

**Issue by madmunsterdaddy** [aspnet/Tooling#1016]
Don't know where to put this, so going here since it was the upgrade process that got me here.

Had an ASP.net core app that I created with beta tooling. After upgrading to 2017 my pre-publish to Azure script no longer works. Should the upgrade of handled this differently or do I need to make a manual change? 

  <Target Name="PrepublishScript" BeforeTargets="PrepareForPublish">
    <Exec Command="npm install" />
    <Exec Command="bower install" />
    <Exec Command="gulp clean" />
    <Exec Command="gulp min" />
  </Target>

**Comment by AndreiGorlov** [comment]
Same here. Looks like VS doesn't take into account "External Web Tools" settings.

**Comment by madmunsterdaddy** [comment]
Have you found a workaround yet? 

I tried adding  C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External to system PATH variable, but that doesn't work.

**Comment by madmunsterdaddy** [comment]
Reported here: https://developercommunity.visualstudio.com/content/problem/29113/prepublishscript-does-not-look-to-external-web-too.html

**Comment by AndreiGorlov** [comment]
>Have you found a workaround yet?

Adding 
`C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\Web\External;.\node_modules\.bin`
to PATH works for me.

**Comment by madmunsterdaddy** [comment]
Ah, cool. That seems to patch it for now. Thank you! Dig you get the gulp command working though? Works via Task Runner, but not Prepublish

**Comment by AndreiGorlov** [comment]
gulp works everywhere with **.\\node_modules\\.bin** in PATH.

Also check #1017

**Comment by madmunsterdaddy** [comment]
That's what I thought but gulp kept failing. Closed and re-opened VS after adding those to PATH and now we're good. Not the most stable version in recent history it seems! Thanks, man!

**Comment by mlorbetske** [comment]
Per https://github.com/aspnet/Tooling/issues/1017#issuecomment-286079730, this is tracked by https://github.com/dotnet/cli/issues/5498 and https://github.com/aspnet/websdk/issues/114, closing this here since it's being tracked on those repos

**Comment by AndreiGorlov** [comment]
@mlorbetske It's separate issue not related to dotnet/cli#5498 and aspnet/websdk#114
