### ISSUE TITLE
Razor editor with new tag helpers extension blocks on the following scenario

### ISSUE THREAD

**Issue by javiercn** [aspnet/Tooling#1018]
Repro steps:
<input type="hidden" asp-for="value" ...
go to asp-for and type @ after the opening quotes.
asp-for="@ value"

The editor blocks and the error message says 
![image](https://cloud.githubusercontent.com/assets/6995051/23915725/231c8dd6-08a7-11e7-8ee2-8f46fdccf083.png)

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/Razor#1083
