### ISSUE TITLE
Watch projects referenced in global.json

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Tooling#102]
Based on https://github.com/aspnet/dnx/issues/1912 it looks like VS doesn't watch external referenced projects so when you edit one it doesn't restart the hosting process for live editing.

**Comment by davidfowl** [comment]
It's not VS, it's a dnx issue.

**Comment by sayedihashimi** [comment]
Closing since its a dnx issue and has already an issue tracking it
