### ISSUE TITLE
Adding a .ts file under wwwroot results in an entry in the project file

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Tooling#1020]
After creating a new ASP.NET Core web project, after adding a `.ts` file under `wwwroot` I get the following in the .csproj file.

```
  <ItemGroup>
    <Content Include="wwwroot\file.ts" />
  </ItemGroup>
```

I looked through the globbing patterns for wwwroot to see if it excluded `.ts` files but it doesn't look that way.

Note: this looks like it only repos if I use the `File->Add New Item`, if I add a `.ts` file in Windows Explorer it's fine. Maybe this is an issue with the item template for `.ts` files.

**Comment by macgyver76** [comment]
Same here for `.js` files.

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/websdk#180
