### ISSUE TITLE
Visual Studio 2017 crashes when opening a razor view file

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/Tooling#1022]
To report new issues, use the [Report a Problem](https://developercommunity.visualstudio.com/) tool. The GitHub Issue Tracker for the aspnet/Tooling repo is now deprecated in favor of the Report a Problem tool.

If you encounter a problem with Visual Studio, we want to know about it so that we can diagnose and fix it. By using the Report a Problem tool, you can collect detailed information about the problem, and send it to Microsoft with just a few button clicks. See [here](https://docs.microsoft.com/en-us/visualstudio/ide/talk-to-us) for more details.

**Comment by NTaylorMullen** [comment]
Can you try deleting your `.vs` folder?

**Comment by MaherJendoubi** [comment]
@NTaylorMullen The problem disppears. Thanks.
