### ISSUE TITLE
Error: Uninstalling Microsoft .Net core 1.0.1 VS2015 Tooling Preview 2

### ISSUE THREAD

**Issue by Shashidanand** [aspnet/Tooling#1024]
I am unable to uninstall .Net Core 1.0.1 VS2015 tooling. Below screenshot for your reference - 
![image](https://cloud.githubusercontent.com/assets/1199387/24320072/78a91bfc-1153-11e7-991e-d81e9f4b8266.png)

**Comment by tlycken** [comment]
I see the same thing; also, when trying to repair the installation, the same error pops up and the repair operation also fails.

**Comment by mlorbetske** [comment]
This looks like #995 and #757. From what I'm able to see in the similar issues, this appears to be related to ASP.NET Core Module (ANCM). I was also able to find mention of this in TFS that indicates that that has been fixed for Visual Studio 2017.

@joeloff or @shirhatti did we find a workaround for Visual Studio 2015?

**Comment by BenjiZombie** [comment]
This happened to me before. Here's how I fixed it:

Look at the log file, it will mention a package that it is not able to uninstall (in my case, `WebToolsExtensionsVS14`). Now go to `C:\ProgramData\Package Cache` and search for `WebToolsExtensionsVS14`, it will lead to the package's location (i.e. `C:\ProgramData\Package Cache\{BFC344B0-DCDE-36EB-AB05-CB194F2BE946}\v14.1.21111.0\packages\WebToolsExtensionsVS14_69.msi`). Now right-click that file, choose uninstall, and voila.

**Comment by kathyrollo** [comment]
@BenjiZombie , you are a very contributing member of society. Worked for me, Thanks!

For those stuck in the "specified account already exists" loop, you have to cancel to view the logfile. `WebToolsExtensionsVS14_69.msi` was also the culprit in my case.

**Comment by unowiz** [comment]
@BenjiZombie Thanks for the workaround, the failing uninstall was bothering me a lot :)

**Comment by PRISMAY** [comment]
@BenjiZombie, Thank you for sharing your solution as it worked for me as well.  Much appreciated.

**Comment by kevchadders** [comment]
@BenjiZombie, your doing gods work, Worked for me also.

**Comment by eriawan** [comment]
Due to the fact this issue has been solved, please close this issue, @Shashidanand 

cc @sayedihashimi , @Andrew-MSFT

**Comment by Andrew-MSFT** [comment]
Closing the issue since it's been resolved
