### ISSUE TITLE
OnAfterBackgroundSolutionLoadComplete is fired before VisualStudioWorkspace has finished loading projects

### ISSUE THREAD

**Issue by JoshVarty** [aspnet/Tooling#103]
[`IVsSolutionLoadEvents.OnAfterBackgroundSolutionLoadComplete`](https://msdn.microsoft.com/en-us/library/microsoft.visualstudio.shell.interop.ivssolutionloadevents.onafterbackgroundsolutionloadcomplete(v=vs.100).aspx) is fired before the VisualStudioWorkspace has fully loaded the projects in the solution. Right now it fires and the `VisualStudioWorkspace` reports that it contains 0 projects. 

(I suspect this occurs because the projects are loaded asynchronously via the DesignTimeHost?)

It is documented as: 

>Fired when the solution load process is fully complete, including all background loading of projects.

It would be great if the ASP .Net 5 project system fired this event only after all projects were loaded into the `VisualStudioWorkspace`.

**Comment by BillHiebert** [comment]
That event is fired by the solution only after all projects are loaded. Note however, that many projects (included Asp.Net5) load asynchronously so they may not be fully initialized when this event fires.

**Comment by JoshVarty** [comment]
Is there no way the `project.json` file could be pre-processed such that the number of projects was known, then this event could be fired after that many projects were asynchronously loaded?

It's a **really** big pain for extension developers if certain project systems don't conform to the existing API. It essentially makes this event useless and requires us to test **each** project system individually to see what APIs they respect and what APIs they do not.

It might even be better not to fire this event at all than to fire it when it's not true.

**Comment by BillHiebert** [comment]
Background solution load complete is fired by the solution once every project in the solution has returned from its CreateProjectAsync call. Dnx projects (as do other projects built on the Common Project System), continue to load asynchronously after it returns from the above call. There is no event in VS which indicates all projects are loaded and fully initialized.  That said we know we have deficiencies in this area which makes it difficult to write extensions that work reliably and will be looking at ways to improve this going forward.

**Comment by AArnott** [comment]
Note: a conversation on this is ongoing on [gitter](https://gitter.im/Microsoft/VSProjectSystem?at=55935231b4ce4e473250f855)

**Comment by JoshVarty** [comment]
After chatting with @AArnott about this it looks as though this will be the new norm in CPS projects and I should probably just avoid `OnAfterBackgroundSolutionLoadComplete` if I need access to the actual projects.
