### ISSUE TITLE
Pack succeeded but with no .nupkg generated for ASP.NET core web project

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [aspnet/Tooling#1030]
create an ASP.NET Core web project, right click the project and click "Pack".

- Expected result: .nupkg is generated under the path bin\debug;
- Actual result: .nupkg is not generated under the path bin\debug or other path. 

![packsucceededwithnonupkggenerated](https://cloud.githubusercontent.com/assets/22901391/25085783/80591c62-2396-11e7-9bf5-04dfa4c27974.PNG)

Test on vsuwpt.26414.03
OS: windows 10 X64

**Comment by mlorbetske** [comment]
This issue was moved to dotnet/project-system#2024
