### ISSUE TITLE
Failed to create an ASP.NET Core web project as a circular dependency error

### ISSUE THREAD

**Issue by MiaomiaoHuangfu** [aspnet/Tooling#1036]
- Create an ASP.NET Core project and prompt a window 
 `Importing the file 'C:\Program Files\dotnet\sdk\1.0.4\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props' into the file 'C:\Program Files\dotnet\sdk\1.0.4\Sdks\Microsoft.NET.Sdk.Web\Sdk\Sdk.props' results in a circular dependency.  `
 ![createaspnnetwebfailed](https://cloud.githubusercontent.com/assets/22901391/25888229/f14270d2-3597-11e7-8598-d2591c33f52a.PNG)
- click "OK" button.
- There is no project shown in "Solution Explorer" window.
 ![createaspnnetwebfailed2](https://cloud.githubusercontent.com/assets/22901391/25888296/35e96d3a-3598-11e7-8d30-1b6de63419af.PNG)
**Expect Result**: create an ASP.NET Core web project successfully with project shown in solution explorer.

Test on build: VSUWPT.26509.01
OS: Windows 10 X64

**Comment by mlorbetske** [comment]
cc @vijayrkn

**Comment by vijayrkn** [comment]
This is because the msbuild changes are not available in vsuwpt yet. Can use this bug to track and close this when the changes reaches vsuwpt.

**Comment by MiaomiaoHuangfu** [comment]
The bug is not repro on vsuwpt.26516.02. 
Close the bug.
