### ISSUE TITLE
Consider supporting the ProjectItemsEvents Interface

### ISSUE THREAD

**Issue by JoshVarty** [aspnet/Tooling#104]
https://msdn.microsoft.com/en-us/library/envdte.projectitemsevents.aspx

This is marked as "Infrastructure. Microsoft Internal Use Only."  so I'd understand if you don't think this should be supported. Unfortunately one of my Visual Studio extensions was using this stuff, so it's currently breaking on ASP .Net 5 projects.

Right now it appears the `ItemAdded` event doesn't fire when I add new documents to a project inside an ASP .Net 5 solution. (I haven't tested out the other events)

**Comment by JoshVarty** [comment]
FWIW this won't be an issue for me now. Following discussion in #103 I plan to rearchitect my extension so it depends on as few EnvDTE interfaces as possible. 

I imagine you guys will have to make the decision as to whether or not you want to support this stuff. I'll leave it open for now so you can close when you see fit.

**Comment by sayedihashimi** [comment]
@billhiebert thoughts?

**Comment by sayedihashimi** [comment]
TFS:149642
I've added this to our internal TFS, we will reply back here soon.
