### ISSUE TITLE
OpenID appears in tfp/IdentityService/Manage/ManageLogins VS 2017 15.3 Preview 1

### ISSUE THREAD

**Issue by Ponant** [aspnet/Tooling#1040]
OpenID appears as button in the ManageLogins for a registered user in ASP.NET Core 2.0 in-app Identity whereas it is not expected, a priori.
Furthermore, clicking on this button leads to the Server Error `The view 'AccessDenied' was not found. `

**Comment by danroth27** [comment]
This issue was moved to dotnet/templating#801
