### ISSUE TITLE
Question on the new ASP.NET Identity Template VS 2017 15.3 Preview 1

### ISSUE THREAD

**Issue by Ponant** [aspnet/Tooling#1041]
Are there any draft docs or a working sample around the new identity template in VS 2017 15.3 Preview 1? We are interested in the new IdentityService which has been refactored and includes new tables, e.g. `dbo.AspNetRedirectUris`, which seems to be for client apps to connect to the mvc template (?).

**Comment by danroth27** [comment]
@javiercn 

Yup, we've added tables for the registration of client apps as required to implement OIDC. Docs are still a work in progress, but the templates in [ASP.NET Core 2.0 Preview 1](https://microsoft.com/net/core/preview) are fully functioning samples.

**Comment by danroth27** [comment]
Tracking adding docs here: https://github.com/aspnet/Docs/issues/3366
