### ISSUE TITLE
Adding application manifest 

### ISSUE THREAD

**Issue by miloush** [aspnet/Tooling#1048]
The project properties designer asks me to add manifest to the project first before it can be selected:
![untitled](https://user-images.githubusercontent.com/10546952/27518138-8a52e322-59d0-11e7-99b8-78a31d72e1a3.png)

However, there does not seem to be a manifest template in the Add New Item list for ASP.NET Core projects.

Either add the manifest template, or let the properties designer generate it, or change the "default settings" to declare newer OS support.

**Comment by mlorbetske** [comment]
This issue was moved to dotnet/project-system#2557
