### ISSUE TITLE
Add-Migration command not working.

### ISSUE THREAD

**Issue by varora1406** [aspnet/Tooling#1052]
IDE : visual studio 15.3 preview 5.0
.net core 2.0
Project : .Net core web application (Angular template) including (Angular v4)

Steps to reproduce:
* Create a new project and all required nuget packages.
![image](https://user-images.githubusercontent.com/24986539/28577409-559354a8-7174-11e7-9dfb-26cc7efc1228.png)

* Try to use Add-Migration command. (Don't worry, context classes and rest have been done)
- Result : The term 'Add-Migration' is not recognized as the name of a cmdlet, function, script file, or operable program. 
![image](https://user-images.githubusercontent.com/24986539/28577463-81e914c0-7174-11e7-97eb-5cd2a5fb3e28.png)

**Comment by mlorbetske** [comment]
This is tracked by https://github.com/nuget/home/issues/5557

As mentioned in #1026, this repo is no longer intended for tracking issues. When reporting issues going forward, please report them on the [Developer Community](https://developercommunity.visualstudio.com/) site
