### ISSUE TITLE
Q: [BrowserLink] HowTo programmatically inject custom script into page body at runtime

### ISSUE THREAD

**Issue by snebjorn** [aspnet/Tooling#1054]
Hi, I'm curious about how you made Browser Link inject a custom script into the page body at runtime.
I have to do something similar (ritterim/stuntman#158) so wondering if you've willing to share the implementation :)

I also made a [stackoverflow post](https://stackoverflow.com/questions/45501245/programmatically-inject-custom-script-into-page-body-at-runtime-like-browser-l)

Thanks

**Comment by barrytang** [comment]
Moved to https://github.com/aspnet/BrowserLink/issues/57.
