### ISSUE TITLE
problems creating new projects with rc 5 and beta 5

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#106]
Hi,
  I created a news project after I installed beta 5 runtime, and tried to update all packages in the project  to the beta 5 version but beyond this

https://github.com/aspnet/dnx/issues/2163

  I'm unable to find beta 5 version of 
    "Microsoft.Framework.ConfigurationModel.Json" and "Microsoft.Framework.ConfigurationModel.UserSecrets" 

 is there any fix to do to run mvc project with beta 5?

thanks

**Comment by RehanSaeed** [comment]
ConfigurationModel was renamed to Configuration.

**Comment by davidfowl** [comment]
See the announcements https://github.com/aspnet/Announcements/issues?q=is%3Aopen+is%3Aissue+milestone%3A1.0.0-beta5
