### ISSUE TITLE
Fix race condition with grunt bower-install task. Fixes issue

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Tooling#107]
There is a race condition in how the bower components are installed. More info at https://github.com/OmniSharp/generator-aspnet/issues/254

The fix is a one line addition, you can see it at https://github.com/OmniSharp/generator-aspnet/pull/257.

cc @rustd @phenning

**Comment by rustd** [comment]
The VS templates use only gulp so this does not apply.
