### ISSUE TITLE
Feedback: ensure that .NET Core 1.0/1.1 tooling only supported in VS 2017 and won't be supported in VS 2019

### ISSUE THREAD

**Issue by eriawan** [aspnet/Tooling#1078]
Apologize if my feedback may sound controversial or may spark a debate.

I need to be sure that the problem mentioned on this [page](https://github.com/aspnet/Tooling/blob/master/known-issues-vs2017.md#to-create-aspnet-core-10--11-projects-install-visual-studios-net-core-10---11-developer-tools-for-web-component) about .NET Core 1.0/1.1 tooling is installed when creating new ASP.NET Core 1.0/1.1 project should not happen or should not be supported in VS 2019.

These are my main concerns:

1. VS 2019 is about to be released in around early 2019
2. ASP.NET Core 1.0/1.1 is not going to be supported anymore, based on [this page](https://github.com/dotnet/core/blob/master/microsoft-support.md).
3. Creating new ASP.NET Core 1.0/1.1 will always install the .NET Core 1.0/1.1 web tooling, and this is not necessary when previous reason has reached the unsupported period and it's quite near or might be the same time of VS 2019 release.
4. Based on the problem mentioned above, VS 2017 has no "built in" tooling when creating new ASP.NET Core 1.0/1.1 project, but the external tooling may help. Therefore for those that still need to maintain ASP.NET Core 1.0/1.1 projects, we could use VS 2017 as long as the VS 2017 is still in support lifecycle or in mainstream support lifecycle.

I welcome feedback 🙂

**Comment by eriawan** [comment]
@sayedihashimi @balachir @Andrew-MSFT 

guys, any update on my feedback? is this repo still active or not?

**Comment by Andrew-MSFT** [comment]
Yes, this is an active repo, but last week was a holiday week in the US so most people were on vacation.

I'm not sure I fully follow your question, but because .NET Core 1.0/1.1 will still be in support when Visual Studio 2019 first releases, the component will be available for installation on the Individual Components tab of Visual Studio 2019, and 2019 will continue to support working with 1.0/1.1 projects.

**Comment by eriawan** [comment]
@Andrew-MSFT 

Thanks for your reply!
I now add more clarification about my concern and still have some questions. I'll try to clarify further about why I thought the tooling for .NET Core 1.0/1.1 should not be supported in VS 2019 anymore.

> because .NET Core 1.0/1.1 will still be in support when Visual Studio 2019 first releases
I know, but .NET Core 1.0/1.1 will have end of support in June 2019, as mentioned in this link:
https://github.com/dotnet/core/blob/master/microsoft-support.md

I imagine this scenario:

Let's say if VS 2019 will have support for .NET Core 1.0/1.1 tooling. Assume VS 2019 will be released on early February 2019. On the other hand, .NET Core 1.0/1.1's support will end on June 2019. 
Then it will be quite strange use case for me if VS 2019 has support for .NET Core 1.0/1.1 but the .NET Core 1.0/1.1 will have end of support after VS 2019 released, as illustrated in this table from the previous link:

![image](https://user-images.githubusercontent.com/8773147/49127433-e0608300-f2f9-11e8-9ace-68c6f5cf2811.png)


> the component will be available for installation on the Individual Components tab of Visual Studio 2019, and 2019 will continue to support working with 1.0/1.1 projects

Does this mean VS 2019 will have its own .NET Core 1.0/1.1 tooling? because VS 2017 depends on VS 2015 tooling for .NET Core 1.0/1,1, as often mentioned in previous issues. So please correct me if I'm wrong on this fact.

**Comment by Andrew-MSFT** [comment]
Visual Studio 2017 has no dependency on VS 2015 for .NET Core tooling. There was a preview extension available for download that would enable Visual Studio 2015 to work with .NET Core projects, but it was never GA and is no longer supported.  If you have pointers to where it's been mentioned that VS2017 depends on 2015 I'd like to see that, as that should be corrected.

GA tooling support for .NET Core began in Visual Studio 2017, and is largely orthogonal to the version of .NET Core being targeted.  What support really means in this case, is that the runtime and SDK will no longer receive any security fixes.  However, the SDK will still be available for download, and as long as the SDK is installed on the machine, Visual Studio is able to open, build, and run those projects and applications.
