### ISSUE TITLE
Gruntfile template should use the correct casing for the filename

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Tooling#108]
We should update the casing of the created file from `gruntfile.js` to `Gruntfile.js` since that is the standard. See related change in `yo aspnet` https://github.com/OmniSharp/generator-aspnet/issues/229.

**Comment by rustd** [comment]
Thanks. we will fix it for beta7

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231275&fullScreen=false&_a=edit">231275</a>

**Comment by barrytang** [comment]
This is fixed.
