### ISSUE TITLE
adding sources from another repository disables Add Solution to Source Control

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#11]
Not a strictly asp.net tools related problem, but if I add to the source the src directory of another repository VIsual Studio recognizes the git repository and shows in the solution and in code lens. 
If the solution isn't already under source control, the Command **Add Solution to Source Control** is not more present: I have to remove all the projects under source control from the solution to have enable the command again.

**Comment by sayedihashimi** [comment]
@lucamorelli sorry for the long delay here. Is this still an issue?

**Comment by lucamorelli** [comment]
hmmm ... I had this issue trying to run asp.net from source adding the sources of the cloned repos to the solution. Now, looks like that the **dnu source**, when available, will be the way to do this, so from this point of view this is not anymore a valid scenario, but I suppose that may be happens that someone publish a package not adding the reference to the sources, so theoretically it can be useful.

Beside this git issue, during these these I found several issues: for example even adding just the **src** directoty, in the compilation of the package, it was compiled using its own .sln and global.json file, not the one of the project that inclded them.
 
I don't know if this happens anymore: I suppose it's better to ask Fowler if this is a supported scenario for asp.net 5; if not I think we can stop investigating and close the issue.

**Comment by sayedihashimi** [comment]
Closing based on email from @lucamorelli
