### ISSUE TITLE
Calling "npm ls -g" several times when the solution opens is making the system slow

### ISSUE THREAD

**Issue by giggio** [aspnet/Tooling#111]
When you open a ASP.NET 5 project in Visual Studio 2015 it will call `npm ls -g` once for each project on the solution, even if there is no `package.json` on the `.xproj` directory. This command is not cheap at all and imposes a heavy burden on the development machine.
You need to figure out a way to do whatever you are doing in a way that impacts less the system. Right now Visual Studio simply becomes unusable until all the commands finish, and the whole system becomes really slow. I am experiencing 100% CPU usage going of for minutes on a Surface Pro 3 with i5 and 8GB RAM.

**Comment by davidfowl** [comment]
@giggio You're using VS 2015 RTM right?

**Comment by giggio** [comment]
@davidfowl Yes, but this has being going on for a while. It was an issue already on RC.
I was looking into it right now, and I am not sure it is exactly one instance per project. I do know it is a lot of instances, and it seems that the larger the solution, the more process are opened.

**Comment by jodavis** [comment]
@giggio Thanks for bringing this to our attention. There shouldn't be any calls to npm for a project that doesn't have a package.json. However, it looks like there could be multiple calls for a single project that does have one, especially if packages are being restored when the project opens. The module we use to get package status keeps detecting changes and re-checking status. I will look for ways to reduce this impact.

**Comment by giggio** [comment]
@jodavis I think you are correct. And I have noticed that whenever I install a package that this also happens. I try not to even touch package.json with VS open at this moment, because my machine gets so slow.
It would be nice maybe to have an option to turn off this package management smarts on VS. I usually manage this things on the command line, this is making me work slower.

**Comment by barrytang** [comment]
TFS#1204168

**Comment by cobywhite** [comment]
This isn't just limited to asp.net 5. I get this problem in Visual Studio 2015 in a asp.net 4 project.

**Comment by giggio** [comment]
Ok, I wrote a quick tool to fix this. It kills any Node processes spawn by VS: https://github.com/giggio/killvsnode
You can install it by running `dnu commands install killvsnode`.

**Comment by giggio** [comment]
Problem persists. This is really annoying. How is this coming?
![screenshot 3](https://cloud.githubusercontent.com/assets/334958/9827888/7361a5c4-58bd-11e5-828e-5087359d56c1.png)

**Comment by llehn** [comment]
I have the same problem. It appeared when I switched from the npm which is installed by the tooling to npm 3:
All was fine with beta7 tooling. Then I rearranged the order of external web tools to have $(PATH) as first. I have npm 3 installed in path. Then VS started spawning countless "npm ls -g", effectively almost killing my system.

**Comment by kidchenko** [comment]
I have too.

**Comment by giggio** [comment]
Problem also happens with Node Tools for Visual Studio. :(

**Comment by mykohsu** [comment]
Is there any improvement to this? I have a solution with one project and a few npm gulp modules. There are over 80 executions of npm ls -g in 3 minutes of opening the solution. This can sometimes go on for hours.

**Comment by giggio** [comment]
@mykohsu I can't work without this tool I wrote: https://github.com/giggio/killvsnode
I hope it helps you too. You lose the benefits of the npm integration on VS, but at least you can work.

**Comment by mykohsu** [comment]
@giggio Thanks. I saw that earlier but it seems overkill (though effective!). I ended up rewriting the npm.cmd script so that that simply reads subsequent ls -g requests from a file until it is invalidated with a different command. Maybe you'll find this useful as node tools integration will continue to work. See it [here](https://gist.github.com/mykohsu/b6256301c722d9bec293).

**Comment by giggio** [comment]
@mykohsu That helped! I updated it a little bit, I commented on your gist.

**Comment by sayedihashimi** [comment]
@jodavis any update on this item?

TFS ID: 110628

**Comment by sgrebnov** [comment]
Same issue

**Comment by jodavis** [comment]
This will improve in the next tooling release. We will start getting all the information we need about multiple projects from a single node.exe instance.

**Comment by mattezell** [comment]
Any update on this?  It's killing VS2015 + Mobile Dev for me - just a terrible experience... Lots of people are reporting this issue, but there's little info from MS officially on how to go about elevating this pain..  

Merely opening a jsproj project renders my system unusable until I kill VS2015.. In Process Explorer, there are numerous child node processes running "npm ls -g" and churning on my global node_modules... 

Any way to instruct web tools to ignore this directory?  I've tried adding AnalysIgnoredDirectory to my jsproj, but it has no affect (I know it's intended for node projects, was just wishing)...

**Comment by srijken** [comment]
Update npm, it'll make the `npm ls -g` call so much faster that it's no longer a problem

**Comment by fabricioferreira** [comment]
@srijken what is the npm/node you're using? I noticed that this issue happens when I try to set an external node version:
![image](https://cloud.githubusercontent.com/assets/1106248/14281780/6a384308-fb11-11e5-993d-89e35ac0f9da.png)

If I check that first checkbox the problem appears, otherwise I can work without issues.
The reason why I'm trying to use an updated version of Node is due to an issue with jsdom, that only supports Node.JS 4 or newer:
![image](https://cloud.githubusercontent.com/assets/1106248/14281840/d1e8290a-fb11-11e5-850e-841585b4ee0e.png)

**Comment by leppie** [comment]
@srijken : Does not work for me. Updated node.exe too. Still cant see why it should be called every second.

**Comment by Layoric** [comment]
Same issue, also using external node setup like @fabricioferreira shows. Brings my desktop to its knees. :disappointed: . Also needed to use newer node version than 0.10.31 bundled with VS External Web Tools.

Using: 
VS 2015 Update 2
NPM 3.8.3
Node 4.2.2

**Comment by mykohsu** [comment]
I have not seen the issue on VS 2015 update 3, worth a try.

Previously I used a modified cmd script to cache the result.

**Comment by ArveSystad** [comment]
I, too, have this issue. Using custom paths for external tools (Node) makes no difference either way. It keeps on spawning node.exe processes that do things like seen below:

![procexpl-screenshot](https://cloud.githubusercontent.com/assets/290195/17295977/2c0e3394-57ff-11e6-85ab-f86ddb5d0422.png)

Constant CPU hog between devenv.exe and node on 20-50%. Makes navigating the IDE a pain.
Setup is:
Windows 7 (!)
VS2015, Update 3 (14.0.25424)
NPM 3.10.3
Node 6.3.1

If I remove the external tools completely, things are smooth again, obviously. 

I read somewhere that McAfee's On-Access Scan might be an issue, which might seem plausible.. Can anyone confirm? (I do not have access to edit my Exceptions, so I can't test it myself... :( )

**Comment by fabricioferreira** [comment]
@ArveSystad I have countless issues with this McAfee's On-Access Scan process. Sometimes I wonder if having it isn't worst than a virus consuming resources on my computer...

Anyways, I don't have access to test it as well, but it is certainly a possibility.

**Comment by ArveSystad** [comment]
@fabricioferreira  I ended up repairing the Visual Studio installation. Seemed like some KB-patches were missing, as they were reinstalled during the repair process. After repair, it's all smooth.

**Comment by giggio** [comment]
This problems seems fixed to me. I am closing the issue.
