### ISSUE TITLE
Tooling Roadmap

### ISSUE THREAD

**Issue by johnciliberti** [aspnet/Tooling#113]
It would be helpful if you had a tooling roadmap that aligns with the ASP.NET 5 roadmap posted 
https://github.com/aspnet/Home/wiki/roadmap
From what was said in the last community stand-up, you will be shipping updates to the Visual Studio tooling for ASP.NET out-of-band with major Visual Studio releases and possibility coordinated with the Beta releases of ASP.NET.

Would I would like to see is a list of milestones / features that will be included with each release. For example when will there be Visual Studio support for:
- Scaffolding
- Unit Testing
- Ability to target full version of IIS

**Comment by sayedihashimi** [comment]
I will be posting a roadmap that's has similar format to the runtime roadmap soon. It should be posted in about a week. I'll close this when it's published. It will include all the items you listed above.

**Comment by MartinJohns** [comment]
@sayedihashimi Any update on this?

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231273&fullScreen=false&_a=edit">231273</a>

**Comment by barrytang** [comment]
@sayedihashimi?

**Comment by mlorbetske** [comment]
Closing this as there hasn't been any discussion on this in over a year
