### ISSUE TITLE
VS2015 RTM wwwroot folder not respected by intellisense

### ISSUE THREAD

**Issue by NotMyself** [aspnet/Tooling#114]
New Web Application from template (beta5) using a relative path (~) assumes project root instead of the project.json wwwroot setting for static files. 

Here is a screenshot to better illustrate what I am trying to say:
![capture](https://cloud.githubusercontent.com/assets/73120/8836492/3450604c-3076-11e5-90cc-1b6dc43eacfd.PNG)

In this case I expect to see the folder structure of my wwwroot directory.

**Comment by NotMyself** [comment]
Looks like this was reported #82 Can confirm that adding type="text/css" fixes the issue. Looks like more of a problem with the default template.

**Comment by sayedihashimi** [comment]
Ok thanks @notmyself I have replied there linking back to this. I'll close this, we can continue at #82.
