### ISSUE TITLE
Cannot publish a website on VS 2015 RTM

### ISSUE THREAD

**Issue by csunali** [aspnet/Tooling#115]
I have a web project which is set to run on Core CLR.

The global.json file has the following data in it:

```
{
    "sdk": {
        "version": "1.0.0-beta7-12255",
        "runtime": "coreclr",
        "architecture": "x64"
    }
}
```

However, when I try to publish the project (the publish profile has the same runtime set within its configuration), I see that the project is being publish using x86 version of the CLR.

```
C:\Users\Coskun\.dnx\runtimes\dnx-clr-win-x86.1.0.0-beta7-12255\bin\dnu.cmd publish "D:\WebApplication1\Src\1.0\WebApplication1" --out "C:\Users\Coskun\AppData\Local\Temp\PublishTemp" --configuration Release --no-source --runtime dnx-clr-win-x86.1.0.0-beta7-12255 --wwwroot-out "wwwroot" --quiet
Microsoft .NET Development Utility CLR-x86-1.0.0-beta7-12255
```

And that returns an error:

```
The project being published does not support the runtime 'dnx-clr-win-x86.1.0.0-beta7-12255'
```

I have never set my project to use neither the full CLR not x86 version of it. Where does that really come from and why?

**Comment by sayedihashimi** [comment]
+ @vijayrkn @BillHiebert 

@csunali is this issue limited to beta7 or does it reproduce for beta5 as well?

**Comment by csunali** [comment]
I cannot recall having such a problem while using Beta 5. 

My question is actually why would the publish procedure try to use full CLR instead of the Core CLR specified as well as why the x86 version instead of the x64 version. 

If I could understand the reason behind that, and avoid VS doing that, I would not get that exception anymore. The exception I get is expected, my Web project intentionally does not support the Full CLR. I want it to run only on Core CLR.

**Comment by vijayrkn** [comment]
This is a known issue in the beta6 release. You can find the details here:
https://github.com/aspnet/Tooling/blob/master/known-issues.md

Work-around.
In the Settings tab of the Publish dialog, explicitly select dnx-coreclr as the target rather than using the 'Default'.
