### ISSUE TITLE
Add - New Item - TagHelper default creates a conflict naming.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#117]
When you do Add, New Item, Razor Tag Helper. It suggest TagHelper as the default name.

The problem is that you end with a file called TagHelper that inherits from TagHelper like this:

```
namespace WebApplication1
{
    // You may need to install the Microsoft.AspNet.Razor.Runtime package into your project
    [TargetElement("tag-name")]
    public class TagHelper : TagHelper
    {
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {

        }
    }
}

```

it's very minor thing. Just wanted to let you know.

**Comment by sayedihashimi** [comment]
@rustd?

**Comment by rustd** [comment]
Yes, that is expected. It does not break anything. If you create multiple TagHelper classes, then you will see TagHelper1 etc.
