### ISSUE TITLE
File new default names inconsistency.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#118]
All items in the file new dialog (client side) default names kind of follows a pattern but it's not consistent:

StyleSheet.css
JavaScript.js
htmlpage.html (all lowercase)
CoffeeScript.coffee
json-schema.json
package.json
etc.

Some must have a specific name (like package.json) while others just reflect the file type. 

I see 2 inconsistencies here:

1) casing is inconsistent.
2) TypeScript it suggest file.ts instead of TypeScript.ts

**Comment by sayedihashimi** [comment]
@rustd?

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231271&fullScreen=false&_a=edit">231271</a>

**Comment by sayedihashimi** [comment]
Sorry for the delay here. We haven't improved this yet, but it's on my radar.

**Comment by mlorbetske** [comment]
This issue was moved to aspnet/Templates#850
