### ISSUE TITLE
Running xunit dnx tests is a lot slower in VS than with console

### ISSUE THREAD

**Issue by ilmax** [aspnet/Tooling#119]
Hi, I've just updated a project to use the new dnx stuff, but running tests in VS is a lot slower than using the old csproj. Interestingly enough, running tests via dnx . test performs as expected. 
The slowdown is quite dramatic, since it goes from ~2.5 s when using dnx . test to > 1m using vs runner with run all.

if you are interested I can provide you a repro.

Posted here as suggested by @DamianEdwards  [here](https://github.com/xunit/xunit/issues/482)

Best regards, Max

**Comment by sayedihashimi** [comment]
+@vijayrkn

**Comment by rynowak** [comment]
A 1 min runtime is definitely not expected. Can you set the environment variable `VS_UTE_Diagnostics` = `1` and paste in the results of running from the VS Output window? Get the output from the "Tests" tab.

**Comment by ilmax** [comment]
[Here](https://gist.github.com/ilmax/ff749ac8cecdcfa96f02) it is!

Running tests actually takes >3m, not > 1m.

**Comment by sayedihashimi** [comment]
@rynowak @vijayrkn any thoughts on the trace from @ilmax?

**Comment by rynowak** [comment]
Sorry, I thought I had replied already.

@ilmax - wow, you're right - this is definitely taking 3 mins for 30 tests. Is this project somewhere in a repo where I can access it? The next step is profile it and see what's going on. None of our stuff has these kinds of delays.

**Comment by ilmax** [comment]
Yes, it's [here](https://github.com/ilmax/AspNet.Security.OpenIdConnect.Server)

**Comment by sayedihashimi** [comment]
Thanks @ilmax, we will get back to you.

**Comment by rynowak** [comment]
@ilmax - I am able to reproduce this, currently looking into it.

**Comment by ilmax** [comment]
@rynowak great!

**Comment by rynowak** [comment]
There's definitely an issue with our capturing of stderr output from the test process going on here:

![image](https://cloud.githubusercontent.com/assets/1430011/9049437/c1259652-39f6-11e5-8cd8-4f391f903b36.png)

First of all, we need to fix what we're doing in capturing the output. It all gets concat'ed to a single string, which is causing the memory issues.

Secondly, it looks like Katana (Microsoft.Owin.Testing) will add a trace listener every time it's created, and doesn't ever take them out. 


If you need an immediate workaround, putting a `Trace.Listeners.Clear()` somewhere that it will be called won't hurt anything. We'll need to fix the VS part of testing to address the first issue.

**Comment by ilmax** [comment]
Thank you @rynowak forma the workaround!

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231270&fullScreen=false&_a=edit">231270</a>

**Comment by sayedihashimi** [comment]
Sorry for the delay here. We've had a lot of updates over the past few months and I believe that this is working now in VS2017 RC. Can you try with the latest VS2017 and try again? I'll close this now, but please reopen if this issue still persists.
