### ISSUE TITLE
differences between the restore at opening of the project and normal restore 

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#12]
I don't know if this is by design, but I noticed that there are some differences between the restore done at the opening of the solution, and the restore triggered saving the project.json: if I manually remove projects imported from the sources, saving all the files, the solution file too, changing and saving the project.json nothing happens.
If I close and reopen the solution the projects are readded to the solution.

**Comment by sayedihashimi** [comment]
We did some work on restore in VS2015 RC and are going to do some further work in the next release. I'll go ahead and close this now, but if you run into issues with RC let me know.
