### ISSUE TITLE
dnu publish fails with nested dependencies

### ISSUE THREAD

**Issue by glatzert** [aspnet/Tooling#120]
I tried to publish an Asp.Net project to the file system and got an error in that it cannot find a referenced assembly. But "building" the project works fine.
#### The Project layout (minimal for presentation purposes)
1. New ASP.NET 5 WebAPI Project (WebApplication1)
2. New Class Library (legacy) (ClassLibrary1)
3. Add some package via nuget package manager (I used AutoMapper here, but other packages will have similar problems)
4. Add a reference from WebApplication1 to ClassLibrary1
5. wrap folder was created and ClassLibrary1/project.json exists now - Automapper is listed as dependency

Now build the project or run it in IIS - it will work fine.
Then I added a publish profile for local file-system (just default settings)
Hitting the publish button now will throw an Error: 

> The dependency AutoMapper >= 3.3.1 could not be resolved.
## 

Now I thought I would be _clever_:
I created a folder "wrap/AutoMapper" and a project.json file with the information, so it'll look like the other project.json file, which VS created. And _whooohoo_ my ErrorList was empty and the publish.. did not throw any error, but told me the publish **failed**.

I copied the dnu command line from the vs output and ran it inside a cmd.exe - with the following result (took this from another project, where I first saw the error):

> Restoring packages for C:\Users\...AppData...\EntityFramework.CodeFirstStoreFunctions\1.0.0\root\project.json
> 
> System.ArgumentNullException: Der Wert darf nicht NULL sein. [The value may not be NULL]

**Comment by sayedihashimi** [comment]
@glatzert could you share a sample solution?

**Comment by glatzert** [comment]
@sayedihashimi Here you go https://github.com/glatzert/ASPToolingPublishFail

**Comment by sayedihashimi** [comment]
@glatzert thanks. I've created an internal TFS bug to track this. We will get back to you.

TFSID 1206645

**Comment by vijayrkn** [comment]
This is a known issue. Tracked by https://github.com/aspnet/dnx/issues/2352

**Comment by sayedihashimi** [comment]
Thanks @vijayrkn, from the issue it looks like it is currently slated to beta8. Can we close this?

**Comment by mlorbetske** [comment]
Closing this as dnu publish is no longer the way to publish .NET Core projects
