### ISSUE TITLE
Code Coverage is not displayed properly in Visual Studio

### ISSUE THREAD

**Issue by Flavien** [aspnet/Tooling#121]
Running unit tests with coverage for an ASP.NET 5 project (with XUnit) doesn't work, as it only shows coverage for the XUnit assemblies, not for the assemblies under test.

The issue was already [reported to XUnit](https://github.com/xunit/xunit/issues/483) but they said this is an issue with tooling.

**Comment by sayedihashimi** [comment]
Code coverage isn't available yet for dnx projects. In a week or so I'll post a roadmap which likely will include details on this.

**Comment by Flavien** [comment]
Thanks, looking forward to the roadmap.

**Comment by ajross** [comment]
Hi, was this feature included in the roadmap?  Will it also be possible to include this within builds from Visual Studio Online?

**Comment by sayedihashimi** [comment]
@ajross I haven't posted the roadmap yet, I got delayed but am hoping to get that out this week.

Regarding code coverage, I checked with @Gopinathch and we are **hoping** to get that enabled by the time that ASP.NET 5 is released as RTM. RTM according to the current [asp.net 5 roadmap](https://github.com/aspnet/Home/wiki/Roadmap) is tentatively scheduled for Q1 2016.

**Comment by jamesla** [comment]
+1

**Comment by tillig** [comment]
Checking in - is this still on track? Is there any workaround, like manually instrumenting assemblies before running the tests from a command line?

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231269&fullScreen=false&_a=edit">231269</a>

**Comment by csmith93** [comment]
Hi @sayedihashimi, I'm not authorized to see the ticket... what's the status of it?

**Comment by gopinathch** [comment]
Sorry chris. I am in india and will respond once I am back at US.
 
Date: Mon, 20 Jun 2016 06:03:56 -0700

**Comment by h3smith** [comment]
Assume there is no update on this? Any alternatives with xUnit. We are hoping to migrate fully to .NET Core for our services but this is important for testing.

**Comment by csmith93** [comment]
@h3smith I haven't made any progress. Still waiting on @sayedihashimi returning to the states.

**Comment by csmith93** [comment]
@sayedihashimi, any update?

**Comment by mkontula** [comment]
Any update on this? We have an n-tier api solution with the usual layers. Funny enough, VS Code Coverage does not recognize the main Api assembly (with controllers, bells & whistles)  nor the Model (Data) assembly with DbContext & code-first model classes. These two have the majority of lines & blocks.

**Comment by sayedihashimi** [comment]
Sorry for the delay here. We've had a lot of updates over the past few months and I believe that this is working now in VS2017 RC. Can you try with the latest VS2017 and try again? I'll close this now, but please reopen if this issue still persists.

**Comment by csmith93** [comment]
@sayedihashimi, the issue was also occurring in VS 2015. Will the fix be applied there?

**Comment by sayedihashimi** [comment]
@csmith93 we are not making significant updates to the `.xproj` experience in VS2015. We are investing in 2017+ for .net core.

**Comment by csmith93** [comment]
To be clear, this wasn't a bug then (despite the TFS ticket), or are you not going to bother patching VS 2015 despite it being a bug? This issue was originally reported a year and a half ago.

**Comment by sayedihashimi** [comment]
@csmith93 if it's not working in VS2015 and it's not blocking critical scenarios then it likely will not be fixed. We are focusing all of our efforts on core for VS2017.

>This issue was originally reported a year and a half ago.

Sorry for the delay. I understand that a year and a half is a long time, and I know it's frustraging. We have gone through a lot of fundamental changes and had to redo stuff which has caused delays in us getting features out. Now that we are based on top of the roslyn project system we should be much more stable and able to get new features out more quickly. We are doing our best to get these features out.

**Comment by spence95** [comment]
This still happens in VS2017. It's still an issue as we can see any actual code coverage. Any updates on this?
