### ISSUE TITLE
VS2015RTM Tests: Unable to find the runtime installation directory for the source

### ISSUE THREAD

**Issue by karldodd** [aspnet/Tooling#122]
After upgrading from 2015 RC to RTM, we bumped into an error that no tests are shown in the VS test explorer windows with the following error:

```
------ Discover test started ------
Unable to find the runtime installation directory for the source: 'C:\repo\src\Solution\src\Project1.Testing\project.json'
Unable to find the runtime installation directory for the source: 'C:\repo\src\Solution\src\Project2.Testing\project.json'
========== Discover test finished: 0 found (0:00:00.5614723) ==========
```

Project.json content:

```
"dependencies": {
    "xunit": "2.1.0-*",
    "xunit.runner.dnx": "2.1.0-*",
    "Microsoft.Framework.Runtime.Abstractions": "1.0.0-beta5"
},
"commands": {
    "test": "xunit.runner.dnx"
},
"frameworks": {
    "dnx451": { } 
}
```

We are using DNX 1.0.0-beta5. Btw, the tests are successfully found and running fine under command line (i.e. by running dnx . test). Please advise. Thanks a lot.

**Comment by sayedihashimi** [comment]
@vijayrkn any ideas?

**Comment by vijayrkn** [comment]
Can you try providing the exact version of xUnit NuGet packages supported by RTM.
    "xunit": "2.1.0-beta3-build3029",
    "xunit.runner.dnx": "2.1.0-beta3-build99",  
http://www.nuget.org/packages/xunit.runner.dnx/2.1.0-beta3-build99
http://www.nuget.org/packages/xunit/2.1.0-beta3-build3029

**Comment by karldodd** [comment]
@vijayrkn Yes, I am using the two specific versions you listed: xunit 2.1.0-beta3-build3029 and xunit.runner.dnx 2.1.0-beta3-build99.

Fortunately I figured out the problem myself:

Go to Visual Studio menu -> Test -> Test Settings -> Default Processor Architecture -> Set it to X86 solves my problem. (It was set to X64 accidentally).

Btw, (1) if VS could give more information (e.g. the dnx path it looked for), the diagnostic process might be much easier. (2) there is already an 'architecture' property in global.json in my solution, wondering why VS has another global test architecture setting that brings a chance of conflict.

Thanks anyway. I guess the issue can be closed.

**Comment by sayedihashimi** [comment]
@vijayrkn seems like something we should fix, thoughts?

>Thanks anyway. I guess the issue can be closed.

Let's keep it open for now until we are sure there is no updates needed.

**Comment by vijayrkn** [comment]
@sayedihashimi  - Yes, We need to fix this from the tooling side to provide a better error message in this case.

**Comment by sayedihashimi** [comment]
TFS:149640
I've added this to our internal TFS, we will reply back here soon.

**Comment by barrytang** [comment]
>Yes, We need to fix this from the tooling side to provide a better error message in this case.

We won't be fixing this for VS2015 and the next version of VS will have a different experience.
