### ISSUE TITLE
VS 2015 freezes on putting " into project.json dependency section

### ISSUE THREAD

**Issue by glatzert** [aspnet/Tooling#125]
Visual Studio 2015 freezes in a project.json, when I going to put a " into the dependency section.
If I change the project.json outside VS, it will try to restore the packages, but ends after `CACHE https://nuget...` or if cache is not present after `GET https://nuget...`

Two side facts:
* "Yesterday it worked fine" - so something changed over night?!
* The building of a project today failed with a message that, it was looking into `project/bin/debug...`instead of `main/artifacts/...`

**Comment by glatzert** [comment]
Using dnu restore directly, will also just wait indefinitely.

**Comment by BillHiebert** [comment]
@PradeepKadubandi

**Comment by davidfowl** [comment]
@glatzert Can you give us a repro project? I can't reproduce this on a small project.

**Comment by glatzert** [comment]
Well, I was out-of-Office some days and after I came back, VS and the package Manager cooperated nicely again. Apparently the fail after the " input had something to do with the package manager not willing to proceed.
**You should really put a timeout into the package manager operations** 

Some thoughts about the issue here:
I rebuild my project structure by creating new xProj-Files and removing csproj files from the folder.
Insinde the folders I had project.json AND package.config - that does not play well with nuget and the compiler.

Also something (perhaps TFS) prevented the project.lock.json from being modified - that's also a probably unhandled problem.

And last but not least. Since a colleague made some check-ins in the meantime, I got my csproj back. So inside the folder was a csproj and a xproj file. Another project referencing those had a reference in project.json and one in xproj. This will also lead to failing builds, since it tries to read from old /bin/debug instead of /artifacts.

I'd be happy to provide more information about my "bug", but it crawled away. But I hope the information provided is useful, nevertheless.

**Comment by sayedihashimi** [comment]
TFS:149639
I've added this to our internal TFS, we will reply back here soon.

**Comment by balachir** [comment]
@glatzert, we have been unable to reproduce this. If you can still reproduce with ASP.NET 5 Beta8 or later, please let us know.
