### ISSUE TITLE
Unable to update to beta6

### ISSUE THREAD

**Issue by slaneyrw** [aspnet/Tooling#128]
I'm getting an error with the installer when trying to update to beta6.

After accepting the T's and C's, the installation phase starts but I get an immediate error
"The product requires Visual Studio 14. Please install Visual Studio 14, then try installing this produce again" in the "Evaluating launch conditions" phase

I have installed VS2015 Enterprise from my MSDN downloads.

There was no link to a log file I could look at to give any further information.

Any ideas ?

Installed versions (as reported by Help | About ): 
VS : 14.0.23107.0 D14REL
ASP.NET and Web Tools: 14.0.20626.0
ASP.NET Web Frameworks and Tools 2013: 5.2.30624.0

**Comment by Eilon** [comment]
@joeloff

**Comment by slaneyrw** [comment]
Second machine upgraded okay.  First machine had VS2015 RC, but that was uninstalled before RTM was installed

**Comment by mayurid** [comment]
Somehow the first machine is still under the impression that the product installed is RC. @joeloff : Can you take a look and see what detection logic we are using.

**Comment by joeloff** [comment]
The launch condition simply looks for the EXE of the SKU - either devenv.exe (community, professional or enterprise) or vwdexpress.exe (express for web).

We do this by looking under this path in the registry (assuming a 64-bit OS) HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\VisualStudio\14.0

And then reading the InstallDir key. This key typically points to a folder such as C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\

From there, we simply check to see whether the EXE is present or not. Unfortunately, we'd need to see the logs to see why the search failed. If you have downloaded the installer, you can product a log by doing the following:

1. Open an administrative command prompt
2. Execute the following: msiexec /i webtoolsextensionsvs14.msi /l*v install.log

In the log file, there should be entries similar to the excerpt below. I removed a few lines that aren't applicable, but kept the order of the ones related to the launch condition.

**Action start 8:47:32: AppSearch.
...
MSI (s) (24:68) [08:47:32:945]: PROPERTY CHANGE: Adding VISUALSTUDIO_INSTALLDIR property. Its value is 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\'.
MSI (s) (24:68) [08:47:32:980]: PROPERTY CHANGE: Adding VISUALSTUDIO_EXE property. Its value is 'C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe'.**

After this the launch condition is evaluated, between the start and end action so this is where I'd suspect it is failing.

**MSI (s) (24:68) [08:47:32:982]: Doing action: LaunchConditions
Action start 8:47:32: LaunchConditions.
<FAILURE SHOULD BE BETWEEN THESE ACTIONS>
Action ended 8:47:32: LaunchConditions. Return value 1.**

**Comment by slaneyrw** [comment]
I ran the above in an administrative command prompt and the installer worked as expected.

Before I was running from double-clicking from windows explorer, it didn't prompt for elevation.  Whether that is a fact I don't know anymore, the installer is doing a repair now.

I'll keep an eye on it when the Beta7 installer is released

**Comment by joeloff** [comment]
The installer does require elevation as it is a per-machine install. However, the prompt usually happens some time after accepting the license. If you don't respond in time, the install is automatically cancelled and the OS unfortunately doesn't inform you of the cancellation.

Let me know how the repair goes.

**Comment by slaneyrw** [comment]
Repair worked fine, but still didn't prompt for elevation, but it also didn't need to do any work

**Comment by sayedihashimi** [comment]
@slaneyrw so did you get this figured out?

**Comment by sayedihashimi** [comment]
Closing because I think this has been resolved. If not please try with [beta7](http://blogs.msdn.com/b/webdev/archive/2015/09/02/announcing-availability-of-asp-net-5-beta7.aspx) and then reopen if you're still facing issues.
