### ISSUE TITLE
Remove the Json.net dependency from Unit Test Test adapter.

### ISSUE THREAD

**Issue by vijayrkn** [aspnet/Tooling#129]
Currently, VS unit test adapter depends on Json.Net to serialize and de-serialize messages. Need to remove this dependency so that json.net changes does not impact the unit test discovery/execution.

Issue description is available here - https://github.com/aspnet/Testing/issues/134

**Comment by Eilon** [comment]
I can try to dig up code for this if needed. It'll be similar to the code we use to read `project.json`.

**Comment by JamesNK** [comment]
No changes to a publicly released version of Json.NET will ever break the unit test tools.

The error I got was from a bug I accidentally introduced during development which took down the unit test tools.

I think this is pretty low priority. The only person it would ever help would be me :smile:

**Comment by sayedihashimi** [comment]
@vijayrkn @Eilon can we close this?

**Comment by Eilon** [comment]
I don't think there's any action for my team here. This is tooling only, right?

**Comment by vijayrkn** [comment]
Yes, This is a tooling only item.
