### ISSUE TITLE
WebApplication template content is missing script tag import

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#132]
As in #131 (Web Application Basic template) the Web application main layout file is also missing script import for development environment.

https://github.com/OmniSharp/generator-aspnet/pull/301
via: generator-aspnet

Thanks!

**Comment by sayedihashimi** [comment]
@rustd incoming template bug

**Comment by rustd** [comment]
ok.

**Comment by peterblazejewicz** [comment]
This one is not fixed in `beta7` templates, is it?

![image](https://cloud.githubusercontent.com/assets/14539/9528846/3ba97016-4cf7-11e5-930e-5381595c1954.png)

**Comment by peterblazejewicz** [comment]
this is fixed:
https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Views/Shared/_Layout.cshtml#L75
