### ISSUE TITLE
How can fakes framework be used to create fakes in ASP.net vnext class libraries?

### ISSUE THREAD

**Issue by glatzert** [aspnet/Tooling#134]
I tried to create fakes via the fakes Framework and failed. Is this/will this be supported?

**Comment by sayedihashimi** [comment]
TFS:149625
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
Sorry for the delay here. There has been a lot of changes that have happened since you filled this issue. Can you try again with VS2017 RC and let us know if this issue persists? I'll close this now, but please reopen if it's still an issue.
