### ISSUE TITLE
Tag Helper intellisense does not work if you target dnx46

### ISSUE THREAD

**Issue by opiants** [aspnet/Tooling#135]
If I change it back to dnx451 it works perfectly. I have `"Microsoft.AspNet.Tooling.Razor": "1.0.0-beta6"` in my project.json so the fix described [here](https://github.com/aspnet/Tooling/issues/73) does not apply.

**Comment by sayedihashimi** [comment]
+ @madskristensen

**Comment by NTaylorMullen** [comment]
This is due to `Microsoft.AspNet.Tooling.Razor` today not building for the dnx46 target, or more specifically "dotnet". We should address this.

**Comment by newsash** [comment]
Same with `"Microsoft.AspNet.Tooling.Razor": "1.0.0-beta7"`

**Comment by opiants** [comment]
What's the latest on this?

**Comment by NTaylorMullen** [comment]
Still need to look into this. We've recently made the Razor plugin that's responsible for TagHelper IntelliSense a public repo. Could you move this to https://github.com/aspnet/RazorTooling/issues.

**Comment by opiants** [comment]
Looks like you already did. Thanks
[https://github.com/aspnet/RazorTooling/issues/19]()

**Comment by NTaylorMullen** [comment]
lmao :+1:. Thanks @opiants
