### ISSUE TITLE
"COM object that has been separated from its underlying RCW cannot be used" when viewing properties of ASP.NET 5 project

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Tooling#138]
I'm seeing this error when viewing the properties of any ASP.NET 5 application:

![screen shot 2015-08-08 at 5 49 24 pm](https://cloud.githubusercontent.com/assets/91933/9153045/a349061a-3df6-11e5-947d-75ced86e1405.png)

I do not see it for any other project type (eg. regular Console Applications are fine). I can replicate the error by starting Visual Studio 2015 and creating a brand new ASP.NET 5 app.

Full ActivityLog.xml output: https://gist.github.com/Daniel15/264b258428e797ec6f91

**Comment by Daniel15** [comment]
Turns out this was caused by a third-party component (GhostDoc), I'll report it to them.

**Comment by golino** [comment]
I was having the same problem.
I disabled [Veracode Extension](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1464889.VeracodeVisualStudioPackage) and VS became normal.

I'm using VS2017 Enterprise V15.8.1

**Comment by lnaie** [comment]
> I was having the same problem.
> I disabled [Veracode Extension](https://marketplace.visualstudio.com/items?itemName=vs-publisher-1464889.VeracodeVisualStudioPackage) and VS became normal.
> 
> I'm using VS2017 Enterprise V15.8.1

that fixed it. thanks!
