### ISSUE TITLE
Support edit-save-refresh even when the debugger is attached

### ISSUE THREAD

**Issue by danroth27** [aspnet/Tooling#14]
See https://github.com/aspnet/Home/issues/264 for the original customer request from @jamesnk.

**Comment by davidfowl** [comment]
Ugh, we just need to support edit and continue.

**Comment by dpen2000** [comment]
@davidfowl, Is edit and continue support coming in RTM? If not, you should consider putting a lock icon on the files (when users are debugging) so people know editing them won't do anything. The current situation is confusing.

**Comment by sayedihashimi** [comment]
@dpen2000 we are working on ENC for the next release, but we ran into some issues. We are working with the appropriate teams. We cannot commit to anything quite yet. I should know more in a week or two.

**Comment by GraemeSMiller** [comment]
Was anything updated on whether ENC was planned? One of my clients was asking.

**Comment by piersh** [comment]
is this going to get fixed? we use EnC extensively in our (rather large) ASP.NET 4.6 project to avoid the ~2 minute aspnet recompilation step.

this is a real deal-breaker for ASP.NET 5.

**Comment by ccooper-ssih** [comment]
We also have a group of large ASP.NET projects and use EnC extensively to make it easier to detect/fix issues in hard-to-set-up bugs. Is there any update on this, @sayedihashimi ?

**Comment by sayedihashimi** [comment]
We've made improvements over the past few months here. I'm hoping that we've been able to improve this scenario. I'll close this now, but if we still have work to do please reopen and let me know.
