### ISSUE TITLE
After updating TypeScript for Visual Studio 2015 today, an exception occured and intellisense not working.

### ISSUE THREAD

**Issue by huytnd** [aspnet/Tooling#143]
I updated TypeScript for Visual Studio 2015 RTM today, and after restarting VS, I got this.
![3](https://cloud.githubusercontent.com/assets/2102905/9197869/3ac8ed44-4062-11e5-95d9-d30e875888d4.jpg)
The entry problem I found in the log file
'''
<entry>
    <record>521</record>
    <time>2015/08/11 12:47:12.080</time>
    <type>Error</type>
    <source>Editor or Editor Extension</source>
    <description>System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---&gt; System.ArgumentException: Item has already been added. Key in dictionary: &apos;RazorSupportedRuntimeVersion&apos;  Key being added: &apos;RazorSupportedRuntimeVersion&apos;&#x000D;&#x000A;   at System.Collections.Hashtable.Insert(Object key, Object nvalue, Boolean add)&#x000D;&#x000A;   at System.Collections.Hashtable.Add(Object key, Object value)&#x000D;&#x000A;   at System.Collections.Specialized.HybridDictionary.Add(Object key, Object value)&#x000D;&#x000A;   at Microsoft.VisualStudio.Utilities.PropertyCollection.AddProperty(Object key, Object property)&#x000D;&#x000A;   at Microsoft.VisualStudio.Html.Package.Razor.RazorVersionDetector.Microsoft.Html.Editor.ContainedLanguage.Razor.Def.IRazorVersionDetector.GetVersion(ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.Html.Editor.ContainedLanguage.Razor.RazorUtility.TryGetRazorVersion(ITextBuffer textBuffer, Version&amp; razorVersion)&#x000D;&#x000A;   at Microsoft.Html.Editor.ContainedLanguage.Razor.RazorErrorTagger..ctor(ITextBuffer textBuffer)&#x000D;&#x000A;   --- End of inner exception stack trace ---&#x000D;&#x000A;   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)&#x000D;&#x000A;   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)&#x000D;&#x000A;   at System.RuntimeType.CreateInstanceImpl(BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes, StackCrawlMark&amp; stackMark)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, BindingFlags bindingAttr, Binder binder, Object[] args, CultureInfo culture, Object[] activationAttributes)&#x000D;&#x000A;   at System.Activator.CreateInstance(Type type, Object[] args)&#x000D;&#x000A;   at Microsoft.Html.Editor.ContainedLanguage.Common.ContainedCodeErrorTaggerProvider`1.CreateTagger[T](ITextBuffer textBuffer)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.GatherTaggers(ITextBuffer textBuffer)</description>
  </entry>
'''

**Comment by huytnd** [comment]
I used this command
'''
devenv.exe /resetuserdata
'''
And then I got this error message after restating VS again
![4](https://cloud.githubusercontent.com/assets/2102905/9198014/2aa15dba-4063-11e5-858b-e6bc12542d7a.jpg)
These error entries I found in the log file
<entry>
    <record>418</record>
    <time>2015/08/11 12:58:36.909</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [JavaScriptWebExtensionsPackage]</description>
    <guid>{30DB8F9B-EC9F-44D6-B377-83C7C27A1A8B}</guid>
  </entry>
  <entry>
    <record>419</record>
    <time>2015/08/11 12:58:36.936</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>SetSite failed for package [JavaScriptWebExtensionsPackage]</description>
    <guid>{30DB8F9B-EC9F-44D6-B377-83C7C27A1A8B}</guid>
    <hr>80131500</hr>
    <errorinfo>Expected 1 export(s) with contract name "Microsoft.VisualStudio.JavaScript.Web.Extensions.ReferenceAutoSync.IReferencesFilePathProvider" but found 0 after applying applicable constraints.</errorinfo>
  </entry>
  <entry>
    <record>420</record>
    <time>2015/08/11 12:58:36.938</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [JavaScriptWebExtensionsPackage]</description>
    <guid>{30DB8F9B-EC9F-44D6-B377-83C7C27A1A8B}</guid>
    <hr>80131500</hr>
    <errorinfo>Expected 1 export(s) with contract name "Microsoft.VisualStudio.JavaScript.Web.Extensions.ReferenceAutoSync.IReferencesFilePathProvider" but found 0 after applying applicable constraints.</errorinfo>
  </entry>

**Comment by huytnd** [comment]
I also renamed the folder 'ComponentModelCache' in 'Users\<CurrentUser>\AppData\Local\Microsoft\VisualStudio\<version>\' but still no luck

**Comment by BillHiebert** [comment]
s@ToddGrun

**Comment by lucamorelli** [comment]
try if this is of help

https://stackoverflow.com/questions/31741405/error-setsite-failed-for-packa=
ge-apachecordovatoolspackage

**Comment by huytnd** [comment]
Still no luck, I even did repaired VS, and still got the error.

**Comment by huytnd** [comment]
The version of TypeScript for VS after updating.
![5](https://cloud.githubusercontent.com/assets/2102905/9206538/b3162372-4092-11e5-9604-bd209391493c.jpg)

**Comment by ForkBug** [comment]
I got the second error diag. It's reproduced on 3 boxes, with clear installation of windows 10 and vs 2015 full installation.

**Comment by ForkBug** [comment]
It works fine for beta 5. But after I installed beta6, 3 boxes will popup this error diag if a project is opened first time or there are files opened in the editor when you close the project

**Comment by sayedihashimi** [comment]
I'm not sure if the typescript team is listening to this repository so I'm not sure if this is the best place for this feedback.

I'll reach out to the typescript team to make sure they are aware of this issue.

**Comment by polita** [comment]
@huytnd Can you try the solution to this issue and see if it fixes it? https://github.com/Microsoft/TypeScript/issues/4238

Also copying @mhegazy.

**Comment by sayedihashimi** [comment]
@huytnd did the comments at https://github.com/Microsoft/TypeScript/issues/4238 help you? If so I think we can close this.

**Comment by huytnd** [comment]
You can close this @sayedihashimi
