### ISSUE TITLE
After deleting an unsaved file in solution folder, file editor and IDE can't be closed.

### ISSUE THREAD

**Issue by MiguelAlho** [aspnet/Tooling#144]
I deleted an entire folder through the solution explorer (happens in both xproj-based web apps and class libs) that had files open in the editor, and at least one file had unsaved changes. The delete worked, but the file stayed open in the editor, and trying to close the editor window produced an Invalid ItemId error window. Only way to close the window was to kill the VS process.

To reproduce:
1 - Create a new project (web app or class lib)
2 - In solution explorer, add a folder in the project and a new class to that folder
3 - In the editor window, add some changes, but do not save the file
4 - In solution explorer, delete the class file
5 - Attempt to close the file's editor window.

The delete operation seems to work if the class is in the project root. But in a folder, this error occurs.

**Comment by mayurid** [comment]
@MiguelAlho: I have repro'd this issue and looking into fixing this asap. Will keep you posted
