### ISSUE TITLE
Change Startup.Configuration to be IConfigurationRoot

### ISSUE THREAD

**Issue by kirthik** [aspnet/Tooling#145]
Once fix for https://github.com/aspnet/Configuration/issues/246 is checked in, default template should change `Startup.Configuration` to be `IConfigurationRoot`. This is currently in PR - https://github.com/aspnet/Configuration/pull/264

**Comment by peterblazejewicz** [comment]
@kirthik 
This cold be closed I believe. We use updated def in related project:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/Startup.cs#L44

**Comment by sayedihashimi** [comment]
assigning to @rustd

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231266&fullScreen=false&_a=edit">231266</a>

**Comment by sayedihashimi** [comment]
Should be fixed, closing.
