### ISSUE TITLE
"Add as Link" missing from Visual Studio

### ISSUE THREAD

**Issue by Daniel15** [aspnet/Tooling#147]
Classic project types (eg. ASP.NET 4, Console Application, Class Library) have an "Add as Link" option in the "Add Existing Item" dialog. This allows one file to be shared across multiple projects, by adding the file to the project without physically copying the file to the project directory. This button is missing from the Add Existing Item dialog for ASP.NET 5 projects.

It appears you can achieve something similar through the `shared` section in `project.json`. However, files added this way do not appear under the project in Solution Explorer.

**Comment by sayedihashimi** [comment]
@Daniel15 thanks for the note, we have it on our backlog but have not started on it yet. I'll reply here when we do.

**Comment by sayedihashimi** [comment]
TFS:121783

**Comment by joplaal** [comment]
Some scenarios are covered with the solution stated in https://github.com/aspnet/dnx/issues/550 (using "shared files" in project.json (https://github.com/aspnet/Home/wiki/Project.json-file#shared-files) 

But when one needs to have the same file on several projects, that it's not a compilable one, that does not work.

A common usage would be to have a shared config.json file shared between several projects on the same solution. ¿Is there any way to achieve that without linked files?

**Comment by davidfowl** [comment]
You don't have to use shared files:

https://github.com/aspnet/EntityFramework/blob/dev/src/EntityFramework.Sqlite/project.json#L16

More data here:

https://docs.asp.net/en/latest/dnx/projects.html?highlight=working#including-excluding-files

**Comment by Daniel15** [comment]
@davidfowl  - Do files added like that appear in Solution Explorer? Can I add them via the "Add as Link" option in the UI? Not seeing the files in the solution explorer is a pretty big issue - How am I meant to know exactly which files are being included via the `compile` attribute? Manually looking in Windows Explorer isn't really an appropriate solution for something an IDE should handle :smile:

**Comment by sayedihashimi** [comment]
We don't show those files today but we are planning on adding support to show them.

**Comment by niemyjski** [comment]
Any ETA on this? I get that I can do it today but it's kind of black magic without seeing this file in solution explorer.

**Comment by ToddThomson** [comment]
What if I want to share non cs file resources? While in active development, it is simple to add existing common js and less files as links and then have any modification within a project update the original source. The only alternative is to use a client-side package manager like bower, but while in active development this is too time consuming.
Please let us keep the csproj add files as links within visual studio.

**Comment by jordimontana82** [comment]
Is the shared files approach still supported? Links were removed or moved to a different place, getting 404s.

Would be nice to have the ability to add files as links tho.

**Comment by rpaschoal** [comment]
+1

I just needed this feature to share some Angular2 components with another application and couldn't use it.

Any ETA on this?

Thanks!

**Comment by JimmyBoh** [comment]
If you only need it for a file or two, a simple work-around is to edit your `xproj` with the same XML generated within a `csproj`. For example:

```xml
<ItemGroup>
    <Content Include="..\..\Some\Common\Project\file-to-be-shared.json">
      <Link>linked-copy.json</Link>
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content> 
</ItemGroup>
```

**Comment by tom-corwin** [comment]
Is there a simpler way to workaround this issue other than manually adding each one to the `xproj`? This isn't exactly the best workaround for multiple files.

**Comment by JimmyBoh** [comment]
@tom-corwin It's hacky, I know. I'd create a powershell script or two depending on your use case.

If it's the same file (or few files) that must get copied to many projects then just make a simple CLI script to batch update all project files.

The second script would just open a file picker and allow the user to select a file, then update the `xproj` accordingly (meant to be used during active development).

**Comment by JimmyBoh** [comment]
I will try to throw one together later, but if you do make sure to post it here for everyone!

**Comment by tom-corwin** [comment]
@JimmyBoh I will try to create one, but it will probably be a `csproj` since I'm not familiar with PowerScript at all :stuck_out_tongue_winking_eye:

**Comment by madhav5589** [comment]
@davidfowl  The links that you provided isn't working. Can you please provide the updated link?
Thanks.

**Comment by manastalukdar** [comment]
Would appreciate the tooling allowing for adding files as links sooner rather than later. I am having to manually add in linked files by editing the xproj which isn't very productive.

**Comment by mvadu** [comment]
Any ETA on this one? Its open for more than a year with two updates to Visual Studio 2015 in the mean time. I am trying to share same source across .Net Core (1.0) and classic 4.5, and this is a dead end.

**Comment by Daniel15** [comment]
> I am trying to share same source across .Net Core (1.0) and classic 4.5,

I've found the least error-prone way of doing that is to move the code into the .NET Core project, and "Add as Link" from the classic 4.5 project. This will make it appear in both projects in the solution explorer. If you need any conditional bits of code, you can use preprocessor directives.

**Comment by pgmolloy** [comment]
Just adding support for the "Add as link" in Visual Studio. Huge efficiency gains to be created in agile development and multi-refactoring where shared source can be tested across development instances.

Is there a specific MS developer VS feature statistical report on how many developers rank which feature requests at what importance level. GitHub would be a good place to show this metric providing some real time visibility to what is important across the tooling environment.

**Comment by sayedihashimi** [comment]
Support for this will becoming in the next release when we move to .csproj.

**Comment by riiight** [comment]
Chiming in to add my vote for this feature.

**Comment by sayedihashimi** [comment]
Linked files are supported in the latest version of VS2017 RC. @riiight have you tried with VS2017 RC and had issues?

**Comment by 705am** [comment]
vs2015 update 3 .. 
Hold ALT key and Drag&Drop your file.

**Comment by davidfowl** [comment]
This will be fixed with the new csproj tooling in VS 2017

**Comment by zwcloud** [comment]
Is there a way to add multiple directories/files as links at once?

**Comment by sankar1204** [comment]
Based on @JimmyBoh 's idea I did below thing,
(for me, it was to add a shared AssemblyInfo.cs file to project properties)
```
<ItemGroup>
    <Compile Include="..\..\AssemblyInfo.cs">
      <Link>Properties\AssemblyInfo.cs</Link>
    </Compile>
</ItemGroup>
```

It worked and I could also see linked file in SolutionExplorer.

**Comment by prisar** [comment]
I also wanted to know this. Thanks, this issue helped me
