### ISSUE TITLE
the `beta6` templates are using `asp-file-version` attributes instead of `asp-append-version`

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#149]
The change was not announced and shipped quietly with `beta6`:
https://github.com/aspnet/Mvc/issues/2982
https://github.com/aspnet/Mvc/issues/2540#issuecomment-127112284

Thanks!

**Comment by sayedihashimi** [comment]
@rustd incoming template bug, lets fix for beta7 if possible

**Comment by rustd** [comment]
This is already fixed for beta7

**Comment by peterblazejewicz** [comment]
thanks!
