### ISSUE TITLE
After install beta6, intellisense couldn't know types from class library

### ISSUE THREAD

**Issue by ForkBug** [aspnet/Tooling#150]
After install beta6, intellisense couldn't know any types from class library. while the solution could be succeeded build.

**Comment by ForkBug** [comment]
After install beta6, intellisense couldn't know any types from class library projects in the solution

**Comment by sayedihashimi** [comment]
@ForkBug can you try with beta7 and let us know if it works for you? You can get beta7 at http://blogs.msdn.com/b/webdev/archive/2015/09/02/announcing-availability-of-asp-net-5-beta7.aspx

**Comment by sayedihashimi** [comment]
@ForkBug did you have a chance to try with beta7 yet?

**Comment by sayedihashimi** [comment]
@ForkBug I think this has been fixed in beta7. If you find that this is not the case please reopen this.
