### ISSUE TITLE
[dnu restore] package count summary is incorrect when --parallel option is specified

### ISSUE THREAD

**Issue by ChengTian** [aspnet/Tooling#151]
To reproduce, do `dnu restore --no-cache --parallel` in the root dir of Mvc repo. Then you'll see:

![capture](https://cloud.githubusercontent.com/assets/1383883/9318228/a668335a-44f6-11e5-9da0-e0338fe4fc29.PNG)

The installed package number is not constant if you try multiple times. Looks like we have race condition somewhere.

However, if restore without `--parallel`, you'll find the correct number of installed package is 329.

/cc: @BrennanConroy

**Comment by sayedihashimi** [comment]
@ChengTian is there any tooling scenario here? If not then I think this should be moved to the dnx repo.

**Comment by sayedihashimi** [comment]
@ChengTian closing this since I don't understand the work on tooling here. From what I can tell this is a runtime issue and not related to VS. Please reopen with more comments if that is not the case.
