### ISSUE TITLE
Allow 3rd party templates to call into FolderLayoutTemplateWizard

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Tooling#153]
When a dnx project is created in a blank solution the `FolderLayoutTemplateWizard` is hard coded to discover child .vstemplate files from AspNetProjectTemplates under the Visual Studio install directory. This makes it unusable when creating a template in a VSIX.

We have the following external project templates that are currently impacted by this.
- [xUnit in SideWaffle](http://sidewaffle.com)
- [MVC6 Boiler Plate](https://github.com/RehanSaeed/ASP.NET-MVC-Boilerplate)

I chatted with @BillHiebert and we think this can be supported relatively easily. Instead of using the hard coded path, we use a registry key where VSIXs can register the name/location of a template source. Then in the .vstemplate we add that name of the folder as a CustomParameter. Then when the template is invoked it will search in that folder for the template to install.

**Comment by sayedihashimi** [comment]
TFS: 149635

**Comment by RandomlyKnighted** [comment]
Are there any plans to add this in for the RTM release or is this sometjing that will come later in an Update?

**Comment by sayedihashimi** [comment]
The src folder is going away
