### ISSUE TITLE
Note: bootstrap-touch-carousel used in ASP.NET web templates is probably a stale project

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#155]
Folks - just for your consideration:
I've just found that a Bootstrap Touch Carousel used in web templates for ASP.NET 5 in VS and also in tools like `generator-aspnet` is no longer actively developed and maintained:
https://github.com/ixisio/bootstrap-touch-carousel/commit/c92dd728987fae4ae334bd903c90bfb52b4aae14
The last real contribution to the project are at least one year old:
https://github.com/ixisio/bootstrap-touch-carousel/commits/master

The `bootstrap-touch-carousel` has a `hammer.js` as dependency - and these are the two client-side libraries that are used in MVC related web templates that do not have a real meaning to MVC features in my opinion or are not crucial to support markup critical features (like collapsible mobile dropdown menu which requires bootstrap.js library + jQuery). Every client-side library listed below has some crucial meaning to web template I think - except of bootstrap-touch-carousel + hammer.js - they were added to optimize mobile experience only on landing/home page:

``` json
{
  "name": "WebApplicationBasic",
  "private": true,
  "dependencies": {
    "bootstrap": "3.0.0",
    "bootstrap-touch-carousel": "0.8.0",
    "hammer.js": "2.0.4",
    "jquery": "2.1.4",
    "jquery-validation": "1.11.1",
    "jquery-validation-unobtrusive": "3.2.2"
  }
}
```

Thanks!

**Comment by sayedihashimi** [comment]
Thanks @peterblazejewicz, good to know. Let's see what @rustd says

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231265&fullScreen=false&_a=edit">231265</a>

**Comment by peterblazejewicz** [comment]
Closing this as this is probably not a correct repo anynore (maybe dotnet/tooling or aspnet/Templates)
Thanks!
