### ISSUE TITLE
Superfluous class `btn-default` name in web templates

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#156]
The `index.cshtml` markup in the web applications templates contains superfluous class name in button component markup:
```html
<a class="btn btn-default btn-default" href="http://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
```
For example markup ported to `generator-aspnet` contains:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/Views/Home/Index.cshtml#L32

Above applies to Web Application templates that are using Bootstrap markup.

Thanks!

**Comment by sayedihashimi** [comment]
@rustd simple typo in the templates

**Comment by scottaddie** [comment]
+1

**Comment by peterblazejewicz** [comment]
We have updated web templates in `generator-aspnet` already:
https://github.com/OmniSharp/generator-aspnet/pull/349

**Comment by rustd** [comment]
Thanks. We are tracking this.

**Comment by sayedihashimi** [comment]
@rustd you're tracking the deletion of 11 characters from a single file? What's the next step in the process? :)

**Comment by scottaddie** [comment]
FYI, this fix was merged into the Templates repo today: https://github.com/aspnet/Templates/pull/210#event-434335613

**Comment by sayedihashimi** [comment]
Thanks closing

**Comment by peterblazejewicz** [comment]
:bow:
