### ISSUE TITLE
Missing trailing quotes in form TagHelper attributes for return url in web application template

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#157]
All attributes for form in account related views in web application template are missing ending quote:
https://github.com/OmniSharp/generator-aspnet/search?utf8=%E2%9C%93&q=%40ViewData%5B%22ReturnUrl%22%5D
which does not impact compile/build time - but has effect on syntax highlighters, screenshot from Atom editor below:
* incorrect
![20150822232608](https://cloud.githubusercontent.com/assets/14539/9425937/33164936-4925-11e5-90ba-d6562fe5e23a.jpg)
* correct
![image](https://cloud.githubusercontent.com/assets/14539/9425940/4381e0be-4925-11e5-9e00-c70314c34752.png)

Quotes are optional for attributes but missing quote can have unexpected impact for IDE/editors.

Thanks!

**Comment by sayedihashimi** [comment]
@rustd can we get this fixed?

**Comment by sayedihashimi** [comment]
@peterblazejewicz do you know how VS Code treats this? I think we should fix either way, just curious.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 

Better, but not much:
![20150823093814](https://cloud.githubusercontent.com/assets/14539/9427373/e8edbf1e-497a-11e5-8a9d-e8dcdf3c6b9f.jpg)
![20150823093829](https://cloud.githubusercontent.com/assets/14539/9427375/f1d35378-497a-11e5-9358-e656096f8415.jpg)
![20150823093849](https://cloud.githubusercontent.com/assets/14539/9427377/fb8cb08a-497a-11e5-9f92-85a095b137af.jpg)
(the dot notation sample renders best IMO)

see issue for Razor:
https://code.visualstudio.com/Issues/Detail/17619
Thanks!

**Comment by sayedihashimi** [comment]
@rustd any update here?

**Comment by peterblazejewicz** [comment]
This appears to be fixed:
https://github.com/aspnet/Templates/search?utf8=%E2%9C%93&q=ViewData.returnUrl
