### ISSUE TITLE
Consider dropping obsolete hgroup element in web application templates

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#159]
Similar to:
https://github.com/aspnet/MusicStore/issues/523

The web application template markup uses deprecated `hgroup` element. For example:
https://github.com/OmniSharp/generator-aspnet/blob/master/templates/projects/web/Views/Account/ExternalLoginFailure.cshtml#L5-L8

http://www.w3.org/html/wg/drafts/html/master/obsolete.html#non-conforming-features

That's not it does not render correctly - it does. I think simply it should not be part of best-practises-like template code shipping with ASP.NET/MVC templates.

Thanks!

**Comment by sayedihashimi** [comment]
Assigning to @rustd

**Comment by peterblazejewicz** [comment]
closing in favour of:
https://github.com/aspnet/Templates/issues/217
Thanks!
