### ISSUE TITLE
7.0.0-beta2 migration file in VS ASP.Net 5 template has incorrect property name string

### ISSUE THREAD

**Issue by rustd** [aspnet/Tooling#16]
ApplicationDbContextModelSnapshot  file in an ASP.Net 5 project has  b.Property<string>("NormalizedEmail-");  as the property name for  NormalizedEmail . Which (as far as I can tell) is obviously incorrect. It should be  b.Property<string>("NormalizedEmail");  unless I'm missing something.

This was opened in the Identity repo https://github.com/aspnet/Identity/issues/371  so moving it over to the tooling repo

**Comment by sayedihashimi** [comment]
Fixed in Visual Studio 2015 RC
