### ISSUE TITLE
beta7 WebAPIApplication project.json source code comma fix

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#160]
White space fix to avoid false-difference flags in merging/comparing changes in `package.json`:
```
"Microsoft.AspNet.Server.Kestrel": "1.0.0-*"
 ,
```
it should be:
```
"Microsoft.AspNet.Server.Kestrel": "1.0.0-*",
```
Thanks!

**Comment by sayedihashimi** [comment]
@rustd ?

**Comment by peterblazejewicz** [comment]
this is fixed:
https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/WebAPI/project.json
