### ISSUE TITLE
Consider updating Bootstrap 3.0.0 used in web templates to some most recent version

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#163]
This was discussed in generator-aspnet: the version of Bootstrap used in web application templates both via CDN links for production/staging and via Bower for development purposes is the 3.0.0. 

**This version is now exactly > 2 years old**:

https://github.com/twbs/bootstrap/releases/tag/v3.0.0

As far as I can say there are no significant changes that are required to make web templates to work with 3.3.5 version or newer (that cannot be said about future version 4.0).

The Bootstrap 3.3.5 version (and all related content) is fully supported by Microsoft Ajax CDN:
http://www.asp.net/ajax/cdn#Bootstrap_Releases_on_the_CDN_14

Thanks!

**Comment by sayedihashimi** [comment]
@rustd this was brought up in beta6, I checked with @coolcsh and he indicated we should update bootstrap to the latest.

**Comment by rustd** [comment]
This will be done for RC

**Comment by peterblazejewicz** [comment]
Thanks!

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231263&fullScreen=false&_a=edit">231263</a>

**Comment by peterblazejewicz** [comment]
This one can be closed:
https://github.com/aspnet/Templates/pull/452
