### ISSUE TITLE
Deleting an unsaved file makes closing or saving that file impossible

### ISSUE THREAD

**Issue by glatzert** [aspnet/Tooling#164]
If you delete a file in a ASP.NET vNext project, which has not been saved, the following error will occur on saving or closing that file:

```
Invalid itemId
Parameter name: itemId
```

**Comment by BillHiebert** [comment]
Thanks for the report. A fix for this will be available in the next update (Beta7) due out shortly.

**Comment by sayedihashimi** [comment]
I think this has been fixed in beta7 http://blogs.msdn.com/b/webdev/archive/2015/09/02/announcing-availability-of-asp-net-5-beta7.aspx. I'll go ahead and close this, but if you're still facing this with beta7 please reopen this.

**Comment by glatzert** [comment]
With beta 8 this bug is present again.

**Comment by sayedihashimi** [comment]
@billhiebert have you seen this with beta8?

Reopening for now until we know more

**Comment by BillHiebert** [comment]
This should be fixed with VS Update1 which will be available soon

**Comment by sayedihashimi** [comment]
Should be fixed
