### ISSUE TITLE
Tag Helpers not always showing up in intellisense

### ISSUE THREAD

**Issue by dgee2** [aspnet/Tooling#165]
When adding a new TagHelper in a ASP.net 5 project, the helper is not added to the intellisense until a restart of VS. N.B. my tag helpers are in a separate "Class Library (Package)" project.

VS About Page:
Microsoft Visual Studio Express 2015 for Web
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

**Comment by NTaylorMullen** [comment]
What DNX are you using?

**Comment by dgee2** [comment]
Looks like it was just clashing dnx versions. Thanks for the prompt. I've just updated to beta 7. Will reopen if it reoccurs.
