### ISSUE TITLE
MVC Scaffolding does not work if you have configSource on web.config

### ISSUE THREAD

**Issue by regisbsb** [aspnet/Tooling#169]
Following this stack-overflow post that up to today still gets upvotes because the issue is not fixed (http://stackoverflow.com/questions/23910162/scaffolding-controller-doesnt-work-with-visual-studio-2013-update-2/26246534#26246534) may I ask you to investigate why the scaffolding does not work when appSettings or configSettings have configSource attributes on them?

Thanks

**Comment by sayedihashimi** [comment]
TFS:149354

I've added it to our TFS bug tracker, will reply back here soon.

**Comment by regisbsb** [comment]
Cool, cheers

**Comment by regisbsb** [comment]
@sayedihashimi any news?

**Comment by p770820** [comment]
Is it fixed? It still happened. I use VS2015,  ASP.NET MVC 5.2,  EF6.1。

**Comment by regisbsb** [comment]
@sayedihashimi bump

**Comment by crmckenzie** [comment]
+1

**Comment by regisbsb** [comment]
@sayedihashimi still no news?

**Comment by justz** [comment]
Ahaha, nice.  I still have this bug =)

**Comment by micahosborne** [comment]
+1

**Comment by annerajb** [comment]
Any update on this?

**Comment by BlakeWills** [comment]
Any idea when this will get fixed?

**Comment by Worthy7** [comment]
Just discovered this in VS2015, I scaffolded my models, THEN implemented a secretConnection.config file, which is referenced via <connectionStrings configSource="secretConnection.config"> clearly VS is not following this route.

**Comment by regisbsb** [comment]
@sayedihashimi has TFS:149354 being prioritized yet?

**Comment by deanilvincent** [comment]
What I did was Update the EntityFramework using "Manage Nuget Packages" and click "Entity Framework" on the Installed tab then there's Installed Version of 6.1.3 and below is 6.1.2. I clicked the "Update" and the installed turn to "6.1.2" then I click "Update" once again from 6.1.2 -> 6.1.3 and restart the Visual Studio. I created a controller and all is working so soft. :)

**Comment by deanilvincent** [comment]
By the way, I'm using the Visual Studio Community with Updates 2.

**Comment by regisbsb** [comment]
@deanilvincent are you sure you have got configSource pointing to external webconfig?

**Comment by lengluo** [comment]
Does anyone know if this problem has been solved? I think it's more clearly when we use configSource to
add appsettings.

**Comment by davidarborg** [comment]
I found that leaving out the ID field gave this error, once added it worked!

using System;

namespace MvcDemo.Models
{
    public class Demo
    {
        public int ID { get; set; }    // mandatory !!
        public string First_Field { get; set; }
.
.

**Comment by regisbsb** [comment]
Guys, guys focus! This bug is not related to version or your code. @deanilvincent and @davidarborg have you got a config source on the app settings and connection string? An hour external file? If not this is not the issue you should be commenting on.

**Comment by WasabiFan** [comment]
I am also experiencing this error, at this point in Visual Studio 2017 RC. Why hasn't this bug gotten any traction? What's the status internally (@sayedihashimi)?

It would be great to get a fix for this -- having to remove the `configSource` property every time I want to scaffold something is a pain, and discovering the fix in the first place is tough.

**Comment by regisbsb** [comment]
Sorry about my french but I think at this moment they just cannot give a flying "effe". It has been a solid 1 year now that this has been reported and no one picks up. Famous failure of the prioritization process of bugs. @WasabiFan

**Comment by regisbsb** [comment]
@shanselman on failure of software, how bugs go from one version to another after 2 years...

**Comment by mlorbetske** [comment]
Sorry for the long delay here. While I'm closing this issue (since it's been posted on the Developer Community site now https://developercommunity.visualstudio.com/content/problem/39037/mvc-scaffolding-does-not-work-with-external-connec.html, thanks @regisbsb!), I will say that this issue does come up in conversation with some regularity. I don't recall the details offhand, but my understanding from the team is that this is more complicated to accomplish than it appears. @prafullbhosale could you post more detail on what all is involved & some of the challenges that need to be overcome for this to work to the Developer Community post please?
