### ISSUE TITLE
IISExpress SSL

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#17]
There's no UI property to enable SSL on IISExpress (our couldn't find one)

I'm not aware of a command or config that does this either except manually modifying application.host file (didn't tried it).

**Comment by davidfowl** [comment]
It's coming in the next version.

**Comment by sayedihashimi** [comment]
As David indicated we implemented this feature recently in VS2015 for ASP.NET 5 and it should be in the next release. For now you can manually edit the applicationHost.config file. If you are not familiar with what needs to be changed create an ASP.NET 4.6 project enable Auth and then look in the applicaitonHost.config file under %userprofile% IIS Express folder.

Closing this now.
