### ISSUE TITLE
Publishing problem with a long temp path

### ISSUE THREAD

**Issue by Kagamine** [aspnet/Tooling#170]
My project called "CodeComb.vNext.Samples.YuukoBlog", it was crashed caused by a long path when publishing.

C:\Users\AmamiyaYuuko\AppData\Local\Temp\PublishTemp\CodeComb.vNext.Samples.Yuukoblog95

I tried renamed the project into "YuukoBlog", the problem has been solved.

Beta 7

**Comment by Kagamine** [comment]
At the same time, the stack trace has some encoding error.

![Uploading QQ20150906-2@2x.png…]()

**Comment by Kagamine** [comment]
<img width="350" alt="qq20150906-4 2x" src="https://cloud.githubusercontent.com/assets/2216750/9703031/69ef7b74-54a8-11e5-95bf-ebbe7145c222.png">

**Comment by sayedihashimi** [comment]
TFS:149255
I've added it to our TFS bug tracker, will reply back here soon.

**Comment by Kagamine** [comment]
@sayedihashimi How is the result?
