### ISSUE TITLE
Incorrect path for Bootstrap fallback in web application templates not fixed for beta7

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#171]
The Staging/Production imports in web application templates should be fixed for beta7 released code:
https://github.com/aspnet/Tooling/issues/109#issuecomment-123448003
https://github.com/OmniSharp/generator-aspnet/pull/250/files

They seem to be not and we have to re-fix the problem:
https://github.com/OmniSharp/generator-aspnet/pull/336/files

Thanks!

**Comment by sayedihashimi** [comment]
@rustd ?

**Comment by peterblazejewicz** [comment]
this is fixed:
https://github.com/aspnet/Templates/issues/131
