### ISSUE TITLE
Update NPM and Bower dependencies in VS web templates

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#172]
Please consider reviewing and updating dependencies both in NPM and Bower managed resources before RC1 and 1.0.0 releases.

Related:
https://github.com/OmniSharp/generator-aspnet/issues/337
https://github.com/aspnet/Tooling/issues/155
https://github.com/aspnet/Tooling/issues/163
https://github.com/aspnet/jquery-validation-unobtrusive/issues/7
https://github.com/aspnet/jquery-validation-unobtrusive/issues/5

Thanks!

**Comment by sayedihashimi** [comment]
@rustd we should have up to date components before we go live

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231262&fullScreen=false&_a=edit">231262</a>

**Comment by peterblazejewicz** [comment]
This one can be closed:
https://github.com/aspnet/Templates/pull/452
The NPM dependeny is now removed from Templates btw:
https://github.com/aspnet/Templates/pull/592 (and others)
