### ISSUE TITLE
Publish window doesn't show non-compatible DNX versions

### ISSUE THREAD

**Issue by rynowak** [aspnet/Tooling#176]
We tried installing the 1.0.0-beta7 darwin dnx so that we could cross-publish from windows

The publish dialog wasn't showing the darwin dnx from the command line.

`dnu publish` at the commandline works fine

**Comment by sayedihashimi** [comment]
Adding @vijayrkn, we should show all installed versions on the publish dialog.

**Comment by sayedihashimi** [comment]
TFS:149251

**Comment by sayedihashimi** [comment]
This is changing with dotnet. We will have some limited RID support for RC2 and a better story for RTM. Closing this now.
