### ISSUE TITLE
Forward slash instead of backslash in web template Startup.cs string literal

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#179]
Hi,

We have change a string literal slash path to be forward slash - as hinted by ASP.NET 5 team member on generator-aspnet project:
https://github.com/OmniSharp/generator-aspnet/issues/345#issue-105902213
https://github.com/OmniSharp/generator-aspnet/pull/354

Thanks!

**Comment by sayedihashimi** [comment]
@rustd has this been fixed in the templates?

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231258&fullScreen=false&_a=edit">231258</a>

**Comment by sayedihashimi** [comment]
Should be fixed, closing. Please reopen if this is still an issue.
