### ISSUE TITLE
dnx-crl 'default' alias in Visual Studio Publish

### ISSUE THREAD

**Issue by sheinema** [aspnet/Tooling#180]
On my machine I have the 'default' alias set to point at the dnx-clr-win-x64.1.0.0-beta6 runtime.

When publishing to a local folder using the Visual Studio Professional 2015 (V 14.0.23107.0 D14REL) Publish tool, the following bug exists:

Although the Default displays correctly as using the x64 architecture. The x86 architecture is the runtime that is actually published.

![image](https://cloud.githubusercontent.com/assets/5130722/9856745/aba7004c-5ad3-11e5-8ec4-3bc64a04165a.png)

In order to work-around this issue, one must select the x64 architecture in the drop-down that is NOT associated with the 'default' alias.

**Comment by sayedihashimi** [comment]
This should be fixed in beta 7 http://blogs.msdn.com/b/webdev/archive/2015/09/02/announcing-availability-of-asp-net-5-beta7.aspx. I'll close this now but if you are still seeing this with beta7 please reopen.
