### ISSUE TITLE
After installing beta 7 (runtime + web tools) the projects are all incompatible.

### ISSUE THREAD

**Issue by timvanderweijde** [aspnet/Tooling#181]
Atter installing Beta7 and the webstools for VS2015 the projects are all incompatible.

**Comment by timvanderweijde** [comment]
My fix was
Close VS, then delete the folder at %localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache and restart

(From the comment by Sayed Ibrahim Hashimi) 
http://stackoverflow.com/questions/32465495/exception-on-opening-existing-project-after-ugrading-to-asp-net-mvc6-beta7

**Comment by sayedihashimi** [comment]
@timvanderweijde glad you got it fixed
