### ISSUE TITLE
Code coverage in Visual Studio

### ISSUE THREAD

**Issue by Eilon** [aspnet/Tooling#185]
_From @Flavien on July 23, 2015 23:35_

Right now, code coverage doesn't display in Visual Studio 2015 with XUnit: https://github.com/xunit/dnx.xunit/issues/54#issuecomment-124129449

_Copied from original issue: aspnet/Testing#131_

**Comment by sayedihashimi** [comment]
This should be coming in the first Visual Studio update ( no promises of course :) )

**Comment by Flavien** [comment]
In terms of date, is that Q4 2015, Q1 2016?

**Comment by RdHamilton** [comment]
I'd like to know this also.  Moving to DNC has caused us to go to xunit and no code coverage analysis is a bid issue.

**Comment by sayedihashimi** [comment]
Hi guys, I'm really sorry but I am not at liberty to discuss dates of Visual Studio updates. That is controlled by the VS team itself. We normally communicate deliverables in terms of ASP.NET/Web Tools releases but code coverage requires a change to VS itself.

**Comment by davidfowl** [comment]
We're in communication with the team that owns code coverage and they are making good progress in supporting DNX projects.

**Comment by tushargupta51** [comment]
@sayedihashimi any updates on this?

**Comment by Flavien** [comment]
@tushargupta51 If you install Update 1, you will see that code coverage now works.

**Comment by tushargupta51** [comment]
@Flavien thanks, I will try.

**Comment by tushargupta51** [comment]
I updated the VS, and this is what it gives as code coverage results:

![image](https://cloud.githubusercontent.com/assets/803796/11727340/2e5088a8-9f38-11e5-9715-a24952e38dfb.png)

It only shows the coverage for test assemblies but that's not so useful. I want to know how much of the source code is covered with these tests. e.g. information about Microsoft.IdentityModel.Logging.dll.

**Comment by Flavien** [comment]
In my case, it actually stopped working, and doesn't show me anything at all anymore, I only get this message in the "Code Coverage Results" window: "Empty results generated: No binaries were instrumented. Make sure the tests ran, required binaries were loaded, had matching symbol files, and were not excluded through custom settings. For more information see http://go.microsoft.com/fwlink/?LinkID=253731".

**Comment by andresmoschini** [comment]
I cannot see DNX projects in coverage results.

**Comment by BillHiebert** [comment]
@vijayrkn

**Comment by Flavien** [comment]
A few issues I have noticed:

- I have a SQL project in my solution. If the project is loaded, code coverage won't show. If I unload the project it works.
- If I run code coverage by selecting all test (Ctrl + A), and right click => run code coverage, only some tests are run. If I select "Run all tests with coverage" from the menu, they are all run.
- Sometimes, clicking on the "Show code coverage" button crashes VS.

**Comment by tushargupta51** [comment]
Is this the right repo to report Visual Studio issues?

**Comment by vijayrkn** [comment]
Code coverage is handled by the unit test framework team. I have emailed them the issue details.

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231257&fullScreen=false&_a=edit">231257</a>

**Comment by sayedihashimi** [comment]
Sorry for the delay here. We've had a lot of updates over the past few months and I believe that this is working now in VS2017 RC. Can you try with the latest VS2017 and try again? I'll close this now, but please reopen if this issue still persists.
