### ISSUE TITLE
DNX Core 5.0 tests are not discovered in the TestExporer

### ISSUE THREAD

**Issue by Eilon** [aspnet/Tooling#186]
_From @lukaskabrt on June 29, 2015 8:21_

It seems, that Test Explorer is unable to show tests if the test project doesn't use `dnx451` in the frameworks section. 

If `"dnx451": {}` is removed from the `project.json`, then all tests disappear from the Test Explorer, but they are still discovered by `dnx . test` command. According to (https://github.com/xunit/dnx.xunit/issues/39#issuecomment-116365912) the issue is within plugin that bridges Test Explorer - DNX and not within XUnit library.

**project.json**

```
{
    "version": "1.0.0-*",
    "description": "",
    "authors": [ "" ],
    "tags": [ "" ],
    "projectUrl": "",
    "licenseUrl": "",

    "dependencies": {
        "xunit": "2.1.0-beta2-build2981",
        "xunit.runner.dnx": "2.1.0-beta2-build79"
    },
    "commands": {
        "test": "xunit.runner.dnx"
    },
  "frameworks" : {
    "dnxcore50": {
        "dependencies": {
            "System.Collections": "4.0.10-beta-22816",
            "System.Linq": "4.0.0-beta-22816",
            "System.Threading": "4.0.10-beta-22816",
            "Microsoft.CSharp": "4.0.0-beta-22816"
        }
    },
    "dnx451": {}
  }
}
```

_Copied from original issue: aspnet/Testing#127_

**Comment by Eilon** [comment]
_From @danroth27 on July 8, 2015 20:59_

@vijayrkn @rynowak  Can you guys take a look at this?

**Comment by vijayrkn** [comment]
Test discovery and execution should work for DNX Core 5.0 tests.To choose a specific target framework for testing, select the right framework for the test profile.
![image](https://cloud.githubusercontent.com/assets/3981619/9884078/b11370a0-5b92-11e5-92b0-fef7bef2d6c2.png)

**Comment by rynowak** [comment]
@vijayrkn could you add this to the readme.md on the Testing repo?

**Comment by sayedihashimi** [comment]
TFS:149245

**Comment by barrytang** [comment]
@vijayrkn fixed the debug profile issue in beta8. @sayedihashimi is going to hold onto this to see if we need a redesign.
