### ISSUE TITLE
VS needs to tell the test host when to terminate by passing in a process id to watch

### ISSUE THREAD

**Issue by Eilon** [aspnet/Tooling#187]
See the test host issue here: https://github.com/aspnet/Testing/issues/92

**Comment by kichalla** [comment]
TestHost has been now updated with support for killing the process it creates with the checkin: 
https://github.com/aspnet/Testing/commit/de44d22f99b1ad51cfff9ce74162080bed508b93

@vijayrkn

**Comment by sayedihashimi** [comment]
TFS:149243

**Comment by sayedihashimi** [comment]
This should be fixed in beta8 which you can get at http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx. I'll close this now, but if you are still facing this with beta8 please reopen this.
