### ISSUE TITLE
VS with Beta 7 tools ASP.NET 5 Preview Templates -  Web Application template causes entire github repositories to be copied into wwwroot/lib

### ISSUE THREAD

**Issue by jeremyiverson** [aspnet/Tooling#190]
When creating a new project in Visual Studio 2015 with the WebToolsExtensions for ASP.NET 5 Beta 7 installed, .bowerrc is created with the "directory" value set to "wwwroot/lib". This means, for any dependencies specified in bower.json, the entire github repository for each dependency will be downloaded into the static web root of the application. This is unnecessary, and results in hundreds of source files for the 6 dependencies included by default in the project template. Only a handful of these are needed for deployment.

Bower's default setting is to download the repositories into bower_components, and only the appropriate files are copied into the web root for deployment. Gulp or grunt tasks can be used to accomplish this.

**Comment by sayedihashimi** [comment]
I brought this up internally as well. Lets see what @damianedwards and @madskristensen say.

**Comment by peterblazejewicz** [comment]
@sayedihashimi 
That is the same topic surfacing on `generator-aspnet` (gulp tasks, project event scripts, etc).
Reference setup with Gulp based on current templates:
https://github.com/peterblazejewicz/aspnet5-web-gulp-babel-ts/tree/master/src-es5

**Comment by sayedihashimi** [comment]
Assigning to @madskristensen

**Comment by madskristensen** [comment]
You can manually change the behavior to install Bower packages outside the _wwwroot_ and create a Gulp copy task to just copy in what you need
