### ISSUE TITLE
Browserlink doesn't propogate css changes

### ISSUE THREAD

**Issue by kspearrin** [aspnet/Tooling#192]
Using aspnet 5 beta 7, browser link does not appear to work with css changes.

`app.UseBrowserLink();` is in my `Startup.cs` `Configure`. Running with IIS Express. I can see browser link injected into the bottom of my page's source code. I make a change to a css file from within VS and the change does not show until I manually refresh the page. Checking the browser link dashboard in VS shows my browser attached and I can manually issue refresh commands from there as well.

Is this a known issue?

**Comment by madskristensen** [comment]
This is known and will be fixed after the RC release
