### ISSUE TITLE
Wrapped csprojes need to be restored

### ISSUE THREAD

**Issue by anurse** [aspnet/Tooling#193]
When adding a reference from an xproj to a csproj, `dnu wrap` creates a wrapper project.json, for example:

```
/
    src/
        dnxapp/
            project.json
        csprojlib/
            csprojlib.csproj
    wrap/
        csprojlib/
            project.json
```

VS should track `wrap/csprojlib/project.json` like any other `project.json` in the solution and restore it whenever it changes. Right now it appears that it is not doing that, which is causing some publish issues.

**Comment by sayedihashimi** [comment]
TFS:149238
