### ISSUE TITLE
Add support to invoke pre/post publish scripts

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Tooling#195]
On publish the recommend approach to add a pre or post publish step is to modify the `.ps1` file created by VS and add the commands directly to that.

Instead of this it would be easier if separate files are used for the pre/post publish steps. We've heard feedback on this from customers a few times. Most recently at https://github.com/aspnet/Home/issues/622.
### Proposal

I'd like to propose the following. Naming convention is `prepublish` and `postpublish`. We could support invoking either `.ps1` or `.cmd`.

To be more specific, when `Publish-AspNet` is called it, it will look for `prepublish.ps1` or `prepublish.cmd` in the same folder as the `.ps1` file executing. If it exists it will be executed (_before the publish process starts_). If a .ps1 file exists it will take precedence over the `.cmd` file.

Similarly at the end of `Publish-AspNet` (after the publish process completes successfully) it will look for and call `postpublish.ps1` or `postpublish.cmd`.

Before calling any script the working directory will be set to folder containing the file, and it will be restored to the original working directory at the end.

When the first publish profile is created (_i.e. there are no .pubxml files in PublishProfiles_) the publish dialog will create `prepublish.ps1` and `postpublish.ps1` if they do not exist already.

We should also have an item template for this because the parameters on the file will be important. We should have item template for both a `.ps1` file and a `.cmd` file.

**Comment by GuardRex** [comment]
I think this is one of those features that could be a little more useful if it were a bit more flexible ... and I think we have one shot (we'll be stuck with whatever gets decided for a long, long time).

What about having the `prepublish` and `postpublish` elements in `project.json` contain one or several scripts that can also specify the path? It's simple enough to iterate the values and run them as you suggest around the `Publish-AspNet` command, and running them in the order specified would make this a rock-solid enhancement.

```json
"scripts": {
  "prepublish": [
    "c:/some_folder/some_folder/first_script_to_run_prepublish.ps1",
    "/some_folder_in_project_root/second_script_to_run_prepublish.bat"
  ],
  "postpublish": [
    "c:/some_folder/some_folder/first_script_to_run_postpublish.ps1",
    "command_to_execute_second_step.cmd",
    "/some_folder_in_project_root/final_script_to_run_postpublish.bat"
  ]
},
```

**Comment by sayedihashimi** [comment]
@GuardRex thanks for the comments. Let's iterate on this a bit.

The term `publish` is being overloaded here. In the context of `dnu publish` this means a local/file system publish. When being used in VS it refers more to publishing the app to a remote location.

In the scripts section `prepublish` and `postpublish` are specifically around `dnu publish` and not VS publish. So I don't think that we should place pre/post publish config for VS in `prepublish`/`postpublish`. We could support elements like `prevspublish` and `postvspublish`. In that case when publishing from VS the sequence would be.

 1. `prevspublish`
 1. `prepublish`
 1. `dnu publish`
 1. `postpublish`
 1. `postvspublish`

So that would modify your sample to be.

```
scripts": {
  "prevspublish": [
    "c:/some_folder/some_folder/first_script_to_run_prepublish.ps1",
    "/some_folder_in_project_root/second_script_to_run_prepublish.bat"
  ],
  "postvspublish": [
    "c:/some_folder/some_folder/first_script_to_run_postpublish.ps1",
    "command_to_execute_second_step.cmd",
    "/some_folder_in_project_root/final_script_to_run_postpublish.bat"
  ]
},
```

The benefit of placing these items in `project.json` are:
 1. You can see all your scripts directly in `project.json`
 1. Scripts can be executed in the order specified

For the most basic case where a single script is created here is the typical workflow.

 1. Add a publish profile
 1. Add a post-publish script at `Properties\PublishProfiles\postpublish.cmd`
 1. Edit `project.json` and add `postvspublish` pointing to the script just created.

Instead of that I was recommending that we take a strictly convention based approach. Where the third step (editing `project.json`) isn't required. For the case that you mentioned, you want to execute multiple scripts in a specific order. In that case you can simply create `postpublish.cmd` and have it call the scripts with the right settings. Also if you need to do any prep before executing a specific script (i.e. set the working directory or %path%) you can.

From what I can tell the only advantage to adding `prevspublish`/`postvspublish` to `project.json` is that users can have an all up view of the scripts in one place. I'm not sure if the extra step of editing `project.json` is justified. I'd rather go with the simpler approach.

**Comment by GuardRex** [comment]
@sayedihashimi 

> In the scripts section prepublish and postpublish are specifically around dnu publish and not VS publish. 

... which explains all of my original confusion a few months back about what those terms meant and why I didn't see a script running when I thought it would.

Yes, I agree with your proposal ... your logic is solid as usual, and it will be easy for me to get the functionality I'm seeking if the proposal is approved.

Can the VS project templates have empty PS script files (`prepublish.ps1` and `postpublish.ps1`) provided in the `Properties > PublishProfiles` directory in advance? ... or can VS produce them for us when we check the box for "Publish using PowerShell script" in the VS Publish dialog? It's one less thing for us to do/think about.

**Comment by sayedihashimi** [comment]
>or can VS produce them for us when we check the box for "Publish using PowerShell script" in the VS Publish dialog

Sounds good, I have added a note that the scripts should be created for the first publish profile. The publish dialog will only create `.ps1` files but we can support both `.ps1` and `.cmd`. I noted that we should have item templates for both `.ps1` and `.cmd` files.

**Comment by sayedihashimi** [comment]
Thanks, I've added it to the backlog. Not sure when it may ship yet though, stay tuned.

**Comment by GuardRex** [comment]
Here is an additional idea when this comes up on the backlog: The empty script files, having those file names, are fairly obvious as to what they do; however, it might be good to have comments at the top of each file explaining how the paths will work, something like ...
```
# This script is run <before/after> Visual Studio publishes the application.
# You can trigger multiple batch files, commands, and PowerShell scripts 
# in the order that you would like them run. Use '&' and quotes if the path
# or the filename contains spaces. The path '.\' refers to the app root 
# path (i.e., the same folder with project.json). Example:
#
# .\my_first_script_to_run.ps1
# c:/some_folder/some_folder/second_script_to_run.ps1
# .\<path_to_command_file>\command_to_execute.cmd
# & ".\path has spaces or the\filename has spaces.ps1"
# .\some_folder_in_project_root\final_script_to_run.bat
```

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231255&fullScreen=false&_a=edit">231255</a>

**Comment by sayedihashimi** [comment]
This has been fixed
