### ISSUE TITLE
Integrate TSD in Dependencies

### ISSUE THREAD

**Issue by mbeckenbach** [aspnet/Tooling#199]
Would it be possible to integrate TSD for TypeScipt definitions into the dependencies section similar to bower and npm packages? This would make TypeScript development a lot easier.

**Comment by sayedihashimi** [comment]
Adding @madskristensen

**Comment by madskristensen** [comment]
That's a great idea. I'll add that to the team backlog. In the meantime, check out the Package Installer extension which makes installing TSD definitions super easy https://visualstudiogallery.msdn.microsoft.com/753b9720-1638-4f9a-ad8d-2c45a410fd74

**Comment by rosieks** [comment]
It would be nice to have that - at least if VS will download missing definitions after project load like with npm/bower packages.
