### ISSUE TITLE
changes in global,json aren't reflected in solution explorer

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#2]
if I add directories in the source section of the global.json and save the file, the projects aren't added to the solution untile a kpm restore isn't triggeded.
Removing the source folder from the global.json the projects continues to be shown in the solution explorer, although I trigger the restore changing the project.json or even closing and reopening the solution.

**Comment by lucamorelli** [comment]
I seen the first time a save the solution after the projects are added to the solution, those projects are added to the solution, and if I try to remove one of them and reload the project, until the source directory is present in the project.json the projects are readded to the solution, so pratically in this scenario is pratically unuseful to remove them.
Looks like If I remove the source directories from global.json and leave the projects in the solution they're unuseful, because k runtime are not treating them as source packages anymore, and if I used this way to add asp.net source packages to the solution, in the we application looks like those for thos packages the nuget version is used, not the source, looking at the icons in the solution explorer

**Comment by BillHiebert** [comment]
Thanks Luca. Yes this is a known issue and we have work items on our backlog to improve the experience.

**Comment by sayedihashimi** [comment]
@lucamorelli here is what I tried with VS2015 RC.

 1. Create a new ASP.NET 5 web project
 1. Add a reference in project.json to an existing project on disk in another location
 1. Observe restored failed in solution explorer for the reference
 1. Modify global.json to include the folder that contains the other project

At that point the dependent project was added to the solution. I think we've fixed this, so I'll close this. Can you retry and reopen if you have issues?
