### ISSUE TITLE
Empty KRE list when default alias is bad

### ISSUE THREAD

**Issue by danroth27** [aspnet/Tooling#20]
On CTP 6:
![no kres](https://cloud.githubusercontent.com/assets/1874516/6603596/5e243474-c7e0-11e4-8bbe-baec58ce16fd.png)
The default alias was pointing to a beta4 build that the customer had deleted from the .k\runtimes folder. Manually updating default.txt to point back to beta3 fixed the issue.

**Comment by sayedihashimi** [comment]
I'm no longer seeing this particular issue but I've filed #60 which is related. Closing this.
