### ISSUE TITLE
Gulp task failure

### ISSUE THREAD

**Issue by varghesep** [aspnet/Tooling#200]
In my asp.net 5 project, I have a gulp task to copy the JavaScript files that will run after the app is built. I keep getting errors as shown in the image. As a result, the files do not get copied to the **wwwroot\js** folder. I have seen also the file gets copied, so it is intermittent.

Some tips to help:

1. I'm connected to TFS online and all the files in the **wwwroot\js** folder are checked out. The **js** files are *read only* when I look in the windows explorer.
2. I have IISExpress running for the wwwroot folder.

![gulp_error](https://cloud.githubusercontent.com/assets/12233474/10162050/f85e44c2-666d-11e5-9e93-9e443024c2b2.png)

*PS: Please click the image to see it in large size*

The **gulpfile.js** is given below:

```javascript
/// <binding AfterBuild='dashboard:js' Clean='clean' />

var gulp = require("gulp"),
    rimraf = require("rimraf"),
    concat = require("gulp-concat"),
    cssmin = require("gulp-cssmin"),
    uglify = require("gulp-uglify"),
    babel = require('gulp-babel');
    project = require("./project.json");

var paths = {
    webroot: "./" + project.webroot + "/"
};

paths.js = paths.webroot + "js/**/*.js";
paths.minJs = paths.webroot + "js/**/*.min.js";
paths.css = paths.webroot + "css/**/*.css";
paths.minCss = paths.webroot + "css/**/*.min.css";
paths.concatJsDest = paths.webroot + "js/site.min.js";
paths.concatCssDest = paths.webroot + "css/site.min.css";
paths.dashboardApp = "./scripts/dashboard/**/*.*";

gulp.task("clean:js", function (cb) {
    rimraf(paths.js, cb);
});

gulp.task("clean:css", function (cb) {
    rimraf(paths.concatCssDest, cb);
});

gulp.task("clean", ["clean:js", "clean:css"]);

gulp.task("dashboard:js", function () {
    gulp.src(paths.dashboardApp)
        .pipe(gulp.dest("./wwwroot/js"));
});

gulp.task("min:js", function () {
    gulp.src([paths.js, "!" + paths.minJs], { base: "." })
        .pipe(concat(paths.concatJsDest))
        .pipe(uglify())
        .pipe(gulp.dest("."));
});

gulp.task("min:css", function () {
    gulp.src([paths.css, "!" + paths.minCss])
        .pipe(concat(paths.concatCssDest))
        .pipe(cssmin())
        .pipe(gulp.dest("."));
});

gulp.task("min", ["min:js", "min:css"]);
```

**Comment by sayedihashimi** [comment]
Adding @madskristensen

**Comment by scottaddie** [comment]
As a best practice, your Gulp tasks should return streams. For example, your "min:js" task should look as follows:

    gulp.task("min:js", function () {
        return gulp.src([paths.js, "!" + paths.minJs], { base: "." })
            .pipe(concat(paths.concatJsDest))
            .pipe(uglify())
            .pipe(gulp.dest("."));
    });

I wonder if that's the cause of the intermittent behavior.

**Comment by varghesep** [comment]
Thanks for that suggestion. That did **not** help though.

**Comment by sayedihashimi** [comment]
TFS: 168980
I've added this to our internal TFS, we will reply back here soon.

**Comment by barrytang** [comment]
@varghesep, does this work if you run gulp from a command line.

**Comment by madskristensen** [comment]
@varghesep, we haven't heard back from you in a while. If this issue does not repro on the command line, please reopen it.
