### ISSUE TITLE
ReactJS syntax not working

### ISSUE THREAD

**Issue by varghesep** [aspnet/Tooling#201]
I have a reactjs file **index.js** which renders a component. I see errors as you see in the attached image. Please note that the extension of my file is **js** and not **jsx**.

![react](https://cloud.githubusercontent.com/assets/12233474/10163784/bf98c556-667a-11e5-947c-bbb01b72fff6.png)

I'm using Visual Studio 2015 Enterprise Edition with all the latest updates including the ASP.NET.

**Comment by sayedihashimi** [comment]
Adding @madskristensen to reply

**Comment by madskristensen** [comment]
This is tracked internally in TFS and an update will come out with the ASP.NET 5 RC update
