### ISSUE TITLE
Browserlink make website slow. 1000ms is added for secundaire request

### ISSUE THREAD

**Issue by Anderman** [aspnet/Tooling#202]
If I enable browserlink in my startup.cs the website will be slow.
```
public void Configure(IApplicationBuilder app, IHostingEnvironment env, ILoggerFactory loggerFactory)
        {
            if (env.IsDevelopment())
            {
                app.UseBrowserLink();
```
see chrome F12 image with browserlink

![image](https://cloud.githubusercontent.com/assets/1858745/10179925/93f65e42-6709-11e5-8a73-d3205e51bdad.png)

Without browserlink
![image](https://cloud.githubusercontent.com/assets/1858745/10179950/c23aaa06-6709-11e5-8b10-a2e20101b342.png)

**Comment by Eilon** [comment]
@jodavis @NTaylorMullen @pranavkm any ideas on this?

**Comment by sayedihashimi** [comment]
Assigning to @madskristensen

**Comment by NTaylorMullen** [comment]
Hmm I definitely wouldn't expect increase in request times for static files (and even that, it seems random for which static files it affects). @jodavis shouldn't the browserlink middelware stay silent unless it gets hooked up at the beginning of a request that serves a non-static file?

**Comment by Eilon** [comment]
Should be easy to run a profiler on this and see where the time is spent.

**Comment by Anderman** [comment]
It is not random.
The 1000ms seconds is only spend on static files to the server. The other static files come from CDN servers

**Comment by Anderman** [comment]
Reorder the lines will solve this issue also. But I think this is expected.
from:
```
 app.UseBrowserLink();
 app.UseStaticFiles();
```
to:
```
 app.UseStaticFiles();
 app.UseBrowserLink();
```

**Comment by BillHiebert** [comment]
This issue as been added to our internal TFS bug tracking system as TFS#107821

**Comment by madskristensen** [comment]
This is now fixed

**Comment by Anderman** [comment]
Is this fix in Beta8?

**Comment by Mertsch** [comment]
In beta8 as soon as I enable this extension with ```UseBrowserLink``` my Web API performance drops by a huge amount (~1s added per request)

**Comment by madskristensen** [comment]
We've just fixed this for the RC release and the overhead for running Browser Link is now gone. We can hardly meassure the impact. We know it's below 15ms but might be a lot lower
