### ISSUE TITLE
Files structure broken in solution explorer

### ISSUE THREAD

**Issue by sergeyzwezdin** [aspnet/Tooling#203]
There is really nice feature which introduce file grouping by name in solution explorer.

![files1](https://cloud.githubusercontent.com/assets/800755/10182012/f489fb2c-6738-11e5-9465-3c190af54422.PNG)

But in some time it's broken, I now I see following project structure:

![files2](https://cloud.githubusercontent.com/assets/800755/10182023/102e5918-6739-11e5-8729-7076a2690496.PNG)

Could you advise how to fix that?

**Comment by sayedihashimi** [comment]
TFS:149620
I've added this to our internal TFS, we will reply back here soon.

**Comment by sergeyzwezdin** [comment]
@sayedihashimi thanks!

**Comment by bab5139** [comment]
I have run into the same issue.  This happens when you create a file with a name that happens to be the root of another file.  To get visual studio to correct itself, unloading and reloading the project seems to work.  +1 for addressing this soon.

**Comment by BillHiebert** [comment]
This is fixed in beta8.

**Comment by sergeyzwezdin** [comment]
@BillHiebert beta8 already shipped?

**Comment by BillHiebert** [comment]
Not yet. Should be some time next week

**Comment by sergeyzwezdin** [comment]
Thanks!

**Comment by sayedihashimi** [comment]
This should be fixed in beta8 which you can get at http://blogs.msdn.com/b/webdev/archive/2015/10/15/announcing-availability-of-asp-net-5-beta8.aspx. I'll close this now, but if you are still facing this with beta8 please reopen this.

**Comment by sergeyzwezdin** [comment]
@sayedihashimi Great, thank you!
