### ISSUE TITLE
Create ASP.net templates for DNX

### ISSUE THREAD

**Issue by xanather** [aspnet/Tooling#204]
Will this eventually be added in visual studio? Something along the lines like:
- ASP.net Classic DNX application
- ASP.net MVC DNX application

Right now you have to try to use DNX MVC example project as a reference, located here https://github.com/aspnet/Home/tree/dev/samples/latest/HelloMvc While its not difficult to analyze the example MVC project, a template could help out.

**Comment by Eilon** [comment]
Visual Studio already has ASP.NET templates for MVC application. Can you share more specific details about what is missing?

**Comment by xanather** [comment]
You right, my bad, completely missed it (I was looking at the wrong spot in VS), closing.
