### ISSUE TITLE
Adding sources to global.json does not load the projects from the sources occasionally

### ISSUE THREAD

**Issue by kichalla** [aspnet/Tooling#205]
Repro:
- create a dnx console application and add a package reference to `Microsoft.AspNet.Server.Kestrel` in project.json and save (this should trigger package restore)
- clone kestrelhttpserver repo and add the path to the source of this repo to `global.json` file above and save.
- you should see that the projects are not loaded

Workaround: I deleted the project.lock.json and reopened the solution which then loaded the projects.

Also this whole doesn't seem to happen if I try with a package like `Microsoft.Framework.Logging` where the projects get loaded without the above workaround.

**Comment by sayedihashimi** [comment]
TFS:150843
I've added it to our internal TFS tracker, we will reply back here soon.

**Comment by tuespetre** [comment]
Thanks @kichalla, was having the same problem and deleting the lock file let me continue my work.

**Comment by sayedihashimi** [comment]
This should be fixed in the last release, closing now.
