### ISSUE TITLE
Please stop breaking cordova projects.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#209]
I want to ask if you can please have a better quality control of updates regarding to cordova projects.

First I had this few month ago 

Unable to start debugging in Visual Studio RTM for cordova app
----
http://stackoverflow.com/questions/31530014/unable-to-start-debugging-in-visual-studio-rtm-for-cordova-app

-----

now I experiencing this:

An equivalent project (a project with the same global properties and tools version) is already present in the project collection
---
http://stackoverflow.com/questions/32575903/visual-studio-tools-for-apache-cordova-error-when-creating-or-opening-project

which I cannot solve yet.

the suggested devenv /resetuserdata didn't fixed the issue for me.

Any suggestion to fix this error is welcome as I cannot load the project at all.

**Comment by sayedihashimi** [comment]
Are you saying that ASP.NET 5 projects are impacting Cordova projects? This repo os specifically for ASP.NET 5 projects.

**Comment by Bartmax** [comment]
@sayedihashimi Yes I'm saying that. ASP.NET 5 Beta 7 Update brokes Cordova Projects.

**Comment by sayedihashimi** [comment]
@bartmax ok try deleting ComponentModelCache folder under %localappdata% sorry don't remember the full path off the top of my head.

**Comment by Bartmax** [comment]
thank you @sayedihashimi unfortunatelly, after deleting that folder I still get the same error.

**Comment by sayedihashimi** [comment]
@Billhie any ideas how we may negatively impact Cordova projects?

**Comment by jzoss** [comment]
I'm in the same boat.. @Bartmax Did you ever fix it?

**Comment by Bartmax** [comment]
@jzoss not yet. I will try to uninstall the beta tools, then doing /resetuserdetails and then install the beta tools. unfortunately I don't have the luxury to invest much time on this, because I need to work with the ASPNET5 project and the cordova one, so I will work on the aspnet5 part until this is resolved somehow, maybe with the beta8 tools, not sure. I will let you know if I manage to get it working tho.

**Comment by sayedihashimi** [comment]
TFS:150833

@Bartmax I have opened an issue in our internal tracker. We will reply back here soon.

For the repro steps are you having issues with new projects or just existing one?

**Comment by Bartmax** [comment]
@sayedihashimi existing projects. I didn't tried new projects, but on stackoverflow, people is reporting that this is happening for new projects also, can't confirm because I already uninstalled the aspnet5 beta bits, and trying to install again, etc. will let you know how it goes.

**Comment by Bartmax** [comment]
@sayedihashimi Actually I had 2 existing projects, using different project and cli version. Neither works. I think one is from RTM and another from RC. (both worked fine before asp.net tools beta7 update).

**Comment by sayedihashimi** [comment]
Ok thanks hopefully we can get someone to investigate soon. Another thing to try in the mean time, delete any .user/.suo files.

**Comment by Bartmax** [comment]
uninstall Microsoft ASP.NET and Web Tools 2015 (Beta7)
uninstall Microsoft .NET Version Manager (x64) 1.0.0
Launch Visual Studio:
	NET5 Project doesn't open. (expected)
	Cordova (jsproj) loads as empty project (no files seen)

run devenv /clearuserdata

Launch Visual Studio (2nd time):
	NET5 Project doesn't open. (expected)
	Cordova (jsproj) loads as empty project (no files seen) (same as ss provided)

Installed DotNetVersionManager x64
Installed ASP.NET5 Visual Studio Tools 2015 (Beta 7)

Deleted .user and .suo files. and now I don't see the error, but the project is unusable. :( Hope is not worse than before.

![image](https://cloud.githubusercontent.com/assets/3386797/10317223/29eb49ca-6c42-11e5-9988-ef6ace29bbe3.png)

As you can see, both project behave different, I will how the jsproj of both (separate comments to avoid confusion).

**Comment by Bartmax** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|Android">
      <Configuration>Debug</Configuration>
      <Platform>Android</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|iOS">
      <Configuration>Debug</Configuration>
      <Platform>iOS</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Windows-AnyCPU">
      <Configuration>Debug</Configuration>
      <Platform>Windows-AnyCPU</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Windows-x64">
      <Configuration>Debug</Configuration>
      <Platform>Windows-x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Windows-x86">
      <Configuration>Debug</Configuration>
      <Platform>Windows-x86</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Windows-ARM">
      <Configuration>Debug</Configuration>
      <Platform>Windows-ARM</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Windows Phone 8">
      <Configuration>Debug</Configuration>
      <Platform>Windows Phone 8</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Windows Phone (Universal)">
      <Configuration>Debug</Configuration>
      <Platform>Windows Phone (Universal)</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Android">
      <Configuration>Release</Configuration>
      <Platform>Android</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|iOS">
      <Configuration>Release</Configuration>
      <Platform>iOS</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Windows-AnyCPU">
      <Configuration>Release</Configuration>
      <Platform>Windows-AnyCPU</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Windows-x64">
      <Configuration>Release</Configuration>
      <Platform>Windows-x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Windows-x86">
      <Configuration>Release</Configuration>
      <Platform>Windows-x86</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Windows-ARM">
      <Configuration>Release</Configuration>
      <Platform>Windows-ARM</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Windows Phone 8">
      <Configuration>Release</Configuration>
      <Platform>Windows Phone 8</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Windows Phone (Universal)">
      <Configuration>Release</Configuration>
      <Platform>Windows Phone (Universal)</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <ProjectGuid>ad3ce32b-152c-404b-bd65-f25b5d5b6aaf</ProjectGuid>
  </PropertyGroup>
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup Condition="'$(VisualStudioVersion)' == '' or '$(VisualStudioVersion)' &lt; '14.0'">
    <VisualStudioVersion>14.0</VisualStudioVersion>
  </PropertyGroup>
  <PropertyGroup>
    <TypeScriptToolsVersion>1.4</TypeScriptToolsVersion>
    <DefaultReferenceGroup>Implicit (Apache Cordova)</DefaultReferenceGroup>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <TypeScriptCompileOnSaveEnabled>false</TypeScriptCompileOnSaveEnabled>
    <TypeScriptRemoveComments>false</TypeScriptRemoveComments>
    <TypeScriptSourceMap>true</TypeScriptSourceMap>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)' == 'Release'">
    <TypeScriptCompileOnSaveEnabled>false</TypeScriptCompileOnSaveEnabled>
    <TypeScriptRemoveComments>true</TypeScriptRemoveComments>
    <TypeScriptSourceMap>false</TypeScriptSourceMap>
  </PropertyGroup>
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\ApacheCordovaTools\vs-mda-targets\Microsoft.MDA.FileMirroring.targets" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\ApacheCordovaTools\vs-mda-targets\Microsoft.TypeScript.MDA.targets" />
  <PropertyGroup>
    <ProjectUISubcaption>Tools for Apache Cordova</ProjectUISubcaption>
  </PropertyGroup>
  <PropertyGroup>
    <TargetPlatformIdentifier>MDD</TargetPlatformIdentifier>
  </PropertyGroup>
  <Target Name="EnsureBuildPrerequisites">
    
    <Error Condition="$(MDAPropertiesEvaluated) == 'true' And $(NodeJsDir) == ''" Text="Path to NodeJs could not be determined. Please check that NodeJs has been installed." />
    <Error Condition="$(MDAPropertiesEvaluated) == 'true' And $(MDAVsixDir) == ''" Text="Path to the Visual Studio Extension for Tools for Apache Cordova could not be determined. Please check that the extension has been installed." />
    
    <Error Condition="$(MDAPropertiesEvaluated) == '' And $(NodeJsDir) == ''" Text="Path to NodeJs has not been specified. Please check that NodeJs has been installed and set the NodeJsDir environment variable before building." />
    <Error Condition="$(MDAPropertiesEvaluated) == '' And $(MDAVsixDir) == ''" Text="Path to Visual Studio Extension for Tools for Apache Cordova has not been specified. Please install it and set the MDAVsixDir environment variable before building." />
    
    <Error Condition="!Exists('$(NodeJsDir)') Or !Exists('$(NodeJsDir)\node.exe')" Text="The specified NodeJs directory $(NodeJsDir) either does not exist, or does not contain node.exe. Please check that NodeJs has been installed, and set the NodeJsDir variable to the correct directory." />
    <Error Condition="!Exists('$(MDAVsixDir)') Or !Exists('$(MDAVsixDir)\packages\vs-tac')" Text="The specified directory to the Visual Studio extension $(MDAVsixDir)\node.exe either does not exist, or does not contain a packages\vs-tac sub-directory. Please check that the extension directory exists and set the MDAVsixDir variable to the correct directory." />
    
    <Exec Command="&quot;$(MDAVsixDir)&quot;\packages\vs-tac\install &quot;$(NodeJsDir)&quot; &quot;$(MDAVsixDir)&quot;\packages\vs-tac" />
  </Target>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties />
    </VisualStudio>
  </ProjectExtensions>
  <Import Project="_apacheCordovaProjectSourceItems.Targets" Condition="Exists('_apacheCordovaProjectSourceItems.Targets')" />
</Project>

**Comment by Bartmax** [comment]
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props" Condition="Exists('$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\TypeScript\Microsoft.TypeScript.Default.props')" />
  <ItemGroup Label="ProjectConfigurations">
    <ProjectConfiguration Include="Debug|Android">
      <Configuration>Debug</Configuration>
      <Platform>Android</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|iOS">
      <Configuration>Debug</Configuration>
      <Platform>iOS</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Windows-AnyCPU">
      <Configuration>Debug</Configuration>
      <Platform>Windows-AnyCPU</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Windows-x64">
      <Configuration>Debug</Configuration>
      <Platform>Windows-x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Windows-x86">
      <Configuration>Debug</Configuration>
      <Platform>Windows-x86</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Windows-ARM">
      <Configuration>Debug</Configuration>
      <Platform>Windows-ARM</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Windows Phone 8">
      <Configuration>Debug</Configuration>
      <Platform>Windows Phone 8</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Debug|Windows Phone (Universal)">
      <Configuration>Debug</Configuration>
      <Platform>Windows Phone (Universal)</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Android">
      <Configuration>Release</Configuration>
      <Platform>Android</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|iOS">
      <Configuration>Release</Configuration>
      <Platform>iOS</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Windows-AnyCPU">
      <Configuration>Release</Configuration>
      <Platform>Windows-AnyCPU</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Windows-x64">
      <Configuration>Release</Configuration>
      <Platform>Windows-x64</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Windows-x86">
      <Configuration>Release</Configuration>
      <Platform>Windows-x86</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Windows-ARM">
      <Configuration>Release</Configuration>
      <Platform>Windows-ARM</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Windows Phone 8">
      <Configuration>Release</Configuration>
      <Platform>Windows Phone 8</Platform>
    </ProjectConfiguration>
    <ProjectConfiguration Include="Release|Windows Phone (Universal)">
      <Configuration>Release</Configuration>
      <Platform>Windows Phone (Universal)</Platform>
    </ProjectConfiguration>
  </ItemGroup>
  <PropertyGroup Label="Globals">
    <ProjectGuid>f1f0dc11-7ddd-4aea-90b5-ff7918f0b244</ProjectGuid>
  </PropertyGroup>
  <Import Project="$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props" Condition="Exists('$(MSBuildExtensionsPath)\$(MSBuildToolsVersion)\Microsoft.Common.props')" />
  <PropertyGroup Condition="'$(VisualStudioVersion)' == '' or '$(VisualStudioVersion)' &lt; '14.0'">
    <VisualStudioVersion>14.0</VisualStudioVersion>
  </PropertyGroup>
  <PropertyGroup>
    <TypeScriptToolsVersion>1.5</TypeScriptToolsVersion>
  </PropertyGroup>
  <PropertyGroup>
    <TypeScriptCompileOnSaveEnabled>false</TypeScriptCompileOnSaveEnabled>
  </PropertyGroup>
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\ApacheCordovaTools\vs-mda-targets\Microsoft.TypeScript.MDA.targets" />
  <Import Project="$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)\ApacheCordovaTools\vs-mda-targets\Microsoft.MDA.FileMirroring.targets" />
  <PropertyGroup>
    <ProjectUISubcaption>Tools for Apache Cordova</ProjectUISubcaption>
  </PropertyGroup>
  <PropertyGroup>
    <TargetPlatformIdentifier>MDD</TargetPlatformIdentifier>
  </PropertyGroup>
  <Target Name="EnsureBuildPrerequisites">
    
    <Error Condition="$(MDAPropertiesEvaluated) == 'true' And $(NodeJsDir) == ''" Text="Path to NodeJs could not be determined. Please check that NodeJs has been installed." />
    <Error Condition="$(MDAPropertiesEvaluated) == 'true' And $(MDAVsixDir) == ''" Text="Path to the Visual Studio Extension for Tools for Apache Cordova could not be determined. Please check that the extension has been installed." />
    
    <Error Condition="$(MDAPropertiesEvaluated) == '' And $(NodeJsDir) == ''" Text="Path to NodeJs has not been specified. Please check that NodeJs has been installed and set the NodeJsDir environment variable before building." />
    <Error Condition="$(MDAPropertiesEvaluated) == '' And $(MDAVsixDir) == ''" Text="Path to Visual Studio Extension for Tools for Apache Cordova has not been specified. Please install it and set the MDAVsixDir environment variable before building." />
    
    <Error Condition="!Exists('$(NodeJsDir)') Or !Exists('$(NodeJsDir)\node.exe')" Text="The specified NodeJs directory $(NodeJsDir) either does not exist, or does not contain node.exe. Please check that NodeJs has been installed, and set the NodeJsDir variable to the correct directory." />
    <Error Condition="!Exists('$(MDAVsixDir)') Or !Exists('$(MDAVsixDir)\packages\vs-tac')" Text="The specified directory to the Visual Studio extension $(MDAVsixDir)\node.exe either does not exist, or does not contain a packages\vs-tac sub-directory. Please check that the extension directory exists and set the MDAVsixDir variable to the correct directory." />
    
    <Exec Command="&quot;$(MDAVsixDir)&quot;\packages\vs-tac\install &quot;$(NodeJsDir)&quot; &quot;$(MDAVsixDir)&quot;\packages\vs-tac" />
  </Target>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties />
    </VisualStudio>
  </ProjectExtensions>
  <Import Project="_apacheCordovaProjectSourceItems.Targets" Condition="Exists('_apacheCordovaProjectSourceItems.Targets')" />
</Project>

**Comment by Bartmax** [comment]
Tried manually updating to TypeScript 1.6 for both projects. same results.

**Comment by jzoss** [comment]
I did a forced uninstall of Visual Studio and it was still broken.. Just uninstalled again.. this time I went and deleted the C:\Program Files (x86)\Microsoft Visual Studio 14.0 .. Here's hoping I did not screw it all up.

**Comment by jzoss** [comment]
Well.. That actually worked.. Doing a vs_enterprise.exe /uninstall /force ... then actually deleted the Visual Studio Folder.. then reinstalling fixed it.. Annoying and should not happen, but takes less time than waiting to get a fix.

**Comment by Bartmax** [comment]
@jzoss @sayedihashimi  I finally fixed it (different way of @jzoss) I uninstalled apache cordova tools and then used the VS2015 installer to install from there.

So I guess, this can be helpfull:

If you have Visual Studio installed pre BETA5.
After installing BETA5
remove apache cordova tools
and using the VS installer to install them again
looks like it does the trick. (Deleting ComponentModuleCache and `devenv /resetuserdata` might be need too. can't be sure about that)

**Comment by sayedihashimi** [comment]
Adding @mbraude.

I think there was a Cordova release that may have a fix for this. @mbraude would know for sure.

**Comment by mbraude** [comment]
Hi @Bartmax. We just released Cordova Update 3 which fixes this issue. You will see a notification in the VS notification center shortly, but you can also launch the update by going to the New Project Dialog - you'll see the 'breadcrumb' next to the template for new Cordova Projects. Thanks, and sorry for the trouble.

**Comment by Bartmax** [comment]
@mbraude I guess that's why it was resolved when I uninstalled and reinstalled. The update3 was available. Thanks for the update! really appreciate it!.

**Comment by sayedihashimi** [comment]
Glad we resolved this!
