### ISSUE TITLE
VS2015 hangs when opening ASP.NET 5 project

### ISSUE THREAD

**Issue by jhubsharp** [aspnet/Tooling#21]
I'm trying to take an existing application built with Angular/Bower/Grunt and set it up in 2015. I create a new project in CTP6 using the Empty template, load my NPM packages already defined in my package.json, then save, close VS, and re-open the project. When I re-open, the solution hangs and VS has to be force-closed.

I have a fully built package.json, bower.json, and gruntfile.js.

**Comment by sayedihashimi** [comment]
Can you share a sample?

**Comment by jhubsharp** [comment]
I'll have to work on scrubbing a sample in the morning. It's definitely something to do with the Gruntfile.js though. Are there logs or something I can read when 2015 tries and fails to load the Gruntfile? I know we get some package manager output, but I'm not even getting that far.

**Comment by sayedihashimi** [comment]
If it's grunt related let's see what @madskristensen thinks

**Comment by jhubsharp** [comment]
Here's what I get from the console when I try to refresh Task Runner Explorer:

Failed to run "C:\Code\Mine\WebClient\gruntfile.js"...
cmd.exe /c grunt -b "C:\Code\Mine\WebClient" --gruntfile "C:\Code\Mine\WebClient\gruntfile.js" --tasks "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\TaskRunnerExplorer\Scripts" vs-grunt-task-reader
[4mRunning "vs-grunt-task-reader" task[24m
<vs-grunt-task-reader>
<tasks>
</tasks>
</vs-grunt-task-reader>

[32mDone, without errors.[39m

I noticed I had some manual changes to the order of External Tools paths so I reset that to default and now I get:

Failed to run "C:\Code\Mine\WebClient\gruntfile.js"...
cmd.exe /c grunt -b "C:\Code\Mine\WebClient" --gruntfile "C:\Code\Mine\WebClient\gruntfile.js" --tasks "C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\TaskRunnerExplorer\Scripts" vs-grunt-task-reader
grunt-cli: The grunt command line interface. (v0.1.13)

**Comment by jhubsharp** [comment]
Upon further inspection, I'm starting to wonder if this is an issue with the Task Runner Explorer (or its underlying code) only expecting to parse a file of a certain size. Our gruntfile runs over 600 lines and if I add it to my VS2015 project the project will not load and VS hangs until it is killed. I've rebuilt the file three different times in different orders (all registerTasks and some of my initConfig, all of my initConfig and some of my registerTasks, etc.) and after I get to around 500 lines of me piecing the file together, it starts crashing VS2015. It doesn't seem to matter which tasks I add - when it hits a point it stops working.

I'd love to work with someone on this so we can get this resolved.

**Comment by jhubsharp** [comment]
I went ahead and submitted this to Connect with a scrubbed file attached. Hope that helps. https://connect.microsoft.com/VisualStudio/feedback/details/1207301/ctp6-crashes-when-parsing-large-gruntfiles

**Comment by sayedihashimi** [comment]
Assigning to @madskristensen since its either a grunt or trx issue

**Comment by markentingh** [comment]
For me, Visual Studio hangs for at least 2 minutes when opening my project, which comprises of about 30 classes. It's not really that big of a project at all, and yet, every time I open the project, it takes 2+ minutes to load, and Windows even alerts me that Visual Studio is frozen.

**Comment by cognitivecarbon** [comment]
Have a similar experience.  VS 2015, ASP .NET 5 project. hangs when opening the project, or when attempting to edit files in the solution.  Using GIT as the repository type; not sure, yet, if this also happens to projects we are working on that are in TFS (but also using ASP .NET 5)

**Comment by jimior2** [comment]
Had same problem "Failed to run --gruntfile vs-grunt-task-reader" on VS2015.

**Comment by NageshAndani** [comment]
I have same problem with the ASP.NET Core 1.0 project. It takes ~3-5 minutes to load the project.

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231353&fullScreen=false&_a=edit">231353</a>

**Comment by mlorbetske** [comment]
There hasn't been any activity here for quite some time. Looking at the history on the linked TFS bug, the thinking is that this has been fixed. Closing this for now, please re-open if it's still happening.
