### ISSUE TITLE
Empty wwwroot folder in Empty Template Is Ignored By Git

### ISSUE THREAD

**Issue by ardalis** [aspnet/Tooling#210]
When adding a new project built using the Empty Web Template to a git repository, the empty wwwroot folder is ignored. Thus, when the project is pulled down and opened in another location, the wwwroot folder doesn't exist, which results in an error. Adding any file to the folder would eliminate this issue - perhaps an empty/blank favicon.ico file could be added, simply to address this issue?

**Comment by sayedihashimi** [comment]
@ardalis thanks for the report, this is a known issue. I think @BillHiebert recently fixed this. @BillHiebert can you confirm, also do you know if the fix is in the [canary release](https://github.com/aspnet/Tooling/releases/tag/Canary-0921)?

**Comment by sayedihashimi** [comment]
@ardalis I spoke with @BillHiebert  and he confirmed that the fix has been made. It should be in the [canary release](https://github.com/aspnet/Tooling/releases/tag/Canary-0921) for sure and may even have made beta7 (_not sure though_).

@ardalis can we close this?

**Comment by ardalis** [comment]
I can confirm it's not in beta 7. Good to know it's known/fixed - thanks! Closing.
