### ISSUE TITLE
Nested Files Using Partial Classes in Solution Explorer

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Tooling#211]
I have split up my Startup class into separate files using partial classes. In VS Solution Explorer the files are nested nicely under Startup.cs. My project before upgrading to Beta 7:

```
*Other files omitted*
Startup.cs
    Startup.Antiforgery.cs
    Startup.CacheProfiles.cs
    Startup.Caching.cs
    Startup.Configuration.cs
    etc.
```

After upgrading to Beta 7, only one file is strangely nested and the others are all in the project root:

```
*Other files omitted*
Startup.cs
    Startup.Antiforgery.cs
Startup.CacheProfiles.cs
Startup.Caching.cs
Startup.Configuration.cs
etc.
```

![untitled](https://cloud.githubusercontent.com/assets/2270364/10338954/c9c7ed2c-6d00-11e5-961d-eb32ae9c92ac.png)

I ignored it for a while but I've had a look and it looks like this issue has not been raised yet.

**Comment by BillHiebert** [comment]
Thanks for reporting this. It has been fixed in beta8 (to be released in a week or so).
