### ISSUE TITLE
dnx gen does not work with beta7 tooling

### ISSUE THREAD

**Issue by medhatelmasry** [aspnet/Tooling#214]
I executed the following command in package manager:

dnx gen controller --controllerName SponsorController --model Sponsor --dataContext NetBcContext

Added following to project.json, dependencies:
"Microsoft.Framework.CodeGenerators.Mvc": "1.0.0-*"

Added following to project.json, commands:
"gen": "Microsoft.Framework.CodeGeneration"

This produces the following error:

dnx : System.InvalidOperationException: Unable to resolve service for type 'Microsoft.Framework.Runtime.ILibraryManager' while attempting to 
activate 'Microsoft.Framework.CodeGeneration.DefaultCodeGeneratorAssemblyProvider'.
At line:1 char:1
+ dnx gen controller --controllerName SponsorController --model Sponsor ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (System.InvalidO...emblyProvider'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Microsoft.Framework.Dependency
Injection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
   at Microsoft.Framework.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
   at Microsoft.Framework.DependencyInjection.ActivatorUtilities.CreateInstance[T](IServiceProvider provider, Object[] parameters)
   at Microsoft.Framework.CodeGeneration.ServiceProvider.AddServiceWithDependencies[TService,TImplementation]()
   at Microsoft.Framework.CodeGeneration.Program.AddCodeGenerationServices(ServiceProvider serviceProvider)
   at Microsoft.Framework.CodeGeneration.Program..ctor(IServiceProvider serviceProvider)

**Comment by sayedihashimi** [comment]
@medhatelmasry the dnx gen command may not work in beta7. We are having some discussion internally about the future of command line scaffolding. I'm not sure if dnx gen will be the way or not yet. Give me about a week or so to gather more info.

**Comment by lkosidlo** [comment]
Hi, any more info about this one

**Comment by sayedihashimi** [comment]
Sorry for the delay here.

For scaffolding there are two high level scenarios.
 - Scaffolding from the command line
 - Scaffolding in Visual Studio

When we started scaffolding our goal was to create a command line scaffolding experience and then build the VS experience on top of that.

After working on the command line scaffolding experience, we realized that we need to take a step back to ensure that we have the right set of features there. At the same time many users are used to, and expect, a scaffolding experience in Visual Studio.

Our current plan is to shelve the command line support and focus on the in Visual Studio experience. At a later time we will revisit the command line scaffolding experience, and when we do we will update the in Visual Studio support to call those new command line scaffolders.

With that said, the Visual Studio support that we are currently working on building will use the gen package to execute scaffolding. The gen command won't be included in the templates. You can add the command to projects and invoke it from the command line, but that scenario won't be formally supported until we revisit command line scaffolding later.

**Comment by medhatelmasry** [comment]
Thanks for the update. I look forward to seeing this scaffolding feature in
Visual Studio and it was in previous versions of ASP.NET MVC.

**Comment by sayedihashimi** [comment]
@medhatelmasry I have added a click through at https://github.com/aspnet/Tooling/blob/master/specs/vs-scaffolding.pptx showing the proposed experience. It's basically exactly what we have for ASP.NET 4.

**Comment by sayedihashimi** [comment]
FYI I just posted the following as well https://github.com/aspnet/Announcements/issues/102 and https://github.com/aspnet/Scaffolding/issues/135.

Let's use https://github.com/aspnet/Scaffolding/issues/135 for any follow up here. I'll close this now.
