### ISSUE TITLE
Consider upgrading Gulp to version 3.9

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#215]
Hi,

Could you take into consideration bumping up Gulp tool version  from 3.8.\* to 3.9?
The Gulp based tasks are part of ASP.NET templates which are used by other tools like `generator-aspnet`.
People started complaining about using older version of Gulp in templates:
https://github.com/OmniSharp/generator-aspnet/issues/337

![Gulp warnings](https://cloud.githubusercontent.com/assets/10702007/9705184/a9ef02fc-5481-11e5-9f43-64af8b05a688.png)

Some other well known and used generators already switched to Gulp 3.9:
https://github.com/Swiip/generator-gulp-angular/commit/8822016f9ded04891d3785b360838f9256611602
https://github.com/yeoman/generator-gulp-webapp/blob/master/app/templates/_package.json#L10
The change should be transparent to the end users and tooling implementation I think:
https://github.com/gulpjs/gulp/blob/master/CHANGELOG.md
and after the change people will be able to add some ES6 sugar to VS tooling:
https://github.com/peterblazejewicz/aspnet5-web-gulp-babel-ts/blob/master/src-babel/gulpfile.babel.js

Thanks!

**Comment by BillHiebert** [comment]
@madskristensen

**Comment by sayedihashimi** [comment]
@madskristensen and @rustd are the right people to look at this. Thoughts?

**Comment by sayedihashimi** [comment]
TFS: 168978
I've added this to our internal TFS, we will reply back here soon.

**Comment by scottaddie** [comment]
@sayedihashimi @madskristensen Now that Gulp 3.9.1 has been released, I'd recommend skipping 3.9 and upgrading straight to this new version.

**Comment by peterblazejewicz** [comment]
No longer relevant as Gulp is no more part of default VS templating content
