### ISSUE TITLE
Will shared projects be supported in `xproj` projects?

### ISSUE THREAD

**Issue by TomasHubelbauer** [aspnet/Tooling#217]
In ASP .NET 4.5 one could hack the `csproj` file to include:

``` xml
<Import Project="..\SharedProject\SharedProject.projitems" Label="Shared" />
```

This would work just fine and as expected. Under references, the shared project would be visible, the code would be shared and so on. It is still a hack, but it feels only like a lack of tooling.

In ASP .NET 5, the `xproj` file can still be patched, but the shared project doesn't appear under _References_ and the code is not shared.

Will this change in the future? Are there plans to add support for shared projects to `xproj` projects? Preferably with the _References_ dialog offering the _Shared projects_ tab.

Redirected here from aspnet/dnx#2973.

**Comment by sayedihashimi** [comment]
We have an item on our backlog to support shared projects/linked files. We were hoping to get started on that by now, but we got side tracked by httpplatformhandler work. I'll check with the team and see when we might be able to get to that.

For now it sounds like you've found a way to workaround.

**Comment by TomasHubelbauer** [comment]
> For now it sounds like you've found a way to workaround.
For `csproj`, yes. For `xproj`, no; the reference system there is all reworked. Could you please confirm the item on your backlog covers `xproj` as well? (Or `xproj` only, I can live with patching `csproj`, but `xproj` I will not make work by patching.) Thanks.

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231254&fullScreen=false&_a=edit">231254</a>

**Comment by sayedihashimi** [comment]
Sorry for the delay here. We've had a lot of updates over the past few months and I believe that this is working now in VS2017 RC. Can you try with the latest VS2017 and try again? I'll close this now, but please reopen if this issue still persists.

**Comment by TomasHubelbauer** [comment]
No worries. I'm not going to try it myself anytime soon because it's not high on my priority list now but I welcome anyone coming across this with a bit of time to please confirm or deny.
