### ISSUE TITLE
Respect NuGet settings for package restore

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Tooling#218]
Xproj projectes ignore the settings below - 

We can change the second text to say automatic restore instead of automatic restore on build.

Right now trying to `git clean -xdf` from the command line, triggers a restore (which is completely unexpected once you drop to the command line). Unloading a solution or closing visual studio for that is painful.

![image](https://cloud.githubusercontent.com/assets/1238711/10467529/1f77a49e-71af-11e5-93b2-5147ca6c70df.png)

**Comment by sayedihashimi** [comment]
TFS: 153396
I've added this to our internal TFS, we will reply back here soon.

**Comment by abpiskunov** [comment]
Yes we need to have a setting that turns on/off automatic restore. What happened is when you did git clean , you killed your project.lock.json and tooling + DTH trigger restore to get it back.

**Comment by yishaigalatzer** [comment]
The settings exist just read it

-----Original Message-----

**Comment by barrytang** [comment]
This is fixed.
