### ISSUE TITLE
Bring back the right-click Set as Start Page option 

### ISSUE THREAD

**Issue by danroth27** [aspnet/Tooling#22]
In MVC 5 you could right-click a view and select Set as Start Page:

![set as start page](https://cloud.githubusercontent.com/assets/1874516/6622407/a27f94a6-c899-11e4-8b02-322f1de2f3b9.png)

We should bring this feature back for MVC 6.

**Comment by sayedihashimi** [comment]
We are working on it. **Hopefully** it will be in the next release.

**Comment by BillHiebert** [comment]
fixing this requires the browser link URL property we have for MVC 5 projects. I am not sure if that will make the next release or not, hopefully.

**Comment by sayedihashimi** [comment]
I think this was fixed, closing.
