### ISSUE TITLE
Remove DnxInvisibleContent: it's reduantant as Visible already exists

### ISSUE THREAD

**Issue by onovotny** [aspnet/Tooling#220]
I don't think there's any need to introduce a special "DnxInvisibleContent" item type to hide things in VS. Any item type can be hidden simply by adding a Visible=False sub-element underneath it.

See https://github.com/xunit/xunit/blob/master/src/xunit.core/build/xunit.core.props#L7 as an example.

To reduce complexity and unnecessary confusion with a new item type, please remove DnxInvisibleContent and just use the `<Visible>` node property.

Thanks

**Comment by sayedihashimi** [comment]
With ASP.NET 5 the files are not listed in the project file, so there is no item to attach Visible=false to. We apply that metadata in the in memory project file using DnxInvisibleContent

**Comment by onovotny** [comment]
So to be clear, that DnxInvisibleContent isn't persisted to the `xproj`? If it is, why can't it just add a regular content node at that point (on demand)?

**Comment by sayedihashimi** [comment]
DnxInvisibleContent is persisted in the .xproj. The reason why we don't let you specify items directly is because that would give the expectation that you can add other metadata values, and they wouldn't be respected. Instead we created a new item type to capture this specific need.

**Comment by onovotny** [comment]
I guess that makes a big more sense -- how about renaming it to just DnxInvisible then as DnxInvisibleContent seems to allude to the existing Content/None/Compile, etc item types?

**Comment by sayedihashimi** [comment]
If we did that we would have to migrate DnxInvisible to DnxInvisibleContent and then beta8 users can't work with people using future releases. So IMO there is not much return for that.

**Comment by onovotny** [comment]
I suppose migration is an issue, though it is beta and not RC. It's also a "behind the scenes" thing that most people probably won't see.

I guess I was just initially taken aback unexpectedly by the addition of an item type for invisible stuff instead of using an existing mechanism.

**Comment by sayedihashimi** [comment]
Thanks @onovotny for your comments. We'd still like beta8 users to be able to work with RC users even though it's prerelease.

Can we close this item?

**Comment by onovotny** [comment]
Sure
