### ISSUE TITLE
HttpPlatformHandler dumping log into wwwroot when running local IIS Express

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Tooling#224]
I just saw this `httpplatform-stdout_1192_2015101605037.log` file in my `wwwroot` folder after turning on logging with `stdoutLogEnabled="true"` in `web.config` ...
```
Process Id: 9412
Waiting for the debugger to attach...
Debugger attached.
Hosting environment: Development
Now listening on: http://localhost:29437
Application started. Press Ctrl+C to shut down.
```
It looks like when you run locally on IIS Express, the log gets dropped into `wwwroot`, so it will get published to the server later without an exclude in place. Is this by-design? 

On the server, the log goes into `<app_physical_path>\logs`. Seems like the log should go into `<project_root>\logs` in the project when running locally ... or somewhere else ... anywhere else given the browseability of `wwwroot`.

**Comment by sayedihashimi** [comment]
That's not good @dfowler @billhiebert

**Comment by GuardRex** [comment]
I'm checking now to see which command did that. Running IIS Express didn't do it. Running "web" didn't do it. Hold on a sec, I'm looking to see if that old "kestrel" command I used to have is what did this. brb

**Comment by GuardRex** [comment]
@sayedihashimi Indeed ... Yes! ... It is under IIS Express. You have to close the solution and re-open it to see the log files. Apparently, VS will not update the `wwwroot` contents in the UI until you close and re-open, but it is generating these log files there.

**Comment by BillHiebert** [comment]
if you want to change the path the logs are written to set the stdoutLogFile attribte. It takes a relative path or a full path by prefixing it with \\?\.
Examples;
stdoutLogFile="..\..\.vs\logfiles\Mylog"
stdoutLogFile="\\?\c:\logfiles\Mylog"

it is a little quirky in that the log filename is the trailing part of the path and then suffixed with a datetimestamp and extension. I believe the destination folder must already exist.

**Comment by BillHiebert** [comment]
Sorry, forgot about the markdown syntax. The prefix should be \\\\?\ (two leading slashes)

**Comment by GuardRex** [comment]
Ok, so this is by-design, but maybe the templates should default people to that better path?

**Comment by BillHiebert** [comment]
Correct. We'll probably default them to somewhere under the .vs folder.

**Comment by GuardRex** [comment]
The .vs folder isn't in my project, which is just because this app goes way back to like beta4 and I was on Brackets back in those days. Is the .vs folder in the project root (same path as `project.json`, etc.)?
```
stdoutLogFile="..\.vs\logs\httpplatform-stdout"
```

**Comment by GuardRex** [comment]
I did just notice that you have to supply the prefix (e.g., I have `httpplatform-stdout` there), and it's coming out `httpplatform-stdout_13036_2015101622589.log`.

They don't appear automatically in the VS UI. I have to browse the folder to see them.

**Comment by sayedihashimi** [comment]
@billhiebert I fixed the formatting for you above.

**Comment by GuardRex** [comment]
@BillHiebert I don't see VS making `.vs` folders in my projects. What path should it be? I'd like to put this into my "Moving to HttpPlatformHandler-IIS" guidance at: https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294, because I show the `web.config` file there, and I'd like to have that bit in there.

**Comment by BillHiebert** [comment]
VS creates the .vs folder in the same location as the .sln file. It is hidden (not sure why) so you need to show hidden files to see it.

**Comment by GuardRex** [comment]
@BillHiebert Ah, I see. I was able to reach it with ...
```
stdoutLogFile="..\..\..\.vs\logs\httpplatform-stdout"
```
... and like you said, the `logs` folder has to be there or else it won't write the file.

I wonder how this would work for the server environment though. I exclude `.vs` from publish, so the `logs`folder wouldn't be there.

I think what I'll do for now is stick with my `logs` folder in the project. It shows up in the VS UI where I can see it, and I just right-click and browse the folder to see the log files, since VS doesn't update the folder contents on-the-fly. When this goes to the server, they end up at ...
```
F:\<app_folder>\approot\packages\<app_name>\1.0.0\root\logs
```
... which is easy enough to find. Since I'm publishing with the `logs` folder, the folder ends up there on the server and logs will go there.

I'm good now ... thanks for your help.
