### ISSUE TITLE
Don't blindly change the "web" command to Kestrel

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Tooling#231]
I have a project where `"web": "Microsoft.AspNet.Hosting --server Nowin.Vnext"` is configured. During the update to beta8, this was changed to `"web": "Microsoft.AspNet.Server.Kestrel"`, which is quite rude.

**Comment by Tragetaschen** [comment]
Ok, VS is changing this *all the time* even immediately after I have changed it in the IDE. Obviously the "web" command is supposed to be Kestrel any nothing else. I'll change my real command then…

Very rude.

**Comment by sayedihashimi** [comment]
@BillHiebert maybe we can store a property somewhere to not do the change again?

**Comment by sayedihashimi** [comment]
@Tragetaschen starting in beta8 VS requires the web command, and that it's configured to use Kestrel. If the command is not there it will create it and configure it.

I understand that you don't like this, but what issues is it causing you? You can always create another command with a different name.

**Comment by Tragetaschen** [comment]
Don't worry about it. You are right in that I can just use a different command and I do that already. This just caught me by surprise as I only saw it after I had deployed the application and then VS kept changing what I just typed.

An announcement would have been nice, or any hint that this requirement is actively enforced.

As I said: Rude, but definitely not problematic.

**Comment by sayedihashimi** [comment]
FYI starting in the release after beta8 if there is a web command it will be left unmodified.

I'll close this now.
