### ISSUE TITLE
[beta8] Error on opening 

### ISSUE THREAD

**Issue by ycrumeyrolle** [aspnet/Tooling#232]
I have installed the beta8 tools (DNVM & WebTools) on VS2015.
The following message is displayed at the project opening, on any ASPNET5 project (new & older):

>The following error occured attempting to run the DNX design time process (dnx-clr-win-x86.1.0.0-beta8).

>Unable to start the process. 
>System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Framework.DesignTimeHost' or one of its dependencies. The system cannot find the file specified. Filename: 'Microsoft.Framework.DesignTimeHost'
>System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, string codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMarc, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSe ...

>The DNX design time process provides intellisense, build, and reference information to Visual Studio and without it your experience will be very limited. Please try closing and reopening Visual Studio to see if that corrects the problem. Alternatively, check that the 
DNX version is properly installed or try changing to a different installed DNX version using the project property pages.

I have tried unsuccessfully to uninstall the web tools, uninstall dnvm, repair VS2015, reinstall DNVM & web tools, repair Web Tools & DNVM, clean the %APPDATA%\Microsoft\VisualStudio\14.0\ComponentModelCache folder.

**Comment by sayedihashimi** [comment]
@joeloff @BillHiebert any ideas here?

**Comment by sayedihashimi** [comment]
@ycrumeyrolle a few questions.

 - What's in the folder at `C:\Program Files (x86)\Microsoft Web Tools\DNX`? It should just have beta8 items after installing beta8
 - What's in the folder at `C:\Users\sayedha\.dnx\runtimes`?

**Comment by ycrumeyrolle** [comment]
`C:\Program Files (x86)\Microsoft Web Tools\DNX`
>dnx-clr-win-x64.1.0.0-beta8
>dnx-clr-win-x86.1.0.0-beta8
>dnx-coreclr-win-x64.1.0.0-beta8
>dnx-coreclr-win-x86.1.0.0-beta8
>dnx-clr-win-x64.1.0.0-beta8.nupkg
>dnx-clr-win-x86.1.0.0-beta8.nupkg
>dnx-coreclr-win-x64.1.0.0-beta8.nupkg
>dnx-coreclr-win-x86.1.0.0-beta8.nupkg

`C:\Users\me\.dnx\runtimes`
>dnx-clr-win-x64.1.0.0-beta8
>dnx-clr-win-x86.1.0.0-beta8
>dnx-coreclr-win-x64.1.0.0-beta8
>dnx-coreclr-win-x86.1.0.0-beta8
>temp

The temp folder is empty

**Comment by BillHiebert** [comment]
This is odd. The name that is specified in the error is the old name of the DesignTimeHost. It was renamed in Beta7 to Microsoft.Dnx.DesignTimeHost from Microsoft.Framework.DesignTimeHost. It seems like you are running an old version of the tooling though the contents of Microsoft Web Tools\DNX shows otherwise. You don't happen to have the WEBPROJ_ENABLEBETA7RENAMES environment variable set, do you?

**Comment by ycrumeyrolle** [comment]
WEBPROJ_ENABLEBETA7RENAMES was set to 0...
Set to 1, restart VS : OK
Removed the variable, restart VS : OK
Reset the variable to 0, restarted VS : OK

**Comment by BillHiebert** [comment]
Remove that variable. Setting it to 0 is an override to use the pre beta7 names.

**Comment by ycrumeyrolle** [comment]
This is what I finally done.
Thanks for your support.
