### ISSUE TITLE
Clean should delete project.lock.json

### ISSUE THREAD

**Issue by benaadams** [aspnet/Tooling#233]
Not 100% sure on this; but shouldn't the `Build->Clean Solution` also delete the `project.lock.json` files? For a start build from fresh scenario?

There are occasional situations where you have to manually delete them (referencing an unreferencing external projects; changing versions etc)

**Comment by sayedihashimi** [comment]
Hi @benaadams thanks for the note. There are scenarios where `project.lock.json` is checked in, so I'm not sure if it makes sense to delete this file on clean. What issues is the file causing you?

**Comment by benaadams** [comment]
For example adding a new `src` path in `global.json` doesn't always pick up the external project dependency although it does always run a resolve. (Don't unfortunately don't have re-creatable steps)

Deleting the lock file resolves this.

**Comment by sayedihashimi** [comment]
@benaadams that sounds like a specific bug. I know we had some issues around watching files in the past (_and I think we still have some lingering issues that we are planning to work on_). I don't think we should look at deleting `project.lock.json` to solve that specific issue.

If you can reproduce modifying `global.json` and it not being detected please file an issue with repro steps.

I'd like to close this item, let me know if you'd like to discuss it further.

**Comment by benaadams** [comment]
Sure as that would be a different bug; will report back if I get a repo.

**Comment by BillHiebert** [comment]
ASP.NET 5 projects don't do anything on clean. This has been on the backlog for a while.
