### ISSUE TITLE
how to set -allowUntrusted while using VS to publish asp.net 5 website?

### ISSUE THREAD

**Issue by doradaddy** [aspnet/Tooling#235]
how to set -allowUntrusted while using VS to publish asp.net 5 website?

or where I can pass -allowUntrusted to msdeploy in VS?

**Comment by sayedihashimi** [comment]
@vijayrkn are we missing a feature around untrusted certificates? IIRC in WAP projects we do some auto detection relating to the certificate. Do we not have that for ASP.NET 5?

@doradaddy to work around this you can manually add a property to the publish profile (`.pubxml` file under `Properties\PublishProfiles`).

```xml
<AllowUntrustedCertificate>true</AllowUntrustedCertificate>
```

If you add that and it still doesn't work then you may need to update the version number in the `.ps1` file sitting next to your `.pubxml` file. You can update it to that latest which is `1.0.2-beta2`. Note: there may be multiple places in the .ps1 file that need to be updated. If you try that and have issues please let me know.

**Comment by doradaddy** [comment]
@sayedihashimi Thanks. It works now.

**Comment by sharabiania** [comment]
After updating the module version to `1.0.2.-beta2` in the `.ps1` file, I get this error: `The specified module '...\package-downloader\publish-module.10.2-beta2\tools\publish-module.psm1' was not loaded because no valid module file was found in any module directory.`

**Comment by mguinness** [comment]
@sharabiania Check that you have nuget.org setup as a package source.
