### ISSUE TITLE
Localization not working in MVC6 Controller (VS)

### ISSUE THREAD

**Issue by damienbod** [aspnet/Tooling#236]
If I start an ASP.NET 5 application beta8 with Localization in Visual Studio, the  localization does not work, only the default is used. If I start the same application from the console, the localization works.

Here's the Localization issue:
https://github.com/aspnet/Localization/issues/115

Greetings Damien

**Comment by sayedihashimi** [comment]
@damienbod can you provide steps to reproduce the issue?

**Comment by damienbod** [comment]
Hi @sayedihashimi 
Thanks for your answer.
Here's a project to use:
https://github.com/damienbod/AspNet5Localization

Step 1 start from VS 
Step 2 http://localhost:13572/api/about/?culture=fr-FR (Or port 5000)
Step 3 http://localhost:13572/api/about/?culture=de-CH (Or port 5000)
bug: step 2 and 3 should return different strings based on the culture

Step 1 start from Console
Step 2 http://localhost:5000/api/about/?culture=fr-FR
Step 3 http://localhost:5000/api/about/?culture=de-CH
All ok

Greetings Damien

**Comment by sayedihashimi** [comment]
TFS: 156642
I've added this to our internal TFS tracker. We will update this when we have a chance to investigate it.

**Comment by SirajArMVT** [comment]
I have same issue 

How to set default culture as browser culture?

**Comment by damienbod** [comment]
@sayedihashimi @SirajArMVT I've just created a global issue for this, my you could give your views here

https://github.com/aspnet/Home/issues/1142

Greetings Damien

**Comment by sayedihashimi** [comment]
One of the issues that we have is that the .resx generator creates with `internal` now. We are going to switch that to `public` and I think that should help this scenario.

**Comment by sayedihashimi** [comment]
Should be fixed in the next release, closing now.
