### ISSUE TITLE
CTRL + F5 with dnx-watch support ?

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#238]
how can I use visual studio `CTRL` + `F5` to run using `dnx-watch` instead of `dnx` ?

**Comment by sayedihashimi** [comment]
@BillHiebert thoughts?

**Comment by sayedihashimi** [comment]
TFS: 174135
I've added this to our internal TFS, we will reply back here soon.

**Comment by Stev3nT** [comment]
Any news on this?

**Comment by sayedihashimi** [comment]
dnx watch is being replaced with `dotnet watch`. I'm not sure if it will work with VS or not TBH at this time. If `dotnet watch` doesn't work in VS then I think the best thing to do is to open an issue at https://github.com/dotnet/roslyn-project-system. I'll close this item now.
