### ISSUE TITLE
problems debugging async in mvc?

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#24]
I haven't debugged mvc sources before, so I'm not sure is a bug.
I'm using ctp 6, main feed, cloned source from beta 3, and added mvc sources to a web starter app.
I'm debugging the startup process of the application to arrive to the display of the initial.
I am in the **public virtual async Task InvokeAsync()** method of the **FilterActionInvoker** class, and I see the call to **await InvokeAllAuthorizationFiltersAsync();**.
I step into method and debug every step using F10 keystroke, and arrive to the end of the routine: at this point, using neither **f10** or **shift F11** you can return to the InvokeAsync method, and the execution of the program continues and the page is shown.
If I place a breakpoint after the call to InvokeAll.. inside the InvokeAsync I can continue to debug

**Comment by sayedihashimi** [comment]
In beta3 there were issues around getting the sources added correctly and to ensure the correct sources were picked up. I believe that has been fixed for beta4 but not 100%. Could you try with VS2015RC and let me know if it still is an issue. I'll close this now, but if it's still happening please re-open.
