### ISSUE TITLE
Support debugging of JS executed with EdgeJS in VS

### ISSUE THREAD

**Issue by Lenne231** [aspnet/Tooling#240]
We would like to do the server side HTML rendering with ReactJS in our ASP.NET application. This works with EdgeJS, but there is currently no way to debug the JS code in VS. 

It would be nice if this would work and we wouldn't need node-inspector for this.

https://github.com/tjanczuk/edge/issues/316

**Comment by sayedihashimi** [comment]
I believe that this is not planned on being supported. Let's see if @BillHiebert knows?

**Comment by Lenne231** [comment]
MS seems to work on a solution for server side rendering with ASP.NET 5 and EdgeJS, so what are the plans for debugging/tooling?

https://github.com/aspnet/NodeServices/issues/5

**Comment by oceanmountain** [comment]
Hello!

 

You have a new message, please read <http://dukla.sk/private.php?9rr>

 

kay@oceanmountain.nl

**Comment by sayedihashimi** [comment]
I think @madskristensen is looking at node debugging, but not 100% sure.

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231250&fullScreen=false&_a=edit">231250</a>

**Comment by AngelosP** [comment]
We are actively working on this. We will be updating this issue when we ship it.

**Comment by AngelosP** [comment]
This capability shipped with the latest [Visual Studio preview](https://www.visualstudio.com/vs/preview/), but please keep in mind that at time of writing you need to be part of the Windows insider program to have a build of Windows that supports it. Thank you for helping us build a better Visual Studio!
