### ISSUE TITLE
VS 2015 is looking xml-documentations

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Tooling#241]
When referencing an DLL that is created in the artifacts-directory from another solution that only have csproj VS is locking the xml-documentation. To be able to rebuild the project that created the artifacts the other VS instance need to be closed.

Repro steps
1. Open VS and create a new ASPNET5 class project
2. Set the project to generate outputs
3. Add target framework for net451
4. Add some class with documentation
5. Compile the solution
6. Open another VS and create a new CS-project targeting .net 451
7. Make a file-reference to the artifacts that was generated in step 5
8. Create some class that will use the class created in step 4
9. Compile the solution
10. Make some change in class created in step 4
11. Compile the first project to generate new artifacts

In the above steps the step 11 will fail because the previous generated xml-documentation is locked by the other instance of VS.

**Comment by sayedihashimi** [comment]
TFS: 162812
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
@Tasteful sorry for the delay here.

Can you clarify what you are doing in step `#7`? I'm not following exactly what you are doing and want to make sure I'm looking at the right thing here.

**Comment by Tasteful** [comment]
@sayedihashimi I context-click in the solution explorer on the "References" node, select "Add references...". Click on browse and select the artifact that is generated in step 5. 

![image](https://cloud.githubusercontent.com/assets/357589/11515996/2896c91c-9881-11e5-9043-c42989295ede.png)
dialog where selecting the reference as capture below

**Comment by markw-t** [comment]
@Tasteful can you tell me if you are using Visual Studio 2015 RTM? If so can you try updating to Update 1 because we fixed a very similar-sounding bug in this area in the update. Thanks!

**Comment by Tasteful** [comment]
@markw-t I'm using the latest Update 1. During the time when I reported the bug I was using beta/rc version of update 1 downloaded here from github.

I will try again and see if the problem still exist.

**Comment by Tasteful** [comment]
@markw-t I can't reproduce this issue any more. I will close this issue and if it pops up again I will reopen it.

**Comment by markw-t** [comment]
@Tasteful thanks for the info and for letting me know this no longer repros for you. I'll close the internal issue tracking this but will reopen if you or others can repro on VS2015 Update 1 RTM bits.
