### ISSUE TITLE
How can I rename html and TypeScript files when my ASP.NET 5 project is running?

### ISSUE THREAD

**Issue by cveld** [aspnet/Tooling#242]
Refer to http://stackoverflow.com/questions/33267588/how-can-i-add-or-rename-files-in-visual-studio-while-the-project-is-running
I would like to know how I can rename html and TypeScript files when my ASP.NET 5 project is running. Apparently I can only add new files but not rename them. I am currently developing a ASP.NET 5 web application and I continuously need new TypeScript files or html files. It is a pain to always have to stop and start the project again.

I have a gulp watcher running that copies all html changes and compiles all TypeScript files into one app.js towards wwwroot.

**Comment by sayedihashimi** [comment]
TFS: 162811
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
Just to make sure that I understand you. You are running into this when you are ***Debugging*** the application right? If you were to run (i.e. CTRL+F5) you should be able to add/rename/move files as much as needed.

**Comment by cveld** [comment]
That's correct! In non-debugging-run-mode I can do add/rename/move as much
as I like. In debug-mode I can add new files, but I cannot rename them.
Outside Visual Studio this is perfectly possible though. So that's my
current workaround.

2015-12-01 23:06 GMT+01:00 Sayed Ibrahim Hashimi <notifications@github.com>:

**Comment by mlorbetske** [comment]
From the linked TFS item, it seems that there hasn't been enough interest expressed in this capability for it to be pursued. If you feel that that decision should be re-evaluated, please post an issue on the [Developer Community](https://developercommunity.visualstudio.com/) site.
