### ISSUE TITLE
Browserlink can cause deadlocks in Web API calls

### ISSUE THREAD

**Issue by Mertsch** [aspnet/Tooling#248]
Consider the following scenario

```
Microsoft.VisualStudio.Web.BrowserLink.Runtime.dll!Microsoft.VisualStudio.Web.BrowserLink.Runtime.HttpAdapterRequestStream.Write
[External Code]  
<ProjectName>!<ProjectName>.Controllers.NotificationController.GetAllAfter(ulong notificationId) Line 29     
[Resuming Async Method]  
[External Code]  
<ProjectName>!<ProjectName>.Services.NotificationService.Publish(string type, int itemId, string messsage) Line 38   
<ProjectName>!<ProjectName>.Services.ItemService.DoSomethingWith(int itemId, int userId) Line 186    
<ProjectName>!<ProjectName>.Controllers.ItemController.DoSomethingWith(int itemId) Line 72   
[External Code]  
```

`ItemController.DoSomethingWith` is called from the client, performs some operations and goes to the notification service. The notification service has a certain amount of subscribers, waiting to be notified (answering their requests).

The call stack shows a path within the application that could never happen in code, as only external clients can call a controller, never a service.
But this helper module does, which therefore causes a deadlock within my notification controller, which uses a lock to protect its data from concurrent access.

Note that I have a pure Web API project with no HTML pages ever rendered
Using ASP.NET 1.0.0-beta8

**Comment by BillHiebert** [comment]
@madskristensen @jodavis

**Comment by sayedihashimi** [comment]
TFS: 162789
I've added this to our internal TFS, we will reply back here soon.
