### ISSUE TITLE
Renaming files or folder in C# Web Application (4.5.2) cause VS2015 to hang

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Tooling#250]
When I rename files and folder to get a good structure VS 2015 often hang itself and need to kill the process in task manager. 

Is this a common known error?

VS System Info
```
Microsoft Visual Studio Enterprise 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00079

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA094
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

Visual Basic 2015   00322-80000-00000-AA094
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA094
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA094
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015 (Beta8)   14.0.61012.0
ASP.NET and Web Tools 2015 (Beta8)

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

AttachTo   1.0
Adds "Attach to IIS" and "Attach to NUnit" Tools menu commands.

Common Azure Tools   1.6
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Flatten Packages   1.0.9
Flattens the node_modules folder hierarchy by using the "flatten-packages" npm package behind the scenes. Works with long paths

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GhostDoc   4.9.15086.0
GhostDoc automatically generates XML documentation comments.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

GruntLauncher   1.1
Right click extension to launch Grunt commands

JetBrains ReSharper Ultimate 2015.2   Build 103.0.20150818.200216
JetBrains ReSharper Ultimate package for Microsoft Visual Studio. For more information about ReSharper Ultimate, visit http://www.jetbrains.com/resharper. Copyright © 2015 JetBrains, Inc.

Microsoft Azure HDInsight HQL Service   2.0.2600.0
Language service for Hive query

Microsoft Azure HDInsight Tools for Visual Studio   2.0.2600.0
An integrated development environment for HDInsight application development.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.7
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601

Microsoft Code Digger   0.9
Microsoft Code Digger

Microsoft Team Foundation Server 2015 Power Tools   14.0
Power Tools that extend the Team Foundation Server integration with Visual Studio.

Microsoft Visual Studio Process Editor   1.0
Process Editor for Microsoft Visual Studio Team Foundation Server

Microsoft.Pex.VisualStudio   1.0
Pex

NuGet Package Manager   3.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Open Command Line   2.0.157
Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc.

OsirisAssociateRecentWorkItems   1.0
Osiris Associate Recent Work Items

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

RoamedExtensionVSPackage Extension   1.0
RoamedExtensionVSPackage Visual Studio Extension Detailed Info

SQL Server Data Tools   14.0.50730.0
Microsoft SQL Server Data Tools

TFS Source Control Explorer Extension   1.0
Visual Studio Extension for Team Foundation Server Source Control Explorer

TFS Source Control History Visualization   2.0
An Visual Studio extension to visualize TFS source control history.

Visual Studio Window Title Changer   2.1.7
Changes the Visual Studio Window Title by evaluating a user defined expression.

Copyright (c) 2013 István Pásztor

Visual Studio Gallery Page of this extension:
http://visualstudiogallery.msdn.microsoft.com/2e8ebfe4-023f-4c4d-9b7a-d05bbc5cb239

The project is opensource released under the terms of The MIT License:
http://code.google.com/p/vs-window-title-changer/
```

**Comment by sayedihashimi** [comment]
Do you have a solution that reproduces this consistently? If so could you share that plus the steps to reproduce?

**Comment by BillHiebert** [comment]
Any chance you could grab a dump file when VS is hung?

**Comment by Tasteful** [comment]
@sayedihashimi 
I can reproduce the hang in my solution, it contains around 3100 files (aspx, aspx.cs, aspx.cs.designer and a lot of static images). As version control we use TFVC. I can't share this project because it is owned by my work but I will try to setup another solution and hope that I can reproduce it in that also.

@BillHiebert 
If you mean an regular "Create memory dump" from task-manager I can fix that, or if you provide other steps you wan't me to do. How can I transfer the memory-dump to you? (I will not put a public link here)

**Comment by BillHiebert** [comment]
Sounds like this isn't an asp.net 5 project since you have aspx files.  Or do you have both asp.net 5 and webforms projects in your solution.

As for getting a dump, I usually start another instance of VS, attach to the first and break. You can use the Debug\ Save dump file menu command to save the dump.  Can you zip it up and put it on OneDrive?

**Comment by Tasteful** [comment]
I was creating a memdump that I'm uploading right now, my upload speed is not the best so it will take 1h more before it is uploaded. You can then find the dump on https://dl.dropboxusercontent.com/u/16590863/devenv.7z (please tell me when you have downloaded the dump so I can remove that from the public url)

The project is a csproj but I reference output from an xproj because the tooling not support referencing an xproj from the csproj.

**Comment by BillHiebert** [comment]
I started a download but it says it is going to take 7 hours!. Let's hope not.

**Comment by Tasteful** [comment]
Today I found out the "Analyze wait chain" tool inside windows task manager and that is saying the following when the process application is hanging
![image](https://cloud.githubusercontent.com/assets/357589/10908043/00821b74-822f-11e5-8549-a2972411563e.png)

I attached another VS instance and debugged the VS that not was responding any more and regarding to the thread 18664 the hang is regarding to Jetbrains Resharper
![image](https://cloud.githubusercontent.com/assets/357589/10908074/3a801916-822f-11e5-810f-f2d924ab82b4.png)

I will report this bug directly to Jetbrains.

**Comment by sayedihashimi** [comment]
@Tasteful ok so you've narrowed this down to be related to R#? Is there anything needed for us to investigate?

**Comment by Tasteful** [comment]
I have opened a support ticket at Jetbrains and hope that they can narrow it down. If they found that it's not related to R# I will come back and reopen this issue.

**Comment by Tasteful** [comment]
Today I got answer back from Jetbrains after they have analysed mem-dumps.

> According to the file, MSbuild blocks UI which was called by VS API. It seems like you experience the same issue as described here https://youtrack.jetbrains.com/issue/RSRP-450181. It happens only for users with VS2015, since there is Roslyn which allocates a lot of memory in devenv.exe process as well as ReSharper does. We are going to contact MS Team about possible solution how R# can live in VS2015 alongside with Roslyn without causing such issue.
