### ISSUE TITLE
Support for multiple srcset options.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#253]
in the case of `<img srcset="">` you get intellisense for the first argument, but when you type `,` and try to add another argument it gets in the way of the developer, kinda annoying.

sample src tag:
```
<img srcset="~/images/ASP-NET-Banners-02.png 1x, ~/images/ASP-NET-Banners-02 2x" />
```
writting that sometimes is annoying intellisense tries to always keep the first argument.

----
also, that sample won't work, because the ~ is not respected for 2nd argument. it must be written as:
```
<img srcset="~/images/ASP-NET-Banners-02.png 1x, @Url.Content("~/images/ASP-NET-Banners-02") 2x" />
```

**Comment by sayedihashimi** [comment]
TFS: 162787
I've added this to our internal TFS, we will reply back here soon.

**Comment by madskristensen** [comment]
Fixed

**Comment by Bartmax** [comment]
@madskristensen should I enable this somehow or is it planned for next update? im currently on 14.0.24720.00 Update 1

**Comment by madskristensen** [comment]
It's coming in the next release. Probably the ASP.NET RC2 tooling release

**Comment by Bartmax** [comment]
:+1:
