### ISSUE TITLE
Where is code analysis in Beta8?

### ISSUE THREAD

**Issue by ForkBug** [aspnet/Tooling#255]
I couldn't find it.
A test case failed due to a mistake. This type of mistake would lead to warnings for traditional C# programs.

**Comment by RehanSaeed** [comment]
Is there any reason why this issue was closed? The linked issue was also closed. I suspect this is a mistake.

**Comment by alexdresko** [comment]
@RehanSaeed This issue is still open.

**Comment by sayedihashimi** [comment]
Analyzers are not supported in the dnx runtime yet, see https://github.com/aspnet/dnx/issues/2311#issuecomment-139845910. Once it gets added we can investigate adding support in VS.

**Comment by sayedihashimi** [comment]
Closing this this is a runtime issue and is being tracked at https://github.com/dotnet/cli/issues/83
