### ISSUE TITLE
Class Diagram Integration

### ISSUE THREAD

**Issue by wangkanai** [aspnet/Tooling#256]
Could you please add class diagram integration within the asp.net 5 project system like the old full .net framework
![class-diagram](https://cloud.githubusercontent.com/assets/10666633/10853316/0f70f5de-7f68-11e5-9248-1e42d5230aad.png)
![class-diagram-project](https://cloud.githubusercontent.com/assets/10666633/10853326/1761112a-7f68-11e5-91ea-ce6c6f73dc08.png)

**Comment by sayedihashimi** [comment]
TFS: 162784
I've added this to our internal TFS, we will reply back here soon.

**Comment by mlorbetske** [comment]
From the linked TFS item, it appears that this has been marked as fixed. If you're still running in to this, please report the issue on the [Developer Community](https://developercommunity.visualstudio.com/) site
