### ISSUE TITLE
ASP .NET 5 Web App Template in VS 2015 Community Edition

### ISSUE THREAD

**Issue by mchamo** [aspnet/Tooling#258]
Hello,

I have noticed that once a new beta version of ASP .NET 5 comes out, and I install it, when I create a new web application using the ASP .NET 5 web application templates in VS 2015 community edition, the template is always created using the version of ASP .NET 5 that I had before installing the new update.  For example, I used to have beta 5 installed, so my template applications were being created with beta 5 references.  Now that I upgraded to beta 8, the default template application/site is still created with beta 5 references, which causes me to have to manually update the references in project.json, startup.cs, etc. each time in order to use beta 8.  The ASP .NET 5 templates should be smart enough to use the latest beta version installed on the machine.

I attended the DevIntersection conference in Las Vegas last week, and mentioned this issue to Damian Edwards, who presented a couple of sessions on ASP .NET 5, and he recommended that I submit a bug here.

Thank you for you consideration,
Milad

**Comment by BillHiebert** [comment]
@joeloff

**Comment by joeloff** [comment]
@mchamo If you look at Help/About in Visual Studio, what version does it show for Microsoft ASP.NET and Web Tools?

**Comment by mchamo** [comment]
@joeloff for ASP .NET and Web Tools, I have version 14.0.20626.0.  Let me know if you have further questions.

**Comment by joeloff** [comment]
That is the Beta 5 build of Web Tools that shipped with VS2015 RTM in July. You will need to upgrade the Web Tools component to Beta 8. Take a look at http://www.microsoft.com/en-us/download/details.aspx?id=49442 and download the Web Tools Extension MSI and install that. Make sure that VS is closed when you run the install

**Comment by mchamo** [comment]
@joeloff yes, that worked.  Thanks for your prompt responses.

**Comment by joeloff** [comment]
@mchamo You're welcome.
