### ISSUE TITLE
Task Runner Explorer: "Sequence contains no elements"

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#259]
I'm seeing 2 occurrences of the following error in the Output tab's "Task Runner Explorer" view:

Failed to run "C:\working_folder\WebApplication1\package.json"...
Sequence contains no elements

I'm using the Beta 8 tooling. The "Web Application" project template was used from the "ASP.NET 5 Preview Templates" grouping. This error appears immediately after creating or opening the project.

![package_json_error](https://cloud.githubusercontent.com/assets/10702007/10886517/f4abdf02-8147-11e5-9733-dbca3476f683.png)

**Comment by BillHiebert** [comment]
@jodavis @raquelsa

**Comment by sayedihashimi** [comment]
TFS: 162780
I've added this to our internal TFS, we will reply back here soon.

**Comment by madskristensen** [comment]
This is an issue in the NPM Scripts Task Runner extension that I fixed already
