### ISSUE TITLE
Conflict with global bower and local bower

### ISSUE THREAD

**Issue by jhubsharp** [aspnet/Tooling#26]
I am noticing that VS has problems if I try to install a local version of bower that is different from the version installed with VS. Looks like 1.3.8 gets installed when I install VS but if I try to use an earlier or later version locally, VS tooling has a problem showing bower packages in the Dependencies folder or trying to get package intellisense from bower.json it fails (I get "Unavailable" when trying to get intellisense). If I remove the local bower pulled from NPM it works fine.

This is a problem because we have devs on non-Windows environments who aren't relying on having Bower installed globally. I can move the order of sources around in the "Configure External Tools" dialog but it doesn't seem to help.

**Comment by sayedihashimi** [comment]
@madskristensen ?

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231352&fullScreen=false&_a=edit">231352</a>

**Comment by mlorbetske** [comment]
Hi @jhubsharp - are you still running in to this?

**Comment by mlorbetske** [comment]
Since we haven't heard back, I'll close this. There will likely be some changes in this space as well due to bower's [deprecation notice](https://github.com/bower/bower/issues/2298)
