### ISSUE TITLE
IISPlatformHandler's Debug request reaches the users application

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Tooling#261]
If you have the following in your startup application:

```C#
app.Run(async (context) =>
{
    await context.Response.WriteAsync("Hello World!");
});
```

You'll see the middleware be invoked twice.

**Comment by Eilon** [comment]
Hmm why is this a tooling bug?

**Comment by NTaylorMullen** [comment]
Tooling is the one performing two requests :smile:.

1. The normal page request when hitting F5
2. An extra `DEBUG` request to kick start DNX and attach.

**Comment by Eilon** [comment]
I don't think tooling will stop sending the DEBUG request - it has to do that. Is the bug that the request makes it past some DNX/Hosting thing?

**Comment by NTaylorMullen** [comment]
From talks with @BillHiebert it sounded like tooling could write a nativish module to eat the request.

**Comment by Eilon** [comment]
Ah ok...

**Comment by sayedihashimi** [comment]
Is there any action needed here? I think @BillHiebert may have already fixed this but not totally sure.

**Comment by BillHiebert** [comment]
I think the fix would need to occur in middleware. I don't see how tooling can fix this as we need to send a request to get the httpPlatformHandler to start dnx.exe.

**Comment by Eilon** [comment]
@davidfowl @Tratcher any thoughts on this? Can/should we block the DEBUG request from VS at some early layer? I think this might be what's happening here: https://github.com/aspnet/Mvc/issues/3585

**Comment by Tratcher** [comment]
This would be easy for the UseIISPlatformHandler middleware to eat.

**Comment by NTaylorMullen** [comment]
@Tratcher Is it possible to do it earlier? This problem occurs with any server as long as you start it with debugging.

**Comment by Tratcher** [comment]
It's possible, but I don't recommend it. This is specific to IIS/Express and VS.  UseIISPlatformHandler is the second item in our templates after the debugging tools: https://github.com/aspnet/Templates/blob/dev/src/BaseTemplates/StarterWeb/Startup.cs#L49

**Comment by NTaylorMullen** [comment]
Still dependent on where you put it though :/

**Comment by Eilon** [comment]
`UseIISPlatformHandler` has to be super early to work at all.

**Comment by sayedihashimi** [comment]
Is there any tooling work pending here?

**Comment by Tratcher** [comment]
Yes, but we've clearly never closed on the design.

**Comment by Tgueth** [comment]
Because of this "double start", I get an EF error on the second start because it says that EF is in the state of initializing.  So either I need a way to initial EF in Startup (which I don't think is a good idea, but still learning EF) or as way to only keep HomeController from being called just once.

So far, I have not found a solution.  Since this occurs only in debug mode, then obviously a MS ASP.NET5 or MVC6 issue in what it starts.

**Comment by dg9ngf** [comment]
It's still in RC2. So how can I detect it and not start off expensive external tasks two times in parallel? They sometimes end up colliding and all falls apart before it has begun. Very frustrating. Why is anybody doing two requests at all? I don't see any reason in that. After starting the debugging, my web browser opens the first URL. No other instance should request anything from the web application.

**Comment by Tratcher** [comment]
The debugger is sending a DEBUG request to make IIS Express launch the site so it can attach. A simple inline middleware at the top of your Startup.Configure method can filter it out:
```
app.Use((context, next) =>
{
  if (string.Equals(context.Request.Method, "DEBUG"))
  {
    return Task.FromResult(0);
  }
  return next();
});
```

**Comment by dg9ngf** [comment]
Yep, that code fixes to issue. Thanks!

**Comment by dg9ngf** [comment]
Does that mean we'll all have to insert this code to fix a debugger annoyance with the framework? I'm waiting for the first NuGet package to arise that does it. :-p

**Comment by Tratcher** [comment]
@dg9ngf no: https://github.com/aspnet/IISIntegration/pull/194
