### ISSUE TITLE
Hide from Solution Explorer - Rename Folder/File

### ISSUE THREAD

**Issue by VaclavElias** [aspnet/Tooling#262]
This new handy feature comes with one disadvantage that you cannot rename hidden folder/file from the Solution Explorer. You have to click "Show in Solution Explorer" rename file/folder and hide again.

**Functional impact**
1) More clicks, less productivity

**Expected result**
1) Rename option when you right click on the hidden item or
2) When you click on the name of the file/folder you can edit the item name
- simply, behaving same like when it is not hidden when you want to rename it

**Actual result**
1) No rename option when you right click on the hidden item
2) Nothing happens when you click on file/folder to rename it

Visual Studio 2015 Community, ASP.NET 5.0, Beta 8

**Comment by sayedihashimi** [comment]
Thanks @VaclavElias I noticed that in a standard C# project you can rename excluded files. We should have the same ability for ASP.NET 5 projects.

I've opened a bug in our internal tracker. Someone should reply back here soon.
TFS: 162725

**Comment by abpiskunov** [comment]
In U1 it automatically got fixed, since we using new CPS functionality and all files are in the project (before they were excluded from project, now they have Visible=false metadata). This makes them editable when you see them in Solution Explorer with "Show all files" pressed
