### ISSUE TITLE
In Solution Explorer > Right-Click Controllers Folder > Add > Controller ... Missing

### ISSUE THREAD

**Issue by LearnVisualStudio** [aspnet/Tooling#263]
In VS 2013, there's a number of handy (and familiar) contextual menu items like Add > Controller ... however they're not currently in VS 2015.

<img width="629" alt="add-controller-context-menu" src="https://cloud.githubusercontent.com/assets/3912148/10945095/eb6e1b3a-82e1-11e5-8196-7a75fa95a1ae.png">

(If these are not the types of things you're looking for, I apologize.  I didn't see any guidance on what types of issues you were looking for.  Thank you!)

**Comment by sayedihashimi** [comment]
Thats a part of our Visual Studio scaffolding feature that we are working on. The first release of it will be available in the next release. I don't think this particular menu option will be available in the first release but it should be in the release after that. Closing this now.

**Comment by akasarto** [comment]
Just noticed that the Add -> Controller will only show up if the project.json has a dependency on the package 'EntityFramework.MicrosoftSqlServer'.

As I`m not using entity framework it will not be available on the context menu.

Will the mentioned release include this fix as well?

**Comment by VirajKaththriarachchi** [comment]
Oiii
