### ISSUE TITLE
ASP.NET attributes are only allowed in ASP.NET files.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#264]
in a .cshtml page, if you write :
```
<p visible="true">
</p>
```
you get that weird error.

The problem is that with TagHelpers you can have a Visible property and it will show that warning.

![image](https://cloud.githubusercontent.com/assets/3386797/10950731/5efca1fa-8320-11e5-8cf8-9c40187500d5.png)

**Comment by ToddGrun** [comment]
I've logged a bug in our internal DB (161347) to track this issue. Someone (likely me!) will respond once we've had a chance to look into this more. Thanks!

**Comment by NTaylorMullen** [comment]
:+1:

**Comment by Tejas7** [comment]
I am facing the same issue for "visible".

**Comment by ToddGrun** [comment]
OK, we've checked in a fix for this which will be available in a future release
