### ISSUE TITLE
Visual Studio won't start MvcMinimal Sample

### ISSUE THREAD

**Issue by evorine** [aspnet/Tooling#265]
When I try to start an instance of the project (CTRL + F5) Visual Studio won't start the sample project neither IIS Express.
I'm using dnu version `1.0.0-rc1-16048`.

It shows an error dialog says:
> Could not find the Microsoft.AspNet.Loader.IIS.Interop NuGet package in your users packages folder. This NuGet package is required to run ASP.NET 5 web applications.

By the way I can run it using `dnx web` outside Visual Studio.

Those are what I did:

1. Downloaded minimal mvc sample project from https://github.com/aspnet/Mvc/tree/dev/samples/MvcMinimalSample.Web
2. Set runtime version to 1.0.0-rc1-16048 by typing `dnvm use 1.0.0-rc1-16048` in Package Manager Console.
3. Restored dependencies by `dnu restore`
4. CTRL + F5

**Comment by BillHiebert** [comment]
In visual studio open project properties (double-click the properties folder). Which version of DNX is it targeting? My guess is it is a version < RC1

**Comment by evorine** [comment]
Your guess was right. It was `beta8`. I changed it to `rc1-16048` but it didn't solve my problem. The error dialog still appears.

I restarted VS too but still no progress :(

![err](https://cloud.githubusercontent.com/assets/3532488/10992793/353580dc-8472-11e5-8247-ddb3622f2070.png)

**Comment by sayedihashimi** [comment]
@BillHiebert will VS beta8 work with RC1 projects?

**Comment by evorine** [comment]
I have realized Web Tools Beta8 was not installed. I have installed them and now, Visual Studio is able to start IIS Express.

But the current problem is Web Application won't finish the response when I make a request. Page is blank and stays in loading state for ever.

I tried it in beta8 and rc1 both. Same result...

And when I try to start debug, IIS Express turns off itself without any warning or error message.

I looked into **%USERPROFILE%\Documents\IISExpress\** for the log files but there is none :disappointed:

**Comment by sayedihashimi** [comment]
@evorine is this still an issue?

**Comment by robianmcd** [comment]
I'm getting the "Could not find the Microsoft.AspNet.Loader.IIS.Interop" error from Visual Studio Express 2015 for Web Version 14.0.23107.0 D14RLE. It works fine when I run it from the command line.

**Comment by evorine** [comment]
Oh I forgot this issue. As there is no more MvcMinimalSample project I can't test it anymore.
But in `rc1-final` and `rc1-update1` with WebTools (RC), I didn't experience this problem. So I think this is an old issue.
