### ISSUE TITLE
InternalsVisibleTo doesn't work with DNX strong-named assemblies

### ISSUE THREAD

**Issue by tillig** [aspnet/Tooling#266]
In a single solution:

- A DNX (project.json) class library that...
  - Targets `dnxcore50`, `dotnet5.2`, `net45`, `netcore45`
  - Is strong-named with a custom key using `"compilationOptions": { "keyFile": "key.snk" }`
  - Has an attribute `InternalsVisibleTo` enabling internal visibility to a unit test assembly
- A DNX (project.json) unit test class library that...
  - Targets `dnx451` and `dnxcore50`
  - Is strong named with a custom key using `"compilationOptions": { "keyFile": "key.snk" }`

At the command line, both projects compile and the tests run perfectly.

Inside Visual Studio you get errors indicating that internal members in the main class library are not visible to the unit test class library despite the `InternalsVisibleTo` attribute.

When you _build_ in Visual Studio, the build succeeds but the errors remain in the Errors window. You can even run the unit tests via the Test Explorer and have them pass... with the errors in the Errors window sitting right there.

I expect that if there are no errors I shouldn't see any errors. That is, if the build works and I can unit test it and everything that the error window should be empty.

You can see a repro of this by loading up [the Autofac solution at commit 25a8cf5](https://github.com/autofac/Autofac/tree/25a8cf5162097414cdc750d16a15df1c897dfd48).

**Comment by Eilon** [comment]
@cesarbs @moozzyk @pakrym I think one of you mentioned today that this was just recently fixed in tooling, but I don't remember who said it :smile:

**Comment by sayedihashimi** [comment]
It was recently fixed by @abpiskunov. It will be available in the next release of the tooling.

**Comment by moozzyk** [comment]
@Eilon I did based on #360 from the other repo

**Comment by abpiskunov** [comment]
it should be in Dev14 U1 + WTE RC and higher

**Comment by sayedihashimi** [comment]
I'll go ahead and close this since there is no action on our side.
