### ISSUE TITLE
Create project from template error in new installation

### ISSUE THREAD

**Issue by pakrym** [aspnet/Tooling#269]
New installation of Windows 10, Visual Studio 14.0.23107, Tools 2015-11-05_b223 Release.

Template names seem wrong:
![](http://i.imgur.com/ZA1hYeO.png)

After clicking on WebTemplate i get message box with following error:

>Error: this template attempted to load component assembly 'Microsoft.VisualStudio.Web.Project, Version=2.3.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. For more information on this problem and how to enable this template, please see documentation on Customizing Project Templates.

**Comment by barrytang** [comment]
This doesn't look right. Normally, it looks like this:

![image](https://cloud.githubusercontent.com/assets/1648865/11013237/57bafa50-84b9-11e5-9768-df6ef8d9b709.png)

@rustd @balachir , have you guys seen anything like this before?

**Comment by barrytang** [comment]
I think you have some bad internal bits. Please work with @balachir tomorrow. Thanks!

**Comment by sayedihashimi** [comment]
FYI for future reference if you have an issue with an internal build then it should be opened in the internal git repo
