### ISSUE TITLE
Unable to generate public class and properties of .Designer.cs of ResX 

### ISSUE THREAD

**Issue by joplaal** [aspnet/Tooling#270]
When using previous versions of the framework, one could customize the behavior of the designer generated classes by choosing ResXFileCodeGenerator or PublicResXFileCodeGenerator as the Custom Tool in order to get the classes and properties internal or public. 

Now, it seems that there is no way to choose, and the generated classes and properties are internal.

There are many side-effects if the default internal behavior can not be changed:

DisplayAttribute does not work: https://github.com/aspnet/Localization/issues/134 

It does not only apply to MVC Models. It also prevents using DataAnnotations for other validation frameworks, such the one used at EntityFramework or FluentValidation.

It also makes not possible to have a shared resources file with solution wide translations used in several projects.

If it's difficult to change the project.json or .xproj syntax to allow the behavior selection, IMO the default behavior of the generator should be public, since it allows all the scenarios.

**Comment by sayedihashimi** [comment]
TFS: 162671
I've added this to our internal TFS, we will reply back here soon.

**Comment by oliverw** [comment]
:+1:

**Comment by joplaal** [comment]
At rc1, localization is frustrating, important issues like this one are no resolved, as many other ones as stated in https://github.com/aspnet/Home/issues/1142

**Comment by sayedihashimi** [comment]
A change to make the generated classes `public` has been checked in and it should be contained in the next release of the ASP.NET 5 VS drop.

**Comment by sayedihashimi** [comment]
Should be fixed in the next release, closing now.
