### ISSUE TITLE
Version Restore Issue

### ISSUE THREAD

**Issue by endeffects** [aspnet/Tooling#274]
Hi Guys,

i have an issue with the version management of the dnu restore command. I have 2 Solutions, one for a class library (package) and a web applicaton. 

The Package has a dependency for:
"Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc1-*" 

When i'm adding the package to my web application and running a package restore the dependency is changing it's version to:
"Microsoft.Extensions.DependencyInjection.Abstractions": "1.0.0-rc2-15788*" 

My dnx runtime version is:
1.0.0-rc2-16138

Which is probably the reason for the version upgrade. Anyways, from my point of few the restore should respect the versions of library dependencies, or?

**Comment by sayedihashimi** [comment]
This is determined by the asp.net runtime, and not the VS tooling. @endeffects the correct repo for this question is https://github.com/aspnet/dnx. I'll close this issue, but you can open an issue asking in the dnx repo.
