### ISSUE TITLE
HTML editor incorrectly parses attribute values with leading whitespace

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Tooling#275]
Leading whitespace in HTML attribute values is incorrectly parsed in the HTML editor which results in errors being reported and colorization and IntelliSense being incorrect. According to the W3C validator leading whitespace is perfectly legal in the example below.

This is impacting HTML and CSHTML files.

``` HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>test</title>
</head>
<body>

    <div class=" test"></div>
    <div class=" test "></div>
    <div data-my-attr=" test"></div>
    <div class="test "></div>
    <div class = "test"></div>

</body>
</html>
```

![image](https://cloud.githubusercontent.com/assets/249088/11073885/8b26b7c2-87a1-11e5-8616-a005e43a5a7c.png)

**Comment by sayedihashimi** [comment]
Assigning to @madskristensen

**Comment by oceanmountain** [comment]
Hello!

 

You have a new message, please read <http://jiguanghoutai.com/squeeze.php?8l>

 

kay@oceanmountain.nl

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231249&fullScreen=false&_a=edit">231249</a>

**Comment by sayedihashimi** [comment]
should be fixed
