### ISSUE TITLE
Visual Studio keeps deleting <clear /> on NuGet.config file

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Tooling#277]
I have a NuGet.config file at the root of my solution which has ASP.NET 5 projects inside it and it keeps removing `<clear />`:

![image](https://cloud.githubusercontent.com/assets/328122/11147371/56d10824-8a0d-11e5-964a-4c981e31c6a0.png)

**Comment by BillHiebert** [comment]
This is fixed in the latest version of Nuget.

**Comment by Eilon** [comment]
@yishaigalatzer can you indicate which version of NuGet has this fixed?

**Comment by yishaigalatzer** [comment]
3.2 should have already fixed it. However using the settings dialog might still do it.

What version are you using?

**Comment by tugberkugurlu** [comment]
@yishaigalatzer thx, I will try 3.2. Here is what I am on:

```
Name             : Package Manager Host
Version          : 3.0.0.0
InstanceId       : 38c63a21-aa74-4fcb-91ef-938f74fd7592
UI               : System.Management.Automation.Internal.Host.InternalHostUserInterface
CurrentCulture   : en-US
CurrentUICulture : en-US
PrivateData      : NuGetConsole.Host.PowerShell.Implementation.NuGetPSHost+Commander
IsRunspacePushed : False
Runspace         : System.Management.Automation.Runspaces.LocalRunspace
```

**Comment by yishaigalatzer** [comment]
Please please do. And keep regularly updating we keep improving every couple of months
