### ISSUE TITLE
Overriding method introduces [NotNullAttribute] on parameters

### ISSUE THREAD

**Issue by tugberkugurlu** [aspnet/Tooling#278]
When I override a method in an ASP.NET 5 application inside VS 2015, I also get `[NotNullAttribute]` on some parameters. Here is a sample:

```csharp
    public class InvalidModelStateFilterAttribute : ActionFilterAttribute
    {
        public override void OnActionExecuting([NotNullAttribute] ActionExecutingContext context)
        {
            base.OnActionExecuting(context);
        }
    }
```

I am on 1.0.0-beta8 runtime.

**Comment by Eilon** [comment]
Related internal bug: https://github.com/aspnet/Tooling-Internal/issues/104

From what that other bug says, apparently the Roslyn team fixed the issue at least with regard to interfaces that have methods with internal attributes. Perhaps there's more to this issue?

**Comment by sayedihashimi** [comment]
Is this an issue with ASP.NET 5 RC1 + Visual Studio Update 1 RC?

**Comment by sayedihashimi** [comment]
I believe this should no longer happen if you use the latest releases. If you're still getting this when using VS2015 Update 1 + ASP.NET 5 RC1 please reopen this with details.
