### ISSUE TITLE
Configure SSL/HTTPS port

### ISSUE THREAD

**Issue by brockallen** [aspnet/Tooling#279]
Currently using beta8.

When enabling SSL for a ASP.NET 5 web project, the tooling always seems to select port 44300 and does not allow me to change it (even if I manually change the value in the ~/.vs/config/applicationhost.config file and reload VS).

This is painful if I have two copies of VS running two different projects that both need to run SSL (as they conflict due to the same port being used).

**Comment by BillHiebert** [comment]
We fixed this in the upcoming RC. IISExpress registers the port range 44300-44399 at install time so you don't have to run as administrator. VS now selects a random port number (not used in the applicationhost.config file) between this value when SSL is enabled.

**Comment by sayedihashimi** [comment]
Closing based on Bill's comment

**Comment by brockallen** [comment]
But will it be configurable?

**Comment by sayedihashimi** [comment]
Yes

**Comment by brockallen** [comment]
Excellent, thanks.

**Comment by BillHiebert** [comment]
We've also moved the setting to the launchsettings.json file where you can edit the SSLPort and set it to whatever you want. The default behavior when you check the box is as I described.
