### ISSUE TITLE
Lots of empty messages in error list when building ASP.NET 5 class lib

### ISSUE THREAD

**Issue by danroth27** [aspnet/Tooling#28]
![error_list_empty_messages](https://cloud.githubusercontent.com/assets/1874516/6742510/8748169a-ce4d-11e4-8c89-35e446bb6c7d.png)

**Comment by danroth27** [comment]
This is on CTP 6

**Comment by sayedihashimi** [comment]
Should be fixed in Visual Studio 2015 RC, please re open if you see it again.
