### ISSUE TITLE
"Create directory for solution" option is not preserved

### ISSUE THREAD

**Issue by xperiandri** [aspnet/Tooling#280]
@Daniel15, you did some explanation about this on #126

But I have to notice that:

1. Your explanation does not have anything in common with ASP.NET 4 projects. So putting sln file in folder on level up is absolutely unexpected behavior. You must either disable this option for ASP.NET projects or notify user about this somehow. Disabling this option in New project dialog is the most obvious and correct way to fix this.
2. Moreover you put Test projects wherever you want but not wherever user requires. Imagine this structure:

\Solution Root
-\sln file
-\Web folder
So if I put ASP.NET project into Web folder and check to create a test project, the test project will be created on solution root level. Could you just open another dialog about that? Or add a combobox with options where to put test project?

**Comment by Daniel15** [comment]
>  So putting sln file in folder on level up is absolutely unexpected behavior.

Yeah, I agree with this, but @sayedihashimi  said it was by design. ¯\_(ツ)_/¯

**Comment by xperiandri** [comment]
I don't not arguing about design. Design is fine.
I argue about implementation!
