### ISSUE TITLE
Improve New Project dialog experience for auth selection

### ISSUE THREAD

**Issue by Eilon** [aspnet/Tooling#282]
I suggest changing the "Change Authentication" button to instead be a drop-down that allows quickly selecting the auth type.

The behavior should be:
- You can click the <kbd>...</kbd> button to launch the sub-dialog (same behavior as the old button)
- You can use the drop-down to quickly pick a different auth type.
  - If you pick No Auth or Individual Auth you're done
  - If you pick an auth type that requires more info (e.g. Org Auth requires Azure settings) then it pops up the sub-dialog, selects the radio button you wanted, and lets you fill in the required info

Mock-up of the new UI:
![new-project-auth](https://cloud.githubusercontent.com/assets/202643/11219100/5afee422-8d0d-11e5-9495-9906de5d6ab9.png)

For the record, @danroth27 likes it :smile: (Or at least he didn't _dislike_ it!)

**Comment by sayedihashimi** [comment]
Thanks for the suggestion. I'll discuss with @rustd @barrytang and @mlorbetske

**Comment by sayedihashimi** [comment]
TFS: 169734

**Comment by sayedihashimi** [comment]
The long term hope is to remove auth from the one asp.net dialog and make it re-entrant. I'll close this now.
