### ISSUE TITLE
Can't specify SSL port for IISExpress.

### ISSUE THREAD

**Issue by unt1tled** [aspnet/Tooling#286]
I [submitted this to SO](http://stackoverflow.com/questions/33790606/where-do-i-specify-my-ssl-port-for-iisexpress), but didn't get a response.

I used to be able to change the SSL port number in the project properties dialog, but after the asp.net 5 RC1 update, the SSL field is read-only.It ignores the SSLPort value when I attempt to edit the .xproj directly. And it also resets the port in my app host config file ($[solutionDir].vs\config\applicationhost.config) back to the original value when I change the binding and launch my project.

**Comment by sayedihashimi** [comment]
Adding @BillHiebert

**Comment by ArieJones** [comment]
I can second this issue and also add that this causes a problem in which other team members get a random port assigned as they open the project from source control on their local machines. 

This causes issues when we are using Azure AD authentication and the application configuration for that is tied to a specific port. 

The only way we have figured out a way around it is to basically check and uncheck the SSL feature until it assigns the same port as what we had for the person whom initially created the project or our mutually agreed upon port number that we have chosen to use.

**Comment by unt1tled** [comment]
An answer was provided on SO:
>Open launchSettings.json under the ./Properties folder. The int value in iisSettings > iisExpress > sslPort is where it's read from. You can change that value to whatever you want.
````
{
  "iisSettings": {
    "iisExpress": {
      "sslPort": <ssl-port-value>
    }
  }
}
````

**Comment by sayedihashimi** [comment]
Thanks for the feedback here. We have historically not enabled changing the SSL port in the Visual Studio UI. For ASP.NET 5 it's much easier to control the port, you just edit `launchSettings.json` as [previously mentioned](https://github.com/aspnet/Tooling/issues/286#issuecomment-160329637).

For now this experience is the current plan for changing the SSL port. We can leave this issue open for a few more days to see if there is any significant push back here, but I'd rather have the team work on more fundamental issues for the short term.

**Comment by sayedihashimi** [comment]
Closing now
