### ISSUE TITLE
Adding Bower Packages via new UI does work as expected

### ISSUE THREAD

**Issue by shawnwildermuth** [aspnet/Tooling#287]
If you start an empty project and use the new "Manage Bower Packages" UI to add a package, it calls out to "bower install" and since there is no bower.json added to the project, it adds it under the main project. UI should either warn about no bower.json or add the bower.json and .bowerrc file for the user. Installing bower packages to the default location makes them unavailable to wwwroot unless they run a separate script to use it.

**Comment by BillHiebert** [comment]
@jodavis @madskristensen

**Comment by sayedihashimi** [comment]
TFS: 168898
I've added this to our internal TFS, we will reply back here soon.

**Comment by barrytang** [comment]
Thanks for the feedback. We will be addressing this as part of RC2.
