### ISSUE TITLE
Folder hidden in VS 2015 Solution Explorer shows itself if deleted & recreated with the same name

### ISSUE THREAD

**Issue by ghurlman** [aspnet/Tooling#289]
I'm currently building an Ember app that dumps a *ton* of files into the /tmp directory during the build process - Ember:tmp :: .NET:obj.

VS hangs while trying to load this folder into Solution Explorer every time I build, so I've hidden that folder. However, the folder is recreated with every build, so VS re-shows it, and tries to load it, even though it some part of it knows it shouldn't:

![untitled](https://cloud.githubusercontent.com/assets/210325/11273968/2ce0669a-8ea4-11e5-9b93-34f29ba4ac44.png)

It's my feeling that if a folder with the same name as a hidden folder is created, that maybe it should be shown, but with an icon indicator that Solution Explorer isn't loading the files because it was previously configured to be hidden... something like that.

In the meantime, my workaround is to delete everything out of the tmp folder after build, shown below for anyone that finds this that has the same problem:

```
// gulpfile.js

var gulp = require('gulp'),
    shell = require('gulp-shell'),
    del = require('del'),

gulp.task('embercleanbuild', ['emberbuild'], function() {
	del('tmp/**/*');
        // ember's build process deletes everything inside the build target (wwwroot),
        // so we need to copy the web.config back over after build.
	gulp.src('web.config')
		.pipe(gulp.dest('wwwroot'));
})

gulp.task('emberbuild', shell.task([
	'ember build'
]));
```

**Comment by BillHiebert** [comment]
@abpiskunov

**Comment by lucamorelli** [comment]
happens something similar to me with a jspm_packages folder: with beta 8 I was able to hide it and resolve this problem, but now if I hide it Solution Explorer continues to show it

![untitled](https://cloud.githubusercontent.com/assets/127777/11285669/f9c859bc-8f10-11e5-8a7e-8d8435225174.png)

**Comment by abpiskunov** [comment]
I will look into it

**Comment by abpiskunov** [comment]
Yes I can repro it .. sorry its a bug :(. Will add for RC2

**Comment by abpiskunov** [comment]
TFS #166983

**Comment by bab5139** [comment]
The roadmap site doesn't have any information about an RC2.  @abpiskunov do you have any information for when we can expect a rc2 release?

**Comment by abpiskunov** [comment]
RC2 probably will be aligned with Dev14 Update 2. I am not sure if the date is public yet.

**Comment by abpiskunov** [comment]
It is fixed. Fix should be available publicly in our next release which should be ASP.NET 5 RC2 , sometime in February.
