### ISSUE TITLE
Hovering over a property shows intellisense for an extension method

### ISSUE THREAD

**Issue by danroth27** [aspnet/Tooling#29]
When I hover over the Type.IsValueType property it shows intellisense for an extension method in my solution:
![combined_intellisense_backwards](https://cloud.githubusercontent.com/assets/1874516/6743421/e0819c32-ce56-11e4-9889-0edc378d7466.png)

Shouldn't this show the property instead of the extension method?

**Comment by danroth27** [comment]
It actually looks like in the later case intellisense is picking up an extension method in my project instead of the property. Is that expected?

**Comment by sayedihashimi** [comment]
Can you share the solution?

**Comment by davidfowl** [comment]
That's not the same type. If you look carefully, one is an extension method and the other is a property. There is currently a long standing bug in Roslyn that has to do with overloads.

If you have a method Foo and there exists an overload that doesn't exist in the intersection of projects it says unsupported.

**Comment by danroth27** [comment]
@davidfowl Yeah, I realized that after filing the bug and I have already update the issue title and description. What I don't get is why VS thinks this is an method at all instead of a property.

**Comment by sayedihashimi** [comment]
@danroth27 can you try again with VS2015 RC? If it repros I think it may be a roslyn bug. Closing this for now until we hear back.
