### ISSUE TITLE
Reduce number of places "wwwroot" appears

### ISSUE THREAD

**Issue by rustd** [aspnet/Tooling#291]
Copying from the templates repo.
https://github.com/aspnet/Templates/issues/315
If I want to change the web root from "wwwroot" to (say) "webby", I can't just rename the directory and make one change. Would be great to have a single source of truth and include that value on the various command lines. (Yes, this may require tooling updates in addition to changes in this repo. At least  dnu publish  already supports the necessary command-line option.)

Current requirements include renaming the directory and changing the following files (from the no-authentication ASP.NET 5 Web Application template):
•  .bowerrc  # copy to new folder
•  gulpfile.js  # update correct files
•  project.json  # exclude new folder

Must also add a  hosting.json  file e.g.

{
  "webroot":  "webby"
}

And if I choose to publish the project, need to change the  .pubxml  to copy the needed static files:

...
    <WebRoot>webby</WebRoot>
    <WwwRootOut>wwwroot</WwwRootOut>
...

(This step must be repeated for a new publish profile. And the first publish attempt often lacks static files.)

**Comment by sayedihashimi** [comment]
TFS: 168894
I've added this to our internal TFS, we will reply back here soon.
