### ISSUE TITLE
Publish ASP.NET 5 Web Application to remote IIS 

### ISSUE THREAD

**Issue by simonpbond** [aspnet/Tooling#292]
In Visual Studio 2015, I can successfully preview / publish to a remote IIS server with a 4.6 Web application. However, publishing fails when using an ASP.NET 5 template / web applications, it will not even provide a preview.

Is it possible to publish an ASP.NET 5 web application at the current time using Visual Studio 2015 / Publish to a remote IIS server?

If so, is there any instructions on doing this? (not for local IIS).

**Comment by GuardRex** [comment]
@simonpbond Official docs are at: https://docs.asp.net/en/latest/publishing/iis.html
Other notes at: https://github.com/aspnet/Hosting/issues/364#issuecomment-148567294

**Comment by sayedihashimi** [comment]
TFS: 168887
I've added this to our internal TFS, we will reply back here soon.
