### ISSUE TITLE
strange issues updating a beta 8 to rc1 via nuget

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#296]
Hi,
  I have a small application that I started to write with beta 8 and I reopened after the upgrade to rc 1. Opening the nuget window I found that shows some packages in the project.json as upgradable, not all.
![untitled1](https://cloud.githubusercontent.com/assets/127777/11317287/a9d13c2a-9029-11e5-859d-d049f51b8f43.png)

After tried some of them via nuger, opening the project.json I see this message
![untitled2](https://cloud.githubusercontent.com/assets/127777/11317291/141e257a-902a-11e5-9009-5c9436984f97.png)

**Comment by Boglen** [comment]
Are you switch the solution and project to dnx rc1? And don't forget about Microsoft ASP.NET and Web Tools 2015 (RC) – Visual Studio 2015.

**Comment by lucamorelli** [comment]
I installed rc1 web tools before do to this. I manually converted the project and the solution to rc 1 manually and all is working fine.

**Comment by sayedihashimi** [comment]
@lucamorelli ok so you have this working now? Can we close this?

**Comment by lucamorelli** [comment]
yes, I think we can close. I updated the project manually.
the point is that I wasn't able to upgrade asp.net dll from beta 8 to rc, but since vs 2015 update 1 shipped with a new version, I think I'll repeat the test next time we have an update to asp.net 5
