### ISSUE TITLE
Deploy error after rename project's namespace

### ISSUE THREAD

**Issue by regionbbs** [aspnet/Tooling#297]
(ASP.NET 5 RC1)

I created a new ASP.NET 5 RC1 empty application project and authored my Web App, then I change project's default namespace to another in Project Properties editor, and change namespace manually.

When I changed namespace, it failed to deploy to Azure Web App.

I checked my project output (project.json), it's "entryPoint" value couldn't match to namespace I changed.

For example:
1. Create "Portal" project with ASP.NET 5 in VS 2015
2. Create one MVC controller with current namespace.
3. Change namespace in project properties editor and change namespace in controller code.
4. Deploy application to Azure Web App.
5. Application returns HTTP 500 after a several minutes.

**Comment by sayedihashimi** [comment]
@regionbbs in this case when you publish you may need to select `Remove additional files at destination` on the Settings tab under File Publish Options. Please try that and let me know if you're still running into this.

**Comment by regionbbs** [comment]
Hi, I tried this options, but issue still exists.

**Comment by sayedihashimi** [comment]
@regionbbs ok sorry to hear that. The only thing that I can think of is that there may be a value in the `.pubxml` file that needs to be updated. Can you delete the publish profile and re-create it? If that doesn't work then I'm wondering if it's specific to a particular project. So I wonder what happens when you create a new project and publish that?

**Comment by regionbbs** [comment]
Publishing from a new project template is OK (I already tried before report this issue), you can try to change namespace of that, and try to re-publish, error might be reproduced.

**Comment by sayedihashimi** [comment]
TFS: 174131
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
Sorry for the delay here. There has been a lot of changes that have happened since you filled this issue. Can you try again with VS2017 RC and let us know if this issue persists? I'll close this now, but please reopen if it's still an issue.
