### ISSUE TITLE
dragging static files in a mvc view isn't resolved correctly

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#3]
In an asp.net 4 application if I drag a file as an image in a mvc view the link is added correctly, for example
`<img src="~/Content/asp-net-banners-01.png" />`
but if I do the same thing in an asp.net 5 app, where all the static files are inside the wwwroot directory, this link is added to the view
`<img src="~/wwwroot/images/asp-net-banners-01.png" />`
when the application is deployed the link is incorrect and the image isn't shown

**Comment by Tratcher** [comment]
Your pictures broke, try sharing them again.

**Comment by sayedihashimi** [comment]
Fixed in Visual Studio 2015 RC
