### ISSUE TITLE
Intellisense in project.json fails to resolve package System.Xml.XPath

### ISSUE THREAD

**Issue by danroth27** [aspnet/Tooling#30]
On CTP 6 project.json intellisense failed to resolve [System.Xml.XPath](https://nuget.org/packages/System.Xml.XPath):

![no_xpath](https://cloud.githubusercontent.com/assets/1874516/6763618/6e3f073a-cf42-11e4-869e-777945f8572b.png)

**Comment by danroth27** [comment]
Note that I can't repro this behavior consistently. In other cases (in this case a different project in the same solution) it resolves just fine:

![yes_xpath](https://cloud.githubusercontent.com/assets/1874516/6763693/7b60798c-cf45-11e4-8d68-f1046cd407fe.png)

**Comment by davidfowl** [comment]
@danroth27 Crack open fiddler.

**Comment by mayurid** [comment]
@danroth27 this is working consistently in the latest. Are you still seeing this?

**Comment by sayedihashimi** [comment]
@danroth27 since we haven't heard back from you in a while I'll go ahead and close this. If this still happens please reopen with details.
