### ISSUE TITLE
DTH fails on DNX 46

### ISSUE THREAD

**Issue by glatzert** [aspnet/Tooling#301]
I have a web project, with a simple references to another project.
The referred project is net45, net46 (and dnx46 to bypass some resharper issues).

My web project targets dnx46.

The following error will be thrown:
```
Description: The design time host build failed with the following error: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt. (That's a Null-Reference in german)
Project: WebProject	
File: C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\Microsoft.DNX.targets
Line: 166
```

If I switch target to dnx45 everything will build fine.

`dnx web` runs as expected as well.

**Comment by glatzert** [comment]
Appending Line 166:
```
<DesignTimeHostBuild
      Condition="'$(_DesignTimeHostBuild)' == 'true'"
      Port="$(DTHPort)"
      HostID="$(DTHHostID)"
      ContextID="$(DTHContextID)"
      DTHProtocolVersion="$(DTHProtocolVersion)"
      Rebuild ="$(RebuildInvoked)"
    />
```

**Comment by sayedihashimi** [comment]
TFS: 167864

I've added this to our internal issue tracker, we will reply back here soon.

**Comment by edandersen** [comment]
+1 hitting the same issue upgrading a project from beta3 to RC1.

**Comment by davidfowl** [comment]
beta3! That's impressive :smile:

**Comment by davidfowl** [comment]
@edandersen Make a new project file and see if you run into the same problems.

**Comment by edandersen** [comment]
@davidfowl :+1: Fixed now - ended up copy pasting from a new project template. Project diff between beta3 and RC1 in case anyone is interested: https://github.com/edandersen/vnextsimpleblog/commit/1995aad95471b9a5f54be41fc8f6f825b0cf5627

**Comment by sayedihashimi** [comment]
Sounds like you are good now, closing.

**Comment by glatzert** [comment]
Okay - the problem did not just vanish in my case, but i managed to pin-point it.
Possibly this is a still a bug - but that's not me to decide.

I had an Folder in my project:
Compiler > Preprocess > RazorPreCompilation.cs

The latter defining a namespace, but being empty

```c#
namespace Web.Compiler.Preprocess
{
    // Uncomment the following class to enable pre-compilation of Razor views.
    // Pre-compilation may reduce the time it takes to build and launch your project.
    // Please note, in this pre-release of Visual Studio 2015, enabling pre-compilation may cause IntelliSense and build errors in views using Tag Helpers.

    //public class RazorPreCompilation : RazorPreCompileModule
    //{
    //    public RazorPreCompilation(IServiceProvider provider) : base(provider)
    //    {
    //        GenerateSymbols = true;
    //    }
    //}
}
```

Removing this more or less empty file, resolves my problem... I carried this over and over from "the beginning"
