### ISSUE TITLE
Error 0x80091007: Failed to verify hash of payload: DotNetVersionManager_x64

### ISSUE THREAD

**Issue by fuocor** [aspnet/Tooling#302]
I tried to install AspNet5.ENU.RC1.exe and it's throwing a number of hash related exceptions...

Any help is appreciated

**Comment by MartinJohns** [comment]
Create a new directory, move the installer inside, then start it from within the new directory. No joke. The installer goes haywire if there are any other `msi` files in the same directory, and most likely you tried to start it from your downloads directory.

**Comment by sayedihashimi** [comment]
Sorry you're running into this. @MartinJohns is correct.

There is a known issue (that we are working to resolve soon hopefully) in which the installer will get confused if there are any previousy asp.net msi files in the same folder. The workaround given by @MartinJohns above should work.

**Comment by sayedihashimi** [comment]
@barrytang where are we at with getting this fixed?

**Comment by tparnell8** [comment]
:+1:  FYI I just ran into this issue...

**Comment by sayedihashimi** [comment]
FYI we have just updated the installers to resolve this. If you download the installers again you should not run into this. Closing this, if you are still facing this let us know.
