### ISSUE TITLE
Bitdefender blocks Browserlink, keeps site from loading

### ISSUE THREAD

**Issue by SebastianLang** [aspnet/Tooling#309]
Hi,

I'm developing on Windows 10 with ASP.NET 5 RC1 and I have Bitdefender Total Security 2016 installed. When I create the standard "Web Application" Project and start it, the browser keeps loading the page forever. It doesn't matter if I start it in IIS Express or with Kestrel. There are no exceptions or other error messages.

I tested this on another PC with Bitdefender on it -> same problem. Then I created a clean Windows 10 VM, tested it and it worked perfectly. After installing Bitdefender on the VM I had the same problem as before.

Commenting out the "app.UseBrowserLink();" line in the Startup.cs file fixes the problem, which leads me to believe that Bitdefender somehow does not like Browserlink.

**Comment by Eilon** [comment]
@jodavis @barrytang have you guys ever heard of this? Sounds like a false positive to me...

**Comment by pierre-weceipt** [comment]
Hi, I had the same problem of Template project not loading after hitting `f5` and saw on a stackoverflow [post] (http://stackoverflow.com/questions/33527012/cannot-launch-asp-net-5-web-app-in-iis-express) that it could be linked to Bitdefender. After finding this post and commenting `app.UseBrowserLink();` it works like a charm so I think there really is an issue :smile:

**Comment by mogf** [comment]
I have the exact same issue; template project times-out (after 1-2 minutes) when using browserlink. Commenting out `app.UseBrowserlink();` fixes this issue, but of course disables browserlink.

I have an open issue with Bitdefender support about this, but no progress so far (I'm at the stage where they ask me the same question over and over, hopefully that will pass...:D). Completely uninstalling bitdefender does work, but disabling parts of bitdefender has no effect.

**Comment by kuashe** [comment]
I ran into this issue since yesterday , this really helped me out. Bitdefender not answering is very unacceptable .

**Comment by Rick-Anderson** [comment]
@sayedihashimi  I'm gettng alot of customers reporting this problem. See comments at https://docs.asp.net/en/latest/tutorials/first-mvc-app/start-mvc.html

**Comment by matthewtanner** [comment]
Is there any news on this issue yet? I've gotten nothing back from BD support thus far.

**Comment by Rick-Anderson** [comment]
@matthewtanner no need to ping, we'll post when we get anything to report.

**Comment by sayedihashimi** [comment]
Sorry for the delay here. I was hoping that this would get resolved since it was reported to Bitdefender by their customers, but it seems like those who reached out didn't get good traction.

I'm working to see who we know at Bitdefender so I can reach out. If someone here has contact info for someone on the Bitdefender engineering/product team if you could share that with me at sayedha [at] MicrosoftDOTcom that would be greatly appreciated.

cc @shanselman

**Comment by sayedihashimi** [comment]
For those having issues with Bitdefender can you confirm that you're using one of the supported versions (2015 or 2016)?

**Comment by sayedihashimi** [comment]
Bitdefender is asking that users with supported versions to email bitsy@bitdefender.com if you're running into this. You can copy me, or forward, if you like at sayedha@microsoft.com.

**Comment by kuashe** [comment]
@sayedihashimi  I confirm using vs 2015

**Comment by matthewtanner** [comment]
Confirming VS 2015 update 2.

**Comment by sayedihashimi** [comment]
Sorry for the confusion, I meant Bitdefender 2015 or 2016. Older versions are not store supported any more.

**Comment by kuashe** [comment]
@sayedihashimi  It's ok , Bitdefender 2016 and VS 2015 .

**Comment by AlexBitdefender** [comment]
Hello! We are in the process of investigating and reproducing the situation. We kindly ask all users who are experiencing this situation to write at bitsy@bitdefender.com
Besides the description of the issue please mention in the email "Visual Studio incompatibility github.com/aspnet/Tooling/issues/". This will be useful for escalating the case on a high priority. 
@sayedihashimi @shanselman Our team also replied to the open case you have with them. Please reply to it when you have the chance. Thank you all in advance! 
Bitdefender Support

**Comment by miqueljuan** [comment]
Confirming Bitdefender 2016

**Comment by wmsmitty** [comment]
Just want to add to the confirmation list here: 

1. I have Bitdefender 2016 on a Windows 10 OS
2. Visual Studio 2015 Update 2
3. Create a Net Core RC2 web project.
4. Unable to debug the solution and unable to ctrl+f5 (start w/o debugging)
5. Results in a gateway error as indicated in most other threads regarding this issue.
6. Support email sent to bitsy@bitdefender.com

**Comment by AlexBitdefender** [comment]
Hello and thank you for your cooperation! 
@wmsmitty We have received your email and our team will notify as soon as they have an update. @miqueljuan Could you also write us at bitsy@bitdefender.com, when you'll have the chance. Be sure to mention "Visual Studio incompatibility github.com/aspnet/Tooling/issues/" so our team can index it. 
These cases are handled on a separate high priority queue. 
Thanks again!

**Comment by SebastianLang** [comment]
I do not have an active Bitdefender license anymore, but I can confirm:
- Bitdefender 2016
- Visual Studio 2015 Update 2
- ASP.NET Core RC2

**Comment by AlexBitdefender** [comment]
Hello, everyone! The investigation is still in progress. Here's the situation, in short: there are quite a few users who wrote at bitsy@bitdefender.com, and a few others were cases arriving from the other Support channels. We were unable to fully reproduce the situation on our end. The development team and senior technicians offer remote troubleshooting. This would help investigate the situation on site and gather specific Bitdefender module-based logs. So far, we're still waiting for replies form some users and other have completely declined the offer. As soon as a fix is discovered, based on the open cases future interactions we will inform you about it. 
@SebastianLang are you interested in using Bitdefender in the future and in troubleshooting the situation? If "yes" please write us at bitsy@bitdefender.com and specify in your email "Visual Studio incompatibility github.com/aspnet/Tooling/issues/". Thank you!

**Comment by sayedihashimi** [comment]
Hi everyone. We've heard back from bitdefender and they have issued a fix that is available at no cost to existing customers. Here is the quote that I received today regarding this.

>We gladly inform you that the issue is fixed in Bitdefender 2017, released yesterday. 
The new program is available for download in Bitdefender Central for all our customers and the upgrade is free of charge: https://central.bitdefender.com/ 

Closing this now.
