### ISSUE TITLE
Solution Explorer and file system inconsistencies.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#31]
When I add folder to solution It creates a global.json file and a src folder.
**note even the global.json includes a test folder, this one isn't created nor shown on solution explorer**
If I remove the src folder from solution explorer, it get recreated after a kpm restore.

If I create a new project without folder for solution, and create a global.json myself and a new ConsoleApp (asp.net 5) and do a kpm restore i cannot get this src folder to be created.

If I create the test folder manually, and add a Class Library (ASP.NET 5) to this folder, it still shows inside the src folder on solution explorer.

If I open one of the project.json I get the solution reopened.
If I delete the .sln and open one project.json, it gets open alone and it shows the .vs folder inside Solution Explorer.

Looks like there are a some inconsistencies between solution explorer and filesystem / config files.

global.json is not supported for File - Open Project.

note that kpm will work based on global.json (i think ??) but solution explorer uses the sln and it looks like those can get out of sync?

**Comment by sayedihashimi** [comment]
@Bartmax the ```src``` node in Visual Studio is a solution folder. It's not a true representation of the folder on disk. In the future (_likely past the final release of Visual Studio 2015 RTM_) we are hoping to add a ```Unit Test``` checkbox for ASP.NET 5 on the One ASP.NET dialog. When we do that we will also create a ```test``` solution folder with the project under it.

After that when you add a project you should right click on either ```src``` or ```test``` to get your project added to the correct spot.

If you create a test folder manually, you should add a new solution folder named ```test``` and then right click and pick ```Add Existing Project``` to get it in the correct spot.

Can we close this item now?

Related to #61

**Comment by Bartmax** [comment]
@sayedihashimi sure! thanks for the input.
