### ISSUE TITLE
"Change Authentication" template dialog wording issues

### ISSUE THREAD

**Issue by Eilon** [aspnet/Tooling#310]
See screenshot.
- The word `And` needs to be lowercase (not Title Case)
- The multi-org-auth tooltip looks like it's missing a word at the end of the sentence

![auth](https://cloud.githubusercontent.com/assets/202643/11486606/0148f866-976f-11e5-9b6c-ce4dadea08a5.png)

**Comment by BillHiebert** [comment]
@phenning

**Comment by sayedihashimi** [comment]
TFS: 168819
I've added this to our internal TFS, we will reply back here soon.

**Comment by mlorbetske** [comment]
From the TFS item, looks like this has been fixed
