### ISSUE TITLE
resx resources get embedded with the wrong resource identifier if the project's default namespace differs from the project name

### ISSUE THREAD

**Issue by oliverw** [aspnet/Tooling#311]
The compiler currently embeds resx resources with the wrong resource identifier if the project's default namespace differs from the project name.

**Scenario:**

- Project Name: `ConsoleApp1`
- Default Namespace: `ConsoleApp`
- Resource Name: `Resource.resx`

**Expected behavior:**

The resource would be embedded as `ConsoleApp.Resource.resources`

**Actual behavior:**

The resource is embedded as `ConsoleApp1.Resource.resources`

This is especially bad as Designer.cs files generated from .resx resources use the correct identifier when instantiating the resource manager resulting in `MissingManifestResourceException`s thrown at runtime when accessing any of the generated properties.

[Link to demo project](https://onedrive.live.com/redir?resid=754261B3C2015CB0!95771&authkey=!AOguho3aeJSbV3g&ithint=file%2czip)

**Comment by sayedihashimi** [comment]
TFS: 168817
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
Should be fixed in our upcoming RC2 release

**Comment by fubar-coder** [comment]
This is not fixed yet (preview 2). The workaround with "namedResource" isn't usable when you have hundreds of embedded resource files.

**Comment by fubar-coder** [comment]
@sayedihashimi It's not fixed. please reevaluate the issue.
