### ISSUE TITLE
"Produce outputs on build" checkbox does not work

### ISSUE THREAD

**Issue by LeeCheneler** [aspnet/Tooling#313]
Unsure when this bug was introduced (not used the feature in a few weeks)

You can check `Produce outputs on build` in a certain configuration. When you change configuration and then back again it has reset to unchecked. I can't get it to stick on checked and so I cannot produce outputs anymore.

This effects aspnet websites and regular package class libraries that run off of the project.json file.

**Comment by LeeCheneler** [comment]
Hey, yeah that is the intended behaviour however the issue is on my machine it won't stick to checked in any configuration. If I check it, then close the tab or swap configuration then go back to the one I checked it on, it is unchecked. Does that make sense? And so due to it being stuck as unchecked my project won't produce any build output. Thanks for quick response.

**Comment by LeeCheneler** [comment]
OK, so we're having a bit of a nightmare with this now. `Debug` and `Release` configuration always matches, we can't produce output for `Release` builds only. And it seems sporadic as to when we can save the changes to the coniguration, the `*` indicating the configuration can be saved doesn't always show (almost never really) after we've made changes. And the changes don't seem to take effect until the `*` has decided to show itself and we can save the configuration.

**Comment by avanderhoorn** [comment]
I can confirm this issue. I have a solution/project that wont let me select the tickbox. The weird thing is, the xproj is being updated with the following, but its not producing the output and the tickbox shows as unticked next time I open it...

Here is the update that VS did to the xporj (but doesn't change anything)... I also tried removing the `conduction` but it didn't make any difference.
```
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <ProduceOutputsOnBuild>True</ProduceOutputsOnBuild>
  </PropertyGroup>
```

**Comment by LeeCheneler** [comment]
That looks like the correct config to produce output on debug builds. This is what I'm having to add manually to our projects. It works as expected, for us though the issue is that VS isn't producing this.

**Comment by avanderhoorn** [comment]
At least for the issue I had, the following should work...

My xproj file previously looked like the following:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>
  <PropertyGroup Label="Globals">
    <ProjectGuid>06f2ef61-61d8-40c9-8bee-ebf64352de6f</ProjectGuid>
    <RootNamespace>Glimpse.Agent.Web</RootNamespace>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)'=='' ">..\..\artifacts\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <OutputPath Condition="'$(OutputPath)'=='' ">..\..\artifacts\bin\$(MSBuildProjectName)\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <SchemaVersion>2.0</SchemaVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <ProduceOutputsOnBuild>True</ProduceOutputsOnBuild>
  </PropertyGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties />
    </VisualStudio>
  </ProjectExtensions>
  <Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.Props" />
  <Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.targets" />
</Project>
```

And this is what it should have been:
```
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>
  <Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.Props" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>06f2ef61-61d8-40c9-8bee-ebf64352de6f</ProjectGuid>
    <RootNamespace>Glimpse.Agent.Web</RootNamespace>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)'=='' ">..\..\artifacts\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <OutputPath Condition="'$(OutputPath)'=='' ">..\..\artifacts\bin\$(MSBuildProjectName)\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <SchemaVersion>2.0</SchemaVersion>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <ProduceOutputsOnBuild>True</ProduceOutputsOnBuild>
  </PropertyGroup>
  <ProjectExtensions>
    <VisualStudio>
      <UserProperties />
    </VisualStudio>
  </ProjectExtensions>
  <Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.targets" />
</Project>
```
Note the changed position of `<Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.Props" />`.

Turn out this bug effected some people in the Beta4 - Beta5 transition.

**Comment by sayedihashimi** [comment]
@avanderhoorn thanks, yes we had an issue in an earlier build where the `.props` file is not added in the right spot. Moving the import for the `.props` file to the top should resolve it.

@LeeCheneler I think that should fix your issue. I'll go ahead and close this now, but if it doesn't resolve it for you please reopen this.

**Comment by LeeCheneler** [comment]
Sorry for delay.

This is the state of my xproj:

```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="14.0" DefaultTargets="Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <PropertyGroup>
    <TypeScriptCompileOnSaveEnabled>False</TypeScriptCompileOnSaveEnabled>
    <VisualStudioVersion Condition="'$(VisualStudioVersion)' == ''">14.0</VisualStudioVersion>
    <VSToolsPath Condition="'$(VSToolsPath)' == ''">$(MSBuildExtensionsPath32)\Microsoft\VisualStudio\v$(VisualStudioVersion)</VSToolsPath>
  </PropertyGroup>
  <Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.Props" Condition="'$(VSToolsPath)' != ''" />
  <PropertyGroup Label="Globals">
    <ProjectGuid>6cc81765-f5b7-4ab9-955f-072ec02c7cc0</ProjectGuid>
    <RootNamespace>Fire.FrontEnd</RootNamespace>
    <BaseIntermediateOutputPath Condition="'$(BaseIntermediateOutputPath)'=='' ">..\..\artifacts\obj\$(MSBuildProjectName)</BaseIntermediateOutputPath>
    <OutputPath Condition="'$(OutputPath)'=='' ">..\..\artifacts\bin\$(MSBuildProjectName)\</OutputPath>
  </PropertyGroup>
  <PropertyGroup>
    <SchemaVersion>2.0</SchemaVersion>
    <DevelopmentServerPort>27336</DevelopmentServerPort>
    <TypeScriptCompileBlocked>True</TypeScriptCompileBlocked>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <ProduceOutputsOnBuild>True</ProduceOutputsOnBuild>
  </PropertyGroup>
  <Import Project="$(VSToolsPath)\DNX\Microsoft.DNX.targets" Condition="'$(VSToolsPath)' != ''" />
</Project>
```

And I'm afraid this hasn't resolved my issue. I had to manually add the property group to produce output on release only.
