### ISSUE TITLE
Add Output Path UI

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Tooling#314]
Originally posted at https://github.com/aspnet/Home/issues/565 by @smudge202

We have the ability to control the Output Path property in the .xproj file. We should have some UI for that in the property pages so that editing the .xproj directly is not required.

**Comment by sayedihashimi** [comment]
TFS: 168813

**Comment by jorgensigvardsson** [comment]
Status? It's quite annoying not being able to set the output path in multi project solutions.

**Comment by sayedihashimi** [comment]
We have added an output path field on the Build property page. I'll close this now but if you feel this is still an issue please reopen.
