### ISSUE TITLE
error creating solution unchecking Create Directory for solution

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#315]
Hi, a few days ago I saw that using a older beta of the web tools, creating a new asp.net 5 project **unchecking** the **Create directory for solution** option in the New Project wizard window, the project was created in an incorrected model.
I tried with update 1 and rc 1 beta tools and the project isn't created with this error:

![untitled2](https://cloud.githubusercontent.com/assets/127777/11512871/a25ee9b6-9870-11e5-8967-380cc32f679c.png)

Anyway I suppose that using asp.net 5 projects this flag must be ignored, and ensure that every .sln file and src directory is separated from other project, to avoid problems

**Comment by lucamorelli** [comment]
this error message was caused by a mef cache problem, and after the reset the wizard completed, but I see a thing

![untitled](https://cloud.githubusercontent.com/assets/127777/11664894/7ca9afb6-9de4-11e5-8668-228d5e07bcbd.png)

in the created project the **global.json** and **nuget.config** files are not created. Is this a valid configuration?

**Comment by sayedihashimi** [comment]
OK glad you were able to get around this. For `global.json` and `nuget.config` you should keep the checkbox for solution folder checked. Closing this now.
