### ISSUE TITLE
In VS2015, why does running 'dnu' from the Package Manager Console cause my .NET Core Console application to NOT display a Console Window?

### ISSUE THREAD

**Issue by terry420** [aspnet/Tooling#317]
Why does running *dnu* from the *Package Manager Console* cause my .NET Core Console application to fail to display a *Console Window*?

In VS2015:

 1. *File->New->Project*
 2. Choose *Installed->Templates->Visual C#->Web->Console Application (Package)*
 3. Hit *F5* to run, and see the *Console Window* appear, which is expected

Now do the following:

 1. *Tools->NuGet Package Manager->Package Manager Console*
 2. At the *PM>* prompt, enter the following command and hit return:

    *dnu*

 3. Hit *F5* again to run, and note that the *Console Window* does not appear!

This is causing problems, because I'm using the *Console Window* for output.  If I save the Visual Studio project, close Visual Studio 2015, re-open the project and hit F5, the *Console Window* appears.

I'm using this version of *dnu*:

    PM> dnu --version
    Microsoft .NET Development Utility
     Version:      1.0.0-rc1-16202
     Type:         Clr
     Architecture: x86
     OS Name:      Windows
     OS Version:   6.1
     Runtime Id:   win7-x86

I'm using this version of Visual Studio 2015:

    Microsoft Visual Studio Professional 2015
    Version 14.0.23107.0 D14REL

**Comment by sayedihashimi** [comment]
We have a related discussion at https://github.com/aspnet/Tooling/issues/329. It looks like the same underlying issue so I'll close this now. If you think this is different please reopen this with details.

**Comment by terry420** [comment]
#329 seems to be a different issue  (NuGet Package Manager Console hangs).

The issue that I describe above is a .NET Core Console application to fail to display the regular Console Window -- not the NuGet console, but just a regular Console window.

**Comment by terry420** [comment]
I don't think I have the privileges to reopen this issue.  
sayedihashimi, can you please reopen this?

**Comment by oceanmountain** [comment]
Hello!

 

You have a new message, please read <http://kchiryou.net/flood.php?g4>

 

kay@oceanmountain.nl
