### ISSUE TITLE
--no-source flag and "Compile source files into NuGet packages" in VS Publish

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Tooling#318]
Originally posted by @halter73 GuardRex at https://github.com/aspnet/vsweb-publish/issues/27

>RE: VS Publish
Confused a bit on why the setting for "Compile source files into NuGet packages" ... It results in a `dnu publish` command with `--no-source`. I expected the opposite behavior, which means I don't understand what the switch does relative to what the `--no-source` flag means in the command. What am I missing in my understanding? 

>@vijayrkn Ok, thanks. That makes perfect sense. I was just asking b/c I was just talking to @davidfowl  about [getting the signing key of an assembly in the right spot](https://github.com/aspnet/dnx/issues/3029#issuecomment-159675819) in a published app so it would get picked up in the server environment. He said to go "--no-source" to get a full project structure in the published app, and that's when it sort of dawned on me that the name of the flag is kind-of misleading and kind-of doesn't match what the checkbox says with the word "no" in there. I just expected it to go the other way in terms of what the flag did. No worries ... thanks for responding.

>Let me leave you with one idea though along these lines. You say that it was best to not show that checkbox as "--no-source" ... yes ... totally get that ... but when @davidfowl said to publish "--no-source", I went looking for that and it took me a little while to figure it out, especially because the wording seems a little backwards. Just as an idea here: Perhaps making the text of the checkbox read like this ...
```
Compile source files into NuGet packages (--no-source)
```
>... would solve both situations: let folks know what's going to happen but also explain what switch will be added to the publish command. I'll wait to hear if that's a decent idea before closing; but if that's no good and you want to close, please go ahead and close ... this issue was mostly just about my question on it.

**Comment by sayedihashimi** [comment]
I agree let's add `--no-source` to the label for the checkbox so that it's more obvious how it maps to the command line.

**Comment by sayedihashimi** [comment]
TFS: 169345
I've added this to our internal TFS, we will reply back here soon.

**Comment by Bartmax** [comment]
I really like the information consistency with command line and tooling. it's great and easy way to learn, please implement as much as possible on all posible scenarios. :+1:

**Comment by sayedihashimi** [comment]
FYI with the changes to use `dotnet` instead of `dnx` publishing sources will not be supported. So we will be removing this option from the publish dialog. Based on that I'll go ahead and close this.
