### ISSUE TITLE
UTF-8 Without BOM

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#32]
Using tools like jshint-brunch I receive constantly character not recognized due to BOM (signature) of utf8 files.

I don't know what is this exactly, will working with mac / windows line ending and encodings becaming a new problem ?

Right now I just have to save with encoding and choose no signature for all javascript files. I would preffer not to.

**Comment by madskristensen** [comment]
I use this extension to remove the BOM automatically https://visualstudiogallery.msdn.microsoft.com/540ac2d8-f881-4794-8b00-810d28257b70

**Comment by sayedihashimi** [comment]
Is there any further action needed here? If not can we close this?

**Comment by Bartmax** [comment]
@sayedihashimi  Looks like it's fixed on RC.
