### ISSUE TITLE
No JSON schema available for hosting.json

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#320]
In VS 2015 Update 1, there's no JSON schema support for the `hosting.json` file:

![hosting_json](https://cloud.githubusercontent.com/assets/10702007/11581794/a92d8030-9a0b-11e5-8e40-2be454b652b1.png)

I'm willing to submit a PR for this schema; however, I have no idea what the available options are. Is this documented somewhere?

**Comment by sayedihashimi** [comment]
assigned to @madskristensen

**Comment by Tratcher** [comment]
FYI: There is no longer a default file for hosting config.
