### ISSUE TITLE
resx C# generated code invalid in Class Library Package targeting net40

### ISSUE THREAD

**Issue by nlips** [aspnet/Tooling#321]
My package must target .Net 4.0 => 4.5 and DNX.
Il contains a .resx file.
The corresponding designer.cs generated file contains invalid code for .Net 4.0
(due to the new GetTypeInfo extension method)
The generated code should contain precompiler condition statements (as #if NET40) to be valid in each cases.

**Comment by sayedihashimi** [comment]
TFS: 174121
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
@nlips can you share more details about your project? Could you send us a sample?

**Comment by nlips** [comment]
same as #393

**Comment by srollinet** [comment]
Just had this problem now.

I don't know if it is a good solution but as a workaround, you can add a class that is compiled only for .Net 4.0 with a fake implementation of GetTypeInfo()

```
#if LEGACY
namespace System.Reflection
{
    public static class IntrospectionExtensions
    {
        public static Type GetTypeInfo(this Type type)
        {
            return type;
        }
    }
}
#endif
```

and in project.json
```
    "net40": {
      "buildOptions": {
        "define": [ "LEGACY" ]
      }
    }
```

**Comment by sayedihashimi** [comment]
Sorry for the delay here. There has been a lot of changes that have happened since you filled this issue. Can you try again with VS2017 RC and let us know if this issue persists? I'll close this now, but please reopen if it's still an issue.
