### ISSUE TITLE
Asp.Net 5 - xUnit output not showing in Visual Studio 2015 [Tooling]

### ISSUE THREAD

**Issue by michaelvolz** [aspnet/Tooling#324]
Source. https://github.com/xunit/xunit/issues/608#issuecomment-162249954

On the xUnit repo, Brad Wilson wrote:
"The issue here is Visual Studio, not xUnit.net. We send them the output for all tests, passing or otherwise, and they choose whether or not to show that output."

Is this bug known. Is there any way to fix it? 

I Really would love to see some output in my unit tests. 
The workaround is to use the command line but having it in Visual Studio would be much more convenient.

**Comment by sayedihashimi** [comment]
@michaelvolz Do you have a test command in the `project.json`?

**Comment by michaelvolz** [comment]
I have the following lines in my project.json of the test project:

```json
  "commands": {
    "test": "xunit.runner.dnx"
  },
```

**Comment by bluemmc** [comment]
See also "https://github.com/xunit/xunit/issues/718". It appears it is because xunit does not capture output to console/diagnostics but expects output to be made using xunits ITestOutputHelper. The change needed in Visual studio is to display output from ITestOutputHelper.

**Comment by michaelvolz** [comment]
I am already using the ITestOutputHelper. I try to make a very simple example project to demonstrate the problem. I need a little time for that.

Something else happened: When I have a failing test, the output is shown in the Test Explorer, but not in successful tests.

**Comment by Nogbit** [comment]
I have the exact same problem, even when testing a simple "Class Library (Package)".  Only if the test fails is output visible, if the test passes the output is not even available to click on.

xunit project
```
{
  "dependencies": {
    "System.Threading.Tasks": "4.0.11-beta-23516",
    "uwsws": "",
    "xunit": "2.1.0",
    "xunit.runner.dnx": "2.1.0-rc1-build204"
  },
  "commands": {
    "test": "xunit.runner.dnx"
  },
  "frameworks": {
    "dnx46": { },
    "dnxcore50": { }
  }
}
```

Library project
```
{
  "version": "1.0.0-*",
  "description": "uwsws Class Library",
  "authors": [ "marc" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",

  "frameworks": {
    "dnx45": {
      "dependencies": {
        "System.Net.Http": "4.0.1-beta-23516"
      }
    },
    "dotnet5.5": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516",
        "System.Net.Http": "4.0.1-beta-23516"
      }
    }
  }
}

```

**Comment by davidpeden3** [comment]
I have the same issue. There is no `output` link to click per the docs.

Really hoping that https://github.com/xunit/resharper-xunit/issues/38 gets resolved soon and then I will no longer care.

**Comment by michaelvolz** [comment]
I finally had the time to make a very simple test project. https://github.com/michaelvolz/xUnitTestOutputHelper_AspNet5

**Comment by oceanmountain** [comment]
Hello!

 

You have a new message, please read <http://videotelevisions.com/wake.php?l77sc>

 

kay@oceanmountain.nl

**Comment by oceanmountain** [comment]
Hello!

 

You have a new message, please read <http://cn.rinhoo.com/boost.php?ps>

 

kay@oceanmountain.nl

**Comment by kwaclaw** [comment]
This still does not work with ASP.NET Core RC2 tooling in VisualStudio 2015.
Test output (ITestOutpuhelper) is only shown when the test fails.

Here is the project:
```
{
    "version": "1.0.0-*",

    "dependencies": {
        "NETStandard.Library": "1.5.0-rc2-24027",
        "xunit": "2.1.0-*",
        "dotnet-test-xunit": "1.0.0-*"
    },
    "frameworks": {
        "netcoreapp1.0": {
            "dependencies": {
                "Microsoft.NETCore.App": {
                    "type": "platform",
                    "version": "1.0.0-rc2-3002702"
                }
            },
            "imports": [
                "dnxcore50",
                "portable-net45+win8"
            ]
        }
    },
    "testRunner": "xunit"
}
```

Here is the test class:
```
     public class Class1 {
        readonly ITestOutputHelper output;

        public Class1(ITestOutputHelper output) {
            this.output = output;
        }

        [Fact]
        public void ShowOutput() {
            output.WriteLine("Inside Showoutput().");
            //Assert.Equal(2, 3);
        }
    }
```

**Comment by rposener** [comment]
+1 waiting on a resolution

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231247&fullScreen=false&_a=edit">231247</a>

**Comment by niemyjski** [comment]
+1 still not working in rtm.. We have to have this...

**Comment by niemyjski** [comment]
@sayedihashimi what's the status of this?

**Comment by bradwilson** [comment]
@niemyjski To be fair, the tooling is not yet RTM, only the framework. 😺

**Comment by sayedihashimi** [comment]
Sorry for the delay here. We've had a lot of updates over the past few months and I believe that this is working now in VS2017 RC. Can you try with the latest VS2017 and try again? I'll close this now, but please reopen if this issue still persists.

**Comment by TroySchmidt** [comment]
Using VS2015 Update 3 it still isn't working.  Will there be a fix for VS2015?

**Comment by raffaeu** [comment]
@TroySchmidt +1
In VS2015 Update 3 is not working which makes quite hard to use it, especially because we can't use VS 2015 UPD3 + VS 2017 Beta together ...
