### ISSUE TITLE
VS crashes when clicking Project URL link in Bower UI's right panel

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#327]
I'm using Update 1 of VS 2015 and the RC1 Update 1 ASP.NET tooling. When I open the new Bower UI via the "Manage Bower Packages" option, and search for "react", the project URL begins with the "git" protocol:

`git://github.com/facebook/react-bower.git`

Clicking this link causes VS 2015 Update 1 to crash:

![vs2015_crash](https://cloud.githubusercontent.com/assets/10702007/11638696/f725be12-9ced-11e5-8e40-7a8c5aac16a9.png)

Should all occurrences of "git://" be replaced with "https://"? I would expect the clickable link to go here: `https://github.com/reactjs/react-bower`.

**Comment by sayedihashimi** [comment]
Assigning to @madskristensen

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231246&fullScreen=false&_a=edit">231246</a>

**Comment by sayedihashimi** [comment]
Sorry for the delay here. We've had a lot of updates over the past few months and I believe that this is working now in VS2017 RC. Can you try with the latest VS2017 and try again? I'll close this now, but please reopen if this issue still persists.
