### ISSUE TITLE
Issues with doing a build while site is running

### ISSUE THREAD

**Issue by rynowak** [aspnet/Tooling#33]
Copied from https://github.com/aspnet/Routing/issues/170

Hi,

I have an application with URLs with extensions (eg. http://app.com/eZ6Vwe.m). When the URL does not end with / (slash) it sometimes returns 404. But sometimes it works. I don't understand why. Can you help me to find out where is the problem?

Thank you!

> Can you please provide us with a small repro project and some examples of cases that do and do not work so we can investigate?
  
Of course, here it is: http://moontea.net/routewithextension.zip

Open solution in VS 2015 CTP 6
Start project without debugging
Go to /hash.m => should work
Rebuild the solution (do not stop the application)
Go again to /hash.m => returns 404
The following URLs work as expected:

/hash.m/ (with ending slash)
/hash:m
/hash:m/

Do you encounter any routing problems when you don't rebuild while the sever is running?
>
>Do you encounter any routing problems after restarting the server? (It sounds like all of your issues go away if you restart the site).

>I'm suspecting this is a tooling/timing issue because I am unable to reproduce it locally on my VS build (which is newer). If there's no routing problem in steady-state then I'm going to move this bug to the tooling repo and those folks should be able to provide you more information.
  
It doesn't help to restart the site. Actually it seems it stops working after the restart. I've tried to restart a site running on full IIS on Azure and it stopped working. I can restart IIS Express and it helps. But it's only temporary solution. After I make some changes, it stops working again.

I cannot say right now whether it happens when I don't make any changes while the site is running.
@djanosik
  
Ok it seems there are no routing problems when I don't rebuild, restart or change the site while it is running.

**Comment by sayedihashimi** [comment]
@djanosik sorry for the delay here. I'm looking at this now. I tried the link to the sample above http://moontea.net/routewithextension.zip but it's returning a 404. Is this still an issue? If so could you post the sample again?

**Comment by djanosik** [comment]
@sayedihashimi Yes, it's still an issues. I've re-uploaded the sample project.

**Comment by sayedihashimi** [comment]
Our build infrastructure has changed quite a bit in the last two releases and we have made improvements in this area. I think we should be good here. Please reopen if not.
