### ISSUE TITLE
cannot deploy to docker

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#330]
Hi,
  I tried to deploy an asp.net 5 to Docker after the update to Update 1, but when I go to the publish window Docker is not available asd option anymore.
  I have Docker Tools Preview 0.9 installad, I reinstalled it but I don't see it in the publish window.

**Comment by sayedihashimi** [comment]
@vijayrkn @SteveLasker any ideas?

**Comment by vijayrkn** [comment]
Can you please confirm if you have installed the latest ASP Net5 RC tooling? This is required for the latest docker tooling.
(http://blogs.msdn.com/b/webdev/archive/2015/11/18/announcing-asp-net-5-release-candidate-1.aspx)
-----------
When you initially download and install the Visual Studio 2015 Update 1, you will not immediately have the ASP.NET 5 RC tools installed and available.  When you start a new Web Project you will be presented with the ‘New ASP.NET Project’ window to choose a web application template, and among the templates is a ‘Get ASP.NET 5 RC’ template.  When you choose that template, we will install the RC version of ASP.NET 5 tools and frameworks.
-----------

**Comment by lucamorelli** [comment]
hmmm ... yes, I rembered this post, but was a bit confusing: I installed before rc 1 tools, after the installation asp.net 5 rc 1 update 1 was installed and after this I don't see anything new in the control panel, the only visibile difference is that now I see the docker publishing, thanks.
there are any other differences?

@sayedihashimi this doesn't solve the javascript package problems. FYI the error with package happens only if I have an opened ts or js file when opening  the solution, and seems that this initial error is the cause of several crashes of vs while opening: if I close all the ts and js files before closing vs and reopen I don't have the error and Vs seems not crash anymore, but when I open a js file intellisense and coloring is broken.

**Comment by SteveLasker** [comment]
Hi Luca,
Can you confirm you have the latest Docker Tools for VS Installed? The latest as of now is 0.9.1.
We are working on a solution to be notified when updates are available. Because we use a bundled installer to handle dependencies, such as PowerShell tooling, we can't leverage the default VSIX Extension Updates solution
Steve

**Comment by lucamorelli** [comment]
Hi Steve, I suppose I have the latest version installed but these 2 windows give me two different answers

![untitled](https://cloud.githubusercontent.com/assets/127777/11709802/d35a6468-9f1a-11e5-9e80-48d897e4b63a.png)

![untitled2](https://cloud.githubusercontent.com/assets/127777/11709806/d79287f4-9f1a-11e5-8c5a-b4be11ead295.png)

I tried to publish the program in a newly created vm windows server with containers using the publishing window but I obtain this error mesage


Step 1 : FROM microsoft/aspnet:1.0.0-rc1-final
Pulling repository docker.io/microsoft/aspnet
Error: image microsoft/aspnet:1.0.0-rc1-final not found

**Comment by saurabsa** [comment]
Hi @lucamorelli ,

Are you using a Windows Container? If that is the case, are you aware of you are using a DockerFile which is meant to be target a Linux Container. Please confirm that, in case that helps. We are looking into the issue further.

Thanks

**Comment by SteveLasker** [comment]
Luca, you might want to look at the following post, when you may have crossed streams:
http://blogs.msdn.com/b/stevelasker/archive/2015/08/24/deploying-to-linux-amp-windows-docker-containers.aspx

**Comment by sayedihashimi** [comment]
@lucamorelli let me know if Steve's comment did not help you.

**Comment by sayedihashimi** [comment]
This issue is pretty old. We recently released RC2 https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/. I'm hoping that this is no longer an issue so I'm closing this. If this is still an issue with RC2 please reopen this.
