### ISSUE TITLE
Publish to Azure App Service - bower.json not present error

### ISSUE THREAD

**Issue by alvipeo** [aspnet/Tooling#334]
I don't use bower in my asp.net 5 project (just npm) and when I try to publish it to Azure it throws

ENOENT No bower.json present

**Comment by sayedihashimi** [comment]
In project.json is there a "bower install" in the scripts section? If so, it should be removed.

**Comment by alvipeo** [comment]
Thanks, figured that out.

It's just all those little pieces - you have to remember about project.json, package.json, bower.json, gulpfile.js (and what's going on in there, adding new files to minifying, etc), then it's babel with its plugins and configuration and on top of that everything could change with the its newer version. I miss earlier days of development :)
