### ISSUE TITLE
dnx crashing trying to inspect a loaded assembly in vs

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#335]
I'm trying to convert an utility that loads dinamically the compiled dll of asp.net 5 app.
I created a new console app, and inside the application the dll is loaded using Assembly.Load: the assembly is loaded correctly but if I place the cursor above the source code to inspect the content of the loaded assembly

![untitled](https://cloud.githubusercontent.com/assets/127777/11755267/5d652936-a051-11e5-986d-9a25bd438d80.png)

I receive the error message that dnx is crashed

**Comment by sayedihashimi** [comment]
TFS: 174067
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
Sorry for the delay here. There has been a lot of changes that have happened since you filled this issue. Can you try again with VS2017 RC and let us know if this issue persists? I'll close this now, but please reopen if it's still an issue.
