### ISSUE TITLE
Unable to remote debug a ASP.NET 5 WebApp in Azure

### ISSUE THREAD

**Issue by steve-warwick** [aspnet/Tooling#336]
I created a new ASP.NET 5 RC1 WebApp using Visual Studio 2015 and published it to Azure. I turned on remote debugging and selected VS 2015 for the debugger. I can attach to the WebApp, but any breakpoint I set is not showing up completely red. Hovering over the breakpoint gives you the message "The breakpoint will not be currently hit. No symbols have been loaded for this document." I did a bunch of searches to see if anyone else had encountered this issue. I found some articles that pointed to this one: 

http://stackoverflow.com/questions/19869192/azure-website-remote-debugging-with-git-deploy-not-working/19869600#19869600

I tried turning off "Just my code" and adding the app setting, but neither of these worked. I even had a colleague try the same thing from his system and his Azure account to make sure it wasn't just an environmental issue on my system. 

BTW, I tried the same thing with ASP.NET 4.X and it works fine.

Does anyone know how to fix this?

**Comment by sayedihashimi** [comment]
Hi @steve-warwick Remote Debugging was working for ASP.NET 5, but recently we switched our hosting model to support the HttpPlatformHandler. With this change the remote debugging no longer works. We have a feature on our backlog to enable it. We are hoping to get that for the next release but we cannot commit to it at this time.

You can manually invoke the remote debugging by using the Debug -> Attach to Process dialog. See the info at http://blogs.msdn.com/b/webdev/archive/2013/11/05/remote-debugging-a-window-azure-web-site-with-visual-studio-2013.aspx under ***Remote debugging with Visual Studio 2012***. When selecting processes to debug you should select `w3wp.exe` and `dnx.exe`.

**Comment by steve-warwick** [comment]
Thanks for info. For issues like this is there some place I can check to see when it as has been fixed? For instance, I've noticed that logging doesn't appear to be working in Azure as well. I'm not sure if this a bug or if it just isn't supported yet.

**Comment by gdoron** [comment]
@sayedihashimi 
Any update on the remote debugging?
Also, this issue should probably stay open if it hasn't been fixed yet.

Thanks!

**Comment by sayedihashimi** [comment]
Reopened this. The feature will come in for RC2 or the release after that. For now you can use the Attach To Process dialog https://blogs.msdn.microsoft.com/webdev/2016/03/21/remote-debug-aspnet-core-on-azure/.

**Comment by sayedihashimi** [comment]
Should be fixed with the latest RC2 and Azure SDK release. Closing this.
