### ISSUE TITLE
Unable to Change Resx Resources Access Modifier

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Tooling#339]
Create a new Resource.resx and you will see that the access modifier combo box is disabled, thus not allowing you to change it from `internal` to `public`.

**Comment by sayedihashimi** [comment]
TFS: 174065
I've added this to our internal TFS, we will reply back here soon.

**Comment by senritsu** [comment]
Are there any updates on this issue yet?

**Comment by Doslidnyk** [comment]
I've struck this issue as well, and haven't found any solution online yet, at least nothing recent and related to either VS 2015 or the new ASP NET Core stuff.  Is this actually an issue there, then?

**Comment by sayedihashimi** [comment]
Hi everyone, I'm really sorry you're running into this. It was a mistake on our part. In our next release we are going to change it to generate `public` classes by default. In a release after that we'll enable changing the value in the UI.

The only workaround here is to generate the file and then change `internal` to `public`. If you re-generate the .resx file you'll need to update the class again :(.

**Comment by michael-x** [comment]
Hi @sayedihashimi, is the final solution going to be that one can choose between public and internal or is it going to let us choose a custom tool. We've used a custom tool to generate methods with appropriate parameters instead of properties, which makes usage of resource strings type-safe.

**Comment by michael-x** [comment]
Hi @sayedihashimi, just stumbled across aspnet/Home#272, so disregard my comment, please.

**Comment by sayedihashimi** [comment]
See https://github.com/aspnet/Tooling/issues/394.

For this particular issue we already have a fix ready that changes the default to `public`. Later we will come with a better story.

**Comment by weslyisaacd** [comment]
When can we expect public access selector resource? do you have any timeline?

**Comment by Verdant90** [comment]
Any news on the subject?

**Comment by sayedihashimi** [comment]
Sorry for the delay here. I was hoping that this would come "for free" when we moved to the roslyn project system, but it looks like there may be some pending work here.

I've created a new bug to track the pending work at https://github.com/dotnet/roslyn-project-system/issues/1097. Let's use that for any communication going forward. I'll close this one.

**Comment by sayedihashimi** [comment]
FYI this has been fixed I just verified on my other machine.
