### ISSUE TITLE
Automatic versioning during build

### ISSUE THREAD

**Issue by csunali** [aspnet/Tooling#340]
Sorry if I am asking it in a wrong repository.

Is there a way to automatically increment the package versions during build so that the output being produced during gets versions with some nice version number instead of the default 1.0.0 all the time?

**Comment by GuardRex** [comment]
Dup of https://github.com/aspnet/dnx/issues/3209

**Comment by csunali** [comment]
Right! Was not able to find one when I searched through.

Thanks.

**Comment by GuardRex** [comment]
@csunali np. The crappy PS script version I refer to is https://github.com/GuardRex/net5-autoupdate-version ... and yeah ... it's barely even workaround quality. At least it works (barely).

**Comment by csunali** [comment]
Thanks for sharing!

Is there a way to apply these scripts to multiple projects? For instance using `global.json` or something?

I have about 25 projects in a solution and it becomes a huge pain to maintain them.

**Comment by GuardRex** [comment]
@csunali The PS script could point to anything ... and be triggered in any way. If you wanted to have something that you could click and it would just jack the version across-the-board, you could extend that PS script I did to hit a whole bunch of `project.json` files for a whole bunch of projects. Then, you'd just fire off the script. 

The caveats are (a) It's going to hose the formatting of your `project.json` files (just to the eye ... they'll still work), and (b) it may have a bad side effect of being one version number off of the version that is actually being published, as I describe at the top of the dnx issue I filed (but I trigger it automatically from within the project, you may not face this if using an external script that you manually execute).

Whatever the case, it's kind'a cool just from the standpoint that all you really need to do is modify a bunch of `project.json` files ... PS can do it ... just not so pretty.

**Comment by csunali** [comment]
Thank you for the detailed info.

I will check the PS file ASAP and see how/if it can be improved.

Cheers!
