### ISSUE TITLE
When adding new controllers Views are created on wrong folder.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#342]
If I'm on `Areas/Controllers` right click and add an MVC controller picking a model and `DbContext` the views are created at `/Views/Model/..` instead of `/Areas/AreaName/Views/Model/`

**Comment by sayedihashimi** [comment]
@Bartmax what type of project do you have? ASP.NET 5 (MVC 6) or ASP.NET 4 (MVC 5)?

**Comment by Bartmax** [comment]
ASP.NET5 MVC6

**Comment by oceanmountain** [comment]
Hello!

 

You have a new message, please read <http://izmirpeyzaj.gen.tr/feeling.php?02nd>

 

kay@oceanmountain.nl

**Comment by sayedihashimi** [comment]
This issue is pretty old. We recently released RC2 https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/. I'm hoping that this is no longer an issue so I'm closing this. If this is still an issue with RC2 please reopen this.
