### ISSUE TITLE
Creating a new controllers with a model with Guid doesn't include the appropiate namespaces.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#343]
Create a new controller, using DbContext and Model.

If the model, for example, have a `public Guid Id { get; set; }` the controller does not include `using System` and makes a compile time error.

Not THAT bad, minor annoyance at least.

**Comment by sayedihashimi** [comment]
TFS: 174592
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
Should be fixed in the next release, closing now.
