### ISSUE TITLE
Can't remote debug azure webapp with aspnet5 (Symbols not being loaded)

### ISSUE THREAD

**Issue by jamesla** [aspnet/Tooling#348]
I am trying to remotely debug my Azure webapp application written in aspnet5. I can attach the remote debugger via the server explorer and I can create breakpoints that go red like they will be hit but then they don't get hit.

I'm not sure if this is even implemented or how to find out if it is supposed to work. Any guidance on this issue would be greatly appreciated.

**Comment by sayedihashimi** [comment]
Hi @jamesla remote debugging was working in beta8 but then with the switch to httpplatformhandler we lost that ability. It's on our radar but we have a lot of work ahead of us in the dnx->dotnet switch so we may not be able to get it for RC2.

As a workaround in the mean time you can use the Attach To Process dialog to remote debug the app. More info at https://azure.microsoft.com/en-us/documentation/articles/web-sites-dotnet-troubleshoot-visual-studio/ search for "For Visual Studio 2012 with Update 4 or later" and follow the instructions there. You'll likely need to attach to w3wp.exe as well as the process running your application itself.
