### ISSUE TITLE
Incorrect casing for Grunt Configuration File item template

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#349]
In VS 2015 Update 1 (with the ASP.NET 5 Update 1 tooling installed), the Grunt Configuration File item template uses the incorrect casing in its suggested file name. Note the default value in the "Name" textbox in the screenshot below:

![gruntfile](https://cloud.githubusercontent.com/assets/10702007/11970481/b2467e0c-a8f1-11e5-9b39-15235f8e8838.png)
 
Please change the default file name to `Gruntfile.js`, as that's the standard as documented [here](http://gruntjs.com/getting-started#preparing-a-new-grunt-project) and [here](http://gruntjs.com/getting-started#preparing-a-new-grunt-project).

**Comment by sayedihashimi** [comment]
Opened https://github.com/aspnet/Templates/issues/379 closing this one
