### ISSUE TITLE
"New ASP.NET Project" dialog - insufficient button height

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#351]
I'm running Visual Studio 2015 Update 1 with the ASP.NET RC1 Update 1 tooling. I have confirmed that this was also an issue prior to installing VS 2015 Update 1 (with the ASP.NET RC1 Update 1 tooling installed). The text appearing on the "OK" and "Cancel" buttons in the lower right corner of the "New ASP.NET Project" dialog is being cut off.

![new_project_dialog](https://cloud.githubusercontent.com/assets/10702007/12022518/161c411a-ad56-11e5-81fc-1cfa1f1f4a2b.png)

It's worth noting that the "New Project" dialog which appears before this dialog doesn't suffer from the same problem and has the same 2 buttons. The screen resolution being used for the attached screenshot is 1366 x 768.

**Comment by sayedihashimi** [comment]
TFS: 180297
I've added this to our internal TFS, we will reply back here soon.

**Comment by xperiandri** [comment]
What about this?

<img width="400" alt="projectcreationui" src="https://cloud.githubusercontent.com/assets/2365592/13380475/081a426a-de4d-11e5-8bf2-e2471d3c8e8d.png">

And this. Here font size does not correspond to Visual Studio settings.

<img width="622" alt="font issues" src="https://cloud.githubusercontent.com/assets/2365592/13380490/71d344e0-de4d-11e5-8e1e-da687b1497bf.png">

**Comment by mlorbetske** [comment]
This has been fixed for an upcoming release of Visual Studio 2017 (post 2017.3)

**Comment by xperiandri** [comment]
@mlorbetske, is it available in preview 3?

**Comment by mlorbetske** [comment]
No, there's an OK chance that 2017.3 preview 4 will carry the change. If it does not, the fix will come in the next release that updates web tools.

**Comment by xperiandri** [comment]
It would be nice to check before release.
OK, let's wait
