### ISSUE TITLE
Error attempting to run DNX design time process with global runtime

### ISSUE THREAD

**Issue by dls314159** [aspnet/Tooling#353]
I'm trying to open a VS2015 solution with projects that target the dnx-clr-win-x86.1.0.0-rc1-update1 runtime and I get an error message:

>The following error occurred attempting to run the DNX design time process (dnx-clr-win-x86.1.0.0-rc1-update1).
>
>The system cannot find the file specified

I've installed runtimes using the global flag. They appear in C:\ProgramData\Microsoft DNX\runtimes, and they show up in dnvm list (although there is something odd about dnvm list and aliasing with globally installed runtimes).

Is there something else I need to do to get globally installed runtimes working with the VS2015 tooling?

**Comment by dls314159** [comment]
I should have searched more diligently. I think this may be the same issue seen differently in https://github.com/aspnet/Tooling/issues/312

**Comment by solarding** [comment]
I just have the same problem and find no answers from google

**Comment by sayedihashimi** [comment]
What's inside the `global.json` file? Can you share a sample solution?

**Comment by shanekingsley** [comment]
I am having this same issue, Visual studio 2015 community. Trying to create an empty ASP.NET 5 web project

**Comment by lpeteet** [comment]
Same Issue, can someone help?

![image](https://cloud.githubusercontent.com/assets/8249650/12373803/1471e748-bc4c-11e5-8840-9ad2cda65274.png)

**Comment by parak80** [comment]
Hi, my error is a bit different, Im using cache, session and cookie as for my assignments and my solution file opens with this error so it cant run my codes. I also checked which switch on and off windows features/internet informtion services/world wilde web services/application development feachers and chosing .NET there to turn them on but it didnt make any changes. anyone knows what I should do with this error?
![error](https://cloud.githubusercontent.com/assets/14640530/12394986/5c1921c4-bdff-11e5-8932-b04be6b8b1af.jpg)

**Comment by LuisM78** [comment]
Hi, I have the same error message. Did anybody solved it? thanks, Luis

**Comment by parak80** [comment]
Hi Luis,
Yes, I solved it. Its all related to Dnx which the path of the project.
First check your startup page if you have any missing location for example
if you use entity framework or other location. Then go to control panel and
click on switch on and off windows and then find internet services, then
the third option/worldwide and then application, switch on all of them and
apply
Check if your solves with this :)
Good luck

Best,
Parisa

**Comment by dls314159** [comment]
I think I had this issue because that machine had the runtimes installed with the global flag and not in my home directory. I reinstalled the runtimes using dnvm for each user who needed to launch VS and the tooling. That worked, so I assumed it was a limitation of the RC1 tooling and I didn't pursue it further.

I think the error that references an IP address is different from the one I've seen.

**Comment by LuisM78** [comment]
@  parak80 and dls314149. Thanks for your answers!

**Comment by robianmcd** [comment]
I was able to solve this problem with this solution http://stackoverflow.com/a/34972175/373655

**Comment by sayedihashimi** [comment]
Did the workaround in http://stackoverflow.com/questions/34971627/dnx-error-unable-to-start-the-process/34972175#34972175 fix this for everyone? It sounds like it may have.

FYI `dnx` command line is being replaced by `dotnet`. I don't think that we will have this same issue with `dotnet`. I'll close this now, but after the release goes out with `dotnet` let me know if you still run into this.

**Comment by dls314159** [comment]
I was never able to successfully use a globally installed runtime with the VS2015 design time; however that work around worked fine for locally installed runtimes.

**Comment by iulianflorescu** [comment]
Go to the Project-> SolutionDNX SDK version and see what you have there. If nothing open Tools-> NuGet Package Manage-> Console and Install the last version of DNX from here: https://www.nuget.org/packages/dnx-clr-win-x86/1.0.0-rc1-update1
After this Try to select again  Project-> SolutionDNX SDK 
I did this after reinstaling VS and .NET 5 RC and after I have searched for more than 5 hours for resolving this.
Hope you get it done
