### ISSUE TITLE
Hosting:Environment cant changed

### ISSUE THREAD

**Issue by muratg** [aspnet/Tooling#354]
_From @muratg on December 30, 2015 17:50_

_From @endink on December 29, 2015 2:9_

i upgrade my ASP.NET MVC 6 project to RC2, and the I change settings in launchSettings.json,
```
{
  "iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:45646/",
      "sslPort": 0
    }
  },
  "profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "environmentVariables": {
        "ASPNET_ENV": "Development"
      }
    },
    "web": {
      "commandName": "web",
      "launchBrowser": true,
      "launchUrl": "http://localhost:5001",
      "environmentVariables": {
        "ASPNET_ENV": "Development"
      },
      "sdkVersion": "dnx-clr-win-x64.1.0.0-rc2-16302"
    }
  }
}
```
and everythings seems ok, but when i restart VS2015, the property window of the project still like this:
![default](https://cloud.githubusercontent.com/assets/240164/12028541/cbbd1d42-ae13-11e5-88c3-ddab680e57f4.PNG)

and i check the launchSettings.json file , "ASPNET_ENV" be used in launchSettings.json, VS project property window display "Hosting:Environment", i had to change "Hosting:Environment" to "ASPNET_ENV" each time, is there some cache for this settings? please help, thanks!

BTW, only "web" like this, "IIS Express" is OK

_Copied from original issue: aspnet/dnx#3288_

_Copied from original issue: aspnet/Hosting#541_

**Comment by muratg** [comment]
_From @Tratcher on December 30, 2015 19:57_

@BillHiebert this is a tooling bug. @JunTaoLuo and I have run into it too. The UI is not staying in sync with the launchSettings.json file.

**Comment by mikes-gh** [comment]
I confirm this also as tooling bug.  Sometimes environment gets set back to old Hosting:Environment and out of sync with launchSettings.json.
Also note new environment variable is ASPNET_ENVIRONMENT  
ASPNET_ENV istill works but s depreciated.

**Comment by sayedihashimi** [comment]
TFS: 180289
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
This has been recently fixed, which will be in the next release.

**Comment by sayedihashimi** [comment]
Closing
