### ISSUE TITLE
Changes are not allowed while code is running

### ISSUE THREAD

**Issue by atrauzzi** [aspnet/Tooling#355]
I have an ASP.NET MVC 6 project with a very simple `project.json` and `Startup.cs`.  Browser link is included although for some reason, when I run the project from visual studio, it insists that I can't edit my code and have it reload live.  The message is *"Changes are not allowed while code is running"*

Is there something missing or something about my project I need to fix?

**Comment by sayedihashimi** [comment]
@madskristensen is this a browserlink or project system issue?

**Comment by sayedihashimi** [comment]
This issue is pretty old. We recently released RC2 https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/. I'm hoping that this is no longer an issue so I'm closing this. If this is still an issue with RC2 please reopen this.

**Comment by atrauzzi** [comment]
Sounds good.
