### ISSUE TITLE
The following error occurred attempting to run the DNX design time process

### ISSUE THREAD

**Issue by jaganjan** [aspnet/Tooling#358]
When i open my project i was get randomly to this issue.

**The following error occurred attempting to run the DNX design time process (dnx-clr-win-x86.1.0.0-rc1-final)**

**No connection could be made because the target machine actively refused it [::ffff:127.0.0.1]:39084**

**The DNX design time process provides intellisense, build and reference information to Visual Studio and without it your experience will be very limited. Please tyr closing and reopening Visual Studio to see if that corrects the problem. Alternatively, check that the DNX version is properly installed or try changing to a different installed DNX version using the project property pages.**

what is the problem at that time ,when i restart the vs issue  not occured, but reload the project  issue occured sometimes..the similar issue is #232

**Comment by solarding** [comment]
I have the same problem with 1.0.0-rc1-update1.
I used to fixed it by repair the ASP.NET 5 RC1 update1, which took a long time to run.
Yet problems just come back all of a sudden with no reasons :(

**Comment by oliverguhr** [comment]
I got the same problem. I did a repair install with the  ASP.NET 5 installer, but it dind fix the problem.

**Comment by sayedihashimi** [comment]
This sounds like it may be a setup related issue but I'm not sure. @joeloff or @BillHiebert any ideas on next steps?

**Comment by virendrad** [comment]
Well, running dnvm update-self command before opening the project does the job for me. It's also mentioned here 
http://www.talkingdotnet.com/how-to-fix-dnx-project-start-up-error-in-vs-2015/

**Comment by LexDan** [comment]
Worked perfectly using: dnvm update-self command
Thanks much!

**Comment by sayedihashimi** [comment]
It seems like this is no longer a problem so I'll go ahead and close this. FYI when we move from dnx to dotnet we may not have this feature (at least initially).

**Comment by kstr** [comment]
Same problem here with 1.0.0-rc1-update1

**Comment by saadjaved120** [comment]
running "dnvm upgrade" from cmd works for me..

**Comment by Tameshiwari** [comment]
I encountered the very same sporadic issue - as mentioned earlier above - when trying to create a new Asp.Net 5.0 project. 
Running "dnvm upgrade" from Command Prompt(Admin) in project directory
 […\src\projectname] was a fair temporary solution for me to take as it solved the problem. 
I guess this proves that nothing is yet perfect at this stage... so using Core 1.0 is still mainly for R&D development testing...issues can happen... yet it's good to find quick solutions, even if they're temporary. Thanks :)

**Comment by eskandari** [comment]
First going to the project folder using vs command line and running "dnvm upgrade" would fix this issue.
