### ISSUE TITLE
IDE does not apply correct "define"s based on configuration

### ISSUE THREAD

**Issue by mgravell** [aspnet/Tooling#36]
Consider a console exe .json project file that contains:

    "compilationOptions": {"define": ["FOO"]},

and

    "frameworks": {
        "dnx451": {
             "compilationOptions": {"define": ["BAR"]}
        },
        "dnxcore50": {
            "dependencies": {
                "System.Console": "4.0.0-beta-22716"
            }
        }
    }

With code:

    #if FOO
            Console.WriteLine("FOO");
    #endif
    #if BAR
            Console.WriteLine("BAR");
    #endif
    #if DNX451
            Console.WriteLine("DNX451");
    #endif

Now, in VS, select (ctrl+f2) the "{project}.DNX 4.5.1" configuration.

Expectation: the IDE detects the FOO, BAR and DNX451 defines, and displays the 3 lines as enabled.

Reality: the IDE displays the 3 lines as disabled, indicating the IDE has not detected the defines.

The compiler gets this correct; executing the project will print correctly:

    FOO
    BAR
    DNX451

**Comment by davidfowl** [comment]
It's a known issue that is fixed now

**Comment by mgravell** [comment]
Awesome;  that'll make it far easier to see what is happening

**Comment by mgravell** [comment]
Confirmed working in RC

**Comment by davidfowl** [comment]
W00p
