### ISSUE TITLE
No intellisense for TagHelpers

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Tooling#360]
_From @obryckim on January 6, 2016 16:58_

I am not getting any intellisense for tag helpers.  I have seen other issues regarding this and have ensured the following in my project:

project.json contains `"Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final"`
_ViewImports.cshtml contains `@addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"`

![intellisense screenshot](https://cloud.githubusercontent.com/assets/11857283/12148397/29943334-b46c-11e5-8bb3-af6aa42c15ad.png)

The tag helpers are working, though.  When I manually enter them, the text changes in the editor and the proper HTML is generated in the browser.
![intellisense screenshot 2](https://cloud.githubusercontent.com/assets/11857283/12148460/91b671e8-b46c-11e5-9bd6-09cc029e687d.png)

Here is my full project.json: [project.txt](https://github.com/aspnet/Razor/files/80104/project.txt)

My VisualStudio information: [VSInfo.txt](https://github.com/aspnet/Razor/files/80087/VSInfo.txt)

_Copied from original issue: aspnet/Razor#654_

**Comment by NTaylorMullen** [comment]
Very interesting. Moving this over to aspnet/Tooling.

**Comment by mikes-gh** [comment]
Same here although I recall it working at one stage.
I am on rc2 train.

**Comment by chrispickford** [comment]
Identical issue here.

Importing both these packages in `project.json`: 
- `"Microsoft.AspNet.Mvc.TagHelpers": "6.0.0-rc1-final"`
- `"Microsoft.AspNet.Tooling.Razor": "1.0.0-rc1-final"`

Have the following in `_ViewImports.cshtml`
```
@{
    @addTagHelper "*, Microsoft.AspNet.Mvc.TagHelpers"
}
```

Nothing in intellisense.
![image](https://cloud.githubusercontent.com/assets/1290347/13285104/96d05d10-daf0-11e5-9a5e-610625257ba7.png)

**Comment by barrytang** [comment]
Created an internal bug to track - TFS#194770.

**Comment by barrytang** [comment]
Fixed for RC2.
