### ISSUE TITLE
Request for Auto Controllers (Nest Controller and View Model under the View)

### ISSUE THREAD

**Issue by rclabo** [aspnet/Tooling#361]
I have a request that I think would save Asp.Net 5 MVC 6 developers a ton of time.  

I would absolutely love it if the Visual Studio tooling for Asp.Net 5 MVC 6 had a feature that allowed me to create a new strongly typed View and have Visual Studio auto-wire it up to a new ViewModel and a new Controller which it created and visually nested below the View in the solution explorer.

WebForms had a lot of aspects that we all rag on on a regular basis, but one thing that it did really well was simplify the navigation of code between the WebForm and the Code Behind, and the designer file.  In large projects, this can be super helpful.  Heck, it's super helpful even in small projects.  Being able to hit F7 to bounce back and forth between the code behind and the WebForm was absolutely awesome with regards to productivity.  

Working in MVC 6 should have that same level of productivity.  Developers should be able to use F7 (or whatever) and bounce back and forth between the View and the Controller.  Call it an Auto Controller if you will to distinguish it from a manually created controller that is intended for more generic use.  The Auto Controller still only communicates with the View through the shared ViewModel so this approach still adheres to the MVC paradigm, but developers using the Auto Controller approach won't have to hunt for their View, ViewModel and Controller in three separate folders every time they want to work on a page for a large system.  They are all grouped together in the solution explorer.  

So if a developer is looking at a View which has an Auto Controller attached they can just click the little triangle and see the related Controller nested right below the View, and the related View Model right beside it.  Not only does this improve navigation productivity, but it makes it easier for the developer to conceptualize the front end of the system since related files are grouped together.  Thoughts?

**Comment by sayedihashimi** [comment]
@rclabo we are working on supporting scaffolding with ASP.NET 5. It will be similar but different from the scaffolding that we had for ASP.NET 4. We have shipped a version that has some limited support in RC1 and we are continuing to improve that for RC2 and beyond.

One aspect of scaffolding will be extensibility. So you can create your own scaffolders or tweak the generated content from existing scaffolders. I blogged a while back about command line scaffolding at 

 - http://blogs.msdn.com/b/webdev/archive/2014/08/21/command-line-scaffolding-for-asp-net-vnext.aspx
 - http://blogs.msdn.com/b/webdev/archive/2014/08/23/how-to-customize-scaffolding-templates-for-asp-net-vnext.aspx

The Visual Studio support will be based on a command line experience. Note: the specific commands may have changed since that post. We have also decided to [delay command line scaffolding](https://github.com/aspnet/Scaffolding/issues/135) in favor for working on the in Visual Studio experience.

In your case I think you could create a custom scaffolder to realize your scenarios. One feature that we don't have yet is the custom file nesting. We are hoping to work on that for a later release.

**Comment by rclabo** [comment]
@sayedihashimi Thanks, that's great info.  With the default ASP.Net Core scaffolding will there be some hot key (like F7) in Visual Studio that will make it super efficient to jump back and forth between the strongly typed view, the related controller and related view model?  It's this fast navigation that can greatly enhance programmer productivity when doing web development.

**Comment by sayedihashimi** [comment]
@rclabo we haven't added "Go To View" for ASP.NET 5 yet but when we do it should be similar to ASP.NET 4.

In ASP.NET 4 there is a short cut key associated with it. In my VS profile the shortcut is `CTRL + M, CTRL+G`.

@rclabo is there any open item here or can we close this?

**Comment by rclabo** [comment]
@sayedihashimi  Thanks for the response.  My request boils down to two things:

1)The ability to have Visual Studio create a strongly typed view, with a nested related controller and nested related ViewModel via one choice in the Add New Item Dialog.
2)The ability in Visual Studio to use a hot key to quickly jump between any of these three: the strongly typed view, the related controller and the related model.

Will Visual Studio have such support with regard to ASP.NET CORE MVC on launch?

**Comment by sayedihashimi** [comment]
@rclabo for 1 - how is that different from what the Add Scaffolded Item dialog does?

**Comment by rclabo** [comment]
@sayedihashimi - It's just scaffolding, like any other scaffolding. But I'm asking for the scaffolding to create all three files at once and for it to visually nest the controller and strongly typed view model below the view in solution explorer and give them all similar names.  

That way the developer has this trio logically grouped together in the solution explorer, similar to the way that in web forms the web form, code behind, and design file are all grouped together and they share a common name as the first part of the name for each.  The code behind and the design file are logically grouped below the web form in visual studio.  This approach greatly reduces clutter in solution explorer for large projects that have hundreds of web pages, and it makes it very easy to navigate between them in solution explorer.  Since the three files work together as a trio, it's nice not to have them spread out into three different folders in solution explorer.  It's honestly one of the reasons I've waited so many years to convert from web forms to MVC.  I'm not saying it's the main reason, but it was a large consideration give the number of web pages on the sites I manage.

**Comment by sayedihashimi** [comment]
Adding @DamianEdwards @davidfowl to see their thoughts. The tooling in VS just expresses the conventions from the ASP.NET runtime, so this item is really up to them.

**Comment by rclabo** [comment]
@sayedihashimi Thanks for including them in the discussion, I appreciate it.  It'd be great to get their thoughts. Have an awesome day!

**Comment by scottsauber** [comment]
Was mentioned briefly, but +1 to having a shortcut that opens up your model when you're on the view file.  That would be handy.

**Comment by sayedihashimi** [comment]
This is really feedback for runtime conventions. I'm going to close this. If you want to continue the discussion I think it would be better in the repo at https://github.com/aspnet/mvc.
