### ISSUE TITLE
Typescript, wwwroot and source maps

### ISSUE THREAD

**Issue by mbeckenbach** [aspnet/Tooling#362]
Hi, 

i played arround with some typescript in an asp.net 5 project using the builtin typescript compile on save. No gulp or grunt involved.

My files where structured like this:

wwwroot
-> app\demo.js   = compiled javascript
-> app\demo.js.map   = compiled source map
scripts
-> demo.ts   = typescript source
typings
-> xxx.d.ts   = TSD definitions

Now the source map references a path "../../scripts/demo.ts" wich cannot be resolved by browsers as it is not inside wwwroot.

Now i wonder how the suggested best practice for working source maps looks like in asp.net 5 projects.

**Comment by sayedihashimi** [comment]
@mhegazy what's the guidance here?

**Comment by mhegazy** [comment]
use `--soruceRoot` to define the location of the sources for the debugger.

**Comment by mbeckenbach** [comment]
But sources root will not solve the problem for browsers, that cannot access files outside wwwroot.
This works only with the TS debugger. Not with IE, Edge or Chrome Dev tools.

I solved it by placing my TS files inside wwwroot and remove the wwwroot from exclude section in tsconfig for the moment. But this feels kind of wrong. Dont know why.

I know that static file access restriction to wwwroot is not comming from tooling but comming from the framework. It would be great to see some best practice TS setup in ASP.net 5 projects from the view of developers productivity.

**Comment by mhegazy** [comment]
In general users do not like to publish source files (i.e .ts/.d.ts) to production servers. The `--sourceRoot` allows you to specify an alternate location. It can be a local file system, or an internal source server, that you publish your sources too when needed, but is not accessible for the rest of the world. 
the `--sourceRoot` is honored by browsers or any implemenetation of the source map protocol, see https://github.com/mozilla/source-map/#consuming-a-source-map for an example on how it is persisted in the map file.

**Comment by mbeckenbach** [comment]
The internal source server sounds like a good idea. Maybe even some kind of node server running on localhost to have make it available in Dev tools while running locally on the Dev computer.

**Comment by mbeckenbach** [comment]
Which brings me to an idea:
Browserlink runs some kind of web service, correct? Can Browser link act like a proxy that forwards source map URL requests into your project directory? The sources could stay outside of wwwroot and where available in Dev tools while running the project locally.

**Comment by lucamorelli** [comment]
If you need to debug a ts compiled app from chrome tools you can add the settings
    "inlineSourceMap": true,
    "inlineSources": true
to the ts.config file.

**Comment by sayedihashimi** [comment]
This issue is pretty old. We recently released RC2 https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/. I'm hoping that this is no longer an issue so I'm closing this. If this is still an issue with RC2 please reopen this.
