### ISSUE TITLE
TS config ui

### ISSUE THREAD

**Issue by mbeckenbach** [aspnet/Tooling#364]
The typescript section in project properties should reflect what you can do with tsconfig.json

**Comment by sayedihashimi** [comment]
@mbeckenbach thanks for the note. Are you suggesting that we have some features specifically in ASP.NET 5 for this or in general? If you're requesting for better support for tsconfig.json in general I think the item should be filed in https://github.com/Microsoft/TypeScript.

**Comment by sayedihashimi** [comment]
Adding @mhegazy

**Comment by paulvanbrenk** [comment]
This makes indeed more sense in the TypeScript repo.

However our current thinking is to disable the TypeScript property page when we find a `tsconfig.json` in the project, the editing experience is pretty good due to the work @madskristensen has done with schemastore. It's on our radar, but given the other features we want to do, (e.g. Brace Completion) it's not a particular high priority.

That said, due file an issue on the TypeScript GitHub repo, and if we get a lot or response we'll take a another look.

**Comment by mbeckenbach** [comment]
Thanks for your detailed answer. My question was about TS inside ASP.net 5 projects in Visual Studio.

Use case: angular 2 with ASP.net 5. should be quite common.
 
At the moment TS tooling looks a bit confusing, as it is splitted into several places. The tsconfig file, theme properties page and some settings in VS text editor options. 

This makes it hard for newbees to find theme correct settings. Bringing all to one place would be mich easier. Having everything inside tsconfig would be OK too. But then it should have all options like the compile files outside virtual project option from vs text editor settings too.

As it is now, i dont have the feeling of using a huge IDE. It is more like using X tools and a Text editor.

**Comment by paulvanbrenk** [comment]
Thanks for clarifying, the goal is to have all the settings for the project in one location, either in the property page or the `tsconfig.json`. The one option I believe we're missing is 'Compile on Save', and that's something I hope to add this week for the 1.8 release.

**Comment by mbeckenbach** [comment]
That would be great. Will this also address the "compile files outside virtual project" topic?

**Comment by paulvanbrenk** [comment]
That's the one, you shouldn't need that in the future.

**Comment by mbeckenbach** [comment]
Ah OK. I did not see this as the same thing. Sounds cool. Can't wait for that update. :)

**Comment by sayedihashimi** [comment]
I have moved this to https://github.com/Microsoft/TypeScript/issues/6793 closing this now.
