### ISSUE TITLE
What is the state of supporting import of non-VS solution based on global.json with multiple projects.json?

### ISSUE THREAD

**Issue by peterblazejewicz** [aspnet/Tooling#369]
I'm using Mac, but I've got access to PC/Surface and I'm digging with VS tooling for ASP.NET5 projects.
When someone scaffold solution using VS with projects it results in:

```
├── SolutionRoot/
│   ├── global.json
│   ├── src/
│           ├── EmptyProject/
│                      ├── project.json
│           ├── ConsoleProject/
│                      ├── project.json
```

and so on
**NOTE: I've exluded VS .sln and xproject files from the tree for clear picture**

When I recreate the same structure on machine (x-plat) **without VS** there are obviously no solution or VS project files found in such solution structure.
How am I supposed to open the solution - not particual project in VS? For _Open solution/project_ it offers `project.json` only. Should availability of `global.json` at least provide a hint to VS that in lack of .sln file this could still be valid solution with multiple projects?

Thanks!

**Comment by sayedihashimi** [comment]
@peterblazejewicz thanks for bringing this up. It's an issue that we'll need to address. I don't have anything specific for this now, but I'll add it to the backlog. I'll add details here before we start that. We're busy with dnx->dotnet right now.

**Comment by peterblazejewicz** [comment]
Thanks Sayed! YHIGA

**Comment by sayedihashimi** [comment]
I've discussed with various folks and it looks like the plan is to add support for modifying the .sln file on the command line via a new dotnet command. Here is the issue tracking this work https://github.com/dotnet/cli/issues/4513. For more discussion please use that issue. I'll close this one now.
