### ISSUE TITLE
Brunch UI support on Task Runner

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#37]
I used brunch for a while now with AspNet and I find it very useful and simpler than Grunt and Gulp.

I think it would be great if task runner can detect brunch config file and let run it as with grunt and/or gulp.

There are no task involved so the only thing needed is to have a build with/without optimization, and watch with/without optimization (build / build --production and watch / watch --production)

Also is a good way to introduce developers to brunch which is way easier and more likely similar to the bundling we had in mvc5.

note: there is nothing preventing us using brunch already, and the workflow is awesome already.

**Comment by sayedihashimi** [comment]
Assigning to @madskristensen

**Comment by madskristensen** [comment]
Sounds like a perfect candidate for a VS extension

**Comment by madskristensen** [comment]
@Bartmax A Brunch Task Runner extension is now available in the VS Gallery. Try it out here https://visualstudiogallery.msdn.microsoft.com/de706ad0-8a73-4df3-bef5-867bb9a70d51

**Comment by Bartmax** [comment]
Really this was THAT fast!?!?!? wow. I'll give it a try and let you know! great job!

**Comment by madskristensen** [comment]
Yep, took me 1 hour to get it working and 2 hours to make it pretty :)
I've never worked with Brunch before and so I was only looking at the documentation. I hope the extension covers it all, but I'm not sure so please let me know what you think

**Comment by Bartmax** [comment]
Impressive, I will let you know for sure.

**Comment by sayedihashimi** [comment]
Now that is customer service! Thanks @madskristensen

**Comment by madskristensen** [comment]
@Bartmax I made a few updates to the extension and expanded the documentation as well. If you get a chance, I'd love to hear if it works or modifications are needed

**Comment by Bartmax** [comment]
@madskristensen sorry for the delay, I was fighting with NPM upgrade :)

I tried the extension and it does indeed work very well and it's :zap:blazing fast.

The only thing I miss from my normal development experience is the --debug switch, which is useful for debugging brunch/config issues.
While I don't find it necessary, wanted to mention because that was the only thing I found I had to go to the command line (not a bad thing).


very well done. No modifications needed! :+1: Thanks!

**Comment by madskristensen** [comment]
The latest version (1.0.8) now as a _Debug_ toggle button on the left toolbar as shown here:
 
![Debug](https://raw.githubusercontent.com/madskristensen/BrunchTaskRunner/master/art/debug.png)

**Comment by Bartmax** [comment]
oh man! you rocks! i confirm it works flawlessly. good job!

**Comment by Bartmax** [comment]
@madskristensen does it make sense that the extension adds a new item to the Add new item (client side) dialog with a brunch-config.coffee item ?

**Comment by madskristensen** [comment]
It totally does make sense. Question is if I can add a template to a tooling VSIX without the VS Gallery rejects it. It's worth a shot. Wanna open a bug on the Brunch Task Runner extension repo?

**Comment by Bartmax** [comment]
sure!
