### ISSUE TITLE
NU1007 Dependency specified was log4net >= 2.03 but ended up with log4net 1.0.0

### ISSUE THREAD

**Issue by steve-warwick** [aspnet/Tooling#374]
I have an existing ASP.NET 5 project that is attempting to use some existing class libraries using .csproj files. When I attempt to add this existing project file I get the NU1007 specified in the subject of this issue in the references tree. 

The wrap project.json file for the existing project looks like this:

```JSON
{
  "version": "1.0.0-*",
  "frameworks": {
    "net451": {
      "wrappedProject": "../../Common/Logging/Common.Logging.csproj",
      "bin": {
        "assembly": "../../Common/Logging/obj/{configuration}/Cloud.Common.Logging.dll",
        "pdb": "../../Common/Logging/obj/{configuration}/Cloud.Common.Logging.pdb"
      },
      "dependencies": {
        "log4net": "2.0.3",
        "System.Management.Automation": "1.0.0-*"
      }
    }
  }
```

It looks like it also created a wrap file for log4net that looks like this:

```JSON
{
  "version": "1.0.0-*",
  "frameworks": {
    "net451": {
      "bin": {
        "assembly": "../../../packages/log4net.2.0.3/lib/net40-full/log4net.dll"
      }
    }
  }
```

The ASP.NET 5 WebApi that references this existing project's project.json file looks like this:

```JSON
{
  "version": "1.0.0-*",
  "compilationOptions": {
    "emitEntryPoint": true
  },
  "projects": [ ],

  "dependencies": {
    "Microsoft.AspNet.IISPlatformHandler": "1.0.0-rc1-final",
    "Microsoft.AspNet.Mvc": "6.0.0-rc1-final",
    "Microsoft.AspNet.Server.Kestrel": "1.0.0-rc1-final",
    "Microsoft.AspNet.StaticFiles": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.FileProviderExtensions": "1.0.0-rc1-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc1-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc1-final",
    "Microsoft.ServiceFabric.Actors": "1.4.87-preview",
    "Microsoft.ServiceFabric.AspNet.Hosting": "1.0.0-rc1",
    "RestSharp": "105.2.3",
    "Swashbuckle.SwaggerGen": "6.0.0-rc1-final",
    "Swashbuckle.SwaggerUi": "6.0.0-rc1-final"
  },

  "commands": {
    "web": "Microsoft.AspNet.Server.Kestrel"
  },

  "frameworks": {
    "dnx451": {
      "dependencies": {
        "Cloud.Common.Logging": "1.0.0-*"
      }
    }
  },
  "exclude": [
    "wwwroot",
    "node_modules",
    "PackageRoot"
  ],
  "publishExclude": [
    "**.user",
    "**.vspscc",
    "PackageRoot"
  ]
}
```

Any suggestions on what I'm missing here?

I have spent hours trying to figure out what kind of black magic is happening behind the scenes that could possible be causing this problem. This may not be a bug, but at the very least it should indicate how unbelievable frustrating this new project system is for someone who wasn't involved in its design or implementation. Seriously, either the tooling needs to be improved to more clearly indicate how to go about resolving this issue or there is significant bug here.

**Comment by davidfowl** [comment]
That's a pretty odd error, usually it happens when you get a higher version than specified, not lower. My only guess is that you need to force a restore on the project referencing log4net to get the right version.

**Comment by steve-warwick** [comment]
I tried the following, but why would it give this error?

C:\ENowCloud\MicroServices>dnu restore --no-cache
Microsoft .NET Development Utility Clr-x64-1.0.0-rc1-16231

  GET https://www.nuget.org/api/v2/
  OK https://www.nuget.org/api/v2/ 583ms
Restoring packages for C:\ENowCloud\MicroServices\Common\Logging\project.json
----------
System.InvalidOperationException: The project name 'Logging' is ambiguous between the following projects:
C:\ENowCloud\MicroServices\common\Logging
C:\ENowCloud\MicroServices\Common\Logging
   at Microsoft.Dnx.Tooling.ProjectResolver.TryResolveProject(String name, Project& project)
   at Microsoft.Dnx.Tooling.ProjectReferenceDependencyProvider.GetDescription(LibraryRange libraryRange, FrameworkName ta
work)
   at Microsoft.Dnx.Tooling.LocalWalkProvider.FindLibrary(LibraryRange libraryRange, FrameworkName targetFramework, Boole
eUnlisted)
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindProjectMatch>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryMatch>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<FindLibraryEntry>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreOperations.<CreateGraphNode>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<CreateGraphNode>d__71.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<RestoreForProject>d__69.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<>c__DisplayClass68_0.<<Execute>b__2>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dnx.Tooling.RestoreCommand.<Execute>d__68.MoveNext()
----------
Restore failed
The project name 'Logging' is ambiguous between the following projects:
C:\ENowCloud\MicroServices\common\Logging
C:\ENowCloud\MicroServices\Common\Logging

NuGet Config files used:
    C:\Users\Steve\AppData\Roaming\NuGet\nuget.config
    C:\ENowCloud\nuget.config

Feeds used:
    C:\Users\Steve\.nuget
    https://www.nuget.org/api/v2/

**Comment by kakins** [comment]
I'm not sure if this is the place to add my comment, or if I should post a new issue, but I have the same exact error showing when referencing a .csproj Class Library that references the latest Newtonsoft.Json.


From the Error List output:

**Error	NU1002	The dependency Newtonsoft.Json 1.0.0 in project Purity.Web.Api does not support framework DNXCore,Version=v5.0.**


From the References --> DNX 4.5.1 --> MyClassLibrary Node:

**NU1007 Dependency specified was Newtonsoft.Json >= 8.0.2 but ended up with Newtonsoft.Json 1.0.0.**

I know I have Newtonsoft.Json 8.0.2 referenced in my class library.

**Comment by sayedihashimi** [comment]
If you restore/build from the command line are you getting the same results as Visual Studio? If you're getting different results from the command line and Visual Studio can you include the following info.

 - Contents of `global.json` if one exists in your solution
 - Results of `dnvm list` from the command line
 - Summary of the difference between command line and VS

**Comment by crbranch** [comment]
+1 same issue as the original poster

I have class library in its own project built targeting .NET framework 4.6, and my class library includes a reference to Entity Framework 6.1.3.  I have a second project that targets ASP.NET 5 MVC 6.  The frameworks portion of project.json in the ASP.NET project looks like this:

    "frameworks": {
        "dnx46"
    }

When I attempt to Add Reference and reference my class library project (.csproj), it pulls in my class library and also the Entity Framework dependency, but shows the Entity Framework library as version 1.0.0 and generates the NU1007 mentioned by the OP:

![nu1007](https://cloud.githubusercontent.com/assets/17033045/13768276/842cef84-ea4a-11e5-9d2c-91528ec50367.png)

I noticed when poking around in the "wrap" folder at the solution level that there are several `package.json` files that were auto-generated for my class library as well as the Entity Framework dependency.  The auto-generated `package.json` file for Entity Framework looks like this:

    {
      "version": "1.0.0-*",
      "frameworks": {
        "net46": {
          "bin": {
            "assembly": "../../Data/packages/EntityFramework.6.1.3/lib/net45/EntityFramework.dll"
          }
        }
      }
    }

If I hand-edit this file and change the `version` to "6.1.3-*" then reload my ASP.NET project, the NU1007 error message disappears and everything seems to work.

**Comment by sayedihashimi** [comment]
This issue is pretty old. We recently released RC2 https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/. I'm hoping that this is no longer an issue so I'm closing this. If this is still an issue with RC2 please reopen this.
