### ISSUE TITLE
"Produce outputs on build" setting does not apply configuration appropriately

### ISSUE THREAD

**Issue by hamtamtots** [aspnet/Tooling#377]
Hello, this has already been brought up before, but closed due to there being a workaround of editing the xproj xml manually. The workaround works granted but doesn't fix the broken functionality of the checkbox in build properties.

The previous issue mentioned is here: https://github.com/aspnet/Tooling/issues/313

A few minutes of playing should demonstrate the strange behavior, notably the setting applies to the current active configuration, but the checkbox appears checked for all other configurations, and will never add appropriate xml to the proj file to actually set the property. So in my example, I set it when on Debug configuration, I can then no longer add it to release because it shows as checked. I have to manually edit the xproj.

**Comment by LeeCheneler** [comment]
Can confirm this is stil occurring on my machine too. I have Visual Studio 2015 (fully updated).

**Comment by sayedihashimi** [comment]
Thanks for the feedback. Once we switch from dnx to dotnet that option will go away all together. dotnet will always build assemblies on disk.

Since this option will not be available going forward I'm going to go ahead and close this.

**Comment by taori** [comment]
If this option is gone (which yes, it is - that's why i'm here): 

What is the nuget command to push it then? Maybe i'm doing something wrong, but i didn't see a nupkg file which i could upload.
