### ISSUE TITLE
Context Menu performance on wwwroot folder

### ISSUE THREAD

**Issue by fargs** [aspnet/Tooling#378]
Does anyone else notice a delay when opening the wwwroot folder context menu? I don't notice it on regular folders, just the wwwroot.

**Comment by fargs** [comment]
Some more info.
With an empty Asp.Net 5 project, there are no issues. 
After I added a loaded bootstrap using jspm with wwwroot as the BaseURL, the responsiveness of the wwwroot is effected. 
Tried hiding the folder from solution explorer, still poor responsiveness. 
Deleted the jspm_packages folder from wwwroot, the performance went back to normal.

**Comment by sayedihashimi** [comment]
@fargs could you share a project that is showing delays? I'm not seeing any delay.

**Comment by damienbod** [comment]
I have a similar problem. If I run a jspm install {package} from the command-line, VS hangs and I have to kill it. 

At present it is not possible to use JSPM with Visual Studio. 

Greetings Damien

**Comment by sayedihashimi** [comment]
This issue is pretty old. We recently released RC2 https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/. I'm hoping that this is no longer an issue so I'm closing this. If this is still an issue with RC2 please reopen this.
