### ISSUE TITLE
Publish doesn't build Nuget package

### ISSUE THREAD

**Issue by brgrz** [aspnet/Tooling#379]
Even with the "Compile source files into Nuget packages" checked under Settings in the Publish dialog (VS 2015) no packaging is created anywhere. The publish is made to the "artifacts" dir but no .nupkgs exist there after publish.

Neither are packages created under the bin folder.

The only way with RC1 Update 1 to generate a package for project.json projects is by using "dnu pack".

**Comment by davidfowl** [comment]
Publish never builds a nuget packages. We don't support nuget packages for applications (in fact nobody does but octopus deploy and they aren't regular nuget packages).

**Comment by brgrz** [comment]
Hmm?

What's that setting there for then? As far as NuGet and nuspec go (and if I am correct it is the same with project.json) we can actually package anything - and it works

**Comment by davidfowl** [comment]
What setting? Yes, you can pack anything.

**Comment by brgrz** [comment]
The "Compile source files into Nuget packages" setting

![publish-nuget](https://cloud.githubusercontent.com/assets/193816/12515367/5811c302-c128-11e5-8938-e2f0bcfd91ef.png)

**Comment by brgrz** [comment]
On the other hand checking the "Produce outputs on build" in project Properties - Build dialog does produce NuGet packages.

Related issues 

https://github.com/aspnet/Tooling/issues/313
https://github.com/aspnet/Tooling/issues/377

So those are two checkboxes which are vague or hard to understand and they're also buggy to further confuse things

**Comment by davidfowl** [comment]
That dialog needs to be changed. It should just say compile sources.

/cc @sayedihashimi

**Comment by brgrz** [comment]
IMHO there's just too much going on about building/compiling/packaging in too many places, this should be simplified. In VS 2013 we knew exactly where everything was and what it did

**Comment by davidfowl** [comment]
The dotnet CLI does make a bunch of this better as settings like produce outputs on build won't need to exist anymore. Also nuget packages are only every produced when you pack (`dotnet pack`). Publish always is a flat directory structure going forward so that'll also be more similar to how things used to work.

**Comment by brgrz** [comment]
For instance, both `Produce outputs on build` and the `Publish` dialog store to `../../artifacts` by default, but one would expect that `Produce outputs on build` only deals with builds and affects what gets built in `bin`

**Comment by brgrz** [comment]
that's nice to hear;)

**Comment by sayedihashimi** [comment]
The option is going away when we move to dotnet from dnx. dotnet doesn't support running from source so we will always build the package. Based on that I'll close this. If I've misunderstood please let me know.

**Comment by brgrz** [comment]
What you said makes me wonder:

"dotnet doesn't support running from source so we will always build the package."

What exactly do you mean by "doesn't support running from source"?

**Comment by sayedihashimi** [comment]
With dnx you can run your application from source files alone because the app would be compiled in memory. With dotnet you have to build the app, which produces the binaries on disk and then run from those. Running directly from source files won't be supported (May change later but for now that's what I've heard).

**Comment by brgrz** [comment]
Thought so. That's actually a step back, running from source can be quite handy.

**Comment by sayedihashimi** [comment]
@brgrz you can ask at https://github.com/dotnet/corefx

**Comment by davidfowl** [comment]
@brgrz You'll be able to do `dotnet run` and effectively run from source, but binaries are on disk either way.
