### ISSUE TITLE
What is the Typescript story with ASP.NET 5

### ISSUE THREAD

**Issue by toresenneseth** [aspnet/Tooling#38]
Hi,
What is the Typescript story with ASP.NET 5? At the moment (VS 2015 CTP6) it doesn't seem to work very well at all. Since it's still pre-release software I don't expect everything to work smoothly, but I need to know if you're planning on making them work well together for the final release or not.

My main concers are pretty much the same as the questions asked in this forum post (which no one has answered, although they are very specific and clear questions!)
http://forums.asp.net/t/2041054.aspx?Few+questions+about+aspnet+5+and+vs+2015+CTP

1) Will it be possible to prevent VS from generating .js-files? I will never edit the .js-files, and they just create a lot of noise in the solution Explorer. Also, they should never be checked into a Source Control system, and I'm planning on using gulp to generate the .js-files and copying / concat'ing them to the wwwroot-folder.
2) Intellisense does not work / typescript type checking fails when you've added a new .ts-file to the solution. To make it work, I need to drag it into a different folder in the solution, then drag it back to where it should be. Is this related to the fact that there is no template for adding a typescript file to the solution?

At the moment, Typescript does not seem like a first class citizen of an ASP.NET 5 Project, I just need to know if you are planning on making it one, or should we go for ASP.NET 4.6 if we want to use Typescript?

Thanks!

**Comment by sayedihashimi** [comment]
Adding @jonathandturner to comment back

**Comment by sayedihashimi** [comment]
@toresenneseth thanks for posting this issue.

I just asked about this on the typescript repository at https://github.com/Microsoft/TypeScript/issues/7321 let's discuss there. I'll close this.
