### ISSUE TITLE
NuGet Caching Issue

### ISSUE THREAD

**Issue by Fosol** [aspnet/Tooling#380]
We're having serious issues with NuGet Caching within Visual Studio.  The primary problem is that Visual Studio can't handle code changes to the same version of a NuGet package.  Which may seem like a stupid thing to do anyway, but I haven't figured out how to get around it.

1) Team of developers working on and changing common shared libraries on a hourly basis.  We can't stop this regrettably until the core shared libraries are done.  This is a project management issue too, but it's made far worse due to NuGet caching.
2) Visual Studio not understanding that a referenced shared project should be used instead of the cached version of the NuGet package.
3) No way to stop Visual Studio from caching in MEMORY the NuGet Package.

Example
1) Create 4 projects; 2 shared libraries, 2 other projects (MVC in our case)
2) 1 shared library references the 2nd shared library
3) Each project should reference the primary shared library
4) edit the code in the 2nd shared library and see how it works for you...  Visual Studio can't handle this.  You have to do the following
- Stop any running projects
- Close any solutions open
- Delete the NuGet packages from the .packages folder
- Run the following; dnu clear-http-cache, dnu restore --no-cache

Related to the above problem is that Visual Studio constantly shows the red error line under everything due to the above mentioned NuGet caching issues.  Even after through the command line confirming everything builds.  Visual Studio will then build but will remain displaying the errors until you close and open the solution again.

This is all causing countless hours of headaches where developers are coming back and saying I updated the code - look see - but it doesn't work.  It's exhausting.

Is there a way to tell Visual Studio to not use in memory cache when doing certain parts of the projects?  I don't care how slow it is to build.  The current situation isn't working for us.

**Comment by sayedihashimi** [comment]
I think this is related to nuget and the dnx runtime and not something that's specific to the VS tooling for ASP.NET 5.

@yishaigalatzer @davidfowl @BillHiebert @barrytang where is the best place to log this feedback? I don't think this is the correct repo for this feedback.

**Comment by Fosol** [comment]
You're probably correct, however I've never had these issues outside of ASP.NET 5.  That being said I've only developed ASP.NET 5 applications within Visual Studio 2015.

**Comment by sayedihashimi** [comment]
@Fosol I agree that this is likely specific to ASP.NET 5. I was trying to see if this was limited to Visual Studio or not. Can you reproduce the issue without using Visual Studio? If so then a fix is needed in either NuGet or dnx. If it's limited to Visual Studio then it would require some further investigation to figure out where the issue lies.

**Comment by Fosol** [comment]
We're only seeing it in Visual Studio.

If we only use command line (i.e. dnu restore, dnu build) it seems to work ok.  Generally we always have to test if we can build via command line first to determine if it's really a bug or just Visual Studio.

**Comment by sayedihashimi** [comment]
@Fosol ok thanks for the info. I'm trying to reproduce your issue but having a hard time. Can you help me with the following.

 - Sample solutin
 - Results when you execute `dnvm list`

**Comment by Fosol** [comment]
Sorry for the delay.  Work hours are crazy atm.

I'll try and put together a sample project right away.

**Comment by Fosol** [comment]
I've created two solutions in Visual Studio 2015.  Mostly barebones to mimic the annoying issues.  I probably should separate the two websites into two solutions and open them up in different instances of Visual Studio, but for the most part this gives you a start to see the issue.

Two websites - https://github.com/Fosol/Debug.NuGetCaching
Two libraries - https://github.com/Fosol/Debug.NuGetCaching.Tools

You will need to;
- build the "Tools" and place their NuGet Packages in an appropriate folder.
- update the "NuGet.config" file in the web projects to point to the folder those NuGet Packages are located.

I started with the Person object only having  a Name property.  I built and then referenced the NuGet Packages in the Web projects.  All worked.

I then updated the Person object to have FirstName and LastName properties.  I build and then replace the old NuGet packages.  I then attempted to get the Web projects to even see the change.  I also delete the user profile NuGet Packages.  I also do a "dnu clear-http-cache".  I also do a "dnu restore --no-cache".  You have to do all these steps including closing and opening the solution to get it all to work 100%.

If you separate the "Web" projects into two instances of Visual Studio the problem only get worse.

FYI - I know "versioning" would solve a large part of this.  However due to the nature of the project we have multiple developers working on the same libraries throughout the day.  We are not at a point where our core libraries are even remotely stable.  In the past before Rosyln and NuGet Caching we could just copy the assembly into the project and voila - worked!  I need that.

**Comment by yishaigalatzer** [comment]
You really have two choices:

Add the libraries as a project reference
Rev the pre-release versions on build

You can look at how we do the second option in the nuget project where basically we followed the same pattern: https://github.com/nuget/nuget.client

The equicalent of "libraries" are built in the nuget.core solution and they are consumed in the nuget.client solution (yes it is a bit more involved, but it follows the same pattern).

**Comment by Fosol** [comment]
Any documentation that could speed up my learning process or do I have to figure it out?

**Comment by yishaigalatzer** [comment]
Nothing specific I can think of. In general nuget treats the same id and version as the same and hence will not blow the cache. So you want to rev the version regardless if your build is stable or not. You use the pre-release tag for revving.

**Comment by Fosol** [comment]
Not sure where to begin with the nuget project you linked.

**Comment by sayedihashimi** [comment]
Is there any action needed here from ASP.NET 5 tooling? If not then I think we should close this (perhaps migrate it somewhere else?).

**Comment by Fosol** [comment]
I think if you'd provide a way to turn of caching that would be great.  I suspect that won't happen, so I guess you can close it and I'll just live with the issues until such time they go away.

**Comment by sayedihashimi** [comment]
@yishaigalatzer for having a VS setting to turn off NuGet caching already being tracked? If not should I move this to NuGet repo?

**Comment by yishaigalatzer** [comment]
There is no such settings, and I'm not sure we actually need one, the side effects of this suggestion will be pretty significant and detrimental to common scenarios, also we don't want to add more "knobs" that will lead to mis-use and consfusion. We do have a command to wipe the caches (nuget locals -clear all), and we should have a UI to wipe it as well at some point.

In general our recommendation is to not use the same version and id for different content. And we do track a mechanism to have a cache that is key-d by the source. So if your project will separate the package folders, it will work as expected if you use separate feeds for the same package and id.

**Comment by Fosol** [comment]
Common scenario was presented above where you are making continuous change but don't have the processes in place to change the build information.  All you need is one single developer doing what I showed above and it all comes crashing down.  It only gets worse with multiple developers working on the same project.

In an ideal world we all have build servers and automated deployments (with all the checks and balances).  The rest of the world however isn't always so organized.

I agree with your recommendation, I disagree with not having an option.  Before Roslyn (in memory caching) this wasn't a problem.

**Comment by JimHume** [comment]
As mentioned above (@Fosol / Feb 19) this is a common scenario.

Has this been resolved?

**Comment by sayedihashimi** [comment]
Closing this, if this is still an issue please open in one of the NuGet repos https://github.com/NuGet.
