### ISSUE TITLE
Dependency specified was MyLib.Common >= 1.0.0-beta028 but ended up with MyLib.Common 1.0.0-beta025

### ISSUE THREAD

**Issue by barriestewart** [aspnet/Tooling#384]
We have an asp.net 5 class library which is packaged to a private MyGet feed. This class library can then be used in some of our other projects. In the projects consuming the class library, we reference the exact version in our project.json like this:

`"MyLib.Common": "1.0.0-beta025"`

The consuming solutions have the pre-authenticated v3 URL for our MyGet feed stored as package sources in `NuGet.Config`.

The issue is that in the above example, if I want to change our projects from referencing the `1.0.0-beta025` package to `1.0.0-beta028` the we get the following error in VS2015:

`Dependency specified was MyLib.Common >= 1.0.0-beta028 but ended up with MyLib.Common 1.0.0-beta025`

Right-clicking on a project and selecting "Restore Packages" runs but doesn't fix the issue. Running a `dnu restore` from the root of the solution does fix it. Is this a bug or am I doing something wrong?

**Comment by sayedihashimi** [comment]
This seems like a runtime issue instead of a VS Tooling issue.

@BillHiebert @davidfowl  @balachir thougths?

**Comment by sayedihashimi** [comment]
@barriestewart if you use the command line to restore/build do you get the same the same result? Or is Visual Studio doing something different?

**Comment by barriestewart** [comment]
Sayed - I tried this again in my solution. Of the 5 projects in the solution, 4 of them found the correct package version but one of them didn't and showed an error similar to the one I mentioned earlier (the only difference being the beta version numbers of `MyLib.Common`. The one project that had the error did seem to respond to a "Restore Packages" in visual studio and after that seemed to have found the correct version to use.

When I have been experiencing these problems, my current workaround is to remove all `project.lock.json` files in the solution then run a `dnu restore --no-cache` which always seems to work. I will maybe do some more testing with this tomorrow. BT is currently experiencing some issues with their network in the UK which is making my internet access painfully slow.

**Comment by sayedihashimi** [comment]
OK thanks. I'm not sure what's the best way to handle this since it's not clearly actionable. If you find out more in your investigation let me know.

**Comment by sayedihashimi** [comment]
I'm going to close this since it's not actionable currently. I think the underlying reason is likely related to `dnu` which is getting replaced by `dotnet` so the problem may already be fixed. Let's see what happens after dotnet is released.
