### ISSUE TITLE
How to distinguish which I need: (Windows) Class Library or (Web) Class Library (Package)

### ISSUE THREAD

**Issue by muratg** [aspnet/Tooling#387]
_From @nkhut10 on February 2, 2016 10:58_

Before I moved to Asp.Net 5 I used to create standard (Windows) Class Libraries (dlls) and then used them in my Asp.Net 4 Project as references. Now I am confused, should I do the same as before or start creating Class Library (Package) - s which are in "Web" section when creating a new project. Any ideas appreciated. 

_Copied from original issue: aspnet/dnx#3346_

**Comment by sayedihashimi** [comment]
@muratg this is a developer guidance issue, not specifically a tooling issue so I'm not sure why you moved this here. @danroth27 is there any guidance on when to start with a DNX Class Library versus a standard Class Library?

**Comment by muratg** [comment]
@nkhut10 Do you plan to use the class library for regular .NET apps?   If not, I recommend creating dnx class library for now.  

JFYI, in the next release, we're retiring DNX, DNU and DNVM and we'll be moving to dotnet CLI (https://github.com/dotnet/cli)  VS templates will also change accordingly.

**Comment by nkhut10** [comment]
I plan to use this class library for an ERP Web Application. I couldn't decide which one is better to use. Also, while using standard Class Libraries I cannot target them to EF 4.6.1 because then I am unable to make a reference to these classes. ASP.NET 5 dnx version is 4.5.1 and the second problem is that DNX CORE simply cannot refer to these libraries.

**Comment by sayedihashimi** [comment]
@nkhut10 when using a Class Library (Package) project the minimum version of EF is 7. @muratg can correct me if I'm wrong there.

**Comment by muratg** [comment]
Yup, I don't think EF6 was tested with DNX projects. @divega

**Comment by divega** [comment]
@sayedihashimi I think you must be referring to EF Core :wink: 

@muratg Although we haven't done exhaustive testing of EF6 with DNX it should work to the extent that any other package containing regular libraries can be made to work. The main limitations are:

- It will only work with "full" .NET as opposed to .NET Core
- It will require putting some additional code in a class derived from DbConfiguration to wire up providers. In non-DNX applications the wire up is usually contained in the application's .Config file

The following article goes through some of the required steps, although I am not sure how up to date it is: http://bleedingnedge.com/2015/11/01/entity-framework-6-with-asp-net-5/

**Comment by nkhut10** [comment]
@muratg @divega Actually I'm not gonna use EF. I work with MongoDB, therefore I use MongoDB C# driver.

**Comment by divega** [comment]
> I cannot target them to EF 4.6.1 because...

@nkhut10 Ah, I guess you actually meant to type .NET there, which makes more sense with that version number anyway :smile:

**Comment by sayedihashimi** [comment]
I'm going to close this but I've forwarded this item to members that own this experience.
