### ISSUE TITLE
Visual Studio crashes when opening files that were excluded from the project

### ISSUE THREAD

**Issue by brgrz** [aspnet/Tooling#389]
VS 2015 Update 1 with ASP.NET 5 RC 1 crashes when trying to open files that are excluded from the .csproj project.

Clean install with ASP.NET 5 RC 1 web tools applied, no extra extensions (besides the default ones) installed.

Prior to installing the ASP.NET 5 RC 1 tools those files did open fine.

Here is the Connect bug I reported:
https://connect.microsoft.com/VisualStudio/feedback/details/2318215/vs-crashes-when-opening-html-cshtml-file-that-is-not-part-of-a-project-excluded

**Comment by sayedihashimi** [comment]
Thanks for the report. Can you provide some steps to reproduce? Here is what i just tried.

 - Create a new ASP.NET 5 project
 - Add `index.cshtml`
 - Exclude `index.cshtml` in solution explorer
 - File -> Open File -> index.cshtml

The file opened fine for me.

**Comment by brgrz** [comment]
Create a new ASP.NET 4.5.2 project (MVC, for instance), then just exclude _ViewStart.cshtml for example and try to open it. It should crash the VS.

**Comment by sayedihashimi** [comment]
OK I have reproed it. Here are the steps.

 - Create a new MVC 5 project
 - Exclude _ViewStart.cshtml
 - Show all files in Solution Explorer
 - Open _ViewStart.chsml (try first in preview tab, then double click)

At that time I'm seeing a hang. I'll file it in TFS so that we can get someone to look at it.

Thanks for your help.

**Comment by sayedihashimi** [comment]
TFSID: 187431

**Comment by brgrz** [comment]
great, thanks

**Comment by haldiggs** [comment]
seems to happen with almost any file that is under the file structure but has not yet been actually included in the project, .html, .hbs you name it.

Although I did not coincide this with the ASP.NET 5 tools I can confirm that I also have those installed.

**Comment by mlorbetske** [comment]
Could you try the workaround [here](https://blogs.msdn.microsoft.com/webdev/2016/01/12/visual-studio-keeps-showing-suggested-extensions/)?

**Comment by haldiggs** [comment]
good job, that setting looks to have fixed it. only tested it on one set of files (.hbs) that were not part of the solution but they worked.

**Comment by sayedihashimi** [comment]
@mlorbetske if it's been fixed then can we close this?

**Comment by mlorbetske** [comment]
@sayedihashimi Yep, the fix has been made

**Comment by brgrz** [comment]
I guess it can be closed if it will really be fixed becuase this above on the link is only a workaround.

**Comment by dean-yang** [comment]
Fix the crash problem (when trying to open excluded files) indeed.

**Comment by sayedihashimi** [comment]
Yes a fix has been checked in and it will be in the next release. Thanks!

**Comment by brgrz** [comment]
This bug has been reintroduced with Update 2..such incompetence from VS team.

**Comment by mlorbetske** [comment]
@brgrz sorry that we weren't specific about what we meant by "next release". Update 2 did not contain an updated version of what we call Web Tools Extensions (which contains the fix), it goes out next in ASP.NET Core 1 RC2.

**Comment by brgrz** [comment]
This is not how I write software, bug fixes such as this one go out as soon as possible, but ok, you should know better than me.

**Comment by sayedihashimi** [comment]
@brgz we are working hard to get the release out. I understand its frustrating waiting for a fix. Over the past few years we've improved our ability to ship updates, but we are not at the point to be able to deliver individual bug fixes. We're still working to improve this, but it will take us sometime to get there. I'm sorry about the long wait for RC2, we are doing our best to release it as soon as possible.
