### ISSUE TITLE
Visual Studio 2015 CTP 6 : An error occurred trying to load the project properties window

### ISSUE THREAD

**Issue by jaliyaudagedara** [aspnet/Tooling#39]
When opening project properties of any project (MVC, Web API, Class Library, Console Application etc.) created targeting ASP.NET 5, I am getting this error.

"An error occurred trying to load the project properties window.  Close the window and try again. COM object that has been separated from its underlying RCW cannot be used."

![2015-04-23_20-01-13](https://cloud.githubusercontent.com/assets/5653381/7299455/8eff61a6-e9f3-11e4-8eb2-b60c4ac1a39d.png)

Any ideas?

**Comment by BillHiebert** [comment]
Can you use a newer build than CTP6?

**Comment by jaliyaudagedara** [comment]
Issue was present in Visual Studio 2015 RC as well. Contacted Microsoft and the issue was with the GhostDoc VS Extension. Unloaded GhostDoc VS Extension from Visual Studio 2015 RC, and the problem got resolved.

Thank you Microsoft!

**Comment by RehanSaeed** [comment]
Thanks @jaliyaudagedara. I can confirm GhostDoc was the problem. I have emailed them a link to this thread.

**Comment by sergebee** [comment]
Rehan,

Thank you for bringing the thread to our attention!

Yes, we were aware of this and already resolved it. We have a private build of GhostDoc that includes the fix.

Thanks!

**Comment by Daniel15** [comment]
@sergebee - Any updates on this? I recently encountered the same thing (https://github.com/aspnet/Tooling/issues/138), also caused by GhostDoc.

**Comment by SergeBaranovsky** [comment]
@Daniel15 - drop us a note at support at submain dot com and tell which edition you need - we will provide you with download link.

Thanks!

**Comment by Daniel15** [comment]
Thanks @SergeBaranovsky, I sent an email

**Comment by BillKrat** [comment]
Issue also breaking Visual Studio publish; I click on the publish button and nothing happens - I thought it had to do with beta8 but once I uninstalled GhostDoc to eliminate the error addressed here my publish feature started working.

**Comment by RehanSaeed** [comment]
Is this still broken in the latest version. I quite liked GhostDoc.

**Comment by BillKrat** [comment]
It is with Visual Studio 2015 beta 8.  I sent them an email and have a support ticket.  I could have lived with the com error (I like GhostDoc that much) but can't live with the publish issue...

**Comment by BillHiebert** [comment]
This is a known issue in GhostDoc. They released an update available here: http://submain.com/Download/NightlyBuild/gd_4.9.15168.zip

**Comment by SergeBaranovsky** [comment]
Bill, thank you for posting the link. Yes, that build addresses the issue although now is pretty early build and we are about the release v5 that addresses this issue as well. If you want a pre-release build, drop us a note at support at submain dot com. Thanks for your patience!

**Comment by lismore** [comment]
Hi guys,

I find this same issue in the latest version of VS 2015 (Pro)
![image](https://cloud.githubusercontent.com/assets/1145888/10907576/3576de84-8223-11e5-992b-565eb696ffc3.png)

**Comment by zemien** [comment]
@lismore I had to restart Visual Studio after unloading GhostDoc. I can now open Project Properties. 

I have VS Enterprise 2015 Update 1 RC, and ASP.Net 5 RC1.

**Comment by SergeBaranovsky** [comment]
@All,

We have made a new GhostDoc update available yesterday and it includes the fix. Please download the new bits from http://submain.com/ghostdoc - thank you for the patience!

**Comment by rlvandaveer** [comment]
@SergeBaranovsky While that's great that you've fixed it in v5, the latest version of v4 has this issue.

**Comment by SergeBaranovsky** [comment]
@rlvandaveer I'm not sure what the problem is... Upgrade to the v5?

**Comment by rlvandaveer** [comment]
This is probably not the right forum for this (sorry aspnet/tooling folks) but I thought that SubMain's v4 clients that find this thread (and possibly SubMain) might want to know that barring paying for the next version, there is no fix.

**Comment by SergeBaranovsky** [comment]
You are correct, this is not the right forum for that. (sorry aspnet/tooling folks) Users of the free GhostDoc still get their v5 upgrade free, the commercial license users who chose to be getting updates via the software assurance subscription, also get the v5 version free. 

If you want to continue the discussion, please take it to SubMain forums or offline via email. Thanks!

**Comment by BNarayanSharma** [comment]
I was also facing the same issue in Visual Studio 2015. I was using GhostDoc Community 4.9.x and I upgraded it to 5.1.x and issue get resolved.
