### ISSUE TITLE
None parameters shown in DEBUG monitor window when View includes Kendo.UI wrappers

### ISSUE THREAD

**Issue by naskog** [aspnet/Tooling#396]
Parameters in DEBUG monitor window cannot be seen by setting breakpoint in Controller/Action.
This happens when view includes any Kendo.UI wrappers.
The issue is only reproducible on Chinese OS (i.e. Windows 7 / Chinese Simplified)

![02f84af9-5007-4930-9647-4b6b65059f75_debug-issue-none-parameters-in-monitor-when-using-kendo-ui](https://cloud.githubusercontent.com/assets/961037/12889562/2cebe0fa-ce88-11e5-9a78-88e7b3fe482d.png)

![ccf4c9a2-6ba5-4199-9f5f-aee9b71a9762_debug-issue-parameters-in-monitor-when-no-using-kendo-ui](https://cloud.githubusercontent.com/assets/961037/12889563/2ceeed04-ce88-11e5-8328-b515a80b6c4f.png)

**Comment by naskog** [comment]
Sample view source:

@model RegisterViewModel
@{
    ViewData["Title"] = "Register";
}

<h2>@ViewData["Title"].</h2>

<form asp-controller="Account" asp-action="Register" method="post" class="form-horizontal" role="form">
    <h4>Create a new account.</h4>
    <hr />
    <div asp-validation-summary="ValidationSummary.All" class="text-danger"></div>
    <div class="form-group">
        <label asp-for="Email" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Email" class="form-control" />
            <span asp-validation-for="Email" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="Password" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="Password" class="form-control" />
            <span asp-validation-for="Password" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <label asp-for="ConfirmPassword" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            <input asp-for="ConfirmPassword" class="form-control" />
            <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
        </div>
    </div>

    <div class="form-group">
        <label asp-for="OrderTime" class="col-md-2 control-label"></label>
        <div class="col-md-10">
            @(Html.Kendo().DatePickerFor(m => m.OrderTime).Format("yyyy-M-dd").Value(DateTime.Today))
            <span asp-validation-for="OrderTime" class="text-danger"></span>
        </div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <button type="submit" class="btn btn-default">Register</button>
        </div>
    </div>
</form>

@section Scripts {
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial"); }
}

**Comment by sayedihashimi** [comment]
TFS: 192625
I've added this to our internal TFS, we will reply back here soon.

@naskog could you provide a sample that we can use to repro this?

**Comment by sayedihashimi** [comment]
This issue is pretty old. We recently released RC2 https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/. I'm hoping that this is no longer an issue so I'm closing this. If this is still an issue with RC2 please reopen this.
