### ISSUE TITLE
Multiple Startup Websites Fail Using IIS Express The First Time

### ISSUE THREAD

**Issue by MattEdwardsWaggleBee** [aspnet/Tooling#4]
If I have a solution with several Asp Websites, and I select two or more from the "Multiple Startup Projects" list under the Solutions Property pages.  I get the following message box **for each project** I've selected.

![image](https://cloud.githubusercontent.com/assets/6653160/6505406/e90d80d4-c30f-11e4-8853-71498f7cc8f8.png)

If I the go to each project that I wanted to run and set it as the start up project, start debugging, stop debugging.  I can then run time together without that error.  If I restart VS I have to run through each project again.   In my case I have more than 15+ mirco services, that connect to one SPA, so debugging several services together is relatively common.

**Comment by BillHiebert** [comment]
Hi Matt. Were these Asp.Net 5.0 projects

**Comment by MattEdwardsWaggleBee** [comment]
Yes.  Using CTP 6 and Beta3.

**Comment by tommck** [comment]
I have that same problem too.  the problem we had is that the "run multiple" doesn't give you the option of choosing which "command" to run in each project.  It seems to take the last selected command. We were using "k web" to run our projects so we had to individually select and run each project first, then we could use multiple startup projects

**Comment by BillHiebert** [comment]
We'll need to investigate. typically, that dropdown is assicocated withe h startup project. It sounds multiple startup projects needs some inverstiagion. I've opened a tooling bug to look into this.

**Comment by BillHiebert** [comment]
Note that this issue has been fixed in the next release. Thanks again for the feedback.
