### ISSUE TITLE
dnvm upgrade install beta4 version  instead of beta5 after install VS2015RC

### ISSUE THREAD

**Issue by cuiliang** [aspnet/Tooling#40]
There seems VS2015RC installed another dnx in different location.
where dnvm
C:\Program Files\Microsoft DNX\Dnvm\dnvm.cmd
C:\Users\Leal\.dnx\bin\dnvm.cmd

when run dnvm upgrade, the command will set beta4 version of clr to default.
C:\Users\Leal
λ dnvm upgrade
Determining latest version
'dnx-clr-win-x86.1.0.0-beta4-11566' is already installed.
Updating alias 'default' to 'dnx-clr-win-x86.1.0.0-beta4-11566'

**Comment by mgravell** [comment]
I had this same conversation with David on jabbr last night! I am not qualified to say it is safe, but deleting the Program Files version worked for me, allowing the Users version to take over.

There is a second problem here: the installer does not overwrite, so if you have had a previous version on your machine, the command [from here](https://github.com/aspnet/home) *will not overwrite*; you currently need to delete the files from `%USERPROFILE%\.dnx\bin`.

Suggestions for the installer:

- it should overwrite the two files into `%USERPROFILE%\.dnx\bin`
- if correct and possible (admin etc), it should delete the Program Files version completely

**Comment by sayedihashimi** [comment]
@Eilon what is the correct repo for this issue? Since the dnvm installer that goes with VS2015RC is a part of the runtime I think the correct repo is https://github.com/aspnet/dnvm, but not sure. I'll assign to you for now, but let me know.

**Comment by Eilon** [comment]
Yeah dnvm repo sounds right.

**Comment by sayedihashimi** [comment]
Thanks moved to https://github.com/aspnet/dnvm/issues/259 closing this
