### ISSUE TITLE
When you add using with Ctrl + . sometimes the using directive is not in correct order

### ISSUE THREAD

**Issue by ivaylokenov** [aspnet/Tooling#400]
If you have documentation summary on the class, and add new using with Ctrl + . operation, sometimes you may receive the following result:

```c#
    using Builders.Routes;
    using Internal.Application;    /// <summary>
                                   /// Starting point of the ASP.NET MVC testing framework, which provides a way to specify the test case.
                                   /// </summary>
    public static class MyMvc
    {
```

Documentation is not on a new line and the usings may not be sorted. Sometimes it is working, sometimes it does not and I am not quite sure on which conditions it fails.

**Comment by sayedihashimi** [comment]
TFS: 192619
I've added this to our internal TFS, we will reply back here soon.

**Comment by yishaigalatzer** [comment]
@sayedihashimi should we start looping the folks from managed languages on these?

**Comment by sayedihashimi** [comment]
@yishaigalatzer I'm sure that we will once we triage it.

**Comment by sayedihashimi** [comment]
I've ported this to https://github.com/aspnet/Tooling/issues/400 closing this.

**Comment by sayedihashimi** [comment]
Edited above comment to insert the correct link
