### ISSUE TITLE
.html templates caching bug

### ISSUE THREAD

**Issue by newsash** [aspnet/Tooling#402]
I had two files: topBarLogin.directive.js and topBarLogin.html. After I renamed the js file to topBarLogin.js, it became nested to the html file (it's ok), and since then the html file has stopped updating in IIS Express.

**Comment by sayedihashimi** [comment]
@newsash this sounds like it may be a browser caching issue so you may need to clear browser cache and then make the request again. Did you get it working?

**Comment by newsash** [comment]
@sayedihashimi thank you. Indeed, it was the browser caching issue. Clearing the cache helped.
