### ISSUE TITLE
vs hangs adding project reference to project.json

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#405]
After the installation of the updates to asp.net 5 rc 1 and web tools and framework a few days ago, if I open project.json to add a new dependency, as I start to type the name of the dependency Vs hangs and I have to kill the process.

**Comment by sayedihashimi** [comment]
Assigned to @madskristensen since you're seeing this while you edit `project.json`

**Comment by sayedihashimi** [comment]
I believe this is fixed so I'll close this. If not please reopen.
