### ISSUE TITLE
External Web Tools paths not respected in prepublish

### ISSUE THREAD

**Issue by danwad** [aspnet/Tooling#406]
Some of my gulp tasks require a later version of node than the included v0.10.31 in VS 2015 Update 1.

As mentioned in #101 we can configure the priority of paths VS will search when looking for node in Tools->Options->Projects and Solutions->External Web Tools.

However, when publishing, `C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\extensions\microsoft\web tools\external` is prepended to the PATH and the prepublish script fails due to node v0.10.31.

A workaround is to put everything in a script and modify PATH.

project.json :

    ...
      "scripts": {
        "prepublish": ["prepublish"]
      }
    ...

prepublish.cmd :

    set PATH=C:\Program Files\nodejs;.\node_modules\.bin;%PATH%
    
    call npm install || goto :error
    call bower install || goto :error
    call gulp clean || goto :error
    call gulp min || goto :error
    goto :EOF
    
    :error
    echo Failed with error #%errorlevel%.
    exit /b %errorlevel%

Is there a real workaround or setting to change the PATH which is used when executing prepublish scripts?

**Comment by sayedihashimi** [comment]
TFS: 192610
I've added this to our internal TFS, we will reply back here soon.

@madskristensen @mlorbetske when you configure the NPM paths in the VS UI how can we get that added to the path during build?

**Comment by sayedihashimi** [comment]
Should be fixed in the next release, closing now
