### ISSUE TITLE
Large font issues

### ISSUE THREAD

**Issue by xperiandri** [aspnet/Tooling#407]
There are issues with project creation dialog when large font is used.
Buttons are constrained in size so their text is cut at the bottom.

<img width="1080" alt="large font layout bug" src="https://cloud.githubusercontent.com/assets/2365592/13092407/6e18f6b8-d508-11e5-9350-50ccd1bec42b.png">

Use [CurrentSettings.zip](https://github.com/aspnet/Tooling/files/133335/CurrentSettings.zip) to reproduce

**Comment by scottaddie** [comment]
This looks like a duplicate of https://github.com/aspnet/Tooling/issues/351, which is already TFS tracked.

**Comment by xperiandri** [comment]
Yep
