### ISSUE TITLE
Run npm install during project creation

### ISSUE THREAD

**Issue by rustd** [aspnet/Tooling#408]
Porting from templates repo https://github.com/aspnet/Templates/issues/392

I'm not sure if this belongs in the Tooling repo or here. Feel free to move it over there if that's a better home for it.

When creating a new StarterWeb project, a hydrated [`node_modules` folder](https://github.com/aspnet/Templates/tree/dev/src/BaseTemplates/StarterWeb/node_modules) is included. There's one problem with this approach. For those using npm@3.x, instead of the npm@2.x currently included with the IDE, the npm module folders aren't in the expected flattened folder structure.

When flattened with npm@3.x, I see 167 folders in my `node_modules` folder. With what's included in the StarterWeb template, I see just 6 folders. I propose that the hydrated `node_modules` folder not be included in the project assets. Instead, `npm install` should be run upon project creation. This makes npm@3.x users happy.

I had modified my settings in Tools --> Options --> Projects and Solutions --> External Web Tools to look as follows:

![untitled](https://cloud.githubusercontent.com/assets/10702007/12528043/0a79c4c8-c150-11e5-874f-ca805c62d826.png)

Since npm@3.x is available on the Path variable on my machine, and since the `$(PATH)` entry clearly has precedence, I would expect the flattened folder structure by default in my project's `node_modules` folder.

**Comment by sayedihashimi** [comment]
Assigned to Mads

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231168&fullScreen=false&_a=edit">231168</a>

**Comment by jodavis** [comment]
Two things:
1) VS has been updated to use npm 3.x for listing packages, so the display of flattened hierarchies is now correct.
2) All npm packages have been removed from the templates, so there is no more pre-hydration of npm packages.
