### ISSUE TITLE
Update project.json intellisense

### ISSUE THREAD

**Issue by yishaigalatzer** [aspnet/Tooling#409]
There are quite a few features being added to project.json, adding a short list that will probably need to get updated before everything is said and done. So lets treat this list below as a strawman and update it as things progress with more details

- [ ] Dotnetextensions section (to replace tooling)
- [ ] Imports - Allows for dependency sections to allow for more TFMs
- [ ] Intellisense for RIDs

CC @davidfowl  @emgarten

**Comment by Eilon** [comment]
The project.json Intellisense schema is defined in SchemaStore: https://github.com/SchemaStore/schemastore/blob/master/src/schemas/json/project.json

Teams that make changes to the features of project.json are responsible for sending a PR to SchemaStore.

**Comment by yishaigalatzer** [comment]
@Eilon this issue is for tracking the set of changes that are going on. Some of these might not actually work as schema changes (for example the RID graph cannot be completely expressed in a schema). So for now lets use it for discussion and tracking and finally we can assign a person to make the changes in the schema

**Comment by Eilon** [comment]
Yeah that's fine. I just want to make sure that no one is expecting the schema to magically get updated by some "schema team," cuz there isn't one :smile:

**Comment by madskristensen** [comment]
This change should be submitted by someone on the NuGet team to SchemaStore.org.

**Comment by yishaigalatzer** [comment]
@madskristensen read my statement above please.

1. This is an issue to track and agree on all the changes, not about who is going to make them.
2. There are changes here that are not schema.org only (like RIDs), these could be changes in the code proper

**Comment by madskristensen** [comment]
@yishaigalatzer I was just reacting to being assigned this issue by @sayedihashimi

**Comment by sayedihashimi** [comment]
I'm closing this issue since there doesn't seem to be any update here directly in tooling.
