### ISSUE TITLE
Running with CSPROJ references on Linux

### ISSUE THREAD

**Issue by aluitink** [aspnet/Tooling#413]
Hello, did my best to try and find a duplicate of this issue.

Environment: Linux Ubuntu 3.19.0-15-generic
Running in Docker with microsoft/aspnet:1.0.0-rc1-final

I have an ASPNET console app xproj that has a Nuget reference and a C# DLL (csproj) reference that also has a nuget reference.

Is there a way to build the xproj and its dependencies using dnx/dnu on Linux?

I have only been able to accomplish this by copying Nuget.exe, using mono to execute the package restore for the csproj, then using mono xbuild to build the csproj.

It seems like there has to be a more integrated way to do this with DNX..

**Comment by aluitink** [comment]
Example: https://github.com/aluitink/aspnet-debug

**Comment by davidfowl** [comment]
Csproj on Linux isn't a thing. That's unsupported. You'd need to check in the dll produced by the csproj

**Comment by aluitink** [comment]
Thanks for the confirmation, is there a document that explains this type of stuff anywhere?

**Comment by sayedihashimi** [comment]
@danroth27 for the doc question.

Closing this issue now
