### ISSUE TITLE
Wrap project in different root directory tries to restore from nuget and can download someone elses package

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Tooling#415]
I have 2 projects, one is a ASP.NET Core app the other is a csproj class library. They don't live in the same folder but when I add existing project to the ASP.NET Core solution and add reference to the ClassLibrary1 through the UI it wraps the ClassLibrary1 and downloads a ClassLibrary1 from NuGet and doesn't reference my ClassLibrary1.

The project.json in webapp has `"ClassLibrary1": "1.0.0-*"` and the global.json doesn't point to `../ClassLibrary1/ClassLibrary1`

```
/
    webapp/
        src/
            webapp/
                project.json
/
    ClassLibrary1/
        ClassLibrary1/
            ClassLibrary1.csproj
```

**Comment by sayedihashimi** [comment]
@BrennanConroy the wrap functionality has several significant limitations. It's actually been removed from the next version (dotnet cli tools). We are working to replace the wrap functionality with a new feature. That replacement feature should be more robust than what you're experiencing today.

@BrennanConroy wrap is a runtime feature so the correct repo is likely dnx if you would like to follow up on this. Closing this one.

**Comment by sadjadbp** [comment]
@sayedihashimi since the new Tooling (preview) removed the wrapping, what is the replacement for now. Is it Nuget? if yes, how I should create from my own DLLs (native C++ dll)
