### ISSUE TITLE
Remote Debugging DNX on Linux

### ISSUE THREAD

**Issue by aluitink** [aspnet/Tooling#416]
Is there a way to debug a DNX process running on Linux?

Does MS have anything like this planned and is it scheduled for a release?

**Comment by sayedihashimi** [comment]
@aluitink we have to enable debugging on linux first :)

With that said, can you explain how you might use remote debugging on linux? I'm looking for more scenario info and to get a better sense for what types of scenarios we can investigate.

**Comment by danielbardsley** [comment]
I'm not the original poster my use case for this is as follows: My environment is deployed and configured using vagrant/puppet. Puppet installs dnx and deploys the site already but my workflow would be much more convenient if I could edit files locally, have them synced automatically by vagrant and then debug against the code deployed to the virtual machine. I'm using Visual Studio on Windows but running the asp app on a Linux VM. It would be much more convenient to debug against the deployed version rather than having to go through a debug/deploy cycle.

**Comment by aluitink** [comment]
@sayedihashimi & @danielbardsley I am working on a VS Extension that hopefully will enable remote debugging on Linux. It is quite far from functional at the moment, but I am able to connect to a Mono Debug Agent and issue the initial VMStart command. It is going to be a long road .. quite untraveled by the looks of it. I've never attempted anything like this before, but I've found some similar projects from which I'm borrowing the pattern. 

If you are interested in contributing/testing, the project comes with a Docker container to which the dnx application can be deployed and remotely started. I really only get a couple hours a week to work on this but it seems to be coming along nicely.

https://github.com/aluitink/aspnet-debug

**Comment by aluitink** [comment]
@sayedihashimi Ideally I'd not need to but as Kestrel and this entire framework is not quite finished yet, I sometimes run into issues using Kestrel server on Linux that cannot be reproduced with the Windows host. Generally, I'd just like to be able to step through an application running in Linux, as @danielbardsley mentioned the, Code, Deploy, Run, Exception, Fix, Deploy, Run cycle is tedious at best.

**Comment by sayedihashimi** [comment]
@aluitink I think we are looking at remote debugging but it will be based on .NET Core not mono.

**Comment by sayedihashimi** [comment]
@aluitink FYI https://github.com/Microsoft/MIEngine/wiki/Offroad-Debugging-of-.NET-Core-on-Linux---OSX-from-Visual-Studio. I'm meeting with debugger team to discuss improving this. I'd like for it to be on par with the Windows experience.

**Comment by mlorbetske** [comment]
Debugging .NET Core projects on Linux is possible with Visual Studio 2017 (here's a [blog post](https://blogs.msdn.microsoft.com/devops/2017/01/26/debugging-net-core-on-unix-over-ssh/) on it, it was written for a prerelease of Visual Studio 2017, but it still applies)
