### ISSUE TITLE
Missing Trait's in xUnit actually a VS Tooling Issue

### ISSUE THREAD

**Issue by rjpaulsen** [aspnet/Tooling#419]
Traits from xUnit are not displaying in VSD2015's Test Explorer. The xUnit Team says this was fixed in beta5. Today I posted a comment on xunit @ github since I still see the issue with RC1. The response was that it is an issue for the "ASP.NET Tooling Team". 

https://github.com/xunit/xunit/issues/530

NOTE: beta5/RC1 is in reference to xunit, not .net

**Comment by sayedihashimi** [comment]
@vijayrkn does this still repro with the latest unit testing experience that we have now?

**Comment by sayedihashimi** [comment]
TFS: 203554
I've added this to our internal TFS, we will reply back here soon.

**Comment by rjpaulsen** [comment]
New computer. New VS2015 Install. Everything seems to work as expected now.

**Comment by tutike2000** [comment]
Also having this problem, would rather not reinstall VS or Windows.

`[Trait("asd", "qwe")]
        [Fact]
        public void Nope()
        {
        }`

This test shows up under "No Traits" in Test Explorer, using VS Enterprise 2015, 14.0.25123.00 Update 2

project.json has:
"xunit": "2.2.0-beta1-build3239",
"xunit.runner.dnx": "2.1.0-rc1-build204",

and under frameworks: 
"dnxcore50": {}

**Comment by vijayrkn** [comment]
we haven't added the Trait support in VS tooling yet. This is the issue tracking this work item - https://github.com/dotnet/cli/issues/2252
