### ISSUE TITLE
compile from sources

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#42]
I created a new asp.net mvc application, cloned the mvc repo, checked out the beta 4 tag, and added the src directory to the global.json.
try to recompile and find a lot of errors about the **NotNull** type not found and so on. The NotNullAttribute is defined ina project inside the common repo, so I clone this too, checkout the beta 4 tag, and add the src directory to the global json.
Try to recompile and find this: 
**Dependency System.Runtime >= 4.0.20-* could not be resolved ...src\Microsoft.Framework.CopyOnWriteDictionary.Internal\project.json
Dependency System.IO >= 4.0.10-beta-* could not be resolved	Microsoft.AspNet.PageExecutionInstrumentation.Interfaces	..src\Microsoft.AspNet.PageExecutionInstrumentation.Interfaces\project.json**
and so on.

I'm using 2015 rc and the only version of the dnx runtime is the beta 4

**Comment by davidfowl** [comment]
A couple of issues with the RC build:
- You need to run restore from the command line. VS runs restore on the solution and it misses the correct package feeds. It'll be fixed by RTM.
- We're fixing all of the branches and tags to fix the version numbers. I'll update this thread when we're done.

/cc @PradeepKadubandi @pranavkm @muratg

**Comment by lucamorelli** [comment]
thanks for the info. I have a similar problem with the package "EntityFramework.InMemory", that I'm not able to add to a project. I cannot resolve it even from the cmd line running dnu restore

**Comment by sayedihashimi** [comment]
Assigning to @davidfowl for now since we are waiting on him for an update on the following.

>We're fixing all of the branches and tags to fix the version numbers. I'll update this thread when we're done.

**Comment by davidfowl** [comment]
Going to close this
