### ISSUE TITLE
Turn off C# Interactive

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Tooling#420]
Not sure if this is correct place for this question...

I installed VS 2015 Update 2 RC today and for me the "C# Interactive" window is poping up as fast I press Alt+Enter inside an editor. I'm using alt+enter all the time with Resharper. Does it exists any option to turn off the "C# interactive" ?

**Comment by sayedihashimi** [comment]
@Tasteful I'm not sure if this is the right repo either. @kuhlenh is there a better repo for this? If not I'm OK with using this repo for this issue if you like.

**Comment by kuhlenh** [comment]
Hey @Tasteful, it looks like our keyboard shortcut for C# Interactive isn't in the RC (the keyboard shortcut should be "Ctrl+E, Ctrl+E" instead of "Alt+Enter"). As a current workaround, you should be able to go to your ReSharper Options and "Apply Scheme" to fix your "Alt+Enter" functionality.

**Comment by Tasteful** [comment]
@kuhlenh thanks for the fast reply. I tested earlier today with resetting r# shortcuts and that was working to get shortcut back whe r# have hints, is the cursor on any other rows or the r# hint not is visible yet the alt+enter will anyway open up the c# interactive.

I also checked the kebord shoutcuts and c# interactive was included in the list but no assigned shortcuts.

**Comment by kuhlenh** [comment]
Hmm. Try going to Tools>Options>Environment>Keyboard and unbinding "Alt+Enter" from the command "EditorContextMenus.CodeWindow.ExecuteInInteractive".

**Comment by Tasteful** [comment]
@kuhlenh The ExecuteInInteractive is already Ctrl+E, Ctrl+E
![image](https://cloud.githubusercontent.com/assets/357589/13661485/448df928-e693-11e5-80e6-4f8136c21835.png)

If i try to see all the Alt+Enter I only got the correct one assigned.
![image](https://cloud.githubusercontent.com/assets/357589/13661502/6be71d4c-e693-11e5-8ba4-a0ea8690734f.png)

If I have the cursor on the keyword (green arrow) the chortcut is working, if I place the cursor on the `{` (red arrow) the C# Interactive is popping up.
![image](https://cloud.githubusercontent.com/assets/357589/13661716/5c4368b2-e695-11e5-9061-cf6017bb9670.png)

For the moment I placed C# Interactive window in an own auto hide group that only shows the title bar so it not should disturb when working.

**Comment by kuhlenh** [comment]
@Tasteful I have moved this bug to the roslyn repo where you can track it here https://github.com/dotnet/roslyn/issues/9657
