### ISSUE TITLE
HTTP 500 Error afther publishing to Azure Web App

### ISSUE THREAD

**Issue by dieterhowest** [aspnet/Tooling#422]
Hello

I want to publish my ASP 5 app to azure web app. After the publishing process is finished and I navigate to the URL , a with webpage is shown. When I do a refresh , it takes some time but finally I get a HTTP 500 error.

I have tested with a new ASP 5 application and this works fine. This must be a problem with my app. I have looked in the config json files , but can't find anything that could be wrong.

Update: the azure website now shows a 

> 502 - Web server received an invalid response while acting as a gateway or proxy server.
> There is a problem with the page you are looking for, and it cannot be displayed. When the Web server (while acting as a gateway or proxy) contacted the upstream content server, it received an invalid response from the content server.

regards
Dieter

**Comment by dieterhowest** [comment]
Hello

I found a solution, I don't know if this is a bug, but the problem was unused using in my souce code. The where grayed out but still there. After removing the from source and republish to azure the problem was gone ??

Dieter

**Comment by sayedihashimi** [comment]
@dieterhowest do you have some specific steps that I can follow to reproduce this?

**Comment by dieterhowest** [comment]
The problem is gone, I removed unused namespaces in my code (grayed out namespaces) and then I did a republish and the problem was gone.

I found this solution by logging in into ….scm.azurewebsites.net. I used the console to navigate and to start manual the application by using the “web” command. Then I saw compilation errors (Roslyn?? Errors?). The errors complained about the unused namespaces. I removed them from code , republish and the problem was gone.

**Comment by tinchou** [comment]
I had a similar problem with an error 500. @dieterhowest suggestion to run the `web` command manually in the server lead me to find the error: I wasn't checking the `Remove additional files at destination` option in the VS publish menu, and some old files where messing the server.

**Comment by sayedihashimi** [comment]
Ok @tinchou that makes sense.
It sounds like we can close this?

**Comment by dieterhowest** [comment]
Yes

Sent from Outlook Mobile<https://aka.ms/qtex0l>




On Fri, Mar 18, 2016 at 5:07 PM -0700, "Sayed Ibrahim Hashimi" <notifications@github.com<mailto:notifications@github.com>> wrote:


Ok @tinchou<https://github.com/tinchou> that makes sense.
It sounds like we can close this?

-

**Comment by dieterhowest** [comment]
hello

I had the problem again, I had to clean the folder d:\hom\site\approot\src inside the azure web app, and then the problem was fixed

Dieter

**Comment by Darioth23** [comment]
Hello, I posted my website this has php code, when I run it I get HTTP ERROR 500
