### ISSUE TITLE
error dragging .d.ts file inside a .ts file in a asp.net 4 project

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#424]
vs 2015 update 1.
I have an asp.net 4 project, and I created an typescript intellisense file for a c# class using web essentials, and id I try to drag it in a .ts file inside the same projects, instead to be converted in a reference

`/// <reference path="../../../....cs.d.ts" />`
is added as link
`http://localhost:1692/....cs.d.ts
`
I have to say that since both the source and destination files are in the same project this operation is often unuseful, but I don't think this is the reason

**Comment by sayedihashimi** [comment]
TFS: 203549
I've added this to our internal TFS, we will reply back here soon.

Thanks Luca!

**Comment by billti** [comment]
We're not going to get time to fix this up for the final version of VS 2017. That said, if the .d.ts file is in your project, then you shouldn't need to reference it anyway, all project files are loaded into the language service context - referenced or not.

**Comment by sayedihashimi** [comment]
Closing based on @billti comment above
