### ISSUE TITLE
Pasting bad code over bad code crashes VS

### ISSUE THREAD

**Issue by victorhurdugaci** [aspnet/Tooling#425]
Copied from here: https://github.com/aspnet/RazorTooling/issues/47

1. Create a new web application (no authentication)
2. Open the `Home/Index` view and paste this code (ignore any compilation errors):
    ```
@using BuildDashboard.Server.Models.Dashboard
@using SectionLayout = BuildDashboard.Server.Models.Dashboard.Layout

@model SectionTile

@{
    const int MinGridItemSize = 2;
    const int GridSpaces = 12;
    const int MaxItemsPerRow = GridSpaces / MinGridItemSize;
}

<div class="page-header">
    <h1>@Model.Title</h1>
</div>

@*@if (Model.Layout == SectionLayout.Normal)
{
    foreach (var tile in Model.Tiles)
    {
        @await Component.InvokeAsync("Tile", new { tile })
    }
}
else
{
    var itemsPerRow =
            }*@
```

3. Save
4. Copy the code below

    ```
@using BuildDashboard.Server.Models.Dashboard

@model SectionTile

@{
    const int GridSize = 12;
    
    var actualItemsPerRow = Model.ItemsPerRow;
    if (actualItemsPerRow < 1)
    {
        actualItemsPerRow = 1;
    }
    else if (actualItemsPerRow > 12)
    {
        actualItemsPerRow = 12;
    }
    
    while (GridSize % actualItemsPerRow != 0)
    {
        --actualItemsPerRow;
    }
}

<div class="page-header">
    <h1>@Model.Title</h1>
</div>

<div>@actualItemsPerRow</div>

<!--@*@if (Model.Layout == SectionLayout.Normal)
{
    foreach (var tile in Model.Tiles)
    {
        @await Component.InvokeAsync("Tile", new { tile })
    }
}
else
{
    var itemsPerRow =
            }*@-->
```

5. Go back to the view
6. Select all
7. Paste

Result: VS crashes

VS version: 14.0.23107.0 D14REL
Tooling: 14.1.11116.0

**Comment by sayedihashimi** [comment]
TFS: 203548
I've added this to our internal TFS, we will reply back here soon.

Thanks, I have created an internal issue and indicated that it's a crash.

**Comment by sayedihashimi** [comment]
FYI I tried it with a build about a week ago and it did not crash

@victorhurdugaci is it still reproducing for you?

**Comment by sayedihashimi** [comment]
@victorhurdugaci if the crash is still happening if you can grab a call stack it will be very helpful. Also please include Help->About info from VS so that we know what's installed.

**Comment by sayedihashimi** [comment]
Closing with no repro. @victorhurdugaci if it's reproing please grab a call stack.
