### ISSUE TITLE
Cannot Debug in visual studio if VS is Elevated

### ISSUE THREAD

**Issue by ltheONEl** [aspnet/Tooling#428]
I have a curious issue. To publish to IIS in my dev machine I run visual studio as administrator (bad ok!).
 While visual studio is elevated I cannot debug an MVC project either VS cannot attach or IIS Express dies or kestrel does. not sure which. I don't get any error. VS just exits debug mode.

If I restart VS as normal (Not Elevated) I can debug perfectly.

Has anyone else seen this?

**Comment by sayedihashimi** [comment]
I just tried with a build that was about 1 week old, I couldn't reproduce it. If you do File New Project do you get the same result? I'm wondering if the issue you have is specific to your solution/project.

**Comment by sayedihashimi** [comment]
@ltheONEl I cannot reproduce this. If it's happening for File->New Project, please reopen.

My team is using VS as admin on a daily basis so I highly doubt its a wide spread issue.
