### ISSUE TITLE
IDE tooling : hard to access external code that is defined in "compile"

### ISSUE THREAD

**Issue by mgravell** [aspnet/Tooling#43]
As I migrate between csproj and project.json, I find myself with some DNX projects having to bring in files from outside the project tree using `"compile:"`, for example (from dapper):

    "compile": [ "../Dapper NET40/*.cs", "../Dapper NET45/*.cs" ],

However, these files never appear in the solution, and do not work in search. The only way I've found of getting the IDE to play nicely with such files is to add them as solution items.

Obvious issue: how to make them appear; where to put them; what to do if there are conflicts (an existing file inside the tree with the same name) - I didn't say I had the answers ;p

**Comment by smohekey** [comment]
Is there any traction on this issue? We're working on migrating from a previous internal package management system to dnx and as part of the transition need to use external relative paths like this.

**Comment by sayedihashimi** [comment]
See my comments at https://github.com/aspnet/Tooling/issues/217#issuecomment-147847843. Let's continue the discussion there if needed. I'll close this item out.

If you feel that this is something different please reopen with details.
