### ISSUE TITLE
Environment variables renamed from ASPNET_ to ASPNETCORE_

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Tooling#430]
This is especially relevant for ASPNETCORE_ENVIRONMENT=Development.

**Comment by Eilon** [comment]
Need to fix this for RC2.

**Comment by sayedihashimi** [comment]
TFS: 204015
I've added this to our internal TFS, we will reply back here soon

**Comment by sayedihashimi** [comment]
Fix was checked in. Closing this now
