### ISSUE TITLE
Having multiple sites with the same IIS Express launch url causes VS to launch the wrong site

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Tooling#431]
The Security repo has three sample sites with the same launch url. (It needs to be the same because that url is registered with a remote auth server).  This can cause VS / IIS Express to launch the wrong site.

**Comment by sayedihashimi** [comment]
@Tratcher are they in the same solution? Can you share a sample?

**Comment by sayedihashimi** [comment]
TFS: 204017
I've added this to our internal TFS, we will reply back here soon

**Comment by Tratcher** [comment]
Yes, the same solution.
https://github.com/aspnet/Security/tree/dev/samples/JwtBearerSample
https://github.com/aspnet/Security/tree/dev/samples/OpenIdConnect.AzureAdSample
https://github.com/aspnet/Security/tree/dev/samples/OpenIdConnectSample

**Comment by mjrousos** [comment]
Any updates on this one? Any workarounds? I'm running into the same issue.

**Comment by barrytang** [comment]
No, this is not fixed yet. I moved the issue to https://developercommunity.visualstudio.com/content/problem/118429/having-multiple-sites-with-the-same-iis-express-la.html.

**Comment by barrytang** [comment]
@BillHiebert as FYI.
