### ISSUE TITLE
Add Solution Open Binding to Gulp Task Runner

### ISSUE THREAD

**Issue by derekgreer** [aspnet/Tooling#433]
The 2013 Task Runner plugin allowed you to create a binding which executed when the solution was opened.  This was helpful for tasks which you only want kicked off one time (e.g. watch task, create common AssemblyInfo.cs, etc.)  The new version for 2015 removed this option which forces you to use Project Open for such scenarios.  The problem is that project files are opened frequently, such as when pulling updates from git which affect the project file, switching branches, etc.  This can lead to undesired behavior (e.g. multiple watch tasks getting kicked off).  Please add the support for creating bindings when a solution opens back to the Task Runner.

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231165&fullScreen=false&_a=edit">231165</a>

**Comment by derekgreer** [comment]
I've opened reported this issue in VS's problem tool: https://developercommunity.visualstudio.com/content/problem/104833/add-solution-open-binding-to-task-runner.html

**Comment by barrytang** [comment]
Thanks @derekgreer!
