### ISSUE TITLE
Adding webroot folder and iisexpress configurations to loaded project doesn't allow you to run in IISExpress

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Tooling#435]
**Repro:**
- File => New Web Application => Empty Project
- Add IISExpress config/folder requirements
- ctrl + f5
- You get red error box saying the app isn't configured to run in iis.

If I close the sln then reopen all magically works.

**Comment by sayedihashimi** [comment]
TFS: 210764
I've added this to our internal TFS, we will reply back here soon.

**Comment by barrytang** [comment]
@NTaylorMullen, we think this is a DNX glitch which doesn't apply to .NET Core tooling anymore.

Adding @BillHiebert as well.

**Comment by NTaylorMullen** [comment]
Hu? Like a DNX glitch that affected dotnet tooling? I encountered this when using dotnet tooling.

**Comment by barrytang** [comment]
File=>Empty Project was a DotNet project?

**Comment by barrytang** [comment]
@NTaylorMullen?

**Comment by NTaylorMullen** [comment]
@barrytang Left out one middle piece between file => empty project. SOrry! It's File => New Web Application => Empty Project. I did this before the templates had all of the wwwroot goodness in an empty web app. (My current box does have it).

I currently do not have tooling that is able to run empty projects anymore. However, I'd assume that you could repro this with the new template (and working tooling) where the wwwroot pieces are removed then re-added.

**Comment by barrytang** [comment]
Confirmed with @NTaylorMullen this is working now with the latest bits.
