### ISSUE TITLE
Duplicating global.json

### ISSUE THREAD

**Issue by dazinator** [aspnet/Tooling#436]
Really weird one. 
In my solution I have multiple `xproj`s. I went through most of them and changed the default namespace.

![image](https://cloud.githubusercontent.com/assets/3176632/14110042/bb81be6a-f5bc-11e5-81ba-868162bdd4fc.png)

As I did so I noticed that duplicate global.json's were being added as solution items:

![image](https://cloud.githubusercontent.com/assets/3176632/14110021/b33735be-f5bc-11e5-88a1-f1b4c8694cf0.png)

Double clicking on the global.json file:

![image](https://cloud.githubusercontent.com/assets/3176632/14110067/d12ca662-f5bc-11e5-8337-e83d3be6cb01.png)

**Comment by sayedihashimi** [comment]
What happens if you close and reopen VS?

**Comment by sayedihashimi** [comment]
@dazinator I tried this and I didn't see the behavior you described. A couple of questions.

 1. Is it happening for new solutions with new projects or just one particular solution?
 1. Is it happening on a different machine?

**Comment by dazinator** [comment]
I'll try and figure out repro steps

**Comment by sayedihashimi** [comment]
Thanks @dazinator

**Comment by sayedihashimi** [comment]
Closing for now until you get some steps to reproduce.
