### ISSUE TITLE
_references.js file tooling

### ISSUE THREAD

**Issue by ArieJones** [aspnet/Tooling#437]
The tooling that revolves around the _references.js file needs to be updated to accommodate the new project format. Currently, the file is pulling all javascript files in from the entire project both inside and outside of the wwwroot folder. 

I believe with the new project format for core MVC projects that it should be constrained to the wwwroot folder since that is where our static content is "supposed" to live. 

One of the problems that we run into is the fact that we use sets of typescript files that are combined and minified by gulp into the wwwroot. However, the _references.js file picks up an entry for all of them and then complains on loading the project that it cannot find them...

06:46:07.0787: Referenced file '../typescript/app/allergyforms.js' not found.
06:46:07.0787: Referenced file '../typescript/app/conditionforms.js' not found.
06:46:07.0787: Referenced file '../typescript/app/demographics.js' not found.
06:46:07.0787: Referenced file '../typescript/app/edcuationforms.js' not found.
06:46:07.0787: Referenced file '../typescript/app/encounterforms.js' not found.
06:46:07.0787: Referenced file '../typescript/app/enterkey.js' not found.
06:46:07.0787: Referenced file '../typescript/app/entities/account.js' not found.

**Comment by sayedihashimi** [comment]
assigning to @madskristensen

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231163&fullScreen=false&_a=edit">231163</a>

**Comment by jodavis** [comment]
_references.js is no longer used in VS2017. It's replaced by implicit references which won't have this issue.
