### ISSUE TITLE
Cannot start debugging in IDE (update 2)

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Tooling#439]
VS2K15 Update 2 broke Asp.net core debugging.
![ide_dnx_error](https://cloud.githubusercontent.com/assets/6814395/14231055/9988d06c-f9a6-11e5-8cb8-3de53b9f2221.png)

**Comment by StefH** [comment]
Same issue here.

When upgrading from Visual Studio Update 1 to Update 2, I can debug with dnx-clr-win-x86.1.0.0-rc1-update1, however adding a variable to the debug windows shows error like:

```
   doc	error CS0103: The name 'doc' does not exist in the current context	
```
And when hovering over a variable in the code, nothing happens.

Repairing ASP.NET 5 RC 1 update 1 does not help.

**Comment by sayedihashimi** [comment]
Sorry to hear that you're running into this issue. One thing that you can try, Delete any .suo and .user file and try again.

One question, do this happen for new projects after File->New Project or only for existing projects/solutions?

**Comment by xatabhk** [comment]
@sayedihashimi Both. VS2K15 Update 1 worked. It just VS2K15 Update 2.

**Comment by sayedihashimi** [comment]
@xatabhk I think this may be an issue where the ComponentModelCache folder becomes invalid. After closing Visual Studio, delete the folder at `%appdatalocal%/Microsoft/VisualStudio/14.0` and then restart Visual Studio. Does that fix it for you?

**Comment by StefH** [comment]
I did delete the ```%appdata%/Microsoft/VisualStudio/14.0``` folder, however this did not solve the issue for me.

**Comment by sayedihashimi** [comment]
@BillHiebert any ideas what may be happening here?

**Comment by sayedihashimi** [comment]
TFS: 219231
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
Should be fixed in our upcoming RC2 release
