### ISSUE TITLE
IDE tooling suggestion: nuget push equivalent

### ISSUE THREAD

**Issue by mgravell** [aspnet/Tooling#44]
Automatic artifact nupkg is great, but it would be good if we could also use the IDE to do a deploy - essentially a `nuget push`, but without needing any solution-level tools.

I'm imagining: right-click on a **library** DNX project and select "Publish"; UI appears; if the user has not previously configured an api-key, prompt for a key (or prompt for web login, and have VS fetch it?) - essentially doing the same as `nuget setApiKey`

"This will upload {package name} to {target} blah blah blah; [confim]"

When click ok, do it.

Questions:

- can you target multiple nugets?
- does it upload to the doc server too?
- how does/should key invalidation work? detect specific failure and prompt for re-entry?

Nice-to-haves:

- check that the current user has access to push that package while the confirmation window is up (new package name, or owner)
- check that the new version makes sense (not already exists? higher version?)
- warn if it isn't a Release build?

Aside:

The current Publish option for DNX **library** projects appears to be web publish; does that even make sense?

**Comment by sayedihashimi** [comment]
I think this belongs in https://github.com/NuGet/NuGet3 instead of here. @mgravell can you port it to that repo? From there hopefully you'll get answers to your questions.

>The current Publish option for DNX library projects appears to be web publish; does that even make sense?

I have create a new issue for this https://github.com/aspnet/Tooling/issues/67

I'll close this now.

**Comment by mgravell** [comment]
K, thanks. Sorry for misdirecting: it is quite hard (from the outside
looking in) to know what goes where.

**Comment by yishaigalatzer** [comment]
@sayedihashimi all NuGet bugs on the client should go to Nuget/Home

**Comment by sayedihashimi** [comment]
@yishaigalatzer updated the link in the comment above
