### ISSUE TITLE
Feedback on generated content from scaffolders for RC2

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Tooling#444]
We are working on scaffolding support in our upcoming release. In this release the goal was to go from `dnx` to `.net core`. We spent most of the time on the conversion and have not added any new significant features.

We have made some changes to the generated content. We are asking for community feedback on the generated content. We have a [SampleWebApp repo](https://github.com/prafullbhosale/SampleWebApp) which has content that was generated using the new scaffolding bits.

You can view the changes when invoking a scaffolder with the following links.
 - [MvcControllerWithContext](https://github.com/prafullbhosale/SampleWebApp/pull/1/files)
 - [Empty Controller and Controller with Read Write Actions](https://github.com/prafullbhosale/SampleWebApp/pull/2/files)
 - [ApiController With Context](https://github.com/prafullbhosale/SampleWebApp/pull/3/files)

cc @prafullbhosale

**Comment by pebezo** [comment]
On the ApiController this gets included for every action:

```
if (!ModelState.IsValid)
{
    return BadRequest(ModelState);
}
```

Is there no easy way to write that only once? (with the caveat that I many not want it 100%)

**Comment by sayedihashimi** [comment]
@pebezo I don't think that we can refactor it to be any better. If we added a method to check the model state instead of evaluating `ModelState.IsValid`, we basically have the same code but instead calling another method. Or maybe I'm misunderstanding the recommendation here.

**Comment by pebezo** [comment]
You probably can't solve this at a "template" level. I was just saying that it would be nice to not have all that copy+pasted code for every action. Maybe a "OnPreAction" function that could be called before every action? You'd probably need something in the MVC framework itself -- don't know if there something like this.

**Comment by sayedihashimi** [comment]
> You'd probably need something in the MVC framework itself -- don't know if there something like this.

For feedback on the framework please file it at https://github.com/aspnet/mvc

**Comment by AcousticGuitar** [comment]
Thanks gents for your work on this!
