### ISSUE TITLE
Question: Updating TypeScript tool

### ISSUE THREAD

**Issue by pebezo** [aspnet/Tooling#445]
If I go to Help > About, I see TypeScript 1.8.29.0. If I run the installer from https://www.microsoft.com/en-us/download/details.aspx?id=48593 it doesn't update this value. Is this expected? Thanks.

**Comment by sayedihashimi** [comment]
Hi @pebezo thanks for the note. This repository is specifically for ASP.NET Core Visual Studio tooling. Typescript has it's own repo at https://github.com/Microsoft/TypeScript.

Closing this now.
