### ISSUE TITLE
Open console on the context menu

### ISSUE THREAD

**Issue by ciel** [aspnet/Tooling#446]
I know people ask for things on an hourly basis, but seeing as how new tools for Visual Studio 2015 are coming up with the pending release of .NET Core/ASP.NET Core, and how Visual Studio 15 is on its way, I thought I'd ask again.

I know integrating a whole console into Visual Studio is difficult - but would it be hard just to add a context menu item that opens a cmd/powershell in the directory of the file you click it from?

This exists as an add-on already, and works so well; [Open Command Line](https://visualstudiogallery.msdn.microsoft.com/4e84e2cf-2d6b-472a-b1e2-b84932511379)

I am trying out Visual Studio 15 and notice it still lacks this functionality, and the add-on isn't compatible. I really miss it already - it made coding in .NET Core a lot better since we have to use the command line so much for it - it's a pain to navigate folders all the time. 

It doesn't need to be much. It doesn't need to be a window inside of Visual Studio - just give us very simple options. The path to the command line we want to open, for example; Perhaps a smattering of 3 or 4 options we can pass through arguments like Visual Studio Code has (`{ApplicationRoot}`,`{FileFolder}`)

![Open Command Line Extension](http://i.xomf.com/vmlkc.jpg)

I know this might not be the appropriate place to put this, and if that is the case I'll remove my post - I'm also leaving this on the Visual Studio _uservoice_ if I can find it again.

**Comment by sayedihashimi** [comment]
@madskristensen are you planning to roll in the extension to VS itself or is it going to stay as an extension?

**Comment by madskristensen** [comment]
I don't plan on building it in, but I'll update the extension to work on VS15 soon

**Comment by madskristensen** [comment]
It now works on VS15
