### ISSUE TITLE
Cannot see local variables while debugging

### ISSUE THREAD

**Issue by rosieks** [aspnet/Tooling#448]
I cannot debug my console application because there is no local variables inside locals or watch like on the screenshot:

![image](https://cloud.githubusercontent.com/assets/1107959/14408442/5428b0e2-fef5-11e5-9861-6b796c6f8116.png)

I'm using Visual Studio 2015 Update 2 and runtime in version 1.0.0-rc-1-update-1/platform: .NET Framework

**Comment by sayedihashimi** [comment]
@rosieks a fix has been released for this. See https://github.com/aspnet/Tooling/issues/438#issuecomment-209267495. Closing this now.
