### ISSUE TITLE
Project Types : Please make them C# for Templates

### ISSUE THREAD

**Issue by ciel** [aspnet/Tooling#451]
Right now, making custom `ItemTemplates` or `ProjectTemplates` for an ASP.NET Core application is annoying because you have to hunt down the type to put them under; After a while, I discerned that they're currently being reported as `DNX` types.

Since you can put so much in these projects, could we possibly get them to accept normal C# and/or web ItemTemplates? The `Add ...` dialog is so confusing with the way it is laid out.

You don't have a `web.config` - you've got like 8 `.json` types that aren't clear, and are scattered across about 3 categories - you have to hunt for a simple `.cs` file - I know it's all in 'beta', but it's a bit of a mess right now and I think this should be an area to clean up for RC2.

Or perhaps instead of just calling them C# or Web, at least an updated monicker, like `Core/Code`, `Core/Web`, `Core/C#`. It might make it simpler to organize them.

**Comment by sayedihashimi** [comment]
Moved to https://github.com/aspnet/Templates/issues/527 closing.
