### ISSUE TITLE
Disable Automatic restore on project.json change

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Tooling#453]
Now dotnet cli has extra restore logic for tools for example is it possible to disable the auto restore in visual studio.  Otherwise they are fighting each other.
I know its a short term thing.

**Comment by sayedihashimi** [comment]
Hi @mikes-gh, have you tried unchecking the automatic restore setting in Tools->Options shown below?

![nuget](https://cloud.githubusercontent.com/assets/1283154/14829248/3bc9032e-0b9f-11e6-9836-fb5267b0be1c.png)

**Comment by mikes-gh** [comment]
I tireied it but I still seem to get automatic restores.
Its temporary until dotnet cli tooling is visual studio so closing for now
