### ISSUE TITLE
.xproj OutputPath setting should be renamed to BuildBasePath

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Tooling#455]
The `OutputPath` is not passed to `dotnet build` as the output path parameter (`-o`). Instead it's passed in as the `--build-base-path`. This is quite misleading given the names.

**Comment by sayedihashimi** [comment]
The names are defined by dotnet cli. With that said we are changing vs to not pass either (go with default).

**Comment by NTaylorMullen** [comment]
Ah, default parameters will be awesome! As for naming, isn't this name defined by VS/installed msbuild bits:
```XML
<OutputPath Condition="'$(OutputPath)'=='' ">..\..\artifacts</OutputPath>
```

**Comment by sayedihashimi** [comment]
@NTaylorMullen the names of the parameters is defined in the cli, so if you have feedback on the names please open an issue in dotnet/cli. Closing this.
