### ISSUE TITLE
Adding a new folder to a project can crash Visual Studio

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Tooling#459]
Repros on two different machines:
- clone this repository: `https://github.com/OrchardCMS/Orchard2`
- open `Orchard.sln`
- expend `src/Modules/Orchard.Demo`
- right-click on the project, select `Add`, then `New Folder`

Visual Studio is then not responsive, and after a long time the popup appears at the top left, clicking anything crashes VS.

**Comment by sayedihashimi** [comment]
TFS: 219214
I've added this to our internal TFS, we will reply back here soon.

**Comment by sebastienros** [comment]
I already added it yesterday as Barry requested as I was asking for feedback.

**Comment by BillHiebert** [comment]
@sebastienros 
Turns out to be a performance issue in Scaffolding. Working on a fix

**Comment by sayedihashimi** [comment]
Should be fixed in our upcoming RC2 release
