### ISSUE TITLE
In Web Site template, the casing of the ICompileModule folder is wrong

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Tooling#46]
The folders `compiler/preprocess` [are lower case](https://github.com/aspnet/dnx/blob/master/src/Microsoft.Framework.Runtime.Hosting/ProjectFilesCollection.cs#L14). The way they are now, the project silently (!) won't precompile on Mono.

aspnet/dnx#1645

**Comment by sayedihashimi** [comment]
Adding @pranavra

**Comment by sayedihashimi** [comment]
Assigning to @rustd

**Comment by rustd** [comment]
We don't have this file anymore in the templates.
