### ISSUE TITLE
Web Deploy packages should contain the version number

### ISSUE THREAD

**Issue by StevenLiekens** [aspnet/Tooling#460]
The naming convention for Web Deploy packages is `$(WebPublishPipelineProjectName).zip`.

Example
- MyWebApplication.zip

From that name, it's impossible to tell what version the package contains. Also, you can't store two different releases side-by-side without renaming either one. These problems makes it challenging to automate deploys in an enterprise environment where releases are packaged and archived for later deployment instead of deployed after each build.

Please change the naming convention to `$(WebPublishPipelineProjectName).$(Version).zip`.
- MyWebApplication.1.0.0.0.zip
- MyWebApplication.2.0.0.0.zip

This is the same naming convention that NuGet uses for its packages.

Benefits
- You can tell which version a package contains
- Multiple releases can be stored in the same directory
- You can order releases from new to old by sorting packages alphabetically

**Comment by sayedihashimi** [comment]
@StevenLiekens this is an interesting idea. I think adding the version would be helpful in some cases but it could be problematic for other cases. We could consider adding a checkbox with this behavior. Let's see how much interest there is in this. This is the first time I've heard this particular request.

**Comment by mlorbetske** [comment]
There haven't been any responses here in over a year, since it was meant to gather some additional perspectives & nobody else has chimed in, I'll close this issue.

@sayedihashimi this wasn't actually added to TFS (despite the label). If you think we should track this item, please create a bug for it.

**Comment by StevenLiekens** [comment]
Oh well. I guess not enough people use Web Deploy in that way. Or they just don't care to come and leave their feedback on GitHub.

**Comment by StevenLiekens** [comment]
To be honest it's probably been over a year since I last had to set up a build pipeline where I use Web Deploy in this way.

From what I can remember, my biggest pain point was not being able to tell what version of a web app is in the output zip archive without inspecting the contents.

I also had trouble creating backups of releases because you can't have duplicate file names within a single directory. And of course you wouldn't be able to tell which file is which release any other way than by looking at the file creation date or inspecting the contents of each archive.

It's possible that I can already solve these problems with post-deploy scripts but I'm sure it wouldn't be the easiest thing to do in MSBuild.

**Comment by mlorbetske** [comment]
You might try posting about this on https://github.com/aspnet/websdk, @vijayrkn may have some ideas on how to do it

**Comment by vijayrkn** [comment]
@StevenLiekens - You can set the PackageLocation property to <projectname>.<version> and publish should honor this value. 

To add this feature to websdk, can you please create a bug here - https://github.com/aspnet/websdk
