### ISSUE TITLE
Visual Studio 2015 Update 2 Causing issues

### ISSUE THREAD

**Issue by jln1989** [aspnet/Tooling#469]
Hi,

After installing VS Studio 2015 update 2 we are seeing lot of issues wrt performance, debugger values not available, intermittent crashes, etc

In our project we have around 180 projects and we are able to observe the issues across the machines.

http://stackoverflow.com/questions/28730100/visual-studio-2015-debugging-cant-expand-local-variables

**Comment by jln1989** [comment]
@sayedihashimi I have installed the update for VS 2015 Update 2 which had some bug fixes and after installing the update I noticed that the building of my application not completing and hung in the middle (tried for 5 times)

I have now uninstalled the update and the solution is working fine. Anyone else facing this issue?

https://msdn.microsoft.com/library/mt695655.aspx

**Comment by sayedihashimi** [comment]
@jln1989 sorry for the delay here. We have released RC2. Can you try with RC2 https://blogs.msdn.microsoft.com/webdev/2016/05/16/announcing-asp-net-core-rc2/ and let us know if this is still an issue.

**Comment by sayedihashimi** [comment]
Closing for now, please reopen if this is still an issue with RC2
