### ISSUE TITLE
project.json: commented lines break "compile" arrays

### ISSUE THREAD

**Issue by mgravell** [aspnet/Tooling#47]
This is fine elsewhere, for example:

    "commands": {
        //"dummy": "nothing",
        "test": "xunit.runner.dnx"
    },

Which is then validly ignored:

    D:\Dev\protobuf-net\Protobuf.Tests>dnx . dummy
    System.InvalidOperationException: Unable to load application or execute command
    'dummy'. Available commands: test.

However! It breaks the IDE when used in `"compile:"`:

    "compile": [
        //"../Examples/Diction*.cs",
        "../Examples/Program.cs"
    ],

This causes 3 errors:

- Illegal characters in path.
- NuGet Package Restore failed for one or more packages. See details in the Output window.
- The design time host build failed with the following error: Illegal characters in path.

And the "References" node in the solution explorer breaks (yellow hazard sign)

Note: this also breaks `dnx` when used at the command line, for example:

    D:\Dev\protobuf-net\Protobuf.Tests>dnx . test
    System.ArgumentException: Illegal characters in path.
       at System.IO.Path.CheckInvalidPathChars(String path, Boolean checkAdditional)
       at System.IO.Path.IsPathRooted(String path)
       at Microsoft.Framework.Runtime.PatternsCollectionHelper.CreateCollection(Stri
    ng projectDirectory, String[] patternsStrings)

**Comment by sayedihashimi** [comment]
I think this issue belong in https://github.com/aspnet/dnx/ but not sure. @Eilon can you let us know where it belongs?

**Comment by Eilon** [comment]
Yeah DNX repo.

**Comment by sayedihashimi** [comment]
Thanks created https://github.com/aspnet/dnx/issues/1816, closing this.
