### ISSUE TITLE
Building returns build successful even though errors occurred.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Tooling#470]
## Steps to reproduce
- Create a project with only a `project.json`
```JSON
{
  "dependencies": {
    "Microsoft.AspNetCore.Mvc": "1.0.0-*"
  },
  "frameworks": {
    "net46": {
    }
  }
}
```
![image](https://cloud.githubusercontent.com/assets/2008729/15081516/37f09c4a-1378-11e6-8605-b6c54d29a425.png)

- Force restore
- Force build

## Expected  behavior
Build failure.

Note: dotnet fails behind the scenes due to [this](https://github.com/dotnet/cli/issues/2906) bug. VS should still report errors correctly though.

## Actual behavior
![image](https://cloud.githubusercontent.com/assets/2008729/15081490/1d55c4aa-1378-11e6-8ae7-933dcd699fbb.png)

## Environment data
```
.NET Command Line Tools (1.0.0-rc2-002678)
                                          
Product Information:                      
 Version:     1.0.0-rc2-002678            
 Commit Sha:  3b2ea9d14b                  
                                          
Runtime Environment:                      
 OS Name:     Windows                     
 OS Version:  10.0.10586                  
 OS Platform: Windows                     
 RID:         win10-x64                   
```

**Comment by sayedihashimi** [comment]
TFS: 224923
I've added this to our internal TFS, we will reply back here soon.

**Comment by balachir** [comment]
@NTaylorMullen does the Output Window provide any useful information?

**Comment by NTaylorMullen** [comment]
In the latest dotnet the bug that showcases the weirdness in VS is fixed so I can't reproduce anymore.

**Comment by balachir** [comment]
Ok, closing then as its not repro.
