### ISSUE TITLE
Kestrel - After debugging ends - focus back to default browser - not Command prompt

### ISSUE THREAD

**Issue by MarkPieszak** [aspnet/Tooling#471]
This is occurring in the latest Visual Studio 2015 (update 1), but when Continuing debugging (no more breakpoints) it pops up the Command line where Kestrel is running, instead of going back to the browser (where you would expect it to go). Just wanted to get this issue on the radar in case it hasn't been reported yet.

OS: Win 7
Visual Studio 2015 (update 1)

**Comment by sayedihashimi** [comment]
TFS: 224922
I've added this to our internal TFS, we will reply back here soon.

**Comment by MarkPieszak** [comment]
You're the best! Nice job guys :+1:

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still experiencing issues with this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
