### ISSUE TITLE
Cannot rename solution folder to other case variation

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Tooling#472]
- File => New Application (can be console or web, doesn't matter).
- Try and rename src => Src

It fails. Only way to accomplish this is to rename it to something like `Srcd` and then to `Src`

**Comment by sayedihashimi** [comment]
TFS: 224878
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
@NTaylorMullen the bug was closed by the owning team. They feel that not many users are running into this. I'll close this now. If we get a good number of replies from users running into this I will reopen and bring it back up with the owning team.

**Comment by NTaylorMullen** [comment]
:cry:
