### ISSUE TITLE
Cannot uninstall ANCM after removing IIS

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Tooling#473]
If I remove IIS and then uninstall the server bundle it fails:
```
[0ADC:0FA0][2016-05-10T11:27:32]i301: Applying execute package: AspNetCoreModule_x86, action: Uninstall, path: (null), arguments: ' ARPSYSTEMCOMPONENT="1" MSIFASTINSTALL="7"'
[0ADC:0FA0][2016-05-10T11:27:34]e000: Error 0x80070643: Failed to uninstall MSI package.
[0ADC:0FA0][2016-05-10T11:27:34]e000: Error 0x80070643: Failed to execute MSI package.
[0DD8:0C28][2016-05-10T11:27:34]e000: Error 0x80070643: Failed to configure per-machine MSI package.
[0DD8:0C28][2016-05-10T11:27:34]i319: Applied execute package: AspNetCoreModule_x86, result: 0x80070643, restart: None
```
Note the system32\inetsrv directory contains only the following files after removing IIS:
- aspnetcore.dll
- config\schema\aspnetcore_schema.xml

Full log:
[dd_DotNetCoreWinSvrHosting__20160510112723.txt](https://github.com/aspnet/Tooling/files/257869/dd_DotNetCoreWinSvrHosting__20160510112723.txt)

@pan-wang @shirhatti @glennc @joeloff

**Comment by joeloff** [comment]
That's because ANCM has a custom action. There is a SKIPUNINSTALLCA property we can pass through to the MSI when removing the bundle and finding that IIS is not present.

@pan-wang can we use this property?

**Comment by Tratcher** [comment]
But ANCM is still installed, how do I remove it?

**Comment by joeloff** [comment]
You need to run the MSI manually, e.g. msiexec /x <MSI FILE> SKIPUNINSTALLCA=1

**Comment by Tratcher** [comment]
Or re-add IIS and then uninstall the bundle again.

**Comment by joeloff** [comment]
@Tratcher yes, that would work too, but it's not ideal to ask people to install components to remove another component.

**Comment by Tratcher** [comment]
Agreed. I just verified that it worked.

Note that ANCM does not initially work after re-installing IIS, you need to repair the bundle.

**Comment by joeloff** [comment]
Actually, doing this in the bundle is going to be almost impossible. The ANCM installer's InstallExecute table for the uninstall custom action needs to be fixed to include the logic to detect if IIS is present.

Currently, the table sets the Condition for  IISScheduleUninstallCA to NOT SKIPUNINSTALLCA. This should be (NOT SKIPUNINSTALLCA) AND (IISCOREWEBENGINEINSTALLED = "#1") AND (IISW3SVCINSTALLED = "#1")

@pan-wang

**Comment by sayedihashimi** [comment]
TFS: 224920
I've added this to our internal TFS, we will reply back here soon.

**Comment by Tratcher** [comment]
@pan-wang didn't you fix this for RC2?

**Comment by joeloff** [comment]
This was fixed in ANCM and I validated the MSI changes that @pan-wang made
