### ISSUE TITLE
Project file after it's deleted from source control

### ISSUE THREAD

**Issue by MarekPokornyOva** [aspnet/Tooling#474]
Hi,
I got a question: what will happen when a team member delete a source code file, commit the change to a SC (it will be deleted there) and other team members get the change set or pull the change.

I guess the file will remain in their local project folders. And along with new VS feature "use a file stored within project folder", I guess the deleted file will be still in use by VS (and build/publish) on other team members computers.

I have no test environment wide enough to test this behavior by myself, so sorry I'm raising this question/issue.

Have a nice day
Marek

**Comment by dasMulli** [comment]
Any source control system i have used (svn, git, tfs) should delete the file. That's what it's for. If it doesn't, you should switch to another.
And if your dev setup / project has at least some unit / integration tests that would help you detect such an error quickly (just as quickly as forgetting to add a file - that happens frequently)

**Comment by MarekPokornyOva** [comment]
@dasMulli: hopefully SCs works as you described.
