### ISSUE TITLE
ANCM shutdown signal not received under debug

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Tooling#476]
ANCM will send a CTL+C to the back-end process to request a graceful shutdown, e.g. when there is an `app_offline.htm` file added. If the app was launched under the debugger then this signal is not received. This is because the debugger adds an intermediary process or orchestration purposes. That process needs to relay the shutdown signal.

Workaround: Debug shutdown using self-host.

**Comment by Tratcher** [comment]
RE: https://github.com/aspnet/IISIntegration/issues/171 - Need to disable shutdown timeout under debugger.

**Comment by sayedihashimi** [comment]
TFS: 224876
I've added this to our internal TFS, we will reply back here soon.

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed.
