### ISSUE TITLE
File => New Web Application attempts to hit nuget.org

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Tooling#477]
Based on https://github.com/aspnet/Tooling/issues/461#issuecomment-218837575

Tried this now and it restores pretty quickly. That said, there's an issue with the authoring of two of the CLI packages:
[Microsoft.NETCore.DotNetHostPolicy.nuspec.txt](https://github.com/aspnet/Tooling/files/261962/Microsoft.NETCore.DotNetHostPolicy.nuspec.txt)

Microsoft.NETCore.DotNetHostPolicy depends on Microsoft.NETCore.DotNetHostResolver version `1.0.1-rc2-002700` when the package that is produced is versioned `1.0.1-rc2-002700-00`. This causes VS to attempt to go the network:

```
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "c:\sources\WebApplication5\.vs\restore.dg"
log  : Restoring packages for c:\sources\WebApplication5\src\WebApplication5\project.json...
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethostresolver/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethostresolver/index.json 334ms
info :   GET https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethost/index.json
info :   NotFound https://api.nuget.org/v3-flatcontainer/microsoft.netcore.dotnethost/index.json 265ms
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in c:\sources\WebApplication5\src\WebApplication5\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in c:\sources\WebApplication5\src\WebApplication5\project.json...
log  : Restoring packages for tool 'Microsoft.EntityFrameworkCore.Tools' in c:\sources\WebApplication5\src\WebApplication5\project.json...
log  : Restoring packages for tool 'Microsoft.Extensions.SecretManager.Tools' in c:\sources\WebApplication5\src\WebApplication5\project.json...
log  : Restoring packages for tool 'Microsoft.VisualStudio.Web.CodeGeneration.Tools' in c:\sources\WebApplication5\src\WebApplication5\project.json...
info : Committing restore...
log  : Writing lock file to disk. Path: c:\sources\WebApplication5\src\WebApplication5\project.lock.json
log  : c:\sources\WebApplication5\src\WebApplication5\WebApplication5.xproj
log  : Restore completed in 14025ms.
NuGet Config files used:
    C:\Users\prkrishn\AppData\Roaming\NuGet\NuGet.Config
    C:\ProgramData\nuget\Config\Microsoft.VisualStudio.Offline.config
Feeds used:
    https://api.nuget.org/v3/index.json
    C:\Program Files (x86)\Microsoft SDKs\NuGetPackages\
```

**Comment by pranavkm** [comment]
cc @Eilon \ @barrytang

**Comment by barrytang** [comment]
Just chatted with Phil and project creation does work offline. He tested it as part of integrating the latest Coherence-Signed.

**Comment by barrytang** [comment]
cc @phenning

**Comment by Eilon** [comment]
Perhaps it works offline, but if you're online it pings NuGet.org anyway? That's still something we want to avoid.

**Comment by barrytang** [comment]
Yes, I agree and @phenning will follow up. I just wanted to let folks know that offline project creation does work so this issue is less severe.

**Comment by phenning** [comment]
Is there anything we can do to try to find package issues like this farther up the product build chain? Only having a test at the very last link in the chain seems to be very expensive.

**Comment by pranavkm** [comment]
I can add external packages to Coherence verification to catch these issues.

**Comment by barrytang** [comment]
TFS#223717

**Comment by pranavkm** [comment]
We've been working with the CLI team to get these packages fixed. I modified Coherence to catch these issues.

**Comment by barrytang** [comment]
This is fixed with the latest build.
