### ISSUE TITLE
Opening a project.json generates invalid xproj file

### ISSUE THREAD

**Issue by dasMulli** [aspnet/Tooling#480]
# Steps to reproduce

* Create a new project using the asp.net core web application template (individual auth, no app insights)
* Close solution.
* Delete `.xproj` and `.xproj.user` files
(This state matches a web application created without VS tooling)

* File > Open > Project / Solution > select the `project.json` file

# Expected behavior

A valid `.xproj` file should be generated and opened successfully.

# Actional behavior

An `.xproj` file is generated that fails to load logging: 
```
The imported project "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Web.targets" was not found. Confirm that the path in the <Import> declaration is correct, and that the file exists on disk.  C:\Users\Martin\Documents\Visual Studio 2015\Projects\WebApplication1\src\WebApplication1\WebApplication1.xproj
```

The xproj file contents an invalid reference:
```xml
<Import Project="$(VSToolsPath)\DotNet\Microsoft.DotNet.Web.targets" Condition="'$(VSToolsPath)' != ''" />
```

Manually changing the path to `$(VSToolsPath)\DotNet.Web\Microsoft.DotNet.Web.targets` fixes this problem.

# Environment

Windows 10 x64
Visual Studio 2015 Update 2
(VM Created from Azure VS2015 enterprise on Windows 10 enterprise template)
.NET Core Tooling Preview 1 for Visual Studio 2015

**Comment by sayedihashimi** [comment]
Thanks, I think @BillHiebert is looking into it.
TFSID: 222330

**Comment by conterio** [comment]
this isnt a bug but Microsoft.AspNetCore.Identity": "1.0.0-rc2-final doesn't have .GetUserId() defined, and i cant use     Microsoft.AspNet.Identity": "3.0.0-rc1-final cause im now upgraded to RC2, when will this functionailty be added?  also where should i be posting this?

**Comment by sisovin045** [comment]
I have used @UserManager.GetUserId(User).

**Comment by gsumankumar** [comment]
i too facing the same reference issue, but before that when try to install .Net core 1.0 VS 2015 Tooling Preview 2, i got installation error with log. so i want know do i need to upgrade OS win 8.1 to 10 ?

**Comment by jjintelity** [comment]
I had to copy **Microsoft.DotNet.Web.targets**, running as ADMIN. from **DotNet.Web** to **DotNet** directory.

**Comment by MelbourneDeveloper** [comment]
I'm getting this same issue on one computer. On one computer it works fine, and on the other the file is completely missing. I tried the workaround above but the Microsoft.DotNet.Web.targets doesn't exist in DotNet.Web. When are these tools going to be stable?

**Comment by dasMulli** [comment]
@sayedihashimi, @BillHiebert: This issue no longer reproduces with the latest tooling. at least on my machine. If the mentioned TFS item is indeed already resolved, i suggest closing this issue.

**Comment by gimlichael** [comment]
I just intalled Visuatl Studio 2017 and was trying to open my Nebula project. Unfortunately, it did not go well.

![2016-11-24_2113](https://cloud.githubusercontent.com/assets/8550919/20609296/ff3a9ee8-b28a-11e6-84cd-51b324bc41c2.png)
