### ISSUE TITLE
Variables can't be debugged in Razor

### ISSUE THREAD

**Issue by javiercn** [aspnet/Tooling#482]

**Comment by javiercn** [comment]
Given an instruction pointer in a debugging session and a local variable declared in razor as below.

![image](https://cloud.githubusercontent.com/assets/6995051/15305232/b1610244-1b76-11e6-80b9-840796bb1945.png)

The debugger fails to find it

![image](https://cloud.githubusercontent.com/assets/6995051/15305218/91ab7092-1b76-11e6-8d6c-caf15af1d00d.png)

**Comment by sayedihashimi** [comment]
TFS: 224868
I've added this to our internal TFS, we will reply back here soon.

**Comment by mlorbetske** [comment]
Per the linked TFS item, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site.
