### ISSUE TITLE
No IntelliSense for TagHelpers in RC2 Preview1 Tooling

### ISSUE THREAD

**Issue by cwe1ss** [aspnet/Tooling#484]
Hi! I installed the latest RC2-Preview1 Tooling for Visual Studio 2015 and created a new Web Application. If I open a cshtml-file I still don't get IntelliSense for TagHelpers. However, `dotnet restore` and `dotnet run` works.

We also tried it on a second computer in our office and it also didn't work.

Any suggestions? I had plenty of RC2 daily build stuff installed so I definitely don't have a clean machine.

**Comment by NTaylorMullen** [comment]
@cwe1ss Do you still not get IntelliSense after building your project? That's now a pre-requisite for TagHelper IntelliSense.

Also, if you open up the Package Manager Console in VS and type `dotnet --info` what does it output?

**Comment by cwe1ss** [comment]
My dotnet version is "1.0.0-preview1-002702". 

I was able to get IntelliSense for a File->New web application after compiling it. However, it doesn't yet work for our big web app which we've upgraded. :(

Some more info about the app:

* We have quite a few custom tag helpers
* I get IntelliSense for Razor C# syntax (like `@Model.*`)
* I don't get IntelliSense for stuff like `<input asp-*`
* Colors of tag helpers do not change so it seems like something doesn't kick in
* At runtime, everything works well
* we use a feature folder convention with a custom `IViewLocationExpander`

Our custom expander:
```csharp
public class FeatureFolderViewLocationExpander : IViewLocationExpander
{
    public void PopulateValues(ViewLocationExpanderContext context)
    {
        /* no-op */
    }

    public IEnumerable<string> ExpandViewLocations(ViewLocationExpanderContext context, IEnumerable<string> viewLocations)
    {
        // {0} - Action Name
        // {1} - Controller Name
        // {2} - Area name

        object area;
        if (context.ActionContext.RouteData.Values.TryGetValue("area", out area))
        {
            yield return "/Areas/{2}/{1}/{0}.cshtml";
            yield return "/Areas/{2}/Shared/{0}.cshtml";
            yield return "/Areas/Shared/{0}.cshtml";
        }
        else
        {
            yield return "/Features/{1}/{0}.cshtml";
            yield return "/Features/Shared/{0}.cshtml";
            yield return "/Views/{1}/{0}.cshtml";
            yield return "/Views/Shared/{0}.cshtml";
        }
    }
}
```

This is part of our `Areas\_ViewImports.cshtml`:
```
@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers
@addTagHelper *, C3.AdminWeb.Website
```

**Comment by NTaylorMullen** [comment]
@cwe1ss Ensure in the project you want your `TagHelper` IntelliSense that you have the following in your `project.json`:

- In the `"tools":` section you should have an entry for `Microsoft.AspNetCore.Razor.Tools`, ex:
```JSON
"Microsoft.AspNetCore.Razor.Tools": {
  "version": "1.0.0-preview1-final",
  "imports": "portable-net45+win8+dnxcore50"
},
```
- In the global `"dependencies"` section you have a build time entry for `Microsoft.AspNetCore.Razor.Tools`, ex:
```JSON
"Microsoft.AspNetCore.Razor.Tools": {
  "version": "1.0.0-preview1-final",
  "type": "build"
},
```

- Your application has a `Microsoft.NETCore.App` reference for its `netcoreapp1.0` TFM:
```JSON
"Microsoft.NETCore.App": {
  "version": "1.0.0-rc2-3002702",
  "type": "platform"
},
```

_Note: your custom expander will not be understood by tooling (it shouldn't have in rc1 either) but unless I'm forgetting something I don't believe that'll impact your Razor IntelliSense._

**Comment by cwe1ss** [comment]
that fixed it. sorry for taking up your time - I completely missed that! thank you very much!

**Comment by NTaylorMullen** [comment]
@cwe1ss glad you resolved it :smile:

**Comment by Jmales** [comment]
This did not solve it for me. I still can't have IntelliSense for Tag Helpers.

**Comment by hardCTE** [comment]
@Jmales 
Maybe you should turn off your outdated ReSharper.... (It was my problem)

**Comment by allenz0810** [comment]
@NTaylorMullen  
I have set what all the things you mention and still not working. Also i don't have ReSharper in my vs 2015.

**Comment by NTaylorMullen** [comment]
If you post repro projects I can take a look.

**Comment by wstaelens** [comment]
https://github.com/aspnet/Tooling/issues/846
https://github.com/aspnet/Tooling/issues/135
https://github.com/aspnet/Tooling/issues/484

**Comment by haugan** [comment]
Awesome, but how can I configure this in VS2017 and the new *.csproj format?

**Comment by NTaylorMullen** [comment]
@haugan TagHelper IntelliSense isn't in the box yet for VS2017. See https://github.com/aspnet/Tooling/issues/920#issuecomment-278732790
