### ISSUE TITLE
RC2: Shared projects in VS2015

### ISSUE THREAD

**Issue by antonGritsenko** [aspnet/Tooling#488]
Hi all

Is there any way to add Shared Project (Visual Studio 2015) to ASP.NET Core project using Preview Tools?
I've tried add line to *.xproj file:
`<Import Project="..\SharedCode\SharedCode.projitems" Label="Shared" />`
but no success.

**Comment by sayedihashimi** [comment]
We don't have support for shared projects at this time. We are going to be looking at that later on, we don't have any specific plans yet. For the time being you can edit the `project.json` to add external files to the project.

**Comment by dallasclement** [comment]
Sure would be nice if the shared project support was there.  This is a very useful capability for solutions with large number of projects that need to share code with an ASP.NET Core project.
