### ISSUE TITLE
RC2 - VS2015 Error when creating a new asp.net core app

### ISSUE THREAD

**Issue by alaatm** [aspnet/Tooling#489]
I've just installed RC2 tools for VS2015. When I try to create a new .net core web/console or library, I get the following error:

![image](https://cloud.githubusercontent.com/assets/2095803/15322334/d2f02efc-1c44-11e6-87cd-8db063eb23aa.png)

If I try to build the solution for a console app, I get the following error:

Failed to initialize CoreCLR, HRESULT: 0x80131500
 And it points to: C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets (line 241) which is below:

`<Dnx RuntimeExe="$(SDKToolingExe)" Condition="'$(_DesignTimeHostBuild)' != 'true'" ProjectFolder="$(MSBuildProjectDirectory)" Arguments="$(_BuildArguments)" />`

If I try and run I get the following error:

![image](https://cloud.githubusercontent.com/assets/2095803/15322381/26c5d644-1c45-11e6-9c04-813b771654db.png)

---

I previously had several installation on .net CLI. I think I removed all old stuff through add/remove programs but definitely didn't have a clean machine.

Any idea how I can fix this? I cant use any of the new RC2 project types.

**Comment by sayedihashimi** [comment]
TFS: 223020
I've added this to our internal TFS, we will reply back here soon.

**Comment by dldbu2** [comment]
I have same problem in Visual Studio 2015. When I try from cmd console `dotnet restore` and then `dotnet run` application is ok and wotking. I try to open project in Visual Studio I get Failed to initialize CoreCLR, HRESULT: 0x80131500 !

**Comment by alaatm** [comment]
Here is a workaround that worked for me:
1. Type in the full path to the VS setup application and pass the following command line switches: `/uninstall /force` **Example**: `D:\vs_ultimate.exe /uninstall /force`.
2. Follow prompts from VS installer.
3. Use [VisualStudioUninstaller](https://github.com/Microsoft/VisualStudioUninstaller) to completely remove all VS components. Use the [official release](https://github.com/Microsoft/VisualStudioUninstaller/releases) to uninstall/remove VS leftovers.
4. Now you can install VS then install .net Core then latest nuget package and everything should work as expected.

_**Note**_: If you're using Azure tools for VS, you should manually remove all of them from the Add/Remove programs then reinstall them once all steps above are finished. This may also apply to any packages/components installed through the MS Web Platform Installer.

**Comment by marspd** [comment]
Has anyone found another solution to this problem other than uninstalling VS and all it's components?

**Comment by ThulaseeShan** [comment]
alas, I finally found it. I had Telerik JustMock. When I uninstalled it, everything worked just fine. I don't know why there is a conflict. But things are working well after uninstalling JustMock.

**Comment by rubensmussicury** [comment]
I cant ASP.Net Core Project. Getting following error: 

![core](https://cloud.githubusercontent.com/assets/3310836/15699762/e6b59eec-27a5-11e6-8c56-24a6a5e1208f.PNG)

**Comment by jonlk** [comment]
I get the same error as **rubensmussicury**
![error_rc2](https://cloud.githubusercontent.com/assets/7890387/15872386/31f607c2-2cc7-11e6-8582-b77aaf5b3a32.png)

**Comment by balachir** [comment]
@rubensmussicury , @jonlk : we had other reports of similar issues -- see [here](https://github.com/aspnet/Tooling/issues/515) and [here](https://github.com/aspnet/Home/issues/1455#issuecomment-229146688). This was due to an issue in Visual Studio 2015 Update 3 setup that sometimes caused stale entries in the devenv.exe.config file.

Can you try the following workaround:
 1. Close Visual Studio 
 2. Delete the C:\Users<user>\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config file.
 3. Run the Developer Command Prompt for VS2015 as the Administrator, and execute the devenv /setup command.

**Comment by amicalrahul** [comment]
I am also facing the same issue. I have installed VS2015 update 2.
I tried to follow the above steps but strangely the below directory is empty
C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet

Even there is no dnx folder at below path
*:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\DNX *

I've run RC1 installation successfully and even repaired it many time. But somehow there is nothing installed in the dotnet folder at C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet path

@bernharde @olegburov or anyone - Can you please suggest something else to solve this problem.

I even repaired 
VS2015 installation. 
deleted dev.exe.config file
ran devenv /setup in vs2015 command prompt (as administrator)

I guess the root problem is nothing is installed in dotnet folder in programfiles and no dnx folder is created.

Need help urgently.

**Comment by rubensmussicury** [comment]
@balachir thank you for your reply. Indeed, I was getting this issue after VS15 Update 2, not 3. Anyway, after recently installed Update 3, it has fixed. Have no idea what was causing it but I suspicious it started right after I've uninstalled some .NET Frameworks from Control Panel.

**Comment by mlorbetske** [comment]
Since there hasn't been any activity here in nearly a year & it sounds like moving to Visual Studio 2015 Update 3 helped, closing this. If anyone is still running in to this, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site
