### ISSUE TITLE
Intellisense not working for lambdas in some scenarios

### ISSUE THREAD

**Issue by javiercn** [aspnet/Tooling#494]
Trying to use some Html helpers like
![image](https://cloud.githubusercontent.com/assets/6995051/15341517/060b6870-1c44-11e6-8241-f33125af79c4.png)

Intellisense is not properly displayed. It doesn't happen with all the HTML helpers, only with those for which there is no overload taking just the lambda (TextBox, Password, etc) work fine.

**Comment by sayedihashimi** [comment]
TFS: 223009
I've added this to our internal TFS, we will reply back here soon.

**Comment by mlorbetske** [comment]
cc: @NTaylorMullen

**Comment by NTaylorMullen** [comment]
Roslyn issue covered [here](https://github.com/aspnet/Tooling/issues/494).
