### ISSUE TITLE
RC2: bug with buildOptions->define

### ISSUE THREAD

**Issue by antonGritsenko** [aspnet/Tooling#495]
Hi

Visual Studio 2015 and RC2 installed.
Set the Conditional Complication Symbols in project properties -> Build will generate wrong project.json:

```
 "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true,
    "compile": {
      "exclude": [
        "wwwroot"
      ]
    },
    "define": [ "DEBUG" ], <- _that was added manually_
    "defines": [ "DEBUG", "aaa" ] <- _that was generated by Visual Studio_
  },
```

**Comment by sayedihashimi** [comment]
TFS: 223008
I've added this to our internal TFS, we will reply back here soon.

**Comment by mlorbetske** [comment]
From the linked TFS item, this issue has been marked as fixed. Please open an issue on the [developer community](https://developercommunity.visualstudio.com/) site if you're still experiencing problems with this.
