### ISSUE TITLE
Referencing projects that have a different name than their namespace/assembly name results in unsolvable references in RC2.

### ISSUE THREAD

**Issue by janpieterz** [aspnet/Tooling#496]
Example project showcasing:

https://github.com/janpieterz/WeirdReferencingError

Somehow it is unable to resolve the references, I've been unable to find a workaround besides renaming the projects and re-adding references all around (quite a cumbersome task with 51 projects).

**Comment by janpieterz** [comment]
I just commited the fix, so to see the error use the commit before the 'Showcasing fix' commit.
Basically the assembly name needs to match the project name, otherwise it errors.

**Comment by sayedihashimi** [comment]
TFS: 223007
I've added this to our internal TFS, we will reply back here soon.

**Comment by abpiskunov** [comment]
This issue is resolved and should be available in the next release.
