### ISSUE TITLE
Start Page hasn't been updated to ASP.NET Core.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#497]
![image](https://cloud.githubusercontent.com/assets/3386797/15351640/9c78ae22-1cb6-11e6-8307-dc2ffe0a601c.png)

**Comment by Bartmax** [comment]
The link to Learn about new features ... neither.

https://msdn.microsoft.com/en-us/library/dd831853(v=vs.140).aspx

**Comment by sayedihashimi** [comment]
@balachir didn't you bring this up a bit ago?

TFS: 222999
I've added this to our internal TFS, we will reply back here soon.

**Comment by balachir** [comment]
Yes, I have TFS: 220313 open for the same issue. I resolved 222999 as a dupe.

**Comment by mlorbetske** [comment]
From the linked TFS issue, this has been marked as fixed. If you're still experiencing issues with this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
