### ISSUE TITLE
RC2: unable to create empty view

### ISSUE THREAD

**Issue by antonGritsenko** [aspnet/Tooling#499]
"Add View" UI (right-click, Add -> View... ) doesn't have option to create empty view or view without model.

**Comment by ninety7** [comment]
As a workaround, you can right-click, Add -> New Item... and then select either a View, layout, etc

**Comment by sayedihashimi** [comment]
TFS: 224859
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
This was fixed a while back, closing.
