### ISSUE TITLE
nuget restore of an another application in an asp.net 5 application

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#5]
This is hard to repro.
I'm using vs 2015 for both asp.net 4 and 5, opening more instances and/or switching from a project to another using the same instance.
Twice, while working to an asp.net 5 project, at the moment of the rebuild I seen appear the nuget 2.8 dialog of the restore in progress: at the end of this, I found in the solution folder of the asp.net 5 a package folder with inside the packages of another asp.net 4 app I'm working.

**Comment by davidfowl** [comment]
That's not a bug, it's the current nuget restore behavior.

**Comment by PradeepKadubandi** [comment]
Hmm... this seems to be a VS bug. 

When we have a packages.config for your asp.net 5 projects, nuget is trying to restore packages to the solution level packages folder.

Note that the packages.config file, 'packages' folder and the packages in there are not really used by either VS in anyway (you don't see them in references) nor by runtime when you run the application.

It's just a side effect of NuGet detecting that file and trying to do restore.

Deleting that file from your project is a workaround for you till we fix the issue.

**Comment by lucamorelli** [comment]
![untitled](https://cloud.githubusercontent.com/assets/127777/6510132/56589878-c364-11e4-8c1a-903dfb7f6ba8.png)

this is the solution folder of a very simple  asp.net 5 application.

![untitled](https://cloud.githubusercontent.com/assets/127777/6510159/82bb4b68-c364-11e4-89fc-8c0527da921b.png)

this is what I found inside: packages of another asp.net 4 application

**Comment by davidfowl** [comment]
Do you have an ASP.NET 4.x application in the same solution? Like I said before, that is the current NuGet behavior.

**Comment by lucamorelli** [comment]
No, this solution contains just an asp.net 5 web starter app. May be I worked with that project before open this, this happend in two asp.net 5 test projects

**Comment by davidfowl** [comment]
Is there a packages.config?

**Comment by lucamorelli** [comment]
no
![untitled](https://cloud.githubusercontent.com/assets/127777/6510375/fcf1273a-c365-11e4-981c-79f0d4748b5b.png)

![untitled](https://cloud.githubusercontent.com/assets/127777/6510384/088fe5cc-c366-11e4-8562-c534a00e4065.png)

this the content of the subdirectories

**Comment by lucamorelli** [comment]
this is really strange: I seen happens twice. One times happened  after I changed the order of the directories in the sources variable in the global json and triggered a restore using project.json editor

**Comment by davidfowl** [comment]
Sounds like a nuget bug. The existing package restore only happens with old stuff. You might want to file a bug on the nuget repository.

**Comment by lucamorelli** [comment]
have I to file.in the codeplex site?

**Comment by Eilon** [comment]
NuGet bugs go here: https://nuget.codeplex.com/workitem/list/basic

**Comment by lucamorelli** [comment]
done, thanks
