### ISSUE TITLE
Hard to choose target runtime for IDE-integrated test runner

### ISSUE THREAD

**Issue by mgravell** [aspnet/Tooling#50]
~~At the moment, the only way I've found to change the target runtime for the test runner is via project properties.~~ Edit: scratch that - that doesn't actually seem to work; _nothing_ seems to work!  I have coreclr as my default, and both my test project and library project set to use a specific runtime: coreclr - and the IDE test runner is still using clr

Compared to how easy it is to play or run the console test tool (awesome drop down, thanks) and view code (top left of edit window, also awesome) for different runtimes, this feels awkward.

I don't know how much is possible, but one thing in particular that I notice: if you run a test from the editor, it still uses the project properties runtime, not the top-left-picker runtime.

**Comment by sayedihashimi** [comment]
@vijayrkn thoughts?

FYI @vijayrkn is out of office right now so it may take him some time to reply back.

**Comment by mgravell** [comment]
Not sure how or why I closed this - but this is still a really awkward thing to do;  @vijayrkn - did you ever get a chance to look at this?

**Comment by vijayrkn** [comment]
Are you using the latest preview2 tooling? Test runner uses the first target framework in project.json. 
For e.g: this project.json has both frameworks, VS will use netcoreapp1.0 in this case. If you change the order it will use the net451.
https://github.com/aspnet/Mvc/blob/dev/test/Microsoft.AspNetCore.Mvc.Abstractions.Test/project.json

**Comment by mgravell** [comment]
Yes I'm using all the current tooling, but ... yikes, that's not intuitive
or convenient :/

**Comment by NickCraver** [comment]
Are there planned improvements to this?

**Comment by vijayrkn** [comment]
There is a work item to support running tests for all frameworks in project.json so that switching frameworks wont be required. This needs the trait support to be implemented first. (https://github.com/dotnet/cli/issues/2252)

**Comment by mlorbetske** [comment]
TFS Bug#241358

**Comment by mlorbetske** [comment]
This is now being tracked on the [Microsoft/vstest](https://github.com/Microsoft/vstest) repo as https://github.com/Microsoft/vstest/issues/624 and https://github.com/Microsoft/vstest/issues/298
