### ISSUE TITLE
Trying to load a single .xproj project in VS is loading the entire solution

### ISSUE THREAD

**Issue by kichalla** [aspnet/Tooling#500]
**Repro**
- clone `Antiforgery` repo
- cd to the `src\Microsoft.AspNetCore.Antiforgery` folder and open `Microsoft.AspNetCore.Antiforgery.xproj`
- You should see the entire solution open

You can also try this with `Entropy` repo. Since it has many samples, I wanted to load a single project so as to avoid restoring the other projects which i don't care, but here also it loads the entire solution.

**Comment by sayedihashimi** [comment]
@kichalla whenever you open a project today it loads all the dependent projects. We have a feature to improve this but we don't have any specific timeline for this.
