### ISSUE TITLE
Invalid Child Element aspnetcore in web.config in RC2 final

### ISSUE THREAD

**Issue by mikes-gh** [aspnet/Tooling#501]
_From @mikes-gh on May 19, 2016 8:11_

I know this is cosmetic ....

![schema issue](https://cloud.githubusercontent.com/assets/16208742/15386796/97d54c18-1da1-11e6-8756-ae70ea2acb17.png)

_Copied from original issue: aspnet/IISIntegration#181_

**Comment by mikes-gh** [comment]
_From @davidfowl on May 19, 2016 8:12_

This is pretty annoying. It's a tooling issue though.
/cc @BillHiebert @sayedihashimi

**Comment by mikes-gh** [comment]
I did think about posting it there but that repo doesnt get much :heart: .  Do you want me to move it?

**Comment by mikes-gh** [comment]
_From @davidfowl on May 19, 2016 8:32_

Yap

**Comment by BillHiebert** [comment]
This is fixed in the next update of Visual studio 2015 (Update3). Required a change to the web.config schema which ships with VS.

**Comment by nopara73** [comment]
I have the same warning, even though Visual Sudio 2015 Update 3 is installed.
