### ISSUE TITLE
Intellisense not working with Visual Studio 2015

### ISSUE THREAD

**Issue by derpcoder** [aspnet/Tooling#504]
After installing the preview 1 tools, the intellisense its not working for me or coworker, it does highlights tag helpers but, every function, property, section, injection or model declaration gives the "Cannot resolver symbol 'x'".

Attached is a screenshot
![untitled](https://cloud.githubusercontent.com/assets/225781/15397979/002965e8-1db0-11e6-8d93-eb51c4dce921.png)

**Comment by ToddGrun** [comment]
@derpcoder : Are you able to share your project so I can see if I can reproduce the issue?

**Comment by derpcoder** [comment]
@ToddGrun its not just one project, even if I create a new project using one of the templates, it doesn't work

**Comment by ToddGrun** [comment]
Interesting. Does the new project tag helper functionality light up after building the project the first time?

**Comment by derpcoder** [comment]
Yes they do light up after the first build, but even RenderBody sayscan't be found.

**Comment by derpcoder** [comment]
I just discovered that if I "Go to definition" on the razor file, on any of the "unsolved" symbols (like "Layout" or "RenderBody") it takes me to the RazorPage type, don't know if that helps figuring out anything

**Comment by derpcoder** [comment]
I may have found the reason ...

After suspending ReSharper, the Intellisense started working again with the Razor files ... Seems ReSharper is broken as of now for these kind of files.
