### ISSUE TITLE
RC2 File->New adds wrong GC section

### ISSUE THREAD

**Issue by benaadams** [aspnet/Tooling#505]
The templates add
```json
"runtimeOptions": {
    "gcServer": true
}
```
However they should be adding
```json
{
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  }
}
```
As per all the aspnet samples and tests; the dotnet cli docs, and what happens when you run etc

See also https://github.com/dotnet/coreclr/issues/5117

**Comment by DamianEdwards** [comment]
I don't think you have to set both do you? Only one of those should have any effect.

**Comment by benaadams** [comment]
Sorry edited. Yeah the one in `File->New` which is `gcServer` has no effect.

All the aspnet repos already seem to use `System.GC.Server`

**Comment by benaadams** [comment]
@DamianEdwards spent ages trying to work out why my plaintext throughput was terrible

**Comment by sayedihashimi** [comment]
I have created a corresponding issue in the templates repo https://github.com/aspnet/Templates/issues/575 to track getting the templates updated.

**Comment by benaadams** [comment]
Docs, project.json announcement, schema, template

**Comment by sayedihashimi** [comment]
Closing in favor of https://github.com/aspnet/Templates/issues/575
