### ISSUE TITLE
Bower tooling not working in RC2

### ISSUE THREAD

**Issue by Se3ker** [aspnet/Tooling#506]
Manage Bower Packages screen does not search correctly and cannot find packages

![bower_search](https://cloud.githubusercontent.com/assets/2376327/15429512/8d2b1f08-1ea1-11e6-8f69-0da7766154d8.png)

Quick Install Package search works, but install does not

![bower_quick](https://cloud.githubusercontent.com/assets/2376327/15429654/409f93ac-1ea2-11e6-8c84-2d52ac73c085.png)

**Error:** 
'bower' is not recognized as an internal or external command,
operable program or batch file.

**Comment by Se3ker** [comment]
Tools are setup to default
![webtools](https://cloud.githubusercontent.com/assets/2376327/15448016/50fa9686-1f54-11e6-9462-6935b07e8c3b.png)

**Comment by sayedihashimi** [comment]
TFS: 224857
I've added this to our internal TFS, we will reply back here soon.

**Comment by jodavis** [comment]
@Se3ker The list of packages in the Manage Bower Packages UI is currently limited to the top 1000 Bower packages. We're working on improving that for a future release.

You should be able to install the package you want by typing it into bower.json. As soon as you save that file, a 'bower install' is executed to restore all packages for the project.

**Comment by jodavis** [comment]
Also, the issue with the "Quick Install Package" dialog should be fixed in a newer version of that extension.

**Comment by mlorbetske** [comment]
From the linked TFS issue, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
