### ISSUE TITLE
BrowserLink not working in RC2

### ISSUE THREAD

**Issue by Se3ker** [aspnet/Tooling#507]
BrowserLink connection appears correct, but inspecting DOM elements does not open files at all

![browser_link](https://cloud.githubusercontent.com/assets/2376327/15429822/e9ef90ec-1ea2-11e6-99fc-93979ed72247.png)

**Comment by sayedihashimi** [comment]
TFS: 224856
I've added this to our internal TFS, we will reply back here soon.

**Comment by jodavis** [comment]
Browser Link should work in all released versions of ASP.NET Core. When working in VS 2017, include the Microsoft.VisualStudio.Web.BrowserLink package (not Microsoft.VisualStudio.Web.BrowserLink.Loader), and call `app.UseBrowserLink()` in Startup.cs.

Also, make sure Browser Link is enabled in VS. The easiest way to do that is in the Browser Link Dashboard. If it is displaying web projects, then Browser Link is enabled.
