### ISSUE TITLE
NuGet Tool not showing updates RC2

### ISSUE THREAD

**Issue by Se3ker** [aspnet/Tooling#509]
NuGet updates tab appears to not work

Trying updates tab
![nuget_update](https://cloud.githubusercontent.com/assets/2376327/15430170/6ccdfaac-1ea4-11e6-9e18-38a05589b806.png)

Manually checking and finding available update
![nuget_update_available](https://cloud.githubusercontent.com/assets/2376327/15430185/7c723716-1ea4-11e6-827b-39acaa4b8ea6.png)

**Comment by sayedihashimi** [comment]
TFS: 224854
I've added this to our internal TFS, we will reply back here soon.

**Comment by mlorbetske** [comment]
From the linked TFS issue, it appears that this has been marked as fixed. If you're still experiencing issues with this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
