### ISSUE TITLE
A generated *.xproj when importing a project.json is different from File->New Project

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Tooling#51]
When moving from `*.kproj` to `*.xproj`, I cleared my solution, deleted the `*.kproj` and opened the existing `project.json` to add them back. These generated files are different from the ones generated by File->New Project. For example, the root node has `ToolsVersion="__ToolsVersion__"` instead of `ToolsVersion="14.0"`, the `RootNamespace` is missing as well as the `OutputPath` property.

aspnet/Announcements#1

**Comment by BillHiebert** [comment]
Thanks for reporting. I've opened a bug to get this fixed

**Comment by sayedihashimi** [comment]
Assigning to @BillHiebert since he will be working on this.

**Comment by BillHiebert** [comment]
This has been fixed
