### ISSUE TITLE
ASP.NET Core Web Application template not running properly

### ISSUE THREAD

**Issue by Eilon** [aspnet/Tooling#513]
Copied from https://github.com/aspnet/Mvc/issues/4695
By @gokalpi

------------------
I installed Visual Studio 2015 CE and .NET Core 1.0.0 RC2 - VS 2015 Tooling Preview 1 and created a new web project using ASP.NET Core Web Application template. When I want to run it in Visual Studio 2015, it waits for a time and HTTP Error 502.3 - Bad Gateway error comes up.

When I run the application (dotnet run) in Command Prompt, it is working properly.

dotnet --info output is as follows:

.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64

**Comment by Eilon** [comment]
From @javiercn:

------------
@gokalpi What happens if you press F5 a few seconds later, does the page come up?

**Comment by gokalpi** [comment]
On the output window "Microsoft.AspNetCore.Mvc.ViewFeatures.Internal.ViewResultExecutor: Information: Executing ViewResult, running view at path /Views/Home/Index.cshtml." log appears, but nothing happens after that.

**Comment by barrytang** [comment]
TFS#224248

**Comment by gokalpi** [comment]
I have found root cause of the problem. When I commented app.UseBrowserLink(); line in startup.cs, it started working.

There is something wrong with BrowserLink in ASP.NET Core RC2.

**Comment by Eilon** [comment]
@gokalpi it's probably this issue: https://github.com/aspnet/Mvc/issues/4706

The workaround is indeed to comment out the line that enables BrowserLink.

**Comment by barrytang** [comment]
@jodavis fixed this now.
