### ISSUE TITLE
ASP.NET Core RC2 Project Creation Failed 

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/Tooling#515]
![image](https://cloud.githubusercontent.com/assets/1798510/15449518/708344f4-1f80-11e6-91e2-f49741c96b5b.png)

**Comment by davidfowl** [comment]
Did you try re-installing the tooling?

**Comment by MaherJendoubi** [comment]
I did it many times

**Comment by MaherJendoubi** [comment]
@davidfowl I'm using this version of nuget 
![image](https://cloud.githubusercontent.com/assets/1798510/15449542/dbf424f6-1f80-11e6-844e-e0e8ddd6eda5.png)

**Comment by davidfowl** [comment]
The nuget version has nothing to do with the project creation failure (then again, I don't know what that error translates to). I assume you downloaded the new tooling from http://dot.net

**Comment by MaherJendoubi** [comment]
I find a translation 
![image](https://cloud.githubusercontent.com/assets/1798510/15449581/f08ae3ea-1f81-11e6-9755-7052ae7e388b.png)
Yes, I downloaded the new tooling from http://dot.net

**Comment by joeloff** [comment]
@MaherJendoubi Could you try launching VS from a developer command prompt using devenv /log. Then, navigate through the wizard until you hit the error, then close VS and exit

The VS log files might shed more light. We've seen a few occurrences of this, but we haven't been able to identify whether it's one of the wizard DLLs that failed to load or an actual file from the templates that's missing.

The log file should get dropped under %appdata%\Microsoft\VisualStudio\14.0\ActivityLog.xml.

Could you please attach the log file here?

**Comment by MaherJendoubi** [comment]
[](url)

[ActivityLog.zip](https://github.com/aspnet/Tooling/files/278070/ActivityLog.zip)

**Comment by MaherJendoubi** [comment]
I delete ActivityLog.xml and I do what you request @joeloff and I upload again to have a clean log file focused on this issue 
[ActivityLog.zip](https://github.com/aspnet/Tooling/files/278078/ActivityLog.zip)

**Comment by MaherJendoubi** [comment]
I notice a time lag in the log file actually now it 21:07 but on the log file time is 19:07

**Comment by MaherJendoubi** [comment]
I did another log 
[ActivityLog.zip](https://github.com/aspnet/Tooling/files/278093/ActivityLog.zip)

**Comment by joeloff** [comment]
The logs are not revealing anything, except some string load failures.

However, I can induce the error on my VM by deleting the project wizard DLL (C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet\ProjectSystem\Microsoft.VisualStudio.ProjectSystem.DotNet.Wizard.dll)

That DLL is loaded after you select the actual template, e.g. Web API. Can you confirm whether this DLL is present on your machine?

**Comment by joeloff** [comment]
@MaherJendoubi I think the best way to get information from the system would be to get a procmon trace to see what files VS are trying to load. I've got a suspicion, but will need some hard evidence to confirm this.

1. If you don't have procmon, you can download it from https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx
2. Launch procmon and disable capturing events (Ctrl+E) and clear the captured events (Ctrl+X)
3. Start Visual Studio and open the New Project dialog
4. Start capturing events in procmon
5. Switch back to VS, create the template and wait for the error dialog
6. Disable capturing events (Ctrl+E)
7. Select the filtering option in Procmon and filter all the events where Process Name is devenv.exe
8. Save the filtered trace and attach to the issue please.

**Comment by MaherJendoubi** [comment]
That DLL does exist @joeloff 
![wizard](https://cloud.githubusercontent.com/assets/1798510/15484049/40489b2c-2138-11e6-9186-ad19fff4a57b.png)

**Comment by joeloff** [comment]
Ok, can you try the procmon trace I suggested? Getting a filename is going to be critical to solving this issue

**Comment by MaherJendoubi** [comment]
[Logfile.zip](https://github.com/aspnet/Tooling/files/278254/Logfile.zip)

**Comment by MaherJendoubi** [comment]
I have to delete the trace file it contains confidential IP addresses.

**Comment by MaherJendoubi** [comment]
I don't know if you get it yet or not, otherwise give me please your email I will send you the trace file.

**Comment by joeloff** [comment]
I did get the file. It's fine to delete it. I'll destroy my copy once I have the filename identified. Was hoping the filter for devenv would exclude any confidential information.

**Comment by joeloff** [comment]
Looks like my suspicion was correct. It's trying to find the dotnet wizard. I see quite a few entries like the one below as VS is searching for the file, e.g. VS typically goes through a number of locations, including all the installed extensions, so it should have found the file under Extensions\Microsoft\DotNet\ProjectSystem. Which leads me to believe that the package wasn't loaded by Visual Studio at all.

1:49:50.4618976 PM	devenv.exe	9672	CreateFile	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\CommonExtensions\Microsoft\Roslyn\VisualStudio Interactive Components\Microsoft.VisualStudio.ProjectSystem.DotNet.Wizard.dll	NAME NOT FOUND	Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a

**Comment by joeloff** [comment]
@MaherJendoubi Thank you for getting this information to me. I'm busy discussing possible solutions with the team. I'll keep you posted as soon as I have something.

**Comment by MaherJendoubi** [comment]
@joeloff I can see it here 
![bug](https://cloud.githubusercontent.com/assets/1798510/15485420/67a65f5e-213f-11e6-9f99-6d0ade38aaaa.png)

**Comment by MaherJendoubi** [comment]
@joeloff You're welcome! I'm ready for any informative support. Thank you very much! I really appreciate it.

**Comment by joeloff** [comment]
I've been talking to the VS IDE team and they asked for some additional informaiton. We want to try and get confirmation to see whether the pkgdef is actually being read. Could you try the following.

1. Open a VS developer prompt (as admin)
2. In procmon, configure a filter for 

- Path is C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet\ProjectSystem\Microsoft.VisualStudio.ProjectSystem.DotNet.pkgdef
- Process Name is devenv.exe

4. Start procmon 
4. Run devenv /setup
5. Wait for it to complete and stop the trace (Ctrl+E)

Let me know if you see any entries showing that the file was accessed. You should see something like the line below, but if it was successful, there's likely going to be a bunch of references to the .pkgdef file.

3:19:44.6927928 PM	devenv.exe	2624	CreateFile	C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\DotNet\ProjectSystem\Microsoft.VisualStudio.ProjectSystem.DotNet.pkgdef	SUCCESS	Desired Access: Generic Read, Disposition: Open, Options: Sequential Access, Synchronous IO Non-Alert, Non-Directory File, Attributes: n/a, ShareMode: Read, AllocationSize: n/a, OpenResult: Opened

**Comment by MaherJendoubi** [comment]
I share the resulted trace 
![trace](https://cloud.githubusercontent.com/assets/1798510/15486853/e3709c5e-2148-11e6-87ce-f4142d47d5e4.png)

**Comment by MaherJendoubi** [comment]
@joeloff I see this new KB in the notification I'm installing it first time I see it hope that fix my issue. I'm testing.
![kb](https://cloud.githubusercontent.com/assets/1798510/15487024/24ad45ea-214a-11e6-9550-28facaa82d95.png)

**Comment by MaherJendoubi** [comment]
nothing changed same issue.

**Comment by joeloff** [comment]
yeah, I just read through the KB description. It fixes some general issues, nothing related to RC2 unfortunately.

Do you see any entries in the registry for the wizard DLL? It should be under HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\14.0_Config\RuntimeConfiguration\dependentAssembly\codeBase\{6BB7756B-6A5D-4DFF-93D2-D2D5B873E535}

**Comment by joeloff** [comment]
Another thing to try is to run the fushion log viewer (fuslogvw.exe) You should be able to start it from a developer prompt. It will record things like binding failures.

**Comment by MaherJendoubi** [comment]
Yes, I do see it @joeloff 
![regedit](https://cloud.githubusercontent.com/assets/1798510/15487425/9237f8e6-214d-11e6-9a87-fa3532871413.png)

**Comment by MaherJendoubi** [comment]
*** Entrée du journal Binder d'assembly  (24/05/2016 @ 01:37:58) ***

L'opération a échoué.
Résultat de liaison : hr = 0x80070002. Le fichier spécifié est introuvable.

Gestionnaire des assemblys chargé à partir de :  C:\Windows\Microsoft.NET\Framework\v4.0.30319\clr.dll
Exécution sous l'exécutable  C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe
--- Un journal des erreurs détaillé suit. 

=== Informations d'état de liaison préalable ===
JRN : DisplayName = NuGet.PackageManagement.VisualStudio, Version=3.5.0.1284, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
 (Fully-specified)
JRN : Appbase = file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/
JRN : PrivatePath initial = NULL
JRN : base dynamique = NULL
JRN : base de cache = NULL
JRN : AppName = devenv.exe
Assembly appelant : (Unknown).
===
JRN : cette liaison démarre dans le contexte de chargement de default.
JRN : utilisation du fichier de configuration de l'application : C:\Users\M_Jendoubi\AppData\Local\Microsoft\VisualStudio\14.0\devenv.exe.config
JRN : utilisation du fichier de configuration d'hôte : 
JRN : utilisation du fichier de configuration de l'ordinateur à partir de C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config.
JRN : référence post-stratégie : NuGet.PackageManagement.VisualStudio, Version=3.5.0.1284, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a
JRN : échec de la recherche dans le GAC.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PublicAssemblies/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PublicAssemblies/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TemplateProviders/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TemplateProviders/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Platform/Debugger/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Platform/Debugger/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Platform/DiagnosticsHub/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Platform/DiagnosticsHub/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/DataCollectors/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/DataCollectors/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/DataCollectors/x86/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/DataCollectors/x86/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.DLL.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PublicAssemblies/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PublicAssemblies/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TemplateProviders/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Microsoft/TemplateProviders/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Platform/Debugger/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Platform/Debugger/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Platform/DiagnosticsHub/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/CommonExtensions/Platform/DiagnosticsHub/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/DataCollectors/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/DataCollectors/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/DataCollectors/x86/NuGet.PackageManagement.VisualStudio.EXE.
JRN : tentative de téléchargement de la nouvelle URL file:///C:/Program Files (x86)/Microsoft Visual Studio 14.0/Common7/IDE/PrivateAssemblies/DataCollectors/x86/NuGet.PackageManagement.VisualStudio/NuGet.PackageManagement.VisualStudio.EXE.
JRN : toutes les URL recherchées ont été tentées et ont échoué.

**Comment by MaherJendoubi** [comment]
https://gist.github.com/MaherJendoubi/7370d1009af0310ae2741abef998bee9

**Comment by MaherJendoubi** [comment]
@joeloff Any news from the VS IDE Team please?

**Comment by MaherJendoubi** [comment]
@joeloff I uninstalled nuget 3.5.0.1284 and installed nuget 3.4.3.855 version. This is what I get after running fushion log viewer https://gist.github.com/MaherJendoubi/83add11554ebe7a6f46d14a28476ab09#file-fuslogvw

**Comment by MaherJendoubi** [comment]
@joeloff I disable TFS and Git to focus on the issue and here another fusion log viewer https://gist.github.com/MaherJendoubi/2ba8ba11d0d556b853c7befea6d0a067

**Comment by sayedihashimi** [comment]
TFS: 224849
I've added this to our internal TFS, we will reply back here soon.

**Comment by joeloff** [comment]
@MaherJendoubi One more thing to try: launch VS using devenv /safemode. This disables a lot of extensions that aren't in the VS approved list and might rule out potential conflicts.

Also, could you email me the procmon trace again? You can send it to joeloff at Microsoft dot com

**Comment by MaherJendoubi** [comment]
@joeloff done

**Comment by joeloff** [comment]
@MaherJendoubi Have something to try

1. Close all instances of VS
2. Regen your native image cache (ngen /update - I think that's the command)
3. Restart VS

**Comment by MaherJendoubi** [comment]
@joeloff The command is ngen update. I still having the same problem.

**Comment by MaherJendoubi** [comment]
@joeloff I want to uninstall VS and Cleanup my PC (Windows 7). I'm using CCleaner to clean registries.
Any hints please?

**Comment by MaherJendoubi** [comment]
@joeloff How to fix the following setup failure please?
![setupfailed](https://cloud.githubusercontent.com/assets/1798510/15576443/34874e10-2358-11e6-873b-1fa8388a2553.png)

**Comment by MaherJendoubi** [comment]
@joeloff I share the log here https://gist.github.com/MaherJendoubi/a66850677c74acb0e0dcdefafd22685f

**Comment by MaherJendoubi** [comment]
@joeloff the problem was dotnet framework not installed.

**Comment by MaherJendoubi** [comment]
FYI @davidfowl @joeloff @sayedihashimi I still having the same issue even with the update 3 of Visual Studio 2015.

**Comment by YehudahA** [comment]
## Same issue with VS2015 Update3 & AspNetTools preview2.

**Comment by jamierytlewski** [comment]
I'm having the same issue with VS2015 Update 3 and AspNetTools Preview 2. Everything was working fine until I did an update this morning to go to 1.0.0 instead of RC2. I've uninstalled everything and tried again and nothing has changed.

**Comment by joeloff** [comment]
It might be a problem with the devenv.exe.config missing assembly binding information.

Maybe take a look at [this](https://github.com/aspnet/Home/issues/1455#issuecomment-229146688)

**Comment by joeloff** [comment]
You're welcome. Credit goes to @olegburov

**Comment by jamierytlewski** [comment]
Thank you @olegburov.

**Comment by olegburov** [comment]
@jamierytlewski You are so welcome!

**Comment by Gaby10** [comment]
I can't get rid of problem because I can't uninstall RC1 eaither. VS 2015 enterpirse... Update 3 seems to have affected (I'm not sure yet). It would be great a cleaner... but I know that it's a very complex installer.
