### ISSUE TITLE
Task Runner Explorer: Project Open binding doesn't seem to work after RC2 tooling is installed

### ISSUE THREAD

**Issue by fedotovalex** [aspnet/Tooling#516]
Project Open has no effect after I installed RC2 tooling. It used to work before that.

The other three bindings seem to work fine, it is just Project Open that fails to work for me for some reason. If I start the corresponding task manually, it runs just fine.

**Comment by alehro** [comment]
Project Open didn't work for me too. I use Visual Studio Community 2015. Taking the latest update of the VS resolved the problem

**Comment by fedotovalex** [comment]
Sorry, which update are you referring to?

**Comment by alehro** [comment]
Update 2

**Comment by fedotovalex** [comment]
Well, I have that installed and still no luck.

**Comment by fedotovalex** [comment]
I don't know what changed, but today Project Open binding works for me again. Go figure.
