### ISSUE TITLE
loooking for an easier way to add a reference to a nuget package

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#517]
Hi,
  Is there an easy way to add a nuget package on the fly to a vs project? 
  I was trying a package just updated for rc2, and I found a bug. I cloned  the sources from github and fixed the problem, but at the moment to add the compiled nuget package I found a problem: since has been done with vs code, I don't have the project file, so I had a problem to add to the solution.
  To solve this problem, I had to add a nuget pointing to the package dir and add it to the project.
  Is it possible to have a easier way to load nuget packages ? This could be useful especially because can avoid another problem, this one given by a my forgetfulness: 
  After I solved the problem, I wrote the package author about the issue and deleted the local copy sources to update the package from nuget, and at this point I started to have problems restoring the packages.
  The problem was that I deleted the sources, but I didn't delete the nuget source from vs, and looks like that dotnet blocks if one of the source is incorrect.

**Comment by sayedihashimi** [comment]
@lucamorelli I'm not sure if this is a tooling issue or just a usability issue. I'm not really following the issue. Maybe we can discuss more in our call so that I can get more details here?

**Comment by lucamorelli** [comment]
ok
