### ISSUE TITLE
Right-click on project, choose publish fails in visual studio with rc2

### ISSUE THREAD

**Issue by timmydo** [aspnet/Tooling#518]
When I right-click on my xproj project and choose 'publish...', it fails in visual studio with asp net core rc2.

This is my web config:

```
﻿<?xml version="1.0"?>
<configuration>
  <system.webServer>
    <handlers>
      <add name="aspNetCore" path="*" verb="*" modules="AspNetCoreModule" resourceType="Unspecified" />
    </handlers>
    <aspNetCore processPath="%LAUNCHER_PATH%" arguments="%LAUNCHER_ARGS%" stdoutLogEnabled="true" stdoutLogFile="%home%\LogFiles\dotnetcore" forwardWindowsAuthToken="true"/>
  </system.webServer>
</configuration>

```

I get a message box saying: "There are errors in web.config. Please correct the errors and try again". (Probably the aspNetCore xml element).

**Comment by sayedihashimi** [comment]
TFS: 224848
I've added this to our internal TFS, we will reply back here soon.

**Comment by vijayrkn** [comment]
@timmydo - I can't reproduce this error with the above web.config. Is it possible to provide a repro project?

**Comment by timmydo** [comment]
Looks like a unicode bom-related issue. Thanks
