### ISSUE TITLE
Really awkward to get build outputs if needed for tests

### ISSUE THREAD

**Issue by mgravell** [aspnet/Tooling#52]
I use PEVerify extensively, for example - so I need the build-output dlls as files during the test execution (otherwise: PEVerify complains about missing files). The only way I've found to do this (and it is hack hack hack) is something like:

```
    static PEVerify() // my utility class that invokes PEVerify
    {
        CopyBuildOutputsLocally("Protobuf.Tests");
        CopyBuildOutputsLocally("protobuf_net");
    }
    private static void CopyBuildOutputsLocally(string project)
    {
        var path = "../artifacts/bin/" + project + "/" +
#if DEBUG
            "Debug"
#elif RELEASE
            "Release"
#else
            ""
#error Unknown build
#endif
            + "/" +
#if DNX451
            "dnx451"
#elif DNXCORE50
            ""
#error Unknown runtime
#endif
            ;
        foreach(var file in Directory.GetFiles(path))
        {
            File.Copy(file, Path.GetFileName(file), true);
        }
    }
```

Lots of hackiness here, including hard coding.

Any easier ways?

**Comment by davidfowl** [comment]
Interesting scenario. We don't put anything on disk because unit test just use in memory assemblies. We'll need to look into this some more. That code is pretty hacky :smile:

**Comment by mgravell** [comment]
But it is the only way I could devise to get PEVerify working :)

**Comment by mgravell** [comment]
As an aside, @davidfowl - I am undecided on the wisdom of running tests in the project folder. For anything that writes files, it pollutes things. I'll probably hack around it by adding a ./TestFiles directory that is in my .gitignore and change all my tests so that they only touch files in there, but...

**Comment by rynowak** [comment]
@mgravell you could try to do something similar to what the test host does, and get the assemblies as bytes from from the `ILibraryManager`

**Comment by mgravell** [comment]
Interesting; that could possibly work, but I'd need to do a lot of digging
to find out how to get hold of the ILManager, get an inventory of files,
and extract the bytes :)

It has potential, but very nontrivial.

**Comment by sayedihashimi** [comment]
TFS:151707
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
Sorry for the delay here. There has been a lot of changes that have happened since you filled this issue. Can you try again with VS2017 RC and let us know if this issue persists? I'll close this now, but please reopen if it's still an issue.
