### ISSUE TITLE
BrowserLink.Loader package 14.0.0-rc2-final screwing DOM in Chrome

### ISSUE THREAD

**Issue by ninety7** [aspnet/Tooling#520]
There seems to be an issue in Chrome when using the BrowserLink.Loader package for RC2.

I create a new rc2 web project (full .NET framework or core) and when I run it on Chrome, all of the header tags (scripts, css, title, etc) are moved to the `<body>` and the `<head>` is empty. The first element on the body is the weird character `&#65279;` which inserts an empty space on the page. I don't see it happening on firefox or edge. If I remove this package from the project, there is no problem at all.

Is there a fix in the works?

**Comment by sayedihashimi** [comment]
TFS: 224823
I've added this to our internal TFS, we will reply back here soon.

**Comment by jodavis** [comment]
This will be fixed in Preview 2 of the Web Tools for ASP.NET Core.
