### ISSUE TITLE
Updates on webjob deployment

### ISSUE THREAD

**Issue by bragma** [aspnet/Tooling#524]
Hi,
is there any news on deploying NET Core based webjobs from VS to Azure? Had to be done manually with previous RC1.
Thanks!

**Comment by sayedihashimi** [comment]
We are going to be discussing this soon, I'll get back to you.

cc @mlorbetske

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231161&fullScreen=false&_a=edit">231161</a>

**Comment by mlorbetske** [comment]
.NET Core console applications are now supported as WebJobs (see the writeup [here](https://blogs.msdn.microsoft.com/benjaminperkins/2017/03/07/how-to-deploy-a-net-core-console-application-to-azure-webjob/) for more details). Going forward, we plan to move to Kudu Cron based scheduling & improve the deployment experience for both .NET Core and .NET Framework WebJobs.
