### ISSUE TITLE
RC2: Cannot resolve dependencies when adding existing projects where Assembly Name differs from Project Name

### ISSUE THREAD

**Issue by shrib** [aspnet/Tooling#527]
a. Create a 4.5.2 class-library project with AssemblyName in the project properties is different from the Project Name (Example: Entities.csproj, AssemblyName: Enterprise.Entities)
b. Create a new RC2 WebAPI Project [Or migrate a RC1 project to RC2]
c. Change framework to show "net452", etc.
d. Add class-lib project to this solution
e. Add references to this library
f. VS complains that it cannot resolve references to this project

Notes:
No project.fragment.lock.json is created, errors show up in the Error List window, etc. Normal stuff.

This seems like a bug in the tooling.

Workaround:
1. Remove the class-lib reference from the project.json file
2. Open the class-lib properties and change the AssemblyName to the project name
3. Save and compile the class-lib
4. Add reference to the web-api project

**Comment by abpiskunov** [comment]
TFS 225135

This behavior comes form wrapping times when we added output assembly name as a project dependency name. Fix is available, will check in when approved by triage.

**Comment by abpiskunov** [comment]
It is fixed in RTW
