### ISSUE TITLE
VS2015 .NET Core project icons

### ISSUE THREAD

**Issue by zygimantas** [aspnet/Tooling#529]
If a new project is created using project template "Console Application (.NET Core), the icon of project in Solution Explorer looks identical to "Class Library (.NET Core)" project.

**Expected behavior:** the icon should be represent a console.

**Actual behavior:**

![image](https://cloud.githubusercontent.com/assets/102076/15521932/5ec6924a-2217-11e6-9e68-8da2022eff24.png)

**Comment by sayedihashimi** [comment]
TFS: 225801
I've added this to our internal TFS, we will reply back here soon.

**Comment by mlorbetske** [comment]
From the linked TFS item, this had been copied to https://github.com/dotnet/project-system, but I'm unable to find an issue there corresponding to this one. If you're still experiencing this, please open an issue on that repo.
