### ISSUE TITLE
Publish-AspNet cmdlet app_offline.htm support

### ISSUE THREAD

**Issue by dolly22** [aspnet/Tooling#530]
Is app_offline.htm supported when publishing RC2 project?

When using this snippet to publish Azure App Service...

``` powershell
$publishProperties = @{'WebPublishMethod'='MSDeploy';
                        'MSDeployServiceUrl'=$profile.publishUrl;
                        'DeployIisAppPath'=$profile.msdeploySite;
                        'Username'=$profile.userName;
                        'Password'=$profile.userPWD;
                        'EnableMSDeployAppOffline'='true'
                        'AppOfflineTemplate'='offline-template.html'}

. $PSScriptRoot\default-publish.ps1 -publishProperties $publishProperties -packOutput $Package
```

this command is generated by powershell publish scripts...

``` cmd
msdeploy.exe -source:manifest='[removed]\SourceManifest.xml' -dest:manifest='[removed]DestManifest.xml',ComputerName='https://[removed].scm.azurewebsites.net/msdeploy.axd',UserName='$[removed]',Password='{PASSWORD-REMOVED-FROM-LOG}',IncludeAcls='False',AuthType='Basic',appOfflineTemplate="wwwroot\offline-template.html" -verb:sync -enablerule:AppOffline -enableRule:DoNotDeleteRule -retryAttempts:20 -disablerule:BackupRule
```

and error message

>  Error: The provider 'manifest' does not support the 'appOfflineTemplate' setting. Supported settings are (skipInvalid, authType, computerName, encryptPassword, includeAcls, password, prefetchPayload, userName, wmsvc).

**Comment by sayedihashimi** [comment]
TFS: 225800
I've added this to our internal TFS, we will reply back here soon.

@vijayrkn was looking at this. We think it may be an msdeploy issue, we are looking into it.

**Comment by vijayrkn** [comment]
For app_offline support, you just need to add this property to the script -  'EnableMSDeployAppOffline'='true'. MSDeploy will add the app_offline file automatically during deployment.
Currenlty, 'AppOfflineTemplate' support is not available, we will be adding this in a future release.

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still running in to issues with this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
