### ISSUE TITLE
Resource generator generating ResourceManager basename incorrectly

### ISSUE THREAD

**Issue by BrennanConroy** [aspnet/Tooling#532]
See https://github.com/aspnet/Localization/issues/245 for conversation and reproducible

**Comment by sayedihashimi** [comment]
TFS: 225796
I've added this to our internal TFS, we will reply back here soon.

**Comment by xpding** [comment]
I had the same problem. My website default namespace is different to the web project name. IStringLocalizer<LoginController> won't find resource file in Resources/Controllers.LoginController.zh.resx.

The workaround is to add the namespace to the resource file name, e.g. VP.Web.Controllers.LoginController.zh.resx. Same for viewmodels resource file, add the namespace to the file name like VP.Web.ViewModels.UserLoginVM.zh.resx and it will work.

Looking forward to the fix.

**Comment by LadislavBohm** [comment]
Is there any progress to this? Seven months later in version 1.1 of ASP.NET and this is still happening. It's really annoying to have to keep all resource files in root of our project.

**Comment by harsimranb** [comment]
This issue is still happening.  Any update?

**Comment by Charlkie14** [comment]
Any updates on this? Please.

**Comment by nicolasguzca** [comment]
Any updates? Still happening

**Comment by sayedihashimi** [comment]
This should be fixed, let me know if you still run into issues.
