### ISSUE TITLE
Can't downgrade to RC1

### ISSUE THREAD

**Issue by richardmatsu** [aspnet/Tooling#533]
After installing RC2 and determining that it is too early for us to migrate our projects, I have been unable to get RC1 working again. See forum post: https://forums.asp.net/post/6053125.aspx

xproj projects are not recognized when loading the solution. There is no logs that I can find or any other errors to indicate what is happening.

**Comment by sayedihashimi** [comment]
TFS: 225795
I've added this to our internal TFS, we will reply back here soon.

**Comment by barrytang** [comment]
RC2 supports RC1 tooling. Did you uninstall RC2 already?
