### ISSUE TITLE
I cannot uninstall ASPNET 5 RC1 Update 1

### ISSUE THREAD

**Issue by residentx10** [aspnet/Tooling#534]
I cannot remove this from the App window. It keeps prompting me for some files or something.
This software is affecting the my webpages views all over the place. I can't see dropdowns, postbacks don't work correctly. This has to go. How do I get ride if this?

**Comment by mikes-gh** [comment]
https://github.com/aspnet/Home/issues/1449

**Comment by sayedihashimi** [comment]
TFS: 225794
I've added this to our internal TFS, we will reply back here soon.

**Comment by barrytang** [comment]
Thanks for reporting this. This is a known issue and you can find out more details here - aspnet/Home#1449. Thanks!
