### ISSUE TITLE
Adding App Insights telemetry uses RC1 package

### ISSUE THREAD

**Issue by MaximBalaganskiy** [aspnet/Tooling#535]
A project dropdown menu item "Add Application Insights Telemetry" adds old packages to RC2 projects

**Comment by sayedihashimi** [comment]
TFS: 225793
I've added this to our internal TFS, we will reply back here soon.

**Comment by dnduffy** [comment]
We are actively updating references and testing on internal releases so that the final release will have the latest available references.

**Comment by phenning** [comment]
This was fixed in RTW.
