### ISSUE TITLE
cannot debug ASP.NET Core 2

### ISSUE THREAD

**Issue by pantonis** [aspnet/Tooling#538]
I created new ASP.NET Core Web Application without changing anything in the code and when I run it I get 

```
The program '[2336] dotnet.exe' has exited with code -2147450749 (0x80008083).
The program '[6348] iisexpress.exe: Program Trace' has exited with code 0 (0x0).
The program '[6348] iisexpress.exe' has exited with code 0 (0x0).

```

**Comment by sayedihashimi** [comment]
If you close and reopen the solution does that fix the issue?

**Comment by pantonis** [comment]
No. I tried it and also deleted project.json.lock and still the same. When I run dotnet fun from cmd it works. From vs it does not work

**Comment by sayedihashimi** [comment]
TFS: 225788
I've added this to our internal TFS, we will reply back here soon.

**Comment by balachir** [comment]
@pantonis do you have .NET Core RC2 Tooling installed? Also, what version of dotnet do you have?

**Comment by pantonis** [comment]
@balachir If you mean this: https://go.microsoft.com/fwlink/?LinkId=798481 yes.
dotnet version is 1.0.0-preview1-002702

**Comment by pantonis** [comment]
I mamaged to reproduce it randomly. Whenever I buuld using dotnet build and then press F5 on vs2015 I can debug. If I clean and build from vs2015 I get the error no buuld files exist.

**Comment by arthurgreef** [comment]
I'm getting this problem as well.

The program '[2632] dotnet.exe' has exited with code -2147450749 (0x80008083).
The program '[4892] iisexpress.exe' has exited with code 0 (0x0).

I'm running ASP.Net Core RC2 in VS 2015 Community.

I installed dotnet-dev-win-x64.1.0.0-preview1-002702 and I'm building an x64 bit app.

**Comment by BillHiebert** [comment]
could you be running into this issue? https://github.com/aspnet/Home/issues/1480

**Comment by pantonis** [comment]
managed to reproduce it. 

Delete bin and obj files of the project. Then press build solution from VS2015 and run from VS2015. You will get the error

**Comment by BillHiebert** [comment]
@pantonis - do you have a global.json file at the project root? Tooling is not calculating the output path from dotnet build correctly in this case. The workaround is to remove the global.json or move it up one level

**Comment by pantonis** [comment]
No I dont have a global.json file

**Comment by pantonis** [comment]
I am still wondering why this issue was closed. We have 3 Pcs all having the same problem.

**Comment by pantonis** [comment]
After updating to preview 2 and asp.net core 1 problem still exists.

**Comment by lextm** [comment]
@pantonis you should always have a global.json file as indicated.

**Comment by noahfalk** [comment]
I have also just hit this issue on preview2 tooling. I think this issue has been closed prematurely. Even if a workaround exists, its nice to have a clear message that either the underlying problem has been fixed or the team doesn't plan to fix it.

For the record I tried the following hacks/workarounds:
1. Changed the name of global.json to global.json_ (presumably the same effect as deleting it) - repro still exists
2. Delete the bin directory in the project directory - repro still exists
3. Delete the obj and bin directory in the project directory - repro still exists
4. Close and reopen the VS solution - repro still exists
5. Quit VS and restart - repro still exists
6. Quit VS, delete the obj and bin directory in the project directory, restart VS, F5 - repro still exists

**Comment by noahfalk** [comment]
Switching to the command line was more illuminating (in my case at least, I don't know if this matches issues other posters have). dotnet run gave an error:

    The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc2-3002702' was not found.
       - Check application dependencies and target a framework version installed at:
          C:\Program Files\dotnet\shared\Microsoft.NETCore.App
      - The following versions are installed:
          1.0.0
      - Alternatively, install the framework version '1.0.0-rc2-3002702'.

Changing project.json to reference the 1.0.0 version of NETCore.App, followed by dotnet restore, dotnet build, and dotnet run was successful. At that point VS F5 was also successful.

I would still consider the dubious error messaging within VS to be an issue worthy of fixing, but its certainly must less severe than an issue which blocks running/debugging at all.

**Comment by TobiasKoller** [comment]
I had the same problem and solved it by uninstalling the nuget package "Microsoft.NETCore.Platforms 1.1.0"

**Comment by gecko-8** [comment]
I had this same issue and updating to the latest .NET Core SDK fixed it.

**Comment by Marcel0024** [comment]
Same as gecko-8, I first installed the wrong one x64. After installing the right one x86 it worked
