### ISSUE TITLE
Task Runner Explorer for Gulp absorbs error output

### ISSUE THREAD

**Issue by EricSch** [aspnet/Tooling#543]
Since the latest updates of Visual Studio, ASP.NET Core RC2 and tools (May 2016), Task Runner doesn't show any error messages, for TS errors, only "TypeScript: 1 semantic error", for other gulp tasks nothing. Outside VS, the gulp output is fine.
This happens on all machine in our team,

Thanks
Eric

> Microsoft Visual Studio Professional 2015
> Version 14.0.25123.00 Update 2
> Microsoft .NET Framework
> Version 4.6.01038
> 
> Installed Version: Professional
> 
> LightSwitch for Visual Studio 2015   00322-40000-00000-AA262
> Microsoft LightSwitch for Visual Studio 2015
> 
> Visual Basic 2015   00322-40000-00000-AA262
> Microsoft Visual Basic 2015
> 
> Visual C# 2015   00322-40000-00000-AA262
> Microsoft Visual C# 2015
> 
> Visual C++ 2015   00322-40000-00000-AA262
> Microsoft Visual C++ 2015
> 
> Visual F# 2015   00322-40000-00000-AA262
> Microsoft Visual F# 2015
> 
> Windows Phone SDK 8.0 - ENU   00322-40000-00000-AA262
> Windows Phone SDK 8.0 - ENU
> 
> Add New File   3.3
> The fastest and easiest way to add new files to any project - including files that start with a dot
> 
> ASP.NET and Web Tools 2015.1   14.1.20512.0
> ASP.NET and Web Tools 2015.1
> 
> ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
> For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563
> 
> ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
> For additional information, visit http://www.asp.net/
> 
> Azure App Service Tools v2.9   14.0.20316.0
> Azure App Service Tools v2.9
> 
> Azure Data Lake Node   1.0
> This package contains the Data Lake integration nodes for Server Explorer.
> 
> Azure Data Lake Tools for Visual Studio   2.0.6000.0
> Microsoft Azure Data Lake Tools for Visual Studio
> 
> Clang with Microsoft CodeGen   14.0.25317
> Clang with Microsoft CodeGen
> 
> Common Azure Tools   1.7
> Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.
> 
> DataFactoryProject   1.0
> Microsoft Data Factory Package
> 
> GitHub.VisualStudio   1.0
> A Visual Studio Extension that brings the GitHub Flow into Visual Studio.
> 
> Image Optimizer   3.6.89
> Uses industry standard tools to optimize any JPEG, PNG and Gifs - including animated Gifs. Can do both lossy and lossless optimization.
> 
> JavaScript Language Service   2.0
> JavaScript Language Service
> 
> JavaScript Project System   2.0
> JavaScript Project System
> 
> JustDecompile Tools   1.0
> Makes JustDecompile functionality available in VIsual Studio. Requires JustDecompile installation.
> 
> KofePackagePackage Extension   1.0
> KofePackagePackage Visual Studio Extension Detailed Info
> 
> Microsoft .NET Core Tools (Preview 1)   14.1.20512.0
> Microsoft .NET Core Tools (Preview 1)
> 
> Microsoft Azure Data Factory Node Node   1.0
> Azure Data Factory extension for Visual Studio Server Explorer.
> 
> Microsoft Azure HDInsight HQL Service   2.0.6000.0
> Language service for Hive query
> 
> Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
> An integrated development environment for HDInsight application development.
> 
> Microsoft Azure Mobile Services Tools   1.4
> Microsoft Azure Mobile Services Tools
> 
> Microsoft Azure Tools   2.9
> Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40323.3
> 
> Microsoft Azure Tools   2.7
> Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.7.30818.1601
> 
> Microsoft Azure Tools   2.8
> Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.8.40211.2
> 
> Microsoft MI-Based Debugger   1.0
> Provides support for connecting Visual Studio to MI compatible debuggers
> 
> Microsoft Team Foundation Server 2015 Power Tools   14.0
> Power Tools that extend the Team Foundation Server integration with Visual Studio.
> 
> Microsoft Visual Studio Process Editor   1.0
> Process Editor for Microsoft Visual Studio Team Foundation Server
> 
> NPM Task Runner   1.3.59
> Adds support for package.json's NPM scripts in the Task Runner Explorer
> 
> NuGet Package Manager   3.4.3
> NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.
> 
> Office Developer Tools for Visual Studio 2015 ENU   14.0.23928
> Microsoft Office Developer Tools for Visual Studio 2015 ENU
> 
> Open Command Line   2.1.169
> Opens a command line at the root of the project. Support for all consoles such as CMD, PowerShell, Bash etc. Provides syntax highlighting, Intellisense and execution of .cmd and .bat files.
> 
> PreEmptive Analytics Visualizer   1.2
> Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.
> 
> Python Tools for Visual Studio   2.2.40315.00
> Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.
> 
> Python Tools for Visual Studio - Django Integration   2.2.40315.00
> Provides templates and integration for the Django web framework.
> 
> Python Tools for Visual Studio - Profiling Support   2.2.40315.00
> Profiling support for Python projects.
> 
> RoamedExtensionVSPackage Extension   1.0
> RoamedExtensionVSPackage Visual Studio Extension Detailed Info
> 
> SQL Server Data Tools   14.0.60311.1
> Microsoft SQL Server Data Tools
> 
> SQLPromptVsPackage   1.0
> Information about my package
> 
> T4 Toolbox   14.0.0.0
> Extends code generation capabilities of Text Templates.
> 
> Telerik ASP.NET MVC VSExtensions   2016.2.428.0
> Telerik UI for ASP.NET MVC VSExtensions
> 
> ToolWindowHostedEditor   1.0
> Hosting json editor into a tool window
> 
> TypeScript   1.8.31.0
> TypeScript tools for Visual Studio
> 
> Visual C++ for Cross Platform Mobile Development (Android)   14.0.25116.00
> Visual C++ for Cross Platform Mobile Development (Android)
> 
> Visual C++ for Cross Platform Mobile Development (iOS)   14.0.25116.00
> Visual C++ for Cross Platform Mobile Development (iOS)
> 
> Visual Studio Tools for Apache Cordova   Update 9
> Visual Studio Tools for Apache Cordova
> 
> Visual Studio Tools for Universal Windows Apps   14.0.25219.00
> The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.
> 
> Web Essentials 2015.2   2.0.214
> Adds many useful features to Visual Studio for web developers. Requires Visual Studio 2015
> 
> WebPack Task Runner   1.4.58
> Adds support for WebPack in Visual Studio 2015's Task Runner Explorer.
> 
> Workflow Manager Tools 1.0   1.0
> This package contains the necessary Visual Studio integration components for Workflow Manager.
> 
> Xamarin   4.0.3.214 (0dd817c)
> Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.
> 
> Xamarin.Android   6.0.3.5 (a94a03b)
> Visual Studio plugin to enable development for Xamarin.Android.
> 
> Xamarin.iOS   9.6.1.8 (3a25bf1)
> Visual Studio extension to enable development for Xamarin.iOS.
> 
> XAML Spy   3.0.0-alpha1
> XAML Spy for Visual Studio
> Copyright © First Floor Software. All rights reserved.
> 
> The visual runtime inspector for Android, iOS and Windows
> http://xamlspy.com

**Comment by sayedihashimi** [comment]
TFS: 226142
I've added this to our internal TFS, we will reply back here soon.

**Comment by ChunkNorriss** [comment]
have same problems

**Comment by raquelsa** [comment]
Thank you for reporting the issue. This will be fixed on our upcoming release NET Core Tooling Preview 2 for Visual Studio 2015.

**Comment by MaximRouiller** [comment]
I have the exact issue but with gulp-eslint with `visualstudio` formatter. 

Normal? I have the .NET Core Tooling Preview 2 installed.
