### ISSUE TITLE
Web Deployment Agent Service on Windows 10

### ISSUE THREAD

**Issue by StevenLiekens** [aspnet/Tooling#545]
I had installed Web Deploy 3.6 on my development machine and was ready to test my deploys, only to find out that the web deployment service is not supported on Windows 10.

![error_destination_not_reachable](https://cloud.githubusercontent.com/assets/1583241/15677095/096cde3a-2749-11e6-8337-aad71dd31603.png)

I don't know if the deployment agent does not run on Windows 10 because of technical reasons or because of political reasons, but I do know that it is making my development experience much more frustrating than it has to be.

**Comment by vijayrkn** [comment]
While installing Web Deploy 3.6, make sure "Remote agent service" is selected

![image](https://cloud.githubusercontent.com/assets/3981619/15694034/3c1ad976-274f-11e6-8b44-c56748d48aa4.png)

and the service is running on the local machine.

![image](https://cloud.githubusercontent.com/assets/3981619/15694059/6928c888-274f-11e6-9d3b-3f5b6c61ee87.png)

**Comment by StevenLiekens** [comment]
Thanks, I ran the setup and saw that Remote Agent Service was disabled. I used WebPI to install Web Deploy the first time and I assumed that it would install the service for me.
