### ISSUE TITLE
File => New Web Application when only dotnet on box is newer than the one in template doesn't allow you to open Razor files

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Tooling#546]
I've recently cleaned my box and the only sdk I have on my box is 002886:
![image](https://cloud.githubusercontent.com/assets/2008729/15685840/795861a0-2722-11e6-8eee-605425302e16.png)

And shared framework 1.0.0-rc3-004312:
![image](https://cloud.githubusercontent.com/assets/2008729/15685855/8ae21682-2722-11e6-9eca-b674feeaf434.png)

When I do File => New Web Application it generates a global.json that looks like:

``` JSON
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-preview1-002702"
  }
}
```

Which is intended but results in issues. Leaving the global.json untouched and trying to open the `/Views/Account/Login.cshtml` page does nothing. No error dialog, just double click to nothingness.

I tried attaching to the new web application VS to catch errors, turned common language runtime exceptions on but nothing seems to happen.

Reopening the solution gives me this dialog:
![image](https://cloud.githubusercontent.com/assets/2008729/15686013/3c66515c-2723-11e6-828c-f6d18a368e49.png)

I would have expected this when I first created the project and I would still expect to be able to open Razor files.

_Note:_ Removing the sdk entry in the global.json allows files to be opened.

/cc @ToddGrun

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231159&fullScreen=false&_a=edit">231159</a>

**Comment by sayedihashimi** [comment]
Sorry for the delay here. We've had a lot of updates over the past few months and I believe that this is working now in VS2017 RC. Can you try with the latest VS2017 and try again? I'll close this now, but please reopen if this issue still persists.
