### ISSUE TITLE
Project.json dependency search freezes VisualStudio - VS2015 Tooling Preview 1

### ISSUE THREAD

**Issue by ncthbrt** [aspnet/Tooling#548]
When I am editing the project dependencies in a project.json file (in this case in a solution with multiple projects), the user interface freezes for several minutes and Visual Studio whites out. This consistenly happens.

**Comment by mlorbetske** [comment]
@ncthbrt this is an issue with the default local feeds, see #519 for details. A fix has been checked in for this already and will go out with tooling preview 2.

**Comment by ncthbrt** [comment]
Thanks for the prompt response

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231157&fullScreen=false&_a=edit">231157</a>

**Comment by mlorbetske** [comment]
Sorry, I didn't close this previously - the issue has been fixed, the new internal TFS bug is a duplicate.
