### ISSUE TITLE
NuGet package manager does not maintain alphabetical order of dependencies in project.json

### ISSUE THREAD

**Issue by olegsych** [aspnet/Tooling#55]
Maintaining alphabetical order in package dependency lists helps to reduce merge conflicts and avoid incorrect automatic merges. NuGet Package Manager does this automatically in `packages.config` files but not in `project.json` files, where it appears to always add dependencies to the end.

Steps to reproduce this problem:
- Create a new ASP.NET 5 Web Application project
- Use NuGet Package Manager to add `FakeItEasy` package to the project
- Check `project.json` - FakeItEasy dependency is added to the end of `dependencies`, instead of the place between EntityFramework and Microsoft dependencies.

**Comment by muratg** [comment]
A lot of the developers manually modify the project.json files, so they won't be sorted alphabetically. Would you expect the tooling to reorder all of the dependencies if a package is added via the tooling?

**Comment by olegsych** [comment]
Yes, I would. Having dealt with my fair share of merge problems, both obvious and silent, I feel strongly that NuGet got this right with the `packages.config` files. NuGet should be prescriptive and alphabetize dependencies in the `project.json` files as well. Those burned by merges gone wrong will appreciate it and those who haven't experienced this yet will eventually stop fighting the tooling. By the way, NPM also alphabetizes dependencies in `package.json` files :stuck_out_tongue_winking_eye:

**Comment by muratg** [comment]
How about the scenario where some members of the team use VS and others use other editors (Sublime Text, Visual Studio Code etc)?  This reordering would happen only when VS tooling happens to touch the file, which might cause merge issues as well.

**Comment by davidfowl** [comment]
So adding a new dependency should resort your list?

**Comment by sayedihashimi** [comment]
I don't think it should reorder them. Instead, if the list is alpha sorted before then insert the new string in the correct spot. Otherwise append it to the bottom.

**Comment by glen-84** [comment]
I agree with @sayedihashimi

**Comment by davidfowl** [comment]
Great!

**Comment by olegsych** [comment]
OK, that'll work, as long as empty and single-item lists are considered to be sorted. Do we need  separate issues for VS 2015 project templates, like the _Console Application (Package)_, where dependencies are not alphabetized?

**Comment by sayedihashimi** [comment]
>Console Application (Package), where dependencies are not alphabetized?

Yes please file a new issue, they should be alpha sorted by default.

**Comment by mayurid** [comment]
@pranavra and @phenning for templates
You can also open an issue on templates repo

**Comment by sayedihashimi** [comment]
>You can also open an issue on templates repo
The templates repo is not public, so opening a new issue here is fine.

FYI Pranav is @rustd

**Comment by olegsych** [comment]
OK. I'll file issues for templates here. BTW, I have access to at least some private aspnet repos, but could find the templates repo you mentioned.

**Comment by barrytang** [comment]
@abpiskunov fixed this in beta7.
