### ISSUE TITLE
Browser Link Adds "&#65279;" to the body when enabled

### ISSUE THREAD

**Issue by ctorx** [aspnet/Tooling#552]
Steps to reproduce:
1. Create a new ASP.NET Core Web Application using all the defaults.
2. Start Web Application
3. Using a browser inspector, notice the &#65279; character added to the body (also shown in attachment)

NOTE: This seems to have appeared in RC2
NOTE: Disabling browser link resolves the issue

![badcharacter](https://cloud.githubusercontent.com/assets/343783/15762247/8df7ca1e-28d1-11e6-8582-e2a6f3c10472.PNG)
.

**Comment by Vasimovic** [comment]
Same here, appears not just under <body> but in other places as well - using RC2

**Comment by GuardRex** [comment]
Dup of https://github.com/aspnet/Mvc/issues/4706

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231154&fullScreen=false&_a=edit">231154</a>

**Comment by ZombiesWithCoffee** [comment]
This bug is causing my web pages to completely flash and refresh instead of the smooth transitions I had in RC1.

**Comment by jodavis** [comment]
This was fixed in the RTW/Tooling Preview 1 for VS 2015 a while ago, and it's also fixed in VS 2017.
