### ISSUE TITLE
Resource.designer.cs issue - editing resx causes bad change to file

### ISSUE THREAD

**Issue by Eilon** [aspnet/Tooling#554]
From https://github.com/aspnet/Mvc/issues/4763
By @DandY30
# 

The baseName value of **ResourceManager** changes (to wrong path) every time I add a new row to my .resx.

The working baseName value should be "Namespace.Resources.Resource" and it changes to Namespace.Resource.

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231152&fullScreen=false&_a=edit">231152</a>

**Comment by sayedihashimi** [comment]
Sorry for the delay here. We've had a lot of updates over the past few months and I believe that this is working now in VS2017 RC. Can you try with the latest VS2017 and try again? I'll close this now, but please reopen if this issue still persists.
