### ISSUE TITLE
Microsoft.DotNet.Publishing.targets breaks webdeploy zip support

### ISSUE THREAD

**Issue by timmydo** [aspnet/Tooling#555]
When I create a VS build deployment template in VSTS, it tries building a project or solution with the following arguments:

```
/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:PackageLocation="$(build.artifactstagingdirectory)\\"
```

After the move from DNX targets to DotNet targets, this only builds the project rather than outputting a zip file, breaking the VSTS template.

I'm having a hard time trying to figure out how to call msbuild on my xproj file to get it to build a webdeploy compatible zip package that can be deployed with `Publish-AzureWebsiteProject`.

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231151&fullScreen=false&_a=edit">231151</a>

**Comment by sayedihashimi** [comment]
FYI we don't have support for publishing to a package yet. We haven't started working on that yet, but it is on our radar. Sorry for the delay we have a lot of work ahead of us.

**Comment by mlorbetske** [comment]
Support for publishing to packages is present in the .NET SDK 2.0 or higher
