### ISSUE TITLE
New Publish Profile doesn't let you specify a Web Site

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/Tooling#556]
When you create a new publish profile in a ASP.NET Core project, there's no option to create a new IIS Web site to deploy to. You only get the option to create a new file deploy folder.

> Workaround I've used:
> I explicitly copied a publishing profile from a non-ASP.NET Core project into `\properties\PublishProfiles\<myProfile>.pubxml`.
>
> Additionally needed to add `<AuthType>NTLM</AuthType>` (per previous discussion) to get publish to work project level publishing (individual file publishing worked).

Two suggestions:
* Fix this dialog so you can add a Web site to deploy
* Work with the IIS team to have an option to export a Publish profile

**Comment by sayedihashimi** [comment]
Hi @RickStrahl we are going to be adding support for all the publish options to .NET Core. We are a bit behind there. I think there is another issue discussing this already. Not sure the number.

About IIS support for exporting publish profiles, that feature already exists. If you install Web Deploy (aka MSDeploy) on your IIS machine there is an option during install to include IIS Extensions. When you install that there is a Deploy context menu in IIS Manager which has that menu option.

**Comment by RickStrahl** [comment]
Thanks @sayedihashimi .

I was able to make this work, so the mechanics are working - I think it's just the UI (and perhaps the shipped default script) that need attention in regards to this post.

Thanks. Having publishing work certainly makes life a lot easier.

**Comment by RickStrahl** [comment]
> Re:Web Deploy IIS export: that feature already exists. 

Hmmm... I have Web Deploy installed on my server but I don't see any options to create a publish profile anywhere.

I re-ran the install for Web Deploy for hosting servers from PI, but there are no options from PI. I run a change install and **then** I do see the options. According to the installer it's installed.

Where would this option show up on a site or virtual in the IIS manager?

**Comment by sayedihashimi** [comment]
In IIS Manager, there should be a Deploy fly out. I think you can modify Web Deploy from Add Remove Programs if needed.

**Comment by RickStrahl** [comment]
I re-ran the installer from Add/Remove programs and the Web Deploy Integration features are already installed, but I see nothing in the IIS Admin ui. When you say **fly out** you mean the Features view?

**Comment by RickStrahl** [comment]
Ugh... never mind found it. I wasn't looking on the drop down menu of the site. The right action sidebar doesn't have the 'Configure Publishing' option, so the only place that option is visible is on the right click menu of the site. Pretty hard to find. It'd be nice if this showed up in the actions pane and maybe also had a better name than "Configure Web Deploy Publishing". Generate Publish Settings File would be a lot clearer (unless the feature actually does something else as well).

Thanks.

**Comment by RickStrahl** [comment]
Fwiw, when I use the default publish URL publish doesn't work:

![image](https://cloud.githubusercontent.com/assets/1374013/15809321/62f6cf08-2b43-11e6-9136-1a0565f34d0c.png)

I'm back to the ERROR_ACCESS_DENIED even though when I use the Validate button it does work.

If I switch to back to the the base site `http://west-wind.com/` it works again. Switching to https:// on the same url that works also doesn't work.
