### ISSUE TITLE
Question: Typescript with ASP.NET Core RC2

### ISSUE THREAD

**Issue by crbranch** [aspnet/Tooling#557]
Is it possible to compile Typescript code directly in Visual Studio 2015 using the ASP.NET Core RC2 project templates?  This used to work in RC1, but since updating to RC2 I can't get Typescript and ASP.NET Core working together simultaneously.  If I create a .NET Core project (e.g., **ASP.NET Core Web Application (.NET Core)** template), then I don't see "Typescript Build" properties page in Project Properties (the only property pages available are Application, Build, Debug).  I can create a Typescript project (e.g., **HTML Application with Typescript** template, which uses the csproj format), and Typescript works as expected, but of course I can't use .NET Core in that project.

I have confirmed that my .xproj file does include a reference to Microsoft.DotNet.Web.targets, which I understand is supposed to bring in Typescript support:

```
<Import Project="$(VSToolsPath)\DotNet.Web\Microsoft.DotNet.Web.targets"
        Condition="'$(VSToolsPath)' != ''" />
```

Is the built-in Typescript compilation no longer supported with RC2, or am I missing something somewhere?

**Comment by wangkanai** [comment]
+1

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231150&fullScreen=false&_a=edit">231150</a>

**Comment by AngelosP** [comment]
It's there now 👍
