### ISSUE TITLE
VS Publish Wizard doesn't update existing profiles 

### ISSUE THREAD

**Issue by ArieJones** [aspnet/Tooling#562]
While updating an existing RC1 project to RC2 I ran into this issue with the Visual Studio Tooling when publishing to Azure.  

When publishing with an existing profile you receive the following error from the Google Chrome and similar one from IE 

You do not have permission to view this directory or page.

Using stdout does not work(no files are created) and there are no entries in the eventlog.xml  the app simply does not run. 

Looking in Azure under the wwwroot directory there is no web.config file. So even though the deployment said it was successful something is not working correctly. 

So I performed the following steps. 
1. Going back into the publish profiles, I attempted to run through the wizard with the existing profile in the hopes that it would properly update the deployment scripts. This did not work. 
2. I created a separate profile to publish to a different Azure app area to see if that worked.. it did. 
3. Then I created another profile for the existing Azure deployment in #1 and redeployed. This worked. 

Looking at my PublishProfiles folder. I now have the following 
1.   Isprit - Web Deploy.pubxml 
2.   Isprit - Web Deploy-publish.ps1
3.   Isprit - Web Deploy(2)-publish.ps1 
4.   TestDeploy - Web Deploy-publish.ps1 

And my source control shows that the pubxml ( #1) has changed.... and that #3 and #4 are new files but the file for #2(which is the original profile) has not changed. 

I think that the behavior should be to overwrite this file when the wizard is stepped trough a second time.... especially given the fact that we are looking at more changes down the road with how these projects are structured. 

Thanks
AJ

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231145&fullScreen=false&_a=edit">231145</a>

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
