### ISSUE TITLE
Failed to make the following project runnable, RC 2 Tooling + Service Fabric

### ISSUE THREAD

**Issue by johnkattenhorn** [aspnet/Tooling#563]
We are deploying a DotNetCore MVC6 app into a Service Fabric Cluster which shares an assembly with other Service Fabric Cluster Services.

We've had to put in a post-build script to copy the output of the build for the shared assembly from bin\x64\$(ConfigurationName)* to bin\$(ConfigurationName) in order for the DotNetCore Project to build, looks like it might be something off with the Microsoft.DotNet.Common.Targets ? 

When we flipped the shared project to AnyCPU we get a different error

`Failed to make the following project runnable: xxxx`, it was looking for Newtonsoft.Json.Dll in bin\x64\$(ConfigurationName) when it was sitting in bin\$(ConfigurationName)

Not blocking as post-script step fixed it up for now.

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231144&fullScreen=false&_a=edit">231144</a>

**Comment by johnkattenhorn** [comment]
Thanks @sayedihashimi

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
