### ISSUE TITLE
Bower GUI only accept default source

### ISSUE THREAD

**Issue by Lenny32** [aspnet/Tooling#564]
Trying to add an external server into the ".bowerrc", the GUI is not working and only show the source from "http://bower.herokuapp.com/".
Also auto completion is not working directly in the "bower.json" file. 
If I enter the exact name of the package it is working!

> {
>  "directory": "wwwroot/lib",
>  "registry": {
>    "search": [
>      "https://bower.company.com",
>      "http://bower.herokuapp.com"
>    ]
>  },
>  "timeout": 300000
> }

It is also not possible to remove a package from the bower.json.

Thank you,

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231143&fullScreen=false&_a=edit">231143</a>

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
