### ISSUE TITLE
Core RC2 with wrapped .NET Framework Dlls

### ISSUE THREAD

**Issue by mikebm** [aspnet/Tooling#565]
I am using .NET Core RC2 and referencing .NET Framework dlls in it. To do this, I am using a "wrapped" dll, which I updated the wrap project.json to target framework net451.

My main project json that references the wrapped dll looks like:

```
{
  "version": "1.0.0-*",
  "description": "PS.Diagnostics.Middleware Class Library",
  "frameworks": {
    "net451": {
      "dependencies": {
        "SunGard.PS.Diagnostics": "1.0.0-*"
      }
    }
  },
  "dependencies": {
    "Microsoft.AspNetCore.Http.Abstractions": "1.0.0-rc2-final"
  }
}
```

My wrap project.json looks like:

```
{
  "version": "1.0.0-*",
  "frameworks": {
    "net451": {
      "bin": {
        "assembly": "../../Redist/SunGard.PS.Diagnostics.dll"
      },
      "dependencies": {
        "SunGard.PS.Diagnostics.Resources": "1.0.0-*"
      }
    }
  }
}
```

Now, the code compiles and runs fine. The issue is with intellisense and the Visual Studio errors panel. It shows errors for every line of code that uses the wrapped assemblies, and intellisense is completely missing.

I just updated to the Visual Studio 2015 Update 3 RC and the issue is still present.

**Comment by ddotlic** [comment]
This is not a small issue, coupled with an extension which removed unused usings (all false positives because the editor does not "see" types used from the wrapped assembly) - which amusingly does not work in .NET Core projects (thank God!) - this borks the source and it becomes uncompilable.

I'm assuming this is a silly oversight somewhere seeing how it worked like a charm in RC1.

**Comment by skyflyer** [comment]
A related (older) issue with relevant (current) comments: #45 (and no real solution, sadly).

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231142&fullScreen=false&_a=edit">231142</a>

**Comment by PhillipZada** [comment]
Just wondering if there is an eta on a resolution, as we are are holding migration to dotnet for a few projects that rely on older 451 libraries.

**Comment by lilpug** [comment]
I am also wondering what the eta on this fix is as you have hit RTM 1.0 and yet i cannot really create a windows .net core aspnet website using my libraries due to this.

**Comment by pantonis** [comment]
+1 Blocking issue. Lack of interest from tooling team. No assignee no milestone nothing.

**Comment by carlmon** [comment]
+1 the workaround is painful and impacting our productivity.

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still running in to this, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site
