### ISSUE TITLE
Error List freezing on Build on larger projects 

### ISSUE THREAD

**Issue by ArieJones** [aspnet/Tooling#567]
I have a larger solution involving 4 projects that I have moved from RC1 to RC2. During the conversion process I noticed and still notice that the Error List will freeze and not display all of the errors in a project. This is not some hardline limit like 1000 errors but randomly under 100. The number fluctuates. 

Additionally, when you rebuild it doesn't refresh the errors list without closing down and reopening VS or waiting an inordinate amount of time. The list is frozen basically. You cannot click on the error items to take you to the correct location in the code nor can you use to the keyboard shortcuts to do the same.

**Comment by sayedihashimi** [comment]
Can you share a sample project? My email is sayedha AT microsoftDOTcom.

**Comment by ArieJones** [comment]
I cannot .. it is a Medical EMR application for a client. Now that I have it ported over to RC2 and the error count is low...it is not doing it anymore.. but when the error count was up there it was a PIA because it would keep freezing up. 
This is with an I7 machine ...16GB RAM ... with 2 SSDs in it..... 
Additionally, we are running CodeRush ... but that has it's stuff running as a background process... 

Just letting you guys know before everyone tries to start porting over....

Thanks
AJ

**Comment by sayedihashimi** [comment]
OK, can you tell me a bit more about the project then? How many source files, how many projects in the solution?

**Comment by ArieJones** [comment]
little under 1000 files across 4 projects .... 1 MVC ....3 libraries

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231141&fullScreen=false&_a=edit">231141</a>

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
