### ISSUE TITLE
Deploying ASP.NET Core to Azure with Database

### ISSUE THREAD

**Issue by jbeen19** [aspnet/Tooling#576]
Anytime I have created an "ASP.NET Core Web Application" template and tried to deploy to Azure with setting up a database, always fails. If we publish to azure without the database settings, it will succeed.

I have a feeling it isn't a tooling problem, but an azure problem since MVC 6 is geared to .json, plus I haven't been able to figure out how to get my db string from azure to MVC even though it should be getting it from builder.AddEnvironmentVariables().

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231139&fullScreen=false&_a=edit">231139</a>

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
