### ISSUE TITLE
strange behaviors

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#579]
Hi, 
  I installed update 3 rc a few days ago, but I just started to have a problem, when I open a project the solution explorer window remains empty, but if I drag the source files in the editor everything is working fine.
![error1](https://cloud.githubusercontent.com/assets/127777/15989641/da698bc8-307c-11e6-9fd8-22216d9adced.png)
I receive no error but the windows remains empty.
another thing: I have a strange behavior with the extension and updates windows: continues to say that a few extensions are disabled, but instead are working

![error2](https://cloud.githubusercontent.com/assets/127777/15989657/2b342dce-307d-11e6-9dc8-dd31598dba52.png)
 the windows says that could explorer is disabled, but as you can see is currently working.

Is there any workaround?

**Comment by lucamorelli** [comment]
hmm ... for your informations... looks like I solved the problem of the disappearing solution explorer windows clearing the MEF cache, but I have still the strange issue of the cloud explorer that is working but shown as disabled

**Comment by sayedihashimi** [comment]
TFS: 231112

**Comment by AlexEyler** [comment]
Hey Luca - can you search on your computer to see if there are multiple Microsoft.VisualStudio.ConnectedServices.dll files? This looks like a repro of an issue with some extensions that depend on it.

**Comment by lucamorelli** [comment]
I found a lot of copies
```
 Directory di C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\0idl3k3k.l3s
26/05/2016  08:34            41.248 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\fq2ryko2.nql
11/06/2016  13:03            41.248 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\kxtd41tu.jte
18/03/2015  10:57            26.328 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\kybinjgv.rod
09/07/2015  10:42            41.248 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\otbdvwwe.tmz
30/03/2016  18:53            41.760 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\oybhfjnf.tdz
02/07/2015  07:17            41.248 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\p0tnsbil.i4a
09/07/2015  08:08            41.248 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\qor4afo2.hp0
24/07/2015  17:07            41.248 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\rgqtlur0.ytz
05/04/2016  19:30            41.248 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\sjccj00e.2ti
31/10/2015  01:06            41.256 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\toe52x2g.bno
29/04/2015  22:25            31.448 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\y5hgr1q2.d3r
09/06/2016  08:42            43.816 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Users\luca\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\leeibolb.igv\bin
26/05/2016  08:35            41.248 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Users\luca\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\ov20kr3t.4fx\bin
25/09/2015  16:21            41.248 Microsoft.VisualStudio.ConnectedServices.dll

 Directory di C:\Users\luca\AppData\Local\Microsoft\VisualStudio\14.0\Extensions\y0njv3o4.1zg\bin
25/09/2015  16:29            41.248 Microsoft.VisualStudio.ConnectedServices.dll
```

**Comment by AlexEyler** [comment]
Okay, here's a workaround for you that I think should fix things:

1. You need to find the "correct" DLL by searching for Microsoft.VisualStudio.ConnectedServices.Package2.dll. That should be right next the ConnectedServices.dll. You can verify that it's the correct location by looking at the ".vsixmanifest" file in the same directory and checking the extension's ID (should be ConnectedServices.897486C9-63BD-48D3-8A33-CB770FBD0723). If you have any ".vsixmanifest.deleteme" files, you should start Visual Studio as admin so we automatically remove them. Copy the path to the correct Microsoft.VisualStudio.ConnectedServices.dll.

2. Add the following to your devenv.exe.config file (it is located next to your devenv.exe, default location is C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\devenv.exe.config -- you'll need to open it as admin) under the <assemblyBinding> tag:

```
<dependentAssembly>
    <assemblyIdentity name="Microsoft.VisualStudio.ConnectedServices" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
    <codeBase version="2.0.0.0" href="{relative-path-to-ConnectedServices-from-current-directory}"/>
</dependentAssembly>
```

For example, my ConnectedServices.dll is located in `C:\Program Files (x86)\Microsoft Visual Studio 15.0\Common7\IDE\Extensions\lt2emwgv.uot\Microsoft.VisualStudio.ConnectedServices.dll`, so my entry in devenv.exe.config would look like this:
```
<dependentAssembly>
    <assemblyIdentity name="Microsoft.VisualStudio.ConnectedServices" publicKeyToken="31bf3856ad364e35" culture="neutral"/>
    <codeBase version="2.0.0.0" href="Extensions\lt2emwgv.uot\Microsoft.VisualStudio.ConnectedServices.dll" />
</dependentAssembly>
```

3. Open a developer command prompt (you can just search for "developer command prompt" via windows) and type the following command: `devenv /updateConfiguration`

4. Open VS and you should be able to get the solution explorer every time.


I'll reach out to members of the ConnectedServices team to confirm with them that a fix is in progress in the meantime. Let me know if you need any help

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
