### ISSUE TITLE
Request for clarification on scope of xproj

### ISSUE THREAD

**Issue by mgravell** [aspnet/Tooling#58]
What is the intended scope of xproj? Is it just "dnx, coreclr and multi-target libraries? Or put another way (and more specifically): is it intended that existing MVC projects continue to use csproj, leaving xproj alone?

(Basically, we had lots of problems looking at that, and I'm not sure whether to log as issues, or whether than scenario is explicitly out of scope)

**Comment by Eilon** [comment]
I think you can think of `xproj` as the Visual Studio companion file to `project.json`. Whereas `project.json` is all that's required by the runtime, VS has additional requirements.

`project.json` is used by all DNX-based projects, including the new console and class lib project types, as well as APS.NET 5 projects.

**Comment by mgravell** [comment]
Well, yes: I was implicitly referring to project.json and xproj as a pair.
If you're saying it should work fine for regular asp.net MVC, then I'm
going to have to file some more issues :)

**Comment by Eilon** [comment]
Existing MVC projects (that is, MVC 5.x and earlier) don't work on DNX, so they will stay `.csproj` and `.vbproj` (and maybe some `.fsproj`! :confused: ).

**Comment by mgravell** [comment]
Cool, that was the question. Thanks. I'll close this when I'm at a computer
(or anyone else can)
