### ISSUE TITLE
scaffolded items not discovered automatically in visual studio

### ISSUE THREAD

**Issue by ahmedanis03** [aspnet/Tooling#581]
adding a  new scaffold controller with views or controller alone are not discovered automatically in visual studio solution explorer  and visual studio needs a restart to discover them or I should add them manually.

repro steps: 
1) add new scaffold controller with views using entity framework
2) code generation output state that files generated correctly 
3) files won't be found in solution explorer even it exists in the project directory 

Expected Result:
the generated files to be discovered automatically

Actual Result:
Files not found in solution explorer

**Comment by sayedihashimi** [comment]
TFS: 231110

**Comment by prafullbhosale** [comment]
@ahmedanis03 Can you provide more details regarding the Visual Studio and OS version?
And also the project.json of your project?

**Comment by ahmedanis03** [comment]
dotnet --info output:
```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```
Visual studio:
2015 community, version: 14.0.25123.00 update 2

**Comment by mlorbetske** [comment]
This should be fixed in Visual Studio 2017
