### ISSUE TITLE
Unable to attach to CoreCLR. A debug component is not installed.

### ISSUE THREAD

**Issue by tmds** [aspnet/Tooling#584]
I've installed Nightly - 6/7/16. When I try to launch a project in VS, I get an error message:

> Unable to attach to CoreCLR. A debug component is not installed.

![coreclr_debug](https://cloud.githubusercontent.com/assets/1025424/16039338/7a753f06-3229-11e6-86ac-bc8231c93760.png)

Performing a repair with the tooling installer does not fix the issue.

**Comment by balachir** [comment]
@tmds, thanks for opening the issue. Can you provide some more info about your installation? What's the OS and bitness? And what build of VS do you have installed?

**Comment by sayedihashimi** [comment]
TFS: 231107

**Comment by tmds** [comment]
@balachir 
I am using `Windows 7 64 bit SP1` with `Visual Studio 2015 Professional 14.0.25402.00 Update 3 RC`.
In the programs and features I see 
```
.NET Core 1.0.0 RC3 - VS2015 Tooling Preview 2 (Nightly - 6/7) 1.0.20607.27
.NET Core 1.0.0 RC2 - SDK Preview1 x64 1.0.0.2913
.NET Version Manager x64 1.0.0-rc1 1.0.11123.0
```

**Comment by tmds** [comment]
@balachir what package is supposed to install the debug component?

**Comment by tmds** [comment]
@balachir @sayedihashimi any advice? What should I reinstall?

**Comment by balachir** [comment]
@tmds, we saw this [issue](https://github.com/dotnet/cli/issues/3473) with our internal testing as well on Win7 Sp1 x86 with the pre-release build 'Nightly 6/7/16'. We suspected it's an issue in the dotnet SDK but we were unable to reproduce with newer tooling builds (which include newer dotnet SDK). We are working towards making the next pre-release build available, and it should likely be available in the next day or two. If you cannot wait until then, the best alternative is probably to uninstall 'Nightly 6/7/16' and re-install the RC2 tooling.

**Comment by tmds** [comment]
@balachir thanks for the feedback, I'll wait a couple of days.

**Comment by tmds** [comment]
@balachir is an updated tooling available?

**Comment by balachir** [comment]
@tmds an updated tooling build ([Nightly 6/17/16](https://github.com/aspnet/Tooling/#pre-release-builds)) is available now. Do let me know if this issue is not fixed for you with this new build.

**Comment by tmds** [comment]
great! debugging works again!
