### ISSUE TITLE
Custom t4 scaffolding files not working in ASP.NET MVC under VS Community

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Tooling#585]
We have heard [reports in the SideWaffle repo](https://github.com/ligershark/side-waffle/issues/330) that users are having issues with using custom .t4 scaffolding files when using VS Community edition.

I think there is an issue with either the Add New Scaffolded item dialog or the underlying t4 support in VS Community edition.

**Comment by sayedihashimi** [comment]
TFS: 231106

**Comment by mlorbetske** [comment]
Closing this as it doesn't seem to be a general T4 problem (per the linked TFS item), but the specific templates the issue was reported with.
