### ISSUE TITLE
scaffolded views (span elements not closed probably) causing server side errors to not appear

### ISSUE THREAD

**Issue by ahmedanis03** [aspnet/Tooling#586]
## Issue:

span elements in generated views with asp-validation-for tag helper not showing the error when it comes from _server side_ and by closing the tag probably it works fine.

Generated not working span: 

```
 <span asp-validation-for="MobileNumber" class="text-danger" />
```

Correct span:

```
 <span asp-validation-for="MobileNumber" class="text-danger"></span>
```
#### Steps to repro:
1. Generate a view for posting a form
2. Make a server side validation fail like sending "asdf" to a field with [Phone] attribute 
3. The error message won't appear in the span
#### Expected Behavior:

error message appear in span 
#### Actual Behavior:

Nothing appears 
#### Environment Info:

Browser tested against: 
Chrome, Edge 

dotnet --info output:

```
.NET Command Line Tools (1.0.0-preview1-002702)

Product Information:
 Version:     1.0.0-preview1-002702
 Commit Sha:  6cde21225e

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.10586
 OS Platform: Windows
 RID:         win10-x64
```

Visual studio info:
2015 community, version: 14.0.25123.00 update 2

**Comment by sayedihashimi** [comment]
TFS Bug#231587

**Comment by ahmedanis03** [comment]
https://github.com/aspnet/Scaffolding/issues/227

**Comment by mlorbetske** [comment]
Per the associated TFS item & linked GitHub issue, this has been fixed. If you run in to this again in the future, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
