### ISSUE TITLE
Nuget private server source not working

### ISSUE THREAD

**Issue by Lenny32** [aspnet/Tooling#587]
I added in my Nuget source a private server with this command. 
`nuget.exe sources add -Name NameOfTheSource -Source https://nuget.domain.com -UserName email@domain.com -Password *******`
 
It is working with "Normal" application, unfortunaltly not with dotnet core. It is impossible to do a Nuget restore if you do not remove it.

**Comment by sayedihashimi** [comment]
TFS Bug#231586

**Comment by barrytang** [comment]
Moved to https://github.com/NuGet/Home/issues/2988.
