### ISSUE TITLE
NuGet update fails to work, when involving aspnet tooling?

### ISSUE THREAD

**Issue by rrelyea** [aspnet/Tooling#588]
Please see repro steps here:
https://github.com/NuGet/Home/issues/2976

Unsure if this was tested with the proper version of asp.net tooling installed. Can you please confirm that the behavior is better than we are seeing:

Scenario wise, this seems like it should be addressed before preview 2 ship, if it isn't already addressed.

**Comment by sayedihashimi** [comment]
TFS Bug#231585

**Comment by abpiskunov** [comment]
This is a PMS issue https://github.com/dotnet/cli/issues/3026 which i opened the end of RC2

We also could fix it form tooling side if needed

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
