### ISSUE TITLE
Incorrect ToolsVersion in csproj file for ASP.NET 4.6 Web Application templates

### ISSUE THREAD

**Issue by coxp** [aspnet/Tooling#59]
When adding a new project in Visual Studio 2015 RC using File-New->Project and choosing a template under ASP.NET Web Application->ASP.NET 4.6 Templates, the ToolsVersion of the generated csproj file is 12.0 instead of 14.0.

**Comment by sayedihashimi** [comment]
Adding @rustd

**Comment by rustd** [comment]
This was fixed with VS 2015 RTM.
