### ISSUE TITLE
Manage User Secrets tool does not generate a unique `userSecretsId`

### ISSUE THREAD

**Issue by dougbu** [aspnet/Tooling#591]
At least, not as unique a `userSecretsId` as the templates generate. Like the templates, the Manage User Secrets tool should use a GUID and not a datetime when generating a `userSecretsId` value.

In the snip below, the WebApp.Individual solution was generated from a template and contains a truly unique secrets identifier. I added user secrets to the WebApp.NoAuth solution.
![folders](https://cloud.githubusercontent.com/assets/6431421/16101103/e5a4c6ea-3317-11e6-825a-377b0355762d.png)

**Comment by sayedihashimi** [comment]
TFS Bug#232007

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been fixed.
