### ISSUE TITLE
RC2 compiles much slower than RC1

### ISSUE THREAD

**Issue by ryanhall27** [aspnet/Tooling#592]
I can't seem to find anything about this anywhere, so please tell me if I am posting this in the wrong spot.  

Every project in RC2 seems to take a minimum of 1 second to compile.  Even a class library with 1 class in it.  In RC1, it compiles in .01 seconds.  See the attached screenshot, RC2 on the left and RC1 on the right.

![rc1vsrc2compile](https://cloud.githubusercontent.com/assets/3359985/16105571/33d1e85a-3351-11e6-9b31-d0bc885c4b48.jpg)

I'm seeing this in both my personal projects as well as work projects.  This wouldn't be a big issue if I always had 1 project to compile, but most of the time, i have around 5 class libraries + mvc project.

Does anyone know anything about this issue?

**Comment by BrennanConroy** [comment]
Probably want to post that at https://github.com/dotnet/cli

**Comment by ryanhall27** [comment]
ok, will do, thanks!
