### ISSUE TITLE
Go To Definition takes you to wrong place for CSS classes

### ISSUE THREAD

**Issue by esargent** [aspnet/Tooling#596]
in cshtml file I have a tag with a CSS class defined: `<div class="mystylerule">`

When I right click `"mystylerule"` and select Go To Definition, it opens up a CSS file to the correct rule, but it opens up the file that's part of the "compiled" project - `\bin\debug\net452\win7-x64\publish\wwwroot\css\main.less`, not the source file as expected.

I started editing this file, but realized I had two main.less files open right next to each other. Otherwise this could have led to loss of data (the edits I was making)

**Comment by sayedihashimi** [comment]
TFS Bug#232439

**Comment by mlorbetske** [comment]
This issue was moved to madskristensen/WebEssentials2015#253
