### ISSUE TITLE
aspnetcore.dll failed to load

### ISSUE THREAD

**Issue by teovc** [aspnet/Tooling#597]
Every time a new build is installed, the system stops loading correctly the dll aspnetcore.

Error message in "Event Viewer":
**The Module DLL C:\WINDOWS\system32\inetsrv\aspnetcore.dll failed to load.  The data is the error.**
Log Name: Application
Source: IIS-W3SVC-WP
Level: Error

**Relevant System information:**
OS Name:                   Microsoft Windows 10 Enterprise Insider Preview
OS Version:                10.0.14366 N/A Build 14366
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Product ID:                00359-80000-00001-AA999
Original Install Date:     6/16/2016, 6:37:31 AM
System Boot Time:          6/16/2016, 6:11:50 AM
System Manufacturer:       Hewlett-Packard
System Model:              HP Z420 Workstation
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 45 Stepping 7 GenuineIntel ~3201 Mhz
BIOS Version:              Hewlett-Packard J61 v03.06, 3/27/2013
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     16,307 MB
Available Physical Memory: 7,019 MB
Virtual Memory: Max Size:  19,251 MB
Virtual Memory: Available: 6,503 MB
Virtual Memory: In Use:    12,748 MB
Page File Location(s):     C:\pagefile.sys
Hotfix(s):                 N/A
Network Card(s):           1 NIC(s) Installed.
                           [01]: Intel(R) 82579LM Gigabit Network Connection
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: No
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by sayedihashimi** [comment]
TFS Bug#232438

**Comment by barrytang** [comment]
Moved to https://github.com/aspnet/Home/issues/1583.
