### ISSUE TITLE
Discussion for nightly build 'Nightly - 6/17/16'

### ISSUE THREAD

**Issue by balachir** [aspnet/Tooling#599]
This is a discussion thread for [pre-release build 'Nightly - 6/17/16'](https://github.com/aspnet/Tooling/#pre-release-builds).

**Comment by Bartmax** [comment]
Is there a list of issues resolved for each tooling version or anyway to get that info? Anything will do.

**Comment by peterblazejewicz** [comment]
> Is there a list of issues resolved for each tooling version or anyway to get that info? Anything will do.

https://github.com/aspnet/Tooling#release-notes-and-known-issues

**Comment by Bartmax** [comment]
@peterblazejewicz thanks, still that's not very helpful. I think I'm more interested on details of:
> Includes a new pre-release .NET Core SDK (version 1.0.0-preview2-003041) and .NET Core (version 1.0.0-rc3-004459-00)

**Comment by kuma17** [comment]
I have a problem with nuget when create a class library project (portable) and setting .netstandard 1.5.
When open nuget manager in tab "installed" I see no package but a message "Error occurred"

The schema version of 'NETStandard.Library' is incompatible with version 2.11.1.812 of NuGet. Please upgrade NuGet to the latest version from http://go.microsoft.com/fwlink/?LinkId=213942.

I update neget with last version (3.0.5.1284) but I have some problem

**Comment by mikes-gh** [comment]
The release notes should be referencing the github issues.
The current release notes are just to vague for anyone with specific issues.

**Comment by lucamorelli** [comment]
I cannot install it i
n my configuration: I have this error message

![untitled](https://cloud.githubusercontent.com/assets/127777/16277701/5f5ad852-38b4-11e6-98a6-60347f7d5278.png)

Uninstalled the previous nightly and repaired the vs didn't solve the problem.

**Comment by balachir** [comment]
@lucamorelli did you look at the [Known Issues](https://github.com/aspnet/Tooling#release-notes-and-known-issues) for this build? I suspect you are running into the known issue with the detection logic. The workaround is to run the EXE from a command prompt and then pass SKIP_VSU_CHECK=1 at the end. That should do the trick for you.

**Comment by onovotny** [comment]
The release notes say that this runtime doesn't support publishing to Azure "by default." What's the workaround to publish it anyway?

**Comment by lucamorelli** [comment]
thanks, I solved with that flag. Now I created a new asp.net core web app and recompiling I have this message

```
Severity	Code	Description	
Error	NU1002	The dependency Microsoft.AspNetCore.Mvc 1.0.0-rc3-21343 does not support framework .NETCoreApp,Version=v1.0.	
Error	NU1002	The dependency Microsoft.DotNet.Cli.Utils 1.0.0-preview2-003024 does not support framework .NETCoreApp,Version=v1.0.	
Error	NU1002	The dependency Microsoft.DotNet.ProjectModel.Loader 1.0.0-preview2-003024 does not support framework .NETCoreApp,Version=v1.0.	

```

**Comment by drieseng** [comment]
Since updating to this nightly, **dotnet** always yields the following error:

_Failed to load the dll from [], HRESULT: 0x80070057_

Enabling corehost tracing doesn't provide more info:

_--- Invoked dotnet [version: 1.0.1, commit hash: cee57bf6c981237d80aa1631cfe83cb9ba329f12] main = {
dotnet
}
Failed to load the dll from [], HRESULT: 0x80070057
Load library of  failed_

This is on W10 x64.

**Comment by onovotny** [comment]
@drieseng try clearing your NuGet cache. There's been a lot of churn and rev'ing in-place:

`nuget locals all -clear`

**Comment by drieseng** [comment]
@onovotny This doesn't have anything to do with the NuGet cache. I get that error even when I run **dotnet** without any arguments. So even when I'm not trying to build or restore.

Clearing NuGet cache and re-install of the CLI tools had no effect.

**Comment by balachir** [comment]
@drieseng you can try opening an issue in the [dotnet cli repo](https://github.com/dotnet/cli/issues), that's probably the best way to investigate this issue further.

**Comment by alexanderxe** [comment]
I got this back when I resumed the ReSharper in VS Options. I suspended again ReSharper and cleaned the local nuget cache and I manage to get it working again. 

I am using JetBrains ReSharper Ultimate 2016.2 EAP 5 Build 106.0.20160623.165258-eap5 and I have reported this to JetBrains.

**Comment by mlorbetske** [comment]
Closing this since the build this discussion is for is over a year old
