### ISSUE TITLE
Task Runner Explorer: console.warn not supported

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#600]
TRX supports the `console.log` JavaScript function with ease; however, it seems to ignore `console.warn`. An easy way to reproduce this is by using the following Gulp tasks:

``` javascript
gulp.task("clean:js", function (cb) {
    rimraf(paths.concatJsDest, cb);
    console.warn("cleaned JavaScript");
});

gulp.task("clean:css", function (cb) {
    rimraf(paths.concatCssDest, cb);
    console.log("cleaned CSS");
});

gulp.task("clean", ["clean:js", "clean:css"]);
```

Running the "clean" task yields the following output in TRX:
![trx_output](https://cloud.githubusercontent.com/assets/10702007/16216492/c0be875e-3730-11e6-872d-1bdc33d753cd.png)

Notice that the `console.warn` output is missing. I'm using VS 2015 Update 2.

**Comment by ctolkien** [comment]
We're hitting a similar issue here but for `console.error()`. We intercept errors in our gulp streams (via [gulp-plumber](https://www.npmjs.com/package/gulp-plumber)) and output them with `console.error()`.

Using this method, we don't get any error messages presented in the TRX window. We use this for spitting out things like compilation issues with less.

**Comment by rendmath** [comment]
Same problem here with gulp-typescript, that uses console.error to output compilation errors (see: [reporter.js](https://github.com/ivogabe/gulp-typescript/blob/master/release/reporter.js)). Parts of the error messages are output with gutil.log, which only makes it more confusing because those ones are rendered.

**Comment by barrytang** [comment]
TFS Bug#235763

**Comment by scottaddie** [comment]
@ctolkien @rendmath I can confirm that this issue is fixed for me after installing the ASP.NET Core tooling Preview 2. See Mads' comment in the referenced issue. Have you two tried this yet?

**Comment by mlorbetske** [comment]
From the linked issue & the comment from @scottaddie, it looks like this is fixed, so closing this issue. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site.
