### ISSUE TITLE
BundlerMinifier.Core does not support net452

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Tooling#603]
NuGet Restoring fails if net452 used as follows:
    "frameworks": {
        "net452": {}
    },

**Comment by BillHiebert** [comment]
@madskristensen @mlorbetske

**Comment by mlorbetske** [comment]
@xatabhk just checking, the reference to BundlerMinifier.Core is in the tools section of your project.json and not the dependencies section right?

**Comment by xatabhk** [comment]
@mlorbetske Either way, the same error.

**Comment by mlorbetske** [comment]
@xatabhk this issue was discussed here https://github.com/madskristensen/BundlerMinifier/issues/140 in the context of net461. If you use the example by @madskristensen here https://github.com/madskristensen/BundlerMinifier/wiki#command-line-interface-net-core, does it work?

**Comment by xatabhk** [comment]
@mlorbetske That only enables the package to be  restored. But building fails. Error message:
1>  Project ZaxiTech_demo (.NETFramework,Version=v4.5.2) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
1>  Compiling ZaxiTech_demo for .NETFramework,Version=v4.5.2
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(261,5): error : The specified framework 'Microsoft.NETCore.App', version '1.0.0-rc2-3002702' was not found.
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(261,5): error :   - Check application dependencies and target a framework version installed at:
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(261,5): error :       C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(261,5): error :   - The following versions are installed:
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(261,5): error :       1.0.0
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets(261,5): error :   - Alternatively, install the framework version '1.0.0-rc2-3002702'.

**Comment by mlorbetske** [comment]
@xatabhk Now that .NET Core 1.0.0 has been released (and the version of Bundler Minifier that uses it has been made public), this should be resolved. Can you try again to verify please?

**Comment by xatabhk** [comment]
It got fixed.
