### ISSUE TITLE
Cannot connect to IIS Express if sslPort is set to 443

### ISSUE THREAD

**Issue by xatabhk** [aspnet/Tooling#605]
"iisSettings": {
    "windowsAuthentication": false,
    "anonymousAuthentication": true,
    "iisExpress": {
      "applicationUrl": "http://localhost:62374/",
      "sslPort": 443
    }
![iisexp_error](https://cloud.githubusercontent.com/assets/6814395/16238534/655addde-3813-11e6-986f-16b654eb711f.png)

**Comment by BillHiebert** [comment]
@xatabhk  
See http://benjii.me/2014/11/run-iis-express-on-port-443-using-ssl-and-wildcard-subdomains/

Especially the section titled Now using HTTPS and SSL

Note that you must run VS elevated to for this to work
