### ISSUE TITLE
Core Class Library with Dependent c# Class Library  Added to Core Web Application

### ISSUE THREAD

**Issue by ToddThomson** [aspnet/Tooling#608]
I am using EF6 within a c# class library to provide a data access/repository service. I then have a core class library which provides business services which is dependent on the repository dll.
In VS ( with preview 2 tooling ) I have a core library that defines the dependency with:

```
"frameworks": {
    "net451": {
        "dependencies": {
            "Acme.Pages.Data": {
                "target": "project" <-- change this to "package" to get around the issue 
            }
        }
    }
},
```

This project builds perfectly.

However, when I add the core class library to a core web application ( add existing project ) the core class library still compiles, but within the vs solution all the 'using' namespace references to the data access c# library now show an error ( "are you missing an assembly reference" ).

The core class library still shows the reference to the c# data access c# library.

Thanks in advance for any help figuring this out.

[EDIT] I got around this issue by creating a Nuget package for the c# class library and then using "target":"package" ( see above ) in the dependencies for the core class library.

**Comment by ToddThomson** [comment]
Is this due to the core class library when packed only includes the core class library dll and does not include the c# data access c# library dll?
Is it the case that nuget packages now only include a single dll and that all dependencies also need to be  nuget packages?
My assumption was that the c# library dependent dll would be included in the core class library package. This appears to be wrong and I will need to make another nuget package to include the c# class library dll.

**Comment by ToddThomson** [comment]
In the current VS tooling is there a way to automate the ```dotnet pack``` on the c# class library build?

**Comment by ToddThomson** [comment]
Little bit of a learning curve with Nuget packaging in dotnet core tooling!

**Comment by barrytang** [comment]
TFS Bug#235759

**Comment by mlorbetske** [comment]
Sorry for the delay in responding. We've done a lot of work to smooth these experiences out in Visual Studio 2017, if possible, we recommend using the newer tools to get the best experience. I'm glad you were able to get it working by creating a package from the library to use for the reference, there is not, to my knowledge a built in gesture for creating NuGet packages in Visual Studio 2015 (there is on the right click menu on projects in Visual Studio 2017).
