### ISSUE TITLE
consider put new project default location to src subdir

### ISSUE THREAD

**Issue by cuiliang** [aspnet/Tooling#61]
There is more opportunity user need  to create project into 'src' or 'test' dir.
If user ignored to change the default location, project will be in root dir, then if user move project to 'src' or 'test' dir mannualy, there will be another 'artifacts' in src or test dir.

I think it's better to put new project into src subdir, even if a user want create a test project, they can mannualy move project to test dir without new 'artifacts' dir created.

Another option is allow user select subdir from the 'Add new project' dialog. like this:
![image](https://cloud.githubusercontent.com/assets/1972649/7486987/2d9d5376-f3e1-11e4-9e56-49842f882013.png)

**Comment by herecydev** [comment]
:+1: Although I think it should just be src. Then have a seperate vnext test template that defaults to $slndirectory$/tests

**Comment by sayedihashimi** [comment]
Thanks for the feedback guys. Since this option would be available for project beyond ASP.NET 5 this is not the correct repo for this request. I think the best place for this is likely http://visualstudio.uservoice.com/forums/121579-visual-studio. I'll close this now.
