### ISSUE TITLE
Referencing a net452 csproj class gives an error using sdk 1.0.0-rc2-002542

### ISSUE THREAD

**Issue by erwindevreugd** [aspnet/Tooling#610]
I have a solution with a Asp.net core site that only targets net452.
Within that Asp.net core project I have a reference to a class lib project (csproj) that targets framework 452.

project.json:

```
"frameworks": {
        "net452": {
            "dependencies": {
                "csproj_name": {
                    "target": "project"
                }

            }
        }
    }
```

global.json:

```
{
    "projects": [ "wrap" ],
    "sdk": {
        "version": "1.0.0-preview2-003121"
    }
}
```

and a project.json file is located within the wrap folder within the Asp.net core project.

Using sdk 1.0.0-preview2-003121 this setup works, changing the sdk value in the global.json to 1.0.0-rc2-002543 breaks it. A package restore then gives an error that a csproj project cannot be found that
targets netframework 4.5.2.

Changing the sdk value back fixes it.

Environment:

Dotnet 1.0.0-rc2-002543

Microsoft Visual Studio Community 2015
Version 14.0.25123.00 Update 2
Microsoft .NET Framework
Version 4.6.01038

Visual Basic 2015   00322-20000-00000-AA466
Visual C# 2015   00322-20000-00000-AA466
Visual C++ 2015   00322-20000-00000-AA466
Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA466
Application Insights Tools for Visual Studio Package   1.0
ASP.NET and Web Tools 2015.1   14.1.20512.0
ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
Azure App Service Tools v2.9   14.0.20316.0
Azure Data Lake Node   1.0
Azure Data Lake Tools for Visual Studio   2.0.6000.0
Common Azure Tools   1.7
GitHub.VisualStudio   1.0
JavaScript Language Service   2.0
JavaScript Project System   2.0
Microsoft .NET Core Tools (Preview 1)   14.1.20512.0
Microsoft Azure HDInsight HQL Service   2.0.6000.0
Microsoft Azure HDInsight Tools for Visual Studio   2.0.6000.0
Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Tools   2.9
NCrunch   
Node.js Tools   1.1.30902.01
Node.js Tools - Profiling   1.1.30902.01
NodejsUwp   1.0
NuGet Package Manager   3.4.4
Open Command Line   2.1.175
PreEmptive Analytics Visualizer   1.2
Python Tools for Visual Studio   2.2.40315.00
Python Tools for Visual Studio - Django Integration   2.2.40315.00
Python Tools for Visual Studio - Profiling Support   2.2.40315.00
SQL Server Data Tools   14.0.60311.1
Microsoft SQL Server Data Tools
ToolWindowHostedEditor   1.0
TypeScript   1.8.31.0
TypeScript tools for Visual Studio
Visual Studio Tools for Apache Cordova   Update 10
Visual Studio Tools for Apache Cordova
Visual Studio Tools for Universal Windows Apps   14.0.25219.00
Web Compiler   1.11.315
Web Essentials 2015.2   2.0.219
Xamarin   4.1.0.530 (2e39740)
Xamarin.Android   6.1.0.71 (4e27558)
Xamarin.iOS   9.8.0.323 (39ebb77)

**Comment by barrytang** [comment]
TFS Bug#235757

**Comment by mlorbetske** [comment]
@erwindevreugd is there a reason you need to use 1.0.0-rc2-002543? Preview 2 tools are the current version

**Comment by erwindevreugd** [comment]
No there isn't actually. I guess I got confused about what the latest version was. Thanks!

**Comment by sayedihashimi** [comment]
@erwindevreugd it sounds like this is not an issue based on the comments here. I'll close this now but if I misunderstood please reopen with more details.
