### ISSUE TITLE
Question: How to setup a post build event script

### ISSUE THREAD

**Issue by ToddThomson** [aspnet/Tooling#611]
With a regular c# class project I can perform a nuget.exe pack command using the Post Build event. This allows me to create a nuget package and move it to an output folder so that I can use it locally for testing.
How is this done with a core class library?
Where did the "Generate Outputs on Build" project setting go?

**Comment by GuardRex** [comment]
@ToddThomson Can you make use of `postcompile` in `scripts` of `project.json`?
```json
"scripts": {
    "postcompile": "<action_here>"
},
```

**Comment by ToddThomson** [comment]
@GuardRex It appears that "postcompile" is launched for every file compiled in the project.

I just want to run the ```dotnet pack -o c:\nuget.local``` once the project has been successfully built and outputs have changed.

**Comment by GuardRex** [comment]
Interesting. I've only used `precompile` in one project. How about `postpack`? http://json.schemastore.org/project

**Comment by ToddThomson** [comment]
@GuardRex It's just that the VS Tooling isn't quite there yet. I was hoping that perhaps someone in the tooling group could help me out, but I guess they're all busy with the upcoming RTM and VS Tools preview 2. Hopefully the pre and post build events will be available then.

**Comment by barrytang** [comment]
TFS Bug#235756

**Comment by mlorbetske** [comment]
@ToddThomson could you try the suggestion here https://github.com/dotnet/cli/issues/3066#issuecomment-222333939 ?

**Comment by mlorbetske** [comment]
Pre & post build events are now readily available with the .NET Core MSBuild tooling

**Comment by Ziflin** [comment]
It doesn't look like the "Macros" -- $(ProjectDir) and others -- are being passed into the Pre-build or Post-build events in 2017 RC.4+26206. @mlorbetske do you happen to know if this is a known bug? If not do you know where it is best to file it? Thanks!

**Comment by mlorbetske** [comment]
It looks like (and you've already found it) that this is now being discussed over at https://github.com/dotnet/sdk/issues/677

**Comment by Ziflin** [comment]
(Yup, thanks! I thought I could delete my comment it before anyone noticed :).
