### ISSUE TITLE
CSS Linter. Issue with rule.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#613]
What's the linter extension installed by default on VS 2015 ? Where are documentation?

```
.card-columns.card-columns-2 {
    -ms-column-count:2;
    -webkit-column-count: 2;
    -moz-column-count: 2;
    column-count: 2;
}
```

this rule gives me this warning:

```
 "-ms-column-count" is not a known CSS property name.
```

when I remove the `-ms-column-count:2;`
it gives me this error:

```
The property -ms-column-count is compatible with -webkit-column-count and -moz-column-count and should be included as well.
```

I don't like to have warnings but this one looks like a no-go.

Also, I use the !important in one place (I know what I'm doing). How can I disallow the warning for that particular piece of code?

**Comment by barrytang** [comment]
TFS Bug#235754

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
