### ISSUE TITLE
Update to tooling preview 2 tools fails

### ISSUE THREAD

**Issue by pantonis** [aspnet/Tooling#616]
Hi.

I have downloaded preview tooling 2 from https://go.microsoft.com/fwlink/?LinkId=817245
Once I run the installer I get:

![image](https://cloud.githubusercontent.com/assets/3295086/16388283/1d7d0c0c-3ca1-11e6-8363-3f3596facf15.png)

This is strange because I have vs2015 update 3 rc installed.
![image](https://cloud.githubusercontent.com/assets/3295086/16388317/3926fe9a-3ca1-11e6-9f07-1d3fb405b792.png)

**Comment by balachir** [comment]
@pantonis you need the [RTW version of VS 2015 Update 3](https://www.visualstudio.com/news/releasenotes/vs2015-update3-vs), which became available today as well.

**Comment by pantonis** [comment]
didnt know. perfect. thanks.

One last thing. Do I need the following or is it ok if I uninstall them?

![image](https://cloud.githubusercontent.com/assets/3295086/16388680/dd4cddb8-3ca2-11e6-82ae-81ec9d6f15e7.png)

**Comment by balachir** [comment]
Installing the VS 2015 tooling for .NET Core 1.0.0 should upgrade you from the RC2 VS 2015 tooling. The .NET Core 1.0.0 SDK is side-by-side with .NET Core 1.0.0 RC2 SDK, so you would need to manually uninstall the RC2 one if you don't need it anymore. 

Not sure why the ASP.NET 5 entries are still showing up. You can either leave them alone (should not impact the new install) or uninstall them if you want to clean them out.

**Comment by pantonis** [comment]
Thanks
