### ISSUE TITLE
Migrating from grunt to gulp is bumpy

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Tooling#62]
I tried to migrate my existing ASP.NET 5 web app from grunt to gulp by renaming `gruntfile.js` to `gulpfile.js` and filling it with the contents from the "Web Site" template. In that setup, the Task Runner Explorer Output complained that it could not find the `gulp` command when executing `cmd.exe /c gulp -b ...`. Reloading the project didn't make it work, but restaring VS eventually did.

It was quite confusing why a manually created "Web Site" project would work, but my own project didn't.

**Comment by sayedihashimi** [comment]
@madskristensen ?

**Comment by madskristensen** [comment]
There is no direct migration path between the two other than articles found around the web. Grunt and Gulp are both fully supported in Visual Studio and which one you use is a matter of personal preference.
