### ISSUE TITLE
Incorrect casing in Bower item template description

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#622]
The "Bower Configuration File" item template will create a file named `bower.json`. The template's description should reflect that name exactly. Please convert the uppercase "B" to lowercase.

![bowerjson](https://cloud.githubusercontent.com/assets/10702007/16420128/cca22018-3d15-11e6-9eca-b4e47680288a.png)

The screenshot above depicts what I'm seeing in VS 2015 Update 3.

**Comment by sayedihashimi** [comment]
Moved to https://github.com/aspnet/Templates/issues/637
