### ISSUE TITLE
Bower Configuration File template not producing .bowerrc for .NET Framework

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#623]
In Visual Studio 2015 Update 3, follow these steps to reproduce:
1. File -> New -> Project
2. Select the "ASP.NET Web Application (.NET Framework)" project template. In my case, I had .NET 4.6.1 selected in the drop-down.
3. Add a new item and select the "Bower Configuration File" item template

Notice that the `bower.json` file was generated; however, the `.bowerrc` file was not created:

![bowerrc_missing](https://cloud.githubusercontent.com/assets/10702007/16421027/3974d606-3d19-11e6-96ff-5e2e21b0d321.png)

The item template's behavior in a .NET Core application should match that in a .NET Framework application. In the .NET Core ASP.NET projects, both the `bower.json` and the `.bowerrc` files are created:

![aspnetcore_bowerrc](https://cloud.githubusercontent.com/assets/10702007/16421161/ad8ae7d8-3d19-11e6-83a2-e4c1b8f01032.png)

**Comment by sayedihashimi** [comment]
Moved https://github.com/aspnet/Templates/issues/638

**Comment by phenning** [comment]
For WAPs, we don't need a .bowerrc file since WAPs just use the default bower_components folder. DotNet projects require it though since we need to put the content in wwwroot
