### ISSUE TITLE
.NET Core SDK in VS2015 Update 3 is version 5.0 instead of 1.0

### ISSUE THREAD

**Issue by i3arnon** [aspnet/Tooling#625]
While installing Update 3 RTM it shows installation of "Microsoft .NET Core 5.0 SDK":
![image](https://cloud.githubusercontent.com/assets/6595156/16428116/1b87221a-3d79-11e6-97d1-090666322c0f.png)

I'm assuming 5.0 is wrong here and should be 1.0.

Here's the tweet that sparked the whole thing: https://twitter.com/i3arnon/status/747833940031967232

**Comment by barrytang** [comment]
TFS Bug#235748

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
