### ISSUE TITLE
Microsoft.Net.Compilers is forcing old version of System.Collections.Immutable

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Tooling#626]
I cross-creating the issue here, not sure if the problem is in roslyn package or something in tooling.
https://github.com/dotnet/roslyn/issues/12255

**Version Used**: 
VS 2015 Update 2

**Steps to Reproduce**:

1. Create an empty web application project TFM 4.6.1. The template contains reference to the package `Microsoft.Net.Compilers` version `1.0.0`.
2. Add package reference to `System.Collections.Immutable` version `1.2.0`

**Expected Behavior**:
Get a reference to `C:\Users\user\Documents\Visual Studio 2015\Projects\WebApplication4\packages\System.Collections.Immutable.1.2.0\lib\portable-net45+win8+wp8+wpa81\System.Collections.Immutable.dll`

**Actual Behavior**:
Got a reference to `C:\Users\user\Documents\Visual Studio 2015\Projects\WebApplication4\packages\Microsoft.Net.Compilers.1.0.0\build\..\tools\System.Collections.Immutable.dll`

**Comment by barrytang** [comment]
TFS Bug#235747

**Comment by mlorbetske** [comment]
The primary discussion on this is on dotnet/roslyn#12255
