### ISSUE TITLE
Unable to build Vs sln after install update 2015 update 3 and .net core

### ISSUE THREAD

**Issue by DeepakRajendranMsft** [aspnet/Tooling#627]
Hi, 

I get the following error when I try to open/build my sln (https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Network/)

Severity	Code	Description	Project	File	Line	Suppression State
Error		The .NET Core SDK is not installed or cannot be found under the path C:\Program Files\dotnet\bin. These components are required to build and run this project. Download the version of .NET Core SDK specified in global.json or update the SDK version in global.json to the version that is installed.	Microsoft.Azure.Management.Network	C:\git\Azure\azure-sdk-for-net\src\ResourceManagement\Network\Microsoft.Azure.Management.Network\GETSDKTOOLINGINFO	
I tried installing the workaround mentioned @ https://github.com/aspnet/Tooling/blob/master/known-issues.md#missing-sdk but it doesn't seem to work. Is there anything else I should be trying to do?

Thanks,
Deepak.

**Comment by barrytang** [comment]
TFS Bug#235746

**Comment by DeepakRajendranMsft** [comment]
the issue is resolved after removing all *Cli* from programs and reinstalling RC2
