### ISSUE TITLE
Publishing to IIS with a Web Site Project causes ACLs to be overwritten

### ISSUE THREAD

**Issue by RickStrahl** [aspnet/Tooling#628]
The Visual Studio Publish behavior in a Web Site project apparently causes ACLs to be overridden. I didn't realize this since I rarely have Web Site projects that contain code where this matters, but I added some file writing code recently that failed due to ACLs not being set. Set the ACLs properly so writes would work, then published and the ACLs are gone.

This behavior is not expected and also doesn't match the behavior of other Web Project types which leave the ACLs on the target alone. Please change the default behavior.

I realize this setting can be overridden with:

``` xml
<IncludeSetAclProviderOnDestination>False</IncludeSetAclProviderOnDestination>
```

But this is not very easy to remember or discover. Perhaps if there was an option for this, but I still believe that 90% of the time you do not want to set ACLs on the server. Further I'm not clear what ACL settings are made - they certainly are not being copied from the client side settings (ie. I have NETWORK SERVICE set on my project folder, but that's not making it to the server so it appears the default just removes ACLs completely which is very disruptive).

**Comment by sayedihashimi** [comment]
Thanks @RickStrahl, I've heard this before from other users as well. I never truly understood why we decided to use that as the default (the decision predated me). I think it would be fine to create new profiles which set this value to `false`. That way for users who truly do want that behavior they can open the .pubxml and set it to `true`.

**Comment by RickStrahl** [comment]
Yup that sounds like the right choice. I assume the other project choices have this setting as false because I'm pretty sure it's not happening for Web applications.

Thanks for looking into this.

**Comment by sayedihashimi** [comment]
Unless we changed it recently and I forgot (which is possible) Web App Projects do this as well.

**Comment by mlorbetske** [comment]
TFS Bug#241360

**Comment by mlorbetske** [comment]
This should no longer happen in Visual Studio 2017 - ACLs are no longer set on the destination
