### ISSUE TITLE
For multi-target class library, debugger sometimes refuses to believe file is unchanged

### ISSUE THREAD

**Issue by mgravell** [aspnet/Tooling#63]
Breakpoints etc don't get hit; "The source code is different from the original version", when no: it isn't.

Repro is tricky, but affects [dapper](https://github.com/StackExchange/dapper-dot-net) - load the dnx sln, put a break-point in `QueryImpl<T>`, and run the Dapper.DNX.Tests project (in debug mode).

This issue does not affect the non-DNX solution when using the same IDE (RC)

**Comment by sayedihashimi** [comment]
@mgravell sorry for the delay here. Are you still having issues here? If so could you include some specific steps that we can follow?

**Comment by sayedihashimi** [comment]
Closing since we haven't heard back.
