### ISSUE TITLE
Could we have lightweight template?

### ISSUE THREAD

**Issue by miloush** [aspnet/Tooling#630]
Something between Empty and Web?
That wouldn't have any packages, javascript code or functional structure - just say one static view and one controller saying hello? Kind of minimum MVC...

**Comment by miloush** [comment]
Because currently when you want to create a new project, you either go with Empty and don't really know what you need, or you go with Web, deleting everything until it breaks...

The Web template is good for learning how to do things, but not to do them.

**Comment by barrytang** [comment]
Moved to https://github.com/aspnet/Templates/issues/642.

**Comment by miloush** [comment]
Thanks @barrytang, haven't realized there is a separate repo!
