### ISSUE TITLE
How to run (tests) on .NET 4.x in Visual Studio?

### ISSUE THREAD

**Issue by ericwj** [aspnet/Tooling#634]
All my projects have a .NET Core TFM and a `net451` node in `project.json`, but I'm missing I believe it was a project option in RC1/RC2 to change which target framework is used e.g. when running tests in Visual Studio. I tried to set `sdk/runtime: clr` in `global.json`, but that didn't have any effect.

How do I run my tests against full framework?

**Comment by barrytang** [comment]
@jinujoseph ?

cc @srivatsn

**Comment by jinujoseph** [comment]
This document should be handy http://xunit.github.io/docs/getting-started-dotnet-core.html
{
    "frameworks": {
        "net451": {
            "dependencies": {
                "Microsoft.NETCore.Platforms": "1.0.1"
            }
        }
    }
}
If this doesn't unblock you feel free to send your project.json configuration.

**Comment by ericwj** [comment]
Well I said that I have that in my project.json - not the platforms dependency, but both TFMs: `net451` and `netcoreapp1.0`.

But after adding the platforms dependency, Ctrl+R Ctrl+T will show:
```
'dotnet.exe' (CoreCLR: DefaultDomain): Loaded 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\1.0.0\System.Private.CoreLib.ni.dll'. Skipped loading symbols. Module is optimized and the debugger option 'Just My Code' is enabled.
(...)
'dotnet.exe' (CoreCLR: clrhost): Loaded 'C:\Users\Eric\Source\Local\Project\test\Project.Test\bin\Debug\netcoreapp1.0\Project.Test.dll'. Symbols loaded.
Hellow Orld!
The program '[21168] vstest.executionengine.x86.exe' has exited with code 0 (0x0).
The program '[17112] dotnet.exe' has exited with code 0 (0x0).
```
Which means as far as I understand it, the test runs on .NET Core even though it sais `clrhost`.

My confusion is that [Getting started with xUnit.net](http://xunit.github.io/docs/getting-started-dotnet-core.html) sais with this setup 

> When you run dotnet test with multiple framework entries, the system will run all your framework tests, one after another. 

But that is 1) undesirable from within VS, especially interactively in the normal code/test cycle and 2) Visual Studio doesn't do it and 3) there is no way to choose which runtime VS uses, since I cannot figure out how to configure the project or the solution to one or the other.

Previously, `global.json` would accept `sdk/runtime: clr` or `sdk/runtime: coreclr` and honor that at least after reopening the solution, but right now I just don't see a way to have my test run on `net451` apart from having two projects with different TFM's which compile the same files - or something like that.

Is there an alternative, proper way to do it?
