### ISSUE TITLE
After update to preview2, real-time build errors no longer updating

### ISSUE THREAD

**Issue by smbecker** [aspnet/Tooling#635]
In previous builds of the tooling, when there were build errors, they would show up in the "Errors" tab without having to actually run the Build command or have the file open. After upgrading to Update 3 and preview 2 of the tooling, this no longer happens. Now, In order to see build errors, I need to explicitly run the Build command. Was this an intentional change? I didn't see an announcement about it.

**Comment by sayedihashimi** [comment]
@billhiebert thoughts?

**Comment by pantonis** [comment]
Same problem here. Not only this but If I clean and build no files are produced. have to do it every time from the cmd

**Comment by mlorbetske** [comment]
TFS Bug#241361

**Comment by mlorbetske** [comment]
@smbecker could you check whether the error list says "Build Only" or "Build + Intellisense" in the dropdown? The errors should show up in the case that one of the options that include intellisense things is selected

@pantonis we changed the way we construct the output paths, we now produce outputs under the bin\configuration\runtime\ folder

**Comment by mlorbetske** [comment]
Since there hasn't been any activity here in quite a while, closing this issue. Please re-open if you're still having trouble.
