### ISSUE TITLE
Referencing 3rd Party .dll

### ISSUE THREAD

**Issue by markusvt** [aspnet/Tooling#636]
I am trying to reference other libraries in my Core1.0.0 project.
I already found out, that I need to pack them in a NuGet package and install that package then. If I use the 'net451' Framework, everything works fine.
But if I use 'netcoreapp1.0' as framework, when I install the NuGet Package and the packages are restored, I get the follwing message 
`Package IonicZip 1.0.0 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package IonicZip 1.0.0 supports: net (.NETFramework,Version=v0.0)`

Is there any way I can make my Core project import that dll or do i have to stick to the net451 Framework because of that?

**Comment by WolfspiritM** [comment]
As Dotnet Core is another Framework (which is a subset of the Full Framework) your Nuget package needs to be build for that specific framework, too. There is no way to load a thirdparty .NET Framework (Full) DLL in .NET Core as far as I know as that wouldn't make much sense.

That means the creator of your DLL needs to build it for Dotnet Core (if possible) or you need to stick with the full net4* framework.

**Comment by mlorbetske** [comment]
TFS Bug#241364

**Comment by mlorbetske** [comment]
@markusvt could you try to set the target frameworks in your package similar to what's in one of the Microsoft packages in %userprofile%\.nuget\packages?
