### ISSUE TITLE
Visual Studio 2015 Update 3 broken after installing "DotNetCore.1.0.0-VS2015Tools.Preview2.exe"

### ISSUE THREAD

**Issue by MuiBienCarlota** [aspnet/Tooling#638]
I've installed **Visual Studio 2015 Update 3** as an update of **Visual Studio 2015 Update 2**. I've been able to compile a real size solution without any problem.

But after installing **DotNetCore.1.0.0-VS2015Tools.Preview2.exe**, I'm unable to open any project in VS 2015 Upadte 3.

After several dialog boxes saying that:
"The 'Xxxxx' package did not load correctly"
![image](https://cloud.githubusercontent.com/assets/4465371/16495044/fd070052-3eeb-11e6-805d-f3a975d88f0f.png)
my Visual Studio remains empty.

And then when try to create a new project, I get:
"An Item with the same key has already been added"
![image](https://cloud.githubusercontent.com/assets/4465371/16495425/a6a83b66-3eed-11e6-9fc8-8e49725ee804.png)

Even exiting Visual Studio isn't possible. I get a "An Item with the same key has already been added"
and no exit. I must kill it.

On Visual Studio's Report a problem, someone seems to have similar problem.

One guess: I've installed on this machine several beta/preview version of .NET DNX/Core. I was supposed to have mage proper uninstallation but using [MicrosoftProgram_Install_and_Uninstall.meta.diagcab](https://support.microsoft.com/en-us/help/17588/fix-problems-that-block-programs-from-being-installed-or-removed) show me some were already present. I've use this tools to force uninstallation of each. No success.

I've repaired **Visual Studio 2015 Update 3** without success.
I've uninstalled **DotNetCore.1.0.0-VS2015Tools.Preview2.exe** without success.
I've then uninstalled **Visual Studio 2015 Update 3** completly before reinstalling **Visual Studio 2015 Update 3** with MSDN iso without success.

I've no solution except reinstalling my machine or using a restore point.

**Comment by barrytang** [comment]
Hi @MuiBienCarlota, can you try deleting your MEF cache under %userprofile%\AppData\Local\Microsoft\VisualStudio\14.0\ComponentModelCache and see if it fixes it? Please make a copy of the folder so that I can send it to the MEF team to investigate in case it is the culprit. 

If it doesn't fix it, can you attach the ActivityLog.xml here?

Thanks and sorry for the inconvenience.

**Comment by MuiBienCarlota** [comment]
Hi @barrytang, after deleting ComponentModelCache content, I can again open solutions, create new projects/solutions and compilling them. Good catch!

Unfortunatly, deleted files were not saved and I can't send them to you for investigation.

I will retry to install **DotNetCore.1.0.0-VS2015Tools.Preview2.exe**. I don't hope to fall into same problem, but if it does, I could send your MEF cache files and ActivityLog.xml.

Thanks.

**Comment by chausner** [comment]
I had the exact same issue, the Tools Preview corrupted my whole Visual Studio installation with lots of messages about VSPackage loading errors. I launched the setup file again, pressed Uninstall and after that everything worked again, luckily. I wasn't brave enough to try to install it a second time.

**Comment by MuiBienCarlota** [comment]
Good news. I've reinstalled DotNetCore.1.0.0-VS2015Tools.Preview2.exe and my VS is working.
I think my problem was due to beta/preview version not correctly uninstalled. I must confess that this machine is used to install each beta/preview of Windows 10, Visual Studio and .Net core.

**Comment by barrytang** [comment]
@MuiBienCarlota, glad to hear that things are working well for you now.

@chausner, I took a quick look at your activitylog.xml file and it seems to be extensions/MEF related as well. Did you try deleting your ComponentModelCache folder like I suggested above? Anyway, I will forward your activitylog.xml file along to our extensions/MEF team and see if they can help.

**Comment by AlexEyler** [comment]
@chausner we've had a few reports of this issue and we're looking into it now. A workaround that has worked for some customers is this:

1. Install DotNetCore.1.0.0-VS2015Tools.Preview2.exe
2. Open VS and close VS.
3. Delete this folder: %localappdata%\Microsoft\VisualStudio\14.0\ComponentModelCache
4. Launch VS again.

Hopefully the package load issues will be solved by this workaround for you.

**Comment by chausner** [comment]
I installed it again and this time it works, no workaround needed. I also noticed that this time the install went much quicker (2 minutes) while the first time it took 20 minutes or longer.

**Comment by AlexEyler** [comment]
Okay, thanks for letting me know! That will be some useful data for our investigations.
