### ISSUE TITLE
View Scaffolding with DbContext based on IdentityDbContext fails

### ISSUE THREAD

**Issue by jwdavidson** [aspnet/Tooling#639]
Attempts to generate a view produce this error:

![image](https://cloud.githubusercontent.com/assets/1116398/16508351/28df4ac2-3f00-11e6-949b-0155a91d33a9.png)

I do not find any mechanism to create an EF Core 1.0 DbContext with a "parameterless constructor".

The only constructor I have is

`        public LynxJournalDbContext(DbContextOptions<LynxJournalDbContext> options) : base(options) { }`

**Comment by barrytang** [comment]
Moved to https://github.com/aspnet/Scaffolding/issues/270.
