### ISSUE TITLE
Using NET Framework 4.6.1 project that has a project reference for a netstandard1.1 project does not work.

### ISSUE THREAD

**Issue by MILL5** [aspnet/Tooling#640]
I have a project.json (see below) that specifies netstandard 1.1.  I use this to publish to a nuget package (for yocto).  I have some test applications that are in the same solution that are .NET Framework 4.6.1 projects.  I add a project reference to my project that uses .NET Core.  While the reference is actually made, compilation is not possible because the .NET Framework 4.6.1 does not seem to know about the .NET Core project.  It has to be a path issue with the tooling because I can go to the bin directory that outputs the .net core assembly and directly reference it and that works.

```
{
  "packOptions": {
    "summary": "yocto - a small, yet powerful, Inversion of Control (IoC) container",
    "owners": [ "MILL5" ],
    "requireLicenseAcceptance": false,
    "projectUrl": "https://github.com/MILL5/yocto",
    "licenseUrl": "http://www.apache.org/licenses/LICENSE-2.0",
    "repository": {
      "type": "git",
      "url": "https://github.com/MILL5/yocto"
    },
    "tags": [
      "ioc",
      "di",
      "dependencyinjection"
    ]
  },
  "title": "yocto",
  "copyright": "Copyright MILL5 © 2016",
  "version": "1.5.2-alpha1",
  "description": "yocto - a small, yet powerful, Inversion of Control (IoC) container",
  "frameworks": {
    "netstandard1.1": {
      "imports": "dnxcore50",
      "dependencies": {
        "NETStandard.Library": "1.6.0"
      }
    }
  }
}
```

**Comment by BrennanConroy** [comment]
Not related: Future reference add three ticks ``` around code to keep its format

Its possible that this is because your *.xproj's are using the old format and you'll need to update them. If you create a new project with VS and look at the .xproj you'll see the differences.

**Comment by barrytang** [comment]
@balachir?

**Comment by mlorbetske** [comment]
TFS Bug#241366

**Comment by mlorbetske** [comment]
@rrelyea any ideas?

**Comment by mlorbetske** [comment]
This should be fixed. If you're still running in to this, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site
