### ISSUE TITLE
Build failed asp.net core 5 "version": "1.0.0-rc1-update1" in File Microsoft.DotNetCommon.Targets at line 241 (dnx)

### ISSUE THREAD

**Issue by saadjaved120** [aspnet/Tooling#641]
My Web project is giving "Build Failed" error 
Here is my global.json details
{
  "projects": [ "src", "test" ],
  "sdk": {
    "version": "1.0.0-rc1-update1"
  }
}

Here is my project.json framework details

  "frameworks": {
    "dnx451": {
      "dependencies": {
        "System.Web.Http.Common": "4.0.20126.16343",
        "Glimpse.Ado": "1.7.3",
        "Glimpse.AspNet": "1.9.2",
        "Microsoft.CSharp": "4.0.1-rc2-24027",
        "Microsoft.Owin": "3.0.1",
        "Newtonsoft.Json": "8.0.3",
        "Ninject": "3.2.0",
        "Ninject.Web.Common": "3.2.3",
        "NLog": "4.3.5",
        "Owin": "1.0.0",
        "RestSharp": "105.2.3"
      }
    }
  }

Visual studio 2015 Version 14.0.25123.00 Update 2
![dnvmversion](https://cloud.githubusercontent.com/assets/10254815/16522326/9f32ae1a-3fb6-11e6-8368-204a77221486.PNG)

**Comment by saadjaved120** [comment]
I have tried "dnu restore" and "DotNet restore"

**Comment by barrytang** [comment]
@danroth27, @sayedihashimi, can you point @saadjaved120 to the dnx->dotnet conversion doc?

**Comment by danroth27** [comment]
https://docs.microsoft.com/en-us/dotnet/articles/core/migrating-from-dnx

**Comment by saadjaved120** [comment]
thanks @danroth27  @barrytang
