### ISSUE TITLE
when open cshtml, "dotnet has stopped working"

### ISSUE THREAD

**Issue by szykov** [aspnet/Tooling#644]
When open any cshtml file i receive this error:

> Problem Event Name:	APPCRASH
>   Application Name:	dotnet.exe
>   Application Version:	1.0.1.4500
>   Application Timestamp:	576218d2
>   Fault Module Name:	KERNELBASE.dll
>   Fault Module Version:	6.3.9600.18340
>   Fault Module Timestamp:	57366075
>   Exception Code:	e0434352
>   Exception Offset:	0000000000008a5c
>   OS Version:	6.3.9600.2.0.0.272.7
>   Locale ID:	1033
>   Additional Information 1:	cd7d
>   Additional Information 2:	cd7d63e25da884d2ecaa0b46a0b9ff08
>   Additional Information 3:	3b6f
>   Additional Information 4:	3b6f172f89fe433a3561191eec7c40c2

сshtml file opens but intellisense isn't working in the file.

**Comment by szykov** [comment]
on my another environment works fine. seems it's local issue related to upgrade.

**Comment by ygoe** [comment]
Reproduced here. What should I do?

**Comment by ygoe** [comment]
Now it works, after I had built the project once. Tag Helper highlighting is available now. dotnet.exe seems to be confused (more or less, in other projects it just doesn't crash) if the project hasn't been built yet.
