### ISSUE TITLE
Angular 2 cli tooling

### ISSUE THREAD

**Issue by jmurphzyo** [aspnet/Tooling#645]
Visual Studio Version: VS2015 enterprise Update 1, 2, and 3.
OS: Windows 10 x64.
angular-cli: all versions.

This might be related to #441 or other similar issues but using the angular-cli tooling locks up visual studio when using ng build.
Steps to reproduce issues.

1. install angular-cli tool https://github.com/angular/angular-cli . Instructions are given here in detail.
2. create a new asp.net core web app project.
3. Open cmd and cd to the project root folder and run ng i.
4. Once angular-cli completes the initalization. Generate a component with angular cli  by typing ng g component myComponent in cmd.
5. add a .ember-cli file to the root of the aspnet project with the following content
```js
{
      "output-path": "wwwroot/"
}
```
this will tell angular-cli to build the project in the wwwroot folder.
6. type ng b in cmd and visual studio will freeze.

I am guessing this is related to how broccoli is adding files to the tmp folder and the tracking mechanism that visual studio 2015 uses.

I have attempted all the methods I have been able to find to exclude folders (project.json....builder embed exclude, compile exclude, and dnxexclude in the .xproj file, etc...). I haven't been able to figure out a workaround or a solution.

Any insight or workaround you guys can come up with be greatly appreciated.

**Comment by barrytang** [comment]
@madskristensen, @jodavis?

**Comment by mlorbetske** [comment]
TFS Bug#241367

**Comment by Phatsuo** [comment]
With the latest version of the CLI (1.0.0-beta.11-webpack), this particular problem is gone. 

This version uses webpack instead of Broccoli, and as such there is no tmp folder for VS to track.

That said, it would still be very useful to be able to tell VS to completely ignore arbitrary directories.

**Comment by mlorbetske** [comment]
@Phatsuo unfortunately, this isn't possible to do with xproj/project.json, it will be possible with the move to csproj
