### ISSUE TITLE
cannot debug ASP.NET Core 

### ISSUE THREAD

**Issue by pantonis** [aspnet/Tooling#646]
I created new ASP.NET Core Web Application without changing anything in the code and when I run it I get

The program '[2336] dotnet.exe' has exited with code -2147450749 (0x80008083).
The program '[6348] iisexpress.exe: Program Trace' has exited with code 0 (0x0).
The program '[6348] iisexpress.exe' has exited with code 0 (0x0).

**Comment by barrytang** [comment]
@piotrpMSFT ?

**Comment by piotrpMSFT** [comment]
@schellap is that exit code familiar to you?

can we get `dotnet --info` output?

**Comment by schellap** [comment]
This means either `hostfxr.dll` or `hostpolicy.dll` is missing. The console log would have a clearer error message.

Could you please confirm if either:

`%ProgramFiles%\dotnet\host\fxr\{version-number}\hostfxr.dll`

Or

`%ProgramFiles%\dotnet\hostfxr.dll`

is present?

Also, what is the output when you just run `dotnet.exe` on the `PATH`?


https://github.com/dotnet/core-setup/blob/da800066269351dddae310dc262e2184c674d790/src/corehost/error_codes.h#L11

**Comment by pantonis** [comment]
@piotrpMSFT 
![image](https://cloud.githubusercontent.com/assets/3295086/16610996/82c10f92-4367-11e6-925b-38a016b690ea.png)


@schellap 

C:\Program Files\dotnet\host\fxr\1.0.1\hostfxr.dll is present

C:\Program Files\dotnet\hostfxr.dll is not present

When I run dotnet I get following

Microsoft .NET Core Shared Framework Host

  Version  : 1.0.1
  Build    : cee57bf6c981237d80aa1631cfe83cb9ba329f12

Usage: dotnet [common-options] [[options] path-to-application]

Common Options:
  --help                           Display .NET Core Shared Framework Host help.
  --version                        Display .NET Core Shared Framework Host version.

Options:
  --fx-version <version>           Version of the installed Shared Framework to use to run the application.
  --additionalprobingpath <path>   Path containing probing policy and assemblies to probe for.

Path to Application:
  The path to a .NET Core managed application, dll or exe file to execute.

If you are debugging the Shared Framework Host, set 'COREHOST_TRACE' to '1' in your environment.

To get started on developing applications for .NET Core, install .NET SDK from:
  http://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409

**Comment by piotrpMSFT** [comment]
@barrytang does this project type do anything special in terms of finding dotnet? Perhaps it augments the PATH? uses a different context [32 bit?]?

**Comment by schellap** [comment]
@pantonis, can you try the failing command on the console from the project directory? Does VS console output have the failing command line?

Also, confirm `dotnet --info` runs on `%pfx86%\dotnet`?

**Comment by pantonis** [comment]
@schellap ```dotnet --info``` runs on ```%pfx86%\dotnet```

Failing the command on the console?

**Comment by schellap** [comment]
> Failing the command on the console?

Just like you ran `dotnet --info`, could you run the actual command that exits with this failure code? If you can reproduce the failure on the console, we can see what your command line is and also get a better error message.

Another option is to run "dotnet.exe" under `windbg.exe` with Image File Execution options:

https://msdn.microsoft.com/en-us/library/a329t4ed(v=vs.100).aspx

This would always launch dotnet.exe under windbg. At this point, you will get `dotnet.exe` break in the debugger. To debug all child processes from that point on `.childdbg 1` in `windbg`. You can do `!peb` to get the command line that is failing. You will also get the console window with better error message. Hopefully, this exercise isn't too exhausting. Could you please give this a shot?

**Comment by schellap** [comment]
Once you have the Image File Execution Options set, just follow the same repro steps (File > New Proj or whatever you did in VS to get this repro)

**Comment by schellap** [comment]
Before we go down the above debugging steps, a quick check on the VS "Console Output" Window might help. This is to check if VS printed the full command line invocation of `dotnet.exe` that fails. This will give you the failing command to repro on the console instantly.

**Comment by pantonis** [comment]
sorry didnt mention that this is not a problem with dotnet build. This only happens when I build with VS2015

**Comment by mlorbetske** [comment]
TFS Bug#241369

**Comment by savva-andreas** [comment]
I faced same issue. I made a typo mistake and set localhost to some other ip in my windows host file, setting it back to 127.0.0.1 fixed it!
