### ISSUE TITLE
Project is always rebuilt, regardless of file changes.

### ISSUE THREAD

**Issue by gulbanana** [aspnet/Tooling#647]
I've run into a situation where a .xproj is repeatedly built with the message `(project) will be compiled because inputs were modified`. It seems to happen when the .xproj references two similar projects as dependences for different framework targets - even if they're empty of any actual code. 

https://github.com/gulbanana/StructureMock/tree/rebuild-repro is a branch containing a minimal demonstration of the problem. To reproduce, check out the repository and open it with Visual Studio 2015 Update 3, then select "Build Solution" from the "Build" menu multiple times.

**Comment by mlorbetske** [comment]
TFS Bug#237383

**Comment by balachir** [comment]
This issue is now fixed as part of a [cumulative update](https://github.com/aspnet/Tooling/blob/master/release-notes.md#8112016-tooling-update-for-net-core-100---vs-2015-tooling-preview-2) that we released.

**Comment by gulbanana** [comment]
great, thanks!
