### ISSUE TITLE
New Scaffolding Files not appearing in the project. 

### ISSUE THREAD

**Issue by ArieJones** [aspnet/Tooling#648]
Steps 
1. Created new 1.0 website 
2. Added to GitHub private repo 
3. Add class in Models 
4. Right click on Controllers and Select Add Controller to create new controller and views based off of class created in step 3. 
5. Files not present in the project. Checking Output window shows the files are created. Checking file system the files have been created. 

In my case closing and then reopening the project makes the files finally appear. But doing this after every scaffolding attempt is cumbersome and would be confusing for a new user. 

Thanks
AJ

**Comment by barrytang** [comment]
Moved to https://github.com/aspnet/Scaffolding/issues/271.
