### ISSUE TITLE
Surface Pro 3 - VS2015U3 - Preview2 Tooling 

### ISSUE THREAD

**Issue by mvermef** [aspnet/Tooling#649]
![](https://x2tdpq.bn1301.livefilestore.com/y3m386BVR00z2ns3EXNAIn-EjQyB1fAMKMkNqHI8z8X6ImJe6tFG0sSlop7LWXF8vgub-4qJi_jF6EU2faB7AaT_l8APX025iE4WusnhggNuB4OkvaGU2Zqeu59105bdoPTJQPMqbk1LxEOkBTGxbEVBA?width=2160&height=1440&cropmode=none)

![](https://x2suja.bn1301.livefilestore.com/y3mX1cFpxF1fUqEKu1D7a36yVTSvKyE7yLEZiRENNDq3ZK-na90nW8md6y083v-WEjlBHF5giwkO5gOep1nfZZIqtCD8IV3ObTC7eS5VMaYvK_OFZg7K4FoBAwZStToJiohx64_AOKBFFKf_daZbTJYvg?width=2160&height=1440&cropmode=none)

Can't build .NET Core anything and it is also affecting my UWP projects which are more pressing.  This is starting to look like a complete flop.  I am not sure why this is only affecting my surface pro3 and not my desktop too.

**Comment by barrytang** [comment]
@NTaylorMullen, can you take a look? It looks like it is related to restoring the Microsoft.AspNetCore.Razor.Tools package.

Adding @ToddGrun and @jodavis as well.

**Comment by mvermef** [comment]
problem though is it isn't just asp.net core that is affected... UWP is also borked with relation to my surface as well.  No packages will restore.

**Comment by mvermef** [comment]
Also, vs code also freaks on package restore....

**Comment by NTaylorMullen** [comment]
@mvermef Could you do the following and report on what happens:

1. Drop down to the command line in that project and type `dotnet restore`.
1. Open up the Package Manager Console in Visual Studio and type `dotnet --info` and paste the results here.

**Comment by mvermef** [comment]
got tired of waiting need for road tomorrow or the next day... Restore yields the above.  --info was exactly RTM values.

**Comment by mlorbetske** [comment]
TFS Bug#241368

**Comment by mvermef** [comment]
Close.  No further information to the reason for its cause.
