### ISSUE TITLE
CTRL+F5 IIS Express restarts when an exclude'd file changes

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Tooling#65]
In my web project, I've got an `ICompileModule` and I write the code it generates to a `*.cs` file at the root of the project just to occasionally check its contents against my expectations. This file is part of `project.json`'s `exclude` (and `.gitignore`), so it's not really part of the project.

In a debugging session (F5) or on the command line, everything works as expected and only the first request takes a tad longer. However, when I'm running IIS Express in the background (CTRL+F5), each request takes about 15 seconds and occasionally the content files are not served with a HTTP 503 status code. 

This behavior stops the moment I stop writing to the `*.cs` file, so it looks like the file watcher is too greedy.

On CTP 6, there was a similar issue when running a debugging session: aspnet/Mvc#1860

**Comment by sayedihashimi** [comment]
@BillHiebert this sounds like it may be a Design Time Host or runtime issue, do you know?

**Comment by BillHiebert** [comment]
Yes, sounds like a Design Time Host issue. They should be ignoring changes to excluded files. Alternatively, VS probably shouldn't send file changes for excluded files - though this may be a bit tricky to get right

**Comment by davidfowl** [comment]
yar doubt we'll fix this

**Comment by BillHiebert** [comment]
I opened a bug to look at if in VS. I think it is a very small change. TFS# 1169130

**Comment by BillHiebert** [comment]
This has now been fixed

**Comment by BillHiebert** [comment]
Turns out

**Comment by BillHiebert** [comment]
@davidfowl 
This will need to be fixed in the runtime as it has a file watcher which kills the IIS Express process.
