### ISSUE TITLE
Visual Studio 2015 Update 3: CompileTypeScriptWithTSConfig  Unknown compiler option 'listemittedfiles'

### ISSUE THREAD

**Issue by genereux** [aspnet/Tooling#651]
Since I've updated Visual Studio 2015 Update 3 and installed also and the Visual Studio Tooling Preview 2 for .Net Core, I'm not able to compile my TypeScript project. I've check the compiler output and I got Unknown compiler option '--listemittedfiles', which seems to be added automatically by the TypeScript.Tasks.dll. I've decompiled the dll and the method adding this is `GenerateResponseFileCommands()`. I think the tsc compiler latest version is 1.8.34/1.8.6 and is suporting the `--listFiles` and not the `--listemittedfiles` option.

This is a blocking issue for us

**Comment by paulvanbrenk** [comment]
Can you share a diagnostic build log?

**Comment by genereux** [comment]
The part of the build log that is creating the problems is below. I don't have Dev15 installed on the machine. Is the tsc compiler suppose to support the `--listemittedfiles ` option ?

`1>Target "PreComputeCompileTypeScriptWithTSConfig" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "C:\TFS\MyProject\Dev\MyProject.Web\MyProject.Web.xproj" (target "CompileTypeScriptWithTSConfig" depends on it):
1>       Using "VsTsc" task from assembly "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\TypeScript.tasks.dll".
1>       Task "VsTsc"
1>         C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "C:\TFS\MyProject\Dev\MyProject.Web\scripts\tsconfig.json" --listEmittedFiles
1>       Done executing task "VsTsc".
1>     1>
1>Done building target "PreComputeCompileTypeScriptWithTSConfig" in project "MyProject.Web.xproj".
1>     1>
1>Target "CompileTypeScriptWithTSConfig" in file "C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets" from project "C:\TFS\MyProject\Dev\MyProject.Web\MyProject.Web.xproj" (target "Compile" depends on it):
1>       Task "VsTsc"
1>         C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.8\tsc.exe --project "C:\TFS\MyProject\Dev\MyProject.Web\scripts\tsconfig.json" --listEmittedFiles
1>         C:\TFS\MyProject\Dev\MyProject.Web\error TS5023:Build:Unknown compiler option 'listemittedfiles'.
1>     1>
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets(214,5): error MSB6006: "tsc.exe" exited with code 1.
1>       Done executing task "VsTsc" -- FAILED.
1>     1>
1>Done building target "CompileTypeScriptWithTSConfig" in project "MyProject.Web.xproj" -- FAILED.
1>     1>
`

**Comment by paulvanbrenk** [comment]
Can you share the whole log (make sure you set logging to diagnostic in the tools/options). I'm curious what some of the variables are set too, which is not shown in this part of the log.

That option is not supported on 1.8, so I'm wondering how this mismatch between compiler version and compiler options occurred.

**Comment by genereux** [comment]
Indeed the property ` <TypeScriptToolsVersion>` was set to 1.9 by mistake in my xproj file.
When I switched logging to diagnostic, I saw it in like this `TypeScriptToolsVersion = 1.9`. 
I've changed the .xproj to have 1.8 tooling `<TypeScriptToolsVersion>1.8</TypeScriptToolsVersion>`, and now it works fine.

Thanks alot

**Comment by paulvanbrenk** [comment]
Thanks for confirming!
