### ISSUE TITLE
<aspNetCore> element in web.config shows squiggly

### ISSUE THREAD

**Issue by madskristensen** [aspnet/Tooling#657]
`<aspNetCore>` element in web.config isn't in the schema and shows squiggly. The XSD must be updated to include a definition for `<aspNetCore>`

**Comment by bruceyclee** [comment]
TFS #[210822](https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workitems/edit/210822)

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed.
