### ISSUE TITLE
"dotnet restore" command inconsistency in Visual Studio 2015 Upgrade 3

### ISSUE THREAD

**Issue by SteliyanStoyanov** [aspnet/Tooling#659]
Hello guys,

I am experiencing strange behavior with VS2015 Update 3.
More specifically, when creating a new "ASP.NET Core Web Application". When the solution is created the following restore command is executed:
`C:\Program Files\dotnet\dotnet.exe restore "c:\users\<username>\documents\visual studio 2015\Projects\WebApplication1\.vs\restore.dg" -s "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages"`,
note the `-s "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages"` argument.

However, when the solution is closed and then opened, the following restore command is executed:
`C:\Program Files\dotnet\dotnet.exe restore "C:\Users\<username>\Documents\Visual Studio 2015\Projects\TelerikAspNetCoreApp1\.vs\restore.dg"`

When is this a problem: if the project depends on a package that is not located in: `C:\Program Files (x86)\Microsoft SDKs\NuGetPackages`, this causes the restore to fail, because the **-s** switch overrides all the local configuration ([info](https://docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-restore#options)), however, when the solution is closed and opened, the **-s** is not specified and if the package exists in any other Nuget repository - then the restore is successful. Also, manually executing `dotnet restore` works fine as well.

Does anyone have any idea if this is a desired behavior?

Thanks.

**Comment by mlorbetske** [comment]
TFS Bug#241376

**Comment by mlorbetske** [comment]
@SteliyanStoyanov this is by design behavior. Project templates should contain all of the packages they depend on so that offline creation of the project template works.

**Comment by AlekseyMartynov** [comment]
@mlorbetske 
Could you suggest any resources (docs, etc) describing the use of custom NuGet packages in project.json based templates? How is this supposed to work? As I understand, the `dotnet restore -s ...` command states explicitly: use only this feed and nothing else.

**Comment by San4es** [comment]
@mlorbetske 

It is interesting that the package is successfully restored by the "dotnet restore -s" command if a third-party library version is specified exactly as 1.0.0. However, it fails if the version is specified as 1.0.0-* (my project template includes the NuGet.config file with a custom NuGet source that contains this third-party library).
