### ISSUE TITLE
VS2015RC APPCRASH error

### ISSUE THREAD

**Issue by cuiliang** [aspnet/Tooling#66]
When open and switch between two js files, vs will crash.

![image](https://cloud.githubusercontent.com/assets/1972649/7516593/007795c8-f503-11e4-983b-8d8c364b6839.png)

The detailed info shows (sorry, it's in Chinese):

问题签名:
  问题事件名称:	APPCRASH
  应用程序名:	devenv.exe
  应用程序版本:	14.0.22823.1
  应用程序时间戳:	5538ad9e
  故障模块名称:	chakrals.dll
  故障模块版本:	11.0.10036.0
  故障模块时间戳:	54fea29e
  异常代码:	c0000005
  异常偏移:	001d2d45
  OS 版本:	6.1.7601.2.1.0.256.1
  区域设置 ID:	2052
  其他信息 1:	e74a
  其他信息 2:	e74a8b7f904978d5e56aeabe749bc909
  其他信息 3:	5efd
  其他信息 4:	5efdf01901853bb86ac7b9448f56fcc9

**Comment by sayedihashimi** [comment]
@cuiliang can you give more specific steps to reproduce this? I've never seen this.

**Comment by cuiliang** [comment]
@sayedihashimi

You can download the project from http://urtracker.cn/itemz.web.rar
1. Unzip package to a folder
2. Double click Itemz.Web.xproj to open the project
3. Wait a few seconds for package restore. (some package missing, dont mind)
4. Double click the file  client/app/app.js from Solution Explorer.
5. After few seconds, IDE will show "The Javascript language service is processing your request in the background..." in status bar.
6. Then VS will crash.

Seems open any js file in the client folder, VS will crash after showing "The Javascript language service is processing your request in the background..." in status bar.

**Comment by cuiliang** [comment]
Crash disappeared after install "Web Essentials 2015.0 RC".  and do not appear again even disable or uninstall WebEssentials.

It's interesting.

**Comment by sayedihashimi** [comment]
@cuiliang ok, can we close this?

**Comment by cuiliang** [comment]
yes, i do it.
