### ISSUE TITLE
Intellisense not properly working when typing out @model reference. 

### ISSUE THREAD

**Issue by ArieJones** [aspnet/Tooling#660]
When trying to add a @model reference to a view we are experiencing a problem where it will overwrite the previous entry in the chain. 
So when trying to add a reference for @model Carepilot.Models.AllergyViewModel  intellisense kicks in after the first dot but when we hit enter it overwrites part of the first entry for Carepilot. 
So we end up with 
@model CarModels.Mo

Additionally, sometimes when typing quickly this reference it will duplicate the first portion when we hit the dot. 

So we type out @model Carepilot. 
 and we end up with @model CarepilotCarepilot

This is very inconsistent and makes working with views very hard because of not being able to properly set the model without having to open up Notepad and type the entry in and do a copy/paste. 

Thanks
AJ

**Comment by NTaylorMullen** [comment]
This is related to: https://github.com/aspnet/Tooling/issues/612 (may not seem so based on what's listed in the bug but the underlying issue is the same).

**Comment by Xipooo** [comment]
I have also noticed that I can auto-complete the word by typing . instead of tab, however it adds extra letters and injects words into previous parts of the dot notation.  For example:

The namespace is JobTrackingSystem.  I type Job. and get:
@model JobTrackingSystemob.

Then trying to drill down to my ViewModels folder by typing View. will render this result:
@model JobTrackingSyViewModels.View

**Comment by NTaylorMullen** [comment]
@Xipooo Yup, #612 :smile:. In the end it's a Roslyn tooling issue. Should be fixed in the next release.

**Comment by mariusWeceipt** [comment]
+1 Have the same problem. Here's a gif to show the issue.
![intellisense_bug_view](https://cloud.githubusercontent.com/assets/7679761/16769962/0fa4c3a8-484b-11e6-84f8-01a46b8381a0.gif)

Note that intellisense also does not color asp-related stuff properly. Like for instance, this "asp-action" should be green, not light blue.
![bug color](https://cloud.githubusercontent.com/assets/7679761/16770018/45f81270-484b-11e6-93cb-9cf63ffcad43.JPG)


For reference, I use Tooling Preview 2.

**Comment by mlorbetske** [comment]
TFS Bug#241375

**Comment by mlorbetske** [comment]
From the linked GitHub issue & TFS item, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
