### ISSUE TITLE
.tfignore - Output Window Bug

### ISSUE THREAD

**Issue by Delie** [aspnet/Tooling#661]
The "Source Control - Team Foundation" output in the Output window complains about files which are listed in .tfignore.  Presumably, it shouldn't care about these files if they're meant to be ignored by TFS.

**How to replicate**
1. Create a .net core project.
2. Add some files to a folder
3. Add that folder to .tfignore
4. Delete one of the files
5. You'll see a line appearing in the Output window, which then grabs focus and takes you away from anything else you were looking at at the time.
6. Add new files, repeat, same thing happens - so it's not just files that previously existed before .tfignore was created.

**Example .tfignore file**
wwwroot\build
node_modules

**Example output**
The item C:\Dev\testsolution\src\testproject\wwwroot\build\polyfills.bundle.js could not be found in your workspace, or you do not have permission to access it.

Well, yes, it doesn't exist anymore, because we deleted it, but TFS shouldn't care about this because wwwroot\build is in my .tfignore file

**Comment by Tenmak** [comment]
I think (must confirm) it is because the folders are deleted and then rebuilt as read-only and thus outputting errors.

**Comment by mlorbetske** [comment]
TFS Bug#241377

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
