### ISSUE TITLE
cannot debug on preview 2 tooling

### ISSUE THREAD

**Issue by noahfalk** [aspnet/Tooling#663]
I am filing this new issue to call attention to #538 which I believe was improperly closed. The issue described there does not appear to have been resolved. I'd suggest reopening that issue and closing this one.

**Comment by mlorbetske** [comment]
TFS Bug#241384

**Comment by mlorbetske** [comment]
Sorry for the delay in responding, having a version & bitness of the runtime that is compatible with the tools is essential for having these things work. We've made some improvements to call more attention to the exact cause of problems and their remedies for Visual Studio 2017
