### ISSUE TITLE
Adding Dependencies and restore encoding issues

### ISSUE THREAD

**Issue by lanwilliam** [aspnet/Tooling#667]
I have Chinese string in my workspace path.
When I adding new dependencies,vs2015 auto restore ,and the output text has encoding issues.
Just like this:
C:\Program Files\dotnet\dotnet.exe restore "c:\users\王文斌\documents\visual studio 2015\Projects\PostgresSqlDemo\.vs\restore.dg" -s "C:\Program Files (x86)\Microsoft SDKs\NuGetPackages"
log  : Restoring packages for c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\project.json...
log  : Restoring packages for tool 'BundlerMinifier.Core' in c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\project.json...
log  : Writing lock file to disk. Path: c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\project.lock.json
log  : c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\PostgresSqlDemo.xproj
log  : Restore completed in 9108ms.
PATH=.\node_modules\.bin;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External;%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\Web\External\git
C:\Program Files\dotnet\dotnet.exe restore "c:\users\王文斌\documents\visual studio 2015\Projects\PostgresSqlDemo\.vs\restore.dg"
log  : Restoring packages for c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\project.json...
log  : Installing System.IO 4.0.11-beta-23516.
log  : Installing System.IO.FileSystem 4.0.1-beta-23516.
log  : Installing System.ComponentModel.Primitives 4.0.0.
log  : Installing Microsoft.Extensions.Configuration 1.0.0-rc1-final.
log  : Installing System.ComponentModel.TypeConverter 4.0.1-beta-23516.
log  : Installing System.Text.Encoding 4.0.0.
log  : Installing System.Reflection 4.0.0.
log  : Installing Microsoft.Extensions.Configuration.Binder 1.0.0-rc1-final.
log  : Installing Microsoft.Extensions.Configuration.Abstractions 1.0.0-rc1-final.
log  : Installing System.Reflection.TypeExtensions 4.0.1-beta-23409.
log  : Installing System.Globalization 4.0.11-beta-23516.
log  : Installing System.Linq.Expressions 4.0.11-beta-23516.
log  : Installing System.Linq.Expressions 4.0.10.
log  : Installing Microsoft.Extensions.Primitives 1.0.0-rc1-final.
log  : Installing System.ObjectModel 4.0.10.
log  : Installing System.Reflection.TypeExtensions 4.0.0.
log  : Installing EntityFramework7.Npgsql 3.1.0-rc1-3.
log  : Installing EntityFramework.Commands 7.0.0-rc1-final.
log  : Installing EntityFramework.Relational 7.0.0-rc1-final.
log  : Installing EntityFramework.Core 7.0.0-rc1-final.
log  : Installing System.Diagnostics.DiagnosticSource 4.0.0-beta-23516.
log  : Installing System.Text.RegularExpressions 4.0.11-beta-23516.
log  : Installing System.Data.Common 4.0.1-beta-23516.
log  : Installing Microsoft.CSharp 4.0.1-beta-23516.
log  : Installing Microsoft.Extensions.Caching.Memory 1.0.0-rc1-final.
log  : Installing System.Diagnostics.Tools 4.0.1-beta-23516.
log  : Installing Microsoft.Extensions.Caching.Abstractions 1.0.0-rc1-final.
log  : Installing System.Reflection.Extensions 4.0.1-beta-23516.
log  : Installing System.ComponentModel.Annotations 4.0.11-beta-23516.
log  : Installing System.Threading 4.0.11-beta-23516.
log  : Installing System.Collections.Immutable 1.1.36.
log  : Installing System.Linq 4.0.1-beta-23516.
log  : Installing System.Linq.Queryable 4.0.1-beta-23516.
log  : Installing System.Diagnostics.Debug 4.0.11-beta-23516.
log  : Installing System.Runtime.Extensions 4.0.11-beta-23516.
log  : Installing Microsoft.Extensions.DependencyInjection.Abstractions 1.0.0-rc1-final.
log  : Installing Microsoft.Extensions.DependencyInjection 1.0.0-rc1-final.
log  : Installing System.ComponentModel 4.0.1-beta-23516.
log  : Installing Microsoft.Extensions.Logging.Abstractions 1.0.0-rc1-final.
log  : Installing System.ObjectModel 4.0.11-beta-23516.
log  : Installing System.Collections.Concurrent 4.0.11-beta-23516.
log  : Installing System.Resources.ResourceManager 4.0.1-beta-23516.
log  : Installing Microsoft.Extensions.OptionsModel 1.0.0-rc1-final.
log  : Installing Remotion.Linq 2.0.1.
log  : Installing System.Linq.Expressions 4.0.0.
log  : Installing System.Threading.Tasks 4.0.11-beta-23516.
log  : Installing System.Collections 4.0.11-beta-23516.
log  : Installing System.Runtime.InteropServices 4.0.21-beta-23516.
log  : Installing System.Runtime 4.0.21-beta-23516.
log  : Installing System.Diagnostics.Tracing 4.0.0.
log  : Installing System.Threading.Tasks 4.0.0.
log  : Installing System.Dynamic.Runtime 4.0.0.
log  : Installing System.Collections.NonGeneric 4.0.0.
log  : Installing System.IO 4.0.0.
log  : Restoring packages for tool 'BundlerMinifier.Core' in c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Razor.Tools' in c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\project.json...
log  : Restoring packages for tool 'Microsoft.AspNetCore.Server.IISIntegration.Tools' in c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\project.json...
error: Package EntityFramework7.Npgsql 3.1.0-rc1-3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package EntityFramework7.Npgsql 3.1.0-rc1-3 supports:
error:   - dnx451 (DNX,Version=v4.5.1)
error:   - dnxcore50 (DNXCore,Version=v5.0)
error:   - net451 (.NETFramework,Version=v4.5.1)
error: Package EntityFramework.Commands 7.0.0-rc1-final is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package EntityFramework.Commands 7.0.0-rc1-final supports:
error:   - dnx451 (DNX,Version=v4.5.1)
error:   - dnxcore50 (DNXCore,Version=v5.0)
error:   - net451 (.NETFramework,Version=v4.5.1)
error:   - netcore50 (.NETCore,Version=v5.0)
error: One or more packages are incompatible with .NETCoreApp,Version=v1.0.
log  : Writing lock file to disk. Path: c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\project.lock.json
log  : c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\PostgresSqlDemo.xproj
log  : Restore failed in 300081ms.
Errors in c:\users\���ı�\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgresSqlDemo\PostgresSqlDemo.xproj
    Package EntityFramework7.Npgsql 3.1.0-rc1-3 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package EntityFramework7.Npgsql 3.1.0-rc1-3 supports:
      - dnx451 (DNX,Version=v4.5.1)
      - dnxcore50 (DNXCore,Version=v5.0)
      - net451 (.NETFramework,Version=v4.5.1)
    Package EntityFramework.Commands 7.0.0-rc1-final is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package EntityFramework.Commands 7.0.0-rc1-final supports:
      - dnx451 (DNX,Version=v4.5.1)
      - dnxcore50 (DNXCore,Version=v5.0)
      - net451 (.NETFramework,Version=v4.5.1)
      - netcore50 (.NETCore,Version=v5.0)
    One or more packages are incompatible with .NETCoreApp,Version=v1.0.

**Comment by mlorbetske** [comment]
TFS Bug#241380

**Comment by mlorbetske** [comment]
@lanwilliam the way that this information is presented will be fixed with the upcoming changes for the next version of Visual Studio
