### ISSUE TITLE
Can't chose add "Controller" when the project created by "No Authentication".

### ISSUE THREAD

**Issue by lanwilliam** [aspnet/Tooling#668]
I like the templete "Add Controller".It's very helpful.
But I want to use postgresSql,so I need to create project "No Authentication",because the Identity not support for other database now.
Please let the "Add Controller" templete worked without Authentication.
thx

**Comment by mlorbetske** [comment]
TFS Bug#241379

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed for Visual Studio 2017. If you're still running in to this, please report it on the [developer community](https://developercommunity.visualstudio.com/) site
