### ISSUE TITLE
"Sort usings" doesn't work with #ifdef

### ISSUE THREAD

**Issue by ryanbrandenburg** [aspnet/Tooling#669]
If an #if is among the usings of a file then sorting them will not work.

Example:

```
using System;
#if NETCOREAPP1_0
using System.Reflection;
#endif
using Xunit;
using Microsoft.AspNetCore.Testing;
```

`Microsoft.AspNetCore.Testing` should be above `Xunit`, but if you sort it won't be moved there. If you remove the `#if` and try again it will work. Removing unused items DOES work.

I don't know if this is expected behavior since we can't know for sure that everything is in the correct order, but I thought I would report it just in case.

**Comment by mlorbetske** [comment]
TFS Bug#241387

**Comment by CyrusNajmabadi** [comment]
Sort-Usings author here.  We've avoided touching code that intersects #ifdefs so that we don't screw things up.  Basically, we view it as such an advanced and complicated scenario that we leave it entirely to you to maintain usings in this manner :)

**Comment by mlorbetske** [comment]
Per the response from @CyrusNajmabadi, closing this issue
