### ISSUE TITLE
Add-Migration error

### ISSUE THREAD

**Issue by lanwilliam** [aspnet/Tooling#670]
PM> Add-Migration MyFirstMigration
无法识别的转义序列。 (43): {
    "MigrationFile": "C:\Users\鐜嬫枃鏂孿\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgreSqlDemo2\Migrations\20160713011245_MyFirstMigration.cs",
    "MetadataFile": "C:\Users\鐜嬫枃鏂孿\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgreSqlDemo2\Migrations\20160713011245_MyFirstMigration.Designer.cs",
    "SnapshotFile": "C:\Users\鐜嬫枃鏂孿\documents\visual studio 2015\Projects\PostgresSqlDemo\src\PostgreSqlDemo2\Migrations\BloggingContextModelSnapshot.cs"
}
PM> 
When I‘m follow the getting started https://docs.efproject.net/en/latest/platforms/aspnetcore/new-db.html,I get this error.
I‘m using"Npgsql.EntityFrameworkCore.PostgreSQL": "1.0.0" instead of Sqlserver.And tools is "Microsoft.EntityFrameworkCore.Tools": "1.0.0-preview2-final"。

"无法识别的转义序列" in english maybe is "Unrecognized escape sequence".
But the files has been created.

**Comment by lanwilliam** [comment]
The created files works well. I don't know why shows me the error.

**Comment by mlorbetske** [comment]
TFS Bug#241386

**Comment by mlorbetske** [comment]
@rowanmiller any ideas?

**Comment by rowanmiller** [comment]
I suspect this is an issue in the Npgsql provider, can you open up an issue on https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL. It will probably help get a quicker resolution if you are able to share a project file.

cc @roji who maintains that Npgsql provider

**Comment by rowanmiller** [comment]
@mlorbetske you can probably close this one as external (Npgsql is not a Microsoft product). We'll work with @roji if it ends up being something in the EF code base.

**Comment by mlorbetske** [comment]
@rowanmiller thanks! I'll close the TFS issue

**Comment by mlorbetske** [comment]
Since there hasn't been any activity here in almost a year, closing the issue. If you're still running in to this, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site
