### ISSUE TITLE
trying to add ef daily build to a rtm application

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#675]
Hi, I'm not sure this issue is for the tooling repo.
I'm trying to add the ef daily build to an existing rtm application and I found a strange behavior.
Adding **1.1.0-alpha1-21620** version of the ef libraries I have a conflict in the Extensions.Logging library

> Dependency conflict. Microsoft.EntityFrameworkCore 1.1.0-alpha1-21620 expected Microsoft.Extensions.Logging >= 1.1.0-alpha1-21620 but received 1.0.0

In the solution explorer I have the right warning : 
![error](https://cloud.githubusercontent.com/assets/127777/16887040/0a642a98-4ad8-11e6-8b1e-37fd29a10fe5.png)

But compilation succedes, I can run the app that fails in startup.
There is some way to solve this problem? If not, make sense to make the app startable if there is a critical conflict?

**Comment by mlorbetske** [comment]
TFS Bug#241390

**Comment by mlorbetske** [comment]
@rowanmiller any ideas?

**Comment by rowanmiller** [comment]
@lucamorelli I assume you have the nightly feed configured in your package sources? The feeds that are used should be listed in the Output window once package restore completes.

**Comment by lucamorelli** [comment]
yes, I was trying to use the nightly feed to see if a few bugs are fixed. The question is if it's possible to use nightly build of ef using rtm version of asp.net core.

**Comment by divega** [comment]
This issue was moved to aspnet/EntityFramework#6508
