### ISSUE TITLE
Typescript Errors are not shown or appear after few minutes

### ISSUE THREAD

**Issue by sztrzask** [aspnet/Tooling#676]
On VS 2015 update 3 with latest tooling (the one with preview 2) typescript errors are not shown. I am reporting this solely because there used to be a similar issue - https://github.com/aspnet/Tooling/issues/526 (which is closed. It should not.)

Googling the problem points me in your direction.

**Comment by mlorbetske** [comment]
TFS Bug#242837

**Comment by mlorbetske** [comment]
From the linked TFS item, this is marked as fixed. If you're still running in to this, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site
