### ISSUE TITLE
Typescript rebuild does not work 

### ISSUE THREAD

**Issue by damienbod** [aspnet/Tooling#679]
I'm using an ASP.NET Core project with Typescript  for the SPA. If I do a rebuild, typescript does not build again. If I pull new files from the server, there  is no way of making typescript rebuild all files again. 

Typescript only builds when a  ts file is saved with changes.

**Comment by mlorbetske** [comment]
TFS Bug#243977

**Comment by mlorbetske** [comment]
@paulvanbrenk any ideas?

**Comment by paulvanbrenk** [comment]
Can you share a diagnostic build log? Which version of TypeScript are you using? Are you using Gulp/Grunt to build or MSBuild?

**Comment by damienbod** [comment]
msbuild, Typescript: 1.8.10, latest VS

If I setup using grunt, it works fine.

Greetings Damien

**Comment by paulvanbrenk** [comment]
@damienbod  Can you share the diagnostic msbuild logs of the failing rebuild?

**Comment by damienbod** [comment]
@paulvanbrenk, I have no build logs for this, we changed the typescript build to use grunt.

**Comment by mlorbetske** [comment]
Since we weren't able to get the diagnostic information to look in to this further, closing this issue. If you run in to this again, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site
