### ISSUE TITLE
Generating DLLs in different folders breaks VS Enterprise Architecture

### ISSUE THREAD

**Issue by gabrielcs** [aspnet/Tooling#680]
It appears the layer diagram feature under the Architecture menu on Visual Studio Enterprise expects all DLLs to be available under the `bin/` folder of each project after compilation. However, with .NET Core they seem to be generated under other folders, for example `bin/Debug/netcoreapp1.0/` or `bin/Debug/netstandard1.6/`. See [screenshot](https://www.dropbox.com/s/f14kcz8ty3nax3m/dll-error.png?dl=0).

As a side note, the layer diagram feature also seems to break when setting a different `buildOptions.outputName` in `project.json`.

I am using Visual Studio 2015 update 3.

This issue was originally posted on June 30th on [Microsoft Connect](https://connect.microsoft.com/VisualStudio/feedback/details/2877781/layer-diagram-not-working-with-net-core).

**Comment by mlorbetske** [comment]
TFS Bug#243976

**Comment by mlorbetske** [comment]
From the linked TFS item, this should be working as of the move to csproj based .NET Core projects in Visual Studio 2017. If you're still experiencing this issue, please report it on the [developer community](https://developercommunity.visualstudio.com/) site.
