### ISSUE TITLE
Visual studio 2015 .netcore rc2 auto generation error (minor issue)

### ISSUE THREAD

**Issue by blackdwarf** [aspnet/Tooling#683]
If i create a MVC project and i try generating a missing class based on an existing class in say the models folder then it does get the right name space but end up in the application root folder instead of the espected subfolder where the file i generated it with is located..

Move from dotnet/core#122

/cc @Zerq

**Comment by mlorbetske** [comment]
TFS Bug#243978

**Comment by mlorbetske** [comment]
From the linked TFS item, this has been marked as fixed
