### ISSUE TITLE
DotNetCore.1.0.0-VS2015Tools.Preview2 Setup Failed

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/Tooling#687]
![image](https://cloud.githubusercontent.com/assets/1798510/17155085/fb61be70-5383-11e6-8efd-3d1a06b53e83.png)

https://gist.github.com/MaherJendoubi/975cbca78779ae7653688edec86e6df4

**Comment by rogersachan** [comment]
I'll move my solution here since my issue was closed

## Quick-quick fix

Just run this cmd in the directory you downloaded the tooling
```
DotNetCore.1.0.0-VS2015Tools.Preview2.exe SKIP_VSU_CHECK=1
```

**Comment by atifaziz** [comment]
@rogersachan Is that an official workaround?

**Comment by MaherJendoubi** [comment]
@atifaziz for me yes

**Comment by atifaziz** [comment]
@MaherJendoubi Am glad it works for you but that wasn't my question. :)

**Comment by rogersachan** [comment]
@atifaziz I haven't heard anything but it looks like this is a versioning issue (which I assume is easy to fix).  This workaround is also on MS COnnect so I suppose so.

**Comment by atifaziz** [comment]
@rogersachan [It's reported on MS Connect](https://connect.microsoft.com/VisualStudio/feedback/details/2959391/net-core-1-0-0-vs2015-tooling-preview-2-will-not-install) and several other places (see #655, #685 and aspnet/Home#1626) and yet you're right (thanks!) that only the MS Connect one [points to it as a known issue with `SKIP_VSU_CHECK=1` as a workaround](https://github.com/aspnet/Tooling/blob/master/README.md#release-notes-and-known-issues):

> Due to a known issue in the setup detection logic, even though you have Visual Studio 2015 Update 3 RC installed, you might see the following message when you run the installer. This will be fixed in the next build. For now, to work around this and bypass the check, you can run the EXE from a command prompt and then pass SKIP_VSU_CHECK=1 at the end. 

![Setup failed screenshot](https://cloud.githubusercontent.com/assets/8246794/16207980/dd636272-36e4-11e6-9d5a-295027a5ac5c.png)

However, that mentions the RC whereas the issue persists with the release version of VS 2015 Update 3 so I'm guessing this is one of those bugs they let slip as “has a workaround”? The .NET Core tooling is preview after all.

**Comment by MehdiDehghani** [comment]
I got this error, I tired `DotNetCore.1.0.0-VS2015Tools.Preview2.exe SKIP_VSU_CHECK=1` too, but still got the error.
![error](https://cloud.githubusercontent.com/assets/9152330/17268894/0846d64e-564e-11e6-9960-58168220695c.jpg)

I have installed `VS 2015 update 3 Enterprise edition`, also installed `DotNetCore.1.0.0-Runtime-x86` and `DotNetCore.1.0.0-SDK.Preview2-x86`

**Comment by rogersachan** [comment]
@MehdiDehghani Can you share the log file?

**Comment by MehdiDehghani** [comment]
@rogersachan The error screenshot didn't get enough info?

**Comment by mlorbetske** [comment]
TFS Bug#247565

**Comment by wr125** [comment]
Thanks!! Also, if you find the cmd (pointing the download file directory) a little time consuming/frustrating like I had ;). Just use (in cmd) 'cd..' until "C:\Program Files (x86)" and drag and drop your download.exe file in "C:\Program Files (x86)". And the run "DotNetCore.1.0.0-VS2015Tools.Preview2.exe SKIP_VSU_CHECK=1" script as mentioned. Then, BOOMM!!! Thanks again.

**Comment by MehdiDehghani** [comment]
Nice, I moved `DotNetCore.1.0.0-VS2015Tools.Preview2.exe` to `C:\Program Files` folder and run `DotNetCore.1.0.0-VS2015Tools.Preview2.exe SKIP_VSU_CHECK=1`, the tool was successfully installed.
Thanks @wr125

**Comment by balachir** [comment]
This issue should now be fixed as part of a [cumulative update](https://github.com/aspnet/Tooling/blob/master/release-notes.md#8112016-tooling-update-for-net-core-100---vs-2015-tooling-preview-2) that we released. The VS 2015 Tooling installer on the main [download page](https://www.microsoft.com/net/core#windows) for .NET Core has also been updated to include this cumulative update, so new installs of the tooling will not require the SKIP_VSU_CHECK workaround anymore.
