### ISSUE TITLE
Please allow us to turn off auto-sync of Bower/NPM

### ISSUE THREAD

**Issue by ciel** [aspnet/Tooling#693]
It's pretty frustrating that when you edit a `package.json` or `bower.json` file, Visual Studio automatically tries to run `npm install` or `bower install`. It's slow, cumbersome, and makes the editor lag.

Can we please get an option to turn this off, and only run it when we're ready to?

**Comment by scottaddie** [comment]
This is closely related to issue https://github.com/aspnet/Tooling/issues/357.

**Comment by mlorbetske** [comment]
TFS Bug#247568

**Comment by scottaddie** [comment]
@mlorbetske Should this be closed now that this feature exists in VS 2017 RC? Specifically, this can be accomplished in **Tools** --> **Options** --> **Projects and Solutions** --> **Web Package Management** --> **Package Restore**.

**Comment by mlorbetske** [comment]
@scottaddie yep, thanks!
