### ISSUE TITLE
Migrations Deployment from VSTS

### ISSUE THREAD

**Issue by rowanmiller** [aspnet/Tooling#698]
@bragma had the following question about the `right-click->Publish...` feature in the ASP.NET tooling

> Hi,
>  is there some documentation describing how to apply migrations on deploy using VSTS? I've seen this has been integrated in VS, and I'd like to do the same when deploying from VSTS. Please let me know if I should ask elsewhere.
>  Thanks!

Originally posted in the EF repo: https://github.com/aspnet/EntityFramework/issues/5993

**Comment by mlorbetske** [comment]
TFS Bug#247571

**Comment by mlorbetske** [comment]
Documentation on how to accomplish this can be found [here](https://github.com/aspnet/websdk/blob/dev/README.md)
