### ISSUE TITLE
xproj-project-files have C# in the icon file even on F# projects

### ISSUE THREAD

**Issue by Thorium** [aspnet/Tooling#699]
xproj-project-files have C# in the icon (also in Visual Studio) file even on F# projects.

icons should be language-agnostic.

**Comment by madskristensen** [comment]
@Thorium Where do you see the C# icon? Can you add a screen shot, please?

**Comment by Thorium** [comment]
Sorry, wasn't project.json, was .xproj generated with e.g. `dotnet new -l F#`

**Comment by mlorbetske** [comment]
This issue should be fixed with the upcoming changes that move away from .xproj based projects
