### ISSUE TITLE
Editing commands in the project JSON file causes them to be added to the start button drop down, they are never deleted.

### ISSUE THREAD

**Issue by shanselman** [aspnet/Tooling#7]

**Comment by sayedihashimi** [comment]
Should be fixed in the latest builds. @BillHiebert was just in there making some updates.

@BillHiebert can we close this or is there anything pending from your side?

**Comment by BillHiebert** [comment]
Yes, I fixed this about a month ago. There is a caveat though. If you have updated the definition of command in any way: added an environment variable, command line arg, etc. We leave it alone. This was how it was spec'd to work.

**Comment by sayedihashimi** [comment]
Ok I'll close this.
