### ISSUE TITLE
Browser Link toolbar not visible in the page

### ISSUE THREAD

**Issue by borekb** [aspnet/Tooling#70]
When I open an ASP.NET site in a browser with Browser Link enabled, I see no toolbar at the bottom. I remember that WebEssentials had some kind of config for this, and if I remember correctly pressing Ctrl in the browser brought the toolbar up on demand but it's not working for me in VS2015 RC and Chrome.

By the way, is Browser Link an ASP.NET Tooling feature or a WebEssentials feature? It's advertised on both and it's confusing where to report issues. Any clarification here would be appreciated, thanks.

**Comment by sayedihashimi** [comment]
@madskristensen ?

**Comment by madskristensen** [comment]
Browser Link itself is a VS feature and the bottom browser menu is a Web Essentials feature. We're working on full ASP.NET 5 support on both Browser Link and Web Essentials

**Comment by borekb** [comment]
Ah, that makes sense. Maybe a suggestion then - in the Browser Link Dashboard, amongst the messages like "Project must use Razor v2 or later", maybe there could be a message like "More Browser Link features are available through the [Web Essentials](http://vswebessentials.com/) extension", and the page http://vswebessentials.com/features/browserlink would clarify what ships as part of VS and what's added via the extension.

How does that sound?

**Comment by madskristensen** [comment]
Sounds like a good idea

**Comment by AronGrzywaczewski** [comment]
So what is the answer? I installed the VS Web Essentials 2017 addon to my MS VS 2017 and I still can't see the Tool Bar in the browser? 
Do I need a specific version of the Visual Studio?

**Comment by madskristensen** [comment]
There is now a Google Chrome extension that exposes what used to be on the old menu. Get it here https://chrome.google.com/webstore/detail/web-essentials/mghdcdlpcdiodelbplncnodiiadljhhk

**Comment by AronGrzywaczewski** [comment]
Hi, 
Thanks for getting back to me on this one.
I installed the Chrome extension, but I still can't see the browser link inspector options: Design Mode and Inspect Mode. Do you know what could be the problem?

**Comment by AronGrzywaczewski** [comment]
That's great, thanks Mads

I just wanted to clarify this for everyone who is having the same problem in VS 2017. After installing Web Essentials 2017 and the extension in the Chrome browser:  https://chrome.google.com/webstore/detail/web-essentials/mghdcdlpcdiodelbplncnodiiadljhhk you will also have to install additional addon in Visual Studio in order to work in design mode or to inspect the elements of the website called Browser Link Inspector: https://marketplace.visualstudio.com/items?itemName=MadsKristensen.BrowserLinkInspector2017

**Comment by MarkJhomel** [comment]
How about the Edge? I already installed the Web Essentials 2017 and Browser Link Inspector 2017 but still there are no toolbar available in the Edge browser @madskristensen Sir.

**Comment by madskristensen** [comment]
@MarkJhomel Try this https://github.com/madskristensen/WebEssentialsChrome

**Comment by nishavcm** [comment]
@AronGrzywaczewski  it does not work for me, I have installed Browser link inspector and added web essential extension into chrome.
it always shows me disabled
