### ISSUE TITLE
Got error after installing KB3165756 Update for Microsoft Visual Studio 2015 Update 3 

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/Tooling#704]
![image](https://cloud.githubusercontent.com/assets/1798510/17343918/677c1a5c-5900-11e6-8815-8c152da7c25c.png)

**Comment by MaherJendoubi** [comment]
I've just fixed it. I uninstalled the tooling then I did DotNetCore.1.0.0-VS2015Tools.Preview2.exe SKIP_VSU_CHECK=1

**Comment by jods4** [comment]
Yup, it seems a critical issue has slipped through. 
I installed the Update 3 patch today and I can't start my ASP.NET Core project anymore. :(
I get the 502.5 Process failure as well.

**Comment by mlorbetske** [comment]
Glad to hear this has been figured out. Closing this for now as we are tracking the issues with .NET Core setup with relation to the VS 2015 U3 updates in several other places. Official documentation on the workaround for the installation issue may be found here https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites#issues
