### ISSUE TITLE
Vs2015 update 3 patch1 intellisense doesn't work!!!

### ISSUE THREAD

**Issue by eByte23** [aspnet/Tooling#705]
Seems like after the patch to update 3 the intellisense on dotnet core apps has stopped work.

**Comment by mlorbetske** [comment]
Hi @eByte23 does repairing `Microsoft .NET Core 1.0.0 - VS 2015 Tooling Preview 2` in Programs and Features help at all?

**Comment by mlorbetske** [comment]
Since we've not heard back in nearly a year, closing this one. If you're still experiencing this, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site
