### ISSUE TITLE
project.json no intellisense but Microsoft, System and EntityFramework

### ISSUE THREAD

**Issue by nfdevil** [aspnet/Tooling#707]
The project.json Intellisense doesn't show NuGet packages anymore, even on a RC1 project.

![projectjson](https://cloud.githubusercontent.com/assets/7434048/17361548/634521ec-5971-11e6-8bb2-c9d8d69b18ba.png)

.NET Tooling version: 14.1.20624.0
VS 2015 version: 14.0.25425.01 Update 3
.NET version: 4.6.01055

**Comment by mlorbetske** [comment]
Hi @nfdevil it looks like this may be an issue with Resharper, please post an issue at the address below for that team to address. Thanks!
https://youtrack.jetbrains.com/oauth?state=%2FnewIssue%3Fproject%3DRSRP%26clearDraft%3Dtrue%26c%3DSubsystem%2BJavaScript%26c%3DAssignee%2BAnton.Lobov%26c%3DPriority%2BShow-stopper%26c%3DType%2BBug%26c%3DFix%2Bversion%2B2016.2

**Comment by mlorbetske** [comment]
Closing this one as it seems to be an ReSharper issue
