### ISSUE TITLE
A DNX runtime has not been installed

### ISSUE THREAD

**Issue by andreister** [aspnet/Tooling#71]
After upgrading to VS2015 RC Community Edition, publishing stopped working (right click on the project in Solution Explorer, click "Publish") with the error 

```
All packages are already installed and there is nothing to restore.
NuGet package restore finished.
1>------ Build started: Project: Xxx.Web, Configuration: Debug Any CPU ------
1>
1>  Build succeeded.
1>           0 Warning(s).
1>           0 Error(s).
1>
1>  Time elapsed 00:00:00.3450000
1>
========== Build: 1 succeeded or up-to-date, 0 failed, 0 skipped ==========
Connecting to C:\Temp\Xxx_drop...
A DNX runtime has not been installed.
```

I've done `dnvm upgrade` and here's the `dnvm list` as of now

```
Active Version           Runtime Architecture Location                           Alias
------ -------           ------- ------------ --------                           -----
       1.0.0-beta4       clr     x64          C:\Users\andrew\.dnx\runtimes
       1.0.0-beta4       clr     x86          C:\Users\andrew\.dnx\runtimes
       1.0.0-beta4       coreclr x64          C:\Users\andrew\.dnx\runtimes
       1.0.0-beta4       coreclr x86          C:\Users\andrew\.dnx\runtimes
       1.0.0-beta4-11271 clr     x86          C:\Users\andrew\.dnx\runtimes
       1.0.0-beta4-11271 coreclr x86          C:\Users\andrew\.dnx\runtimes
       1.0.0-beta4-11566 clr     x86          C:\Users\andrew\.dnx\runtimes default
  *    1.0.0-beta4-11566 coreclr x86          C:\Users\andrew\.dnx\runtimes
```

Publishing fails for any runtime I select from the dropdown, and it did work in CTP6.

Is this a VS problem or a `dnvm` one? Is it possible to specify in the error, which runtime exactly is missing?

**Comment by andreister** [comment]
Ok so I deleted all `dnx` runtimes and then run `dnx install latest`.

After that my build started to fail, luckily with the runtime version:
```
1>  Cannot find DNX runtime dnx-clr-win-x86.1.0.0-beta4-11271 
in the folder: C:\Users\andrew\.dnx\runtimes
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DNX\
Microsoft.DNX.targets(117,5): error : The Dnx Runtime package needs to be installed
```

The problem was in my `global.json` so I changed the runtime there from `11271` to `default` and then build succeeded and publishing happily succeeded as well.

So re original problem, looks like even though I was selecting specific dnx from the dropdown in VS publishing wizard, it still somehow wanted to use another dnx (from `global.json`?)

**Comment by sayedihashimi** [comment]
@andreister it sounds like you were able to resolve this. I'll close this now, if there is still any issues please re-open.
