### ISSUE TITLE
Remove bower.json from the default ASP.NET Core Web Application new project template.

### ISSUE THREAD

**Issue by ryanelian** [aspnet/Tooling#710]
The matter of [gulp vs grunt](https://github.com/aspnet/Tooling/issues/83#issuecomment-227527780) was resolved in a manner that did not incite another world war by removing the task runner from the project. (At the end I ended up using gulp nowadays but that's another topic for another day)

Now, can the bower.json be removed as well? (Currently it installs jquery, jquery-validation, jquery-validation-unobtrusive, bootstrap)

- Not everyone uses JQuery to develop the web app. What about Angular? React? Typescript?

- Not everyone uses Bootstrap to develop the UI. What about [Semantic UI](http://semantic-ui.com/)? What about [Material Design](https://material.angularjs.org/latest/)? Zurb Foundation? Surely the sample project UI doesn't need a full-blown responsive framework, yes?

- And finally, not everyone uses Bower. NPM alone is good enough for the job. (NPM can even [install directly from online git repo](http://stackoverflow.com/questions/17509669/how-to-install-nodejs-package-from-github-directly), which is awesome.)

- Also, the I think the `BundlerMinifier.Core` tooling should be removed from the `project.json`. Many people actually use gulp for the job.

**Comment by mlorbetske** [comment]
Moved this to the templates repo, closing this one so we can track it over there
