### ISSUE TITLE
Snippet problem in cshtml

### ISSUE THREAD

**Issue by wjzhou** [aspnet/Tooling#711]
In my custom snippet, the TAB/ENTER key doesn't work as expected.

Expectation:
When I type TAB, it should go to next replacement, and when I type ENTER, it should end the snippet

Actural:
The editor insert a literal TAB/ENTER in the replacement.

More Details:
I intend to create a snippet to help insert html input.

```
<div class="form-group">
      <label asp-for="PropertyName" class="gs-label-group control-label"></label>
      <div class="gs-input-group">
             <input asp-for="PropertyName" class="form-control" />
             <span asp-validation-for="PropertyName" class="text-danger"></span>
       </div>
</div>
```

My snippet definition:

```
<?xml version="1.0" encoding="utf-8"?>
<CodeSnippets
    xmlns="http://schemas.microsoft.com/VisualStudio/2005/CodeSnippet">
    <CodeSnippet Format="1.0.0">
        <Header>
            <Title>input group</Title>
            <Shortcut>gsi</Shortcut>
        </Header>
        <Snippet>
            <Declarations>
                <Literal>
                    <ID>PropertyName</ID>
                    <ToolTip>The ViewModel Property Name</ToolTip>
                    <Default>PropertyName</Default>
                </Literal>
            </Declarations>
            <Code Language="Html">
                <![CDATA[<div class="form-group">
    <label asp-for="$PropertyName$" class="gs-label-group control-label"></label>
    <div class="gs-input-group">
        <input asp-for="$PropertyName$" class="form-control" />
        <span asp-validation-for="$PropertyName$" class="text-danger"></span>
    </div>
</div>
$end$]]>
            </Code>
        </Snippet>
    </CodeSnippet>
</CodeSnippets>
```

The snippet works in html file and ASPNET4/cshtml but not in ASPNET5/cshtml. The editor provide intellisense completion for the asp-for field though, which is very nice.

Also, I have problem for `@if` snippet, when I use it in cshtml. I get a popup says
"Operation is not valid due to the current state of the object."
Don't know if it is related.

**Comment by mlorbetske** [comment]
@alexgav any ideas on this one?

**Comment by mlorbetske** [comment]
I searched for this in the internal bug database & have found an bug that indicates that this has been fixed. If you're still running in to this, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site
