### ISSUE TITLE
Tooling Preview 2 Install failed when using IIS Shared Configuration 

### ISSUE THREAD

**Issue by ahjephson** [aspnet/Tooling#715]
The installer fails with IIS Shared Configuration enabled but does not provide any meaningful message in the logs. After running though the components it is trying to install I found that AspNetCoreModule was the component that was failing.  The log for the aspnetcoremodule_x64_en_rc2_39.msi gave the following error:

CAQuietExec:  Unlocked section "system.webServer/handlers" at configuration path "MACHINE/WEBROOT/APPHOST".
CAQuietExec:  ERROR ( hresult:80070005, message:Failed to commit configuration changes.  
CAQuietExec:  
Access is denied.
CAQuietExec:  
 )

Turning off Shared Configuration allowed the install to take place.

**Comment by GuardRex** [comment]
@ahjephson You prob want to move this over to the IISIntegration repo issues: https://github.com/aspnet/IISIntegration/issues

**Comment by ahjephson** [comment]
Done
