### ISSUE TITLE
The MSBuild OutDir property should not be defined differently in dotnet projects

### ISSUE THREAD

**Issue by dls314** [aspnet/Tooling#716]
I'm not sure why $(OutDir) in my dotnet projects from the current release tooling gets set to `.\bin\` instead of the more normal `.\bin\$(Configuration)`, but it's annoying. I end up with something like the following snippet in every MSBuild integration.

```
  <Choose>
    <When Condition="'$(MSBuildProjectExtension)' == '.xproj'">
      <PropertyGroup>
        <MyOutDir Condition="'$(MyOutDir)' == ''">$(OutDir)$(Configuration)</MyOutDir>
      </PropertyGroup>
    </When>
    <Otherwise>
      <PropertyGroup>
        <MyOutDir Condition="'$(MyOutDir)' == ''">$(OutDir)</MyOutDir>
      </PropertyGroup>
    </Otherwise>
  </Choose>
```

**Comment by mlorbetske** [comment]
This should be fixed in the upcoming move to use csproj project files
