### ISSUE TITLE
refs folder not created with TFS Build using Visual Studio template

### ISSUE THREAD

**Issue by ksatokcc** [aspnet/Tooling#717]
The "refs" folder is created when publishing from a Visual Studio publish profile. However, when I use TFS Build using the Visual Studio template, the "refs" folder does not created (and therefore my website will not run under IIS because it is missing .dlls) How can the refs folder get created via TFS build?

I have preserveCompilationContext set:
"buildOptions": {
"emitEntryPoint": true,
"preserveCompilationContext": true
},

I'm wondering if TFS 2015 Update 1 version might be an issue? Do we need to have the latest Update 3? There is a dependency on SSRS 2012 that is slowing our upgrade plans, as we need to upgrade to that first.

**Comment by mlorbetske** [comment]
@ksatokcc I've reached out to the TFS team on this and have not quite figured out what's going on here. Is this "refs" folder something that's part of a build customization that's not working correctly?

**Comment by ksatokcc** [comment]
No, the "refs" folder is part of the documented directory structure. See https://docs.asp.net/en/latest/hosting/directory-structure.html

I have found a work around to this issue by including the following steps in my build definition:

- Visual Studio Build
- Command Line - dotnet publish

I found that the Visual Studio Build step does not create the "refs" folder, and the dotnet publish command does not build all my subprojects. But if I execute both of these, I get the desired result.

**Comment by mlorbetske** [comment]
Now that the Visual Studio publish gesture and the command line publish gesture both use the same targets, this should be resolved. You can see examples of how to call the web publishing targets at https://github.com/aspnet/websdk. These (of course) apply to the new, csproj .NET Core projects. For project.json based projects, I believe you have the correct solution.
