### ISSUE TITLE
TypeScript - False recursive inheritance compilation error inside MVC areas

### ISSUE THREAD

**Issue by troyji** [aspnet/Tooling#72]
I have a TypeScript AMD class located at "/Scripts/App/MyClass.ts".  I have another class with the same relative file path inside of an MVC Area located at "/Areas/MyArea/Scripts/App/MyClass.ts" that inherits from the original class.

```typescript
// File: /Scirpts/App/MyClass.ts
class MyClass { ... }
export = MyClass;
```

```typescript
// File: /Areas/MyArea/Scirpts/App/MyClass.ts
import CoreMyClass = require("Scripts/App/MyClass");
class MyClass extends CoreMyClass { ... }
export = MyClass;
```

In the area's class, I receive the error "Type 'MyClass' recursively references itself as a base type".  Note that changing the name of one of the classes has no affect.  I speculate that the compiler assumes the two files are the same because they share a relative path, "/Scripts/App/MyClass.ts".  If I change one of the paths slightly (e.g. change App to App2), everything is happy.

Visual Studio 2015 RC
MVC5

**Comment by davidfowl** [comment]
Is this an ASP.NET specific bug? or a general VS 2015 issue?

**Comment by troyji** [comment]
I cannot say for sure - what is responsible for giving the TypeScript compiler order of operations for paths?  Is the TypeScript compiler the only provider of Error List items (is it guaranteed that the compiler is the source of the item)?  I did verify that MVC Areas does not seem to be a factor.  The same problem occurs in the base project.  (e.g. /Scripts/MyClass.ts and /SubFolder/Scripts/MyClass.ts).

**Comment by davidfowl** [comment]
If the same behavior happens outside of an ASP.NET 5 project then the bug doesn't belong here.

**Comment by troyji** [comment]
No, this is MVC5.  Where does it go?

**Comment by troyji** [comment]
All foreplay with you, no joy.

I :heart: ASP.NET 5, :shipit:

Thanks

**Comment by troyji** [comment]
Moved: https://github.com/Microsoft/TypeScript/issues/3162
