### ISSUE TITLE
WebToolsExtensionsVS14 installer doesn't find VS14 installed

### ISSUE THREAD

**Issue by andreszs** [aspnet/Tooling#721]
I can't get **WebToolsExtensionsVS14** to install because it says that _Visual Studio 14 is not installed_. I have installed VS2015 Community, and I'm using W8.1 x64, UAC is disabled and all my cmd windows are executed as Administrator.

Here's a part of the log file, which is attached at the bottom as well as a list of of installed programs. Thanks in advance.

Action start 13:21:54: AppSearch.
AppSearch: Property: NETFRAMEWORK40FULLRTM, Signature: SystemWebDll
MSI (c) (C4:A0) [13:21:54:315]: Note: 1: 1322 2:  
MSI (c) (C4:A0) [13:21:54:315]: Note: 1: 1322 2:  
MSI (c) (C4:A0) [13:21:54:315]: Note: 1: 1322 2:  
MSI (c) (C4:A0) [13:21:54:315]: Note: 1: 1322 2:  
MSI (c) (C4:A0) [13:21:54:315]: Note: 1: 1325 2: System.Web.dll 
MSI (c) (C4:A0) [13:21:54:315]: PROPERTY CHANGE: Adding NETFRAMEWORK40FULLRTM property. Its value is 'C:\Windows\Microsoft.NET\Framework\v4.0.30319\System.Web.dll'.
AppSearch: Property: MSIEXEC_DIR, Signature: MSIEXEC_DIR_KEY
MSI (c) (C4:A0) [13:21:54:331]: PROPERTY CHANGE: Adding MSIEXEC_DIR property. Its value is 'C:\Windows\SysWOW64\'.
AppSearch: Property: VISUALSTUDIO_INSTALLDIR, Signature: VisualStudioInstallDirRegistry
AppSearch: Property: VS_SHELLDIR, Signature: VisualStudioShellDirRegistry
AppSearch: Property: VISUALSTUDIO_PROJ_DIR, Signature: VisualStudioProjTemplateRegistry
MSI (c) (C4:A0) [13:21:54:331]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE32\SOFTWARE\Microsoft\VisualStudio\14.0\VSTemplate\Project 3: 2 
AppSearch: Property: VISUALSTUDIO_ITEM_DIR, Signature: VisualStudioItemTemplateRegistry
MSI (c) (C4:A0) [13:21:54:331]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE32\SOFTWARE\Microsoft\VisualStudio\14.0\VSTemplate\Item 3: 2 
AppSearch: Property: VISUALSTUDIO_EXE, Signature: VISUALSTUDIO_EXE_File
MSI (c) (C4:A0) [13:21:54:331]: Note: 1: 1322 2:  
MSI (c) (C4:A0) [13:21:54:331]: Note: 1: 1322 2:  
AppSearch: Property: VS_NGEN_EXE_CONFIG_PATH, Signature: VS_NGEN_EXE_FileSearch
MSI (c) (C4:A0) [13:21:54:331]: Note: 1: 1322 2:  
MSI (c) (C4:A0) [13:21:54:331]: Note: 1: 1322 2:  
AppSearch: Property: WEBTOOLSITEMTEMPLATESCACHE, Signature: WebToolsItemTemplatesCacheSearch
MSI (c) (C4:A0) [13:21:54:331]: Note: 1: 1402 2: HKEY_LOCAL_MACHINE32\SOFTWARE\Microsoft\Web Tools\Visual Studio 14 3: 2 
Action ended 13:21:54: AppSearch. Return value 1.
MSI (c) (C4:A0) [13:21:54:331]: Doing action: LaunchConditions
Action 13:21:54: LaunchConditions. Evaluating launch conditions
Action start 13:21:54: LaunchConditions.
This product requires Visual Studio 14. Please install Visual Studio 14, then try installing this product again.
MSI (c) (C4:A0) [13:21:58:830]: Note: 1: 2205 2:  3: Error 
MSI (c) (C4:A0) [13:21:58:830]: Note: 1: 2228 2:  3: Error 4: SELECT `Message` FROM `Error` WHERE `Error` = 1709 
MSI (c) (C4:A0) [13:21:58:830]: Product: Microsoft ASP.NET and Web Tools 2015 (Beta8) - Visual Studio 2015 -- This product requires Visual Studio 14. Please install Visual Studio 14, then try installing this product again.

![software](https://cloud.githubusercontent.com/assets/10298071/17596456/caf44dde-5fc7-11e6-8fd9-09acfb5d7625.png)

[install.txt](https://github.com/aspnet/Tooling/files/413700/install.txt)

**Comment by mlorbetske** [comment]
@joeloff any ideas?

**Comment by joeloff** [comment]
WTE installer will look for the matching devenv.exe. Looking at the logs, it's not able to locate it. Did Community install successfully?

**Comment by andreszs** [comment]
I have uninstalled everything, cleared the registry with Norton Utilities, cleared all temp files and downloaded the VS2015 ISO image. The I installed from the ISO without problems, everything worked perfectly. Thank you.

**Comment by balachir** [comment]
@andreszs , it looks like your issue is resolved now. Going ahead and closing this one.
