### ISSUE TITLE
Resource dll does not use project namespace

### ISSUE THREAD

**Issue by sanchobear** [aspnet/Tooling#722]
When building a localized asp.net web app the resource files are compiled to an assembly. The namespace is derived from the directory where the project is located. The default namespace of the project is ignored and the IStringLocalizer inside the controller fails resolving resource strings. The IView localizer seems more tolerant.
The resource compiler should use the project's default namespace setting.

**Comment by mlorbetske** [comment]
This is, unfortunately, by design. However, with the move to using csproj, this should behave like any other .NET project
