### ISSUE TITLE
Can't Exclude Files From Project

### ISSUE THREAD

**Issue by MelbourneDeveloper** [aspnet/Tooling#723]
In the xproj format, you can't exclude files from being compiled. I know that the xproj format is going to get dumped, but this problem needs to be fixed in the new version of the csproj format. Meanwhile, it is still a major problem for ASP.Net Core. This problem coupled with the inability to link files in from another project means that sharing .cs files across platforms is virtually impossible without manually managing files with source control, or batch files.

This is a continuation from this issue because the original repo is now defunct:
https://github.com/aspnet/dnx/issues/3033#issuecomment-239211379

**Comment by smbecker** [comment]
Why can't you use the project.json support for include/exclude to control what files are considered for compilation?

**Comment by MelbourneDeveloper** [comment]
I would love to. How do I do that?

**Comment by MelbourneDeveloper** [comment]
After you mentioned it, I found this in project.json

![exclude content](https://cloud.githubusercontent.com/assets/16697547/17608189/0e39bcea-606e-11e6-958e-d7a977dfcfe2.png)

There is some obscure exclude option there, but it's deprecated, and there is a repo issue to go along with it:
https://github.com/aspnet/dnx/issues/1067

**Comment by MelbourneDeveloper** [comment]
There seems to be a "copyToOutput" element under "buildOptions". Does that imply that we're going to be pushed toward a system where files are copied in to the build folder before a compile is done? If so, that's pretty nuts. Why not just allow the linking in of files from other source directories?

**Comment by smbecker** [comment]
https://github.com/aspnet/Announcements/issues/175

**Comment by MelbourneDeveloper** [comment]
It doesn't work. I tried adding these, but the excludeFiles element does nothing:

{
  "version": "1.0.0-*",

  "dependencies": {
    "NETStandard.Library": "1.5.0-rc2-24027",
    "XivicModelAssembliesStandard": "1.0.0"
  },

  "frameworks": {
    "netstandard1.5": {
      "imports": "dnxcore50"
    }
  },
  "buildOptions": {
    "copyToOutput": {
      "exclude": [ "Class.cs" ],
      "excludeFiles": [ "Class.cs" ]
    }
  }
}

Neither the exclude, or excludeFiles element seem to do anything.

**Comment by MelbourneDeveloper** [comment]
I'll create a sample app.

**Comment by MelbourneDeveloper** [comment]
Here is a sample app that demonstrates that this either does not work, or I'm missing something:

https://dl.dropboxusercontent.com/u/79781769/Sample%20Apps/ExcludeFileSample.zip

**Comment by MelbourneDeveloper** [comment]
Either way, the tooling should work through the front end. We shouldn't have to fool around editing text files to use the tools. The tool's UI should be taking care of this for us.

**Comment by MelbourneDeveloper** [comment]
BTW: The above sample is a .NET Core class library, but it's the same problem with ASP.NET Core projects. It's a problem with the xproj format.

**Comment by MelbourneDeveloper** [comment]
My bad. This works!

 "buildOptions": {
    "compile": {
      "excludeFiles": [ "Class1.cs" ],
      "exclude": ["Excluded"]
    }
  }

**Comment by smbecker** [comment]
As the announcement shows, the exclude property should be inside of the compile block.

```
{
  "buildOptions":
  {
    "compile":
    {
      "exclude": []
    }
  }
}
```

**Comment by MelbourneDeveloper** [comment]
Here is the working sample:
https://dl.dropboxusercontent.com/u/79781769/Sample%20Apps/ExcludeFileSample2.zip

**Comment by MelbourneDeveloper** [comment]
OK, so first of all, why are we getting told about this kind of functionality through an announcement on a repo I'd never heard of up until today? I do understand that you work in a team that does a very specific job, but as a user of Visual Studio, I am totally ignorant of how your teams and projects are separated. I've been looking for an answer to this question for weeks, and have posted all over GitHub, and MSDN Forums to find this particular answer. You have no idea how much time I've spent looking for this answer.

**Comment by MelbourneDeveloper** [comment]
Secondly, it's simply not enough to add functionality to a text file structure, and then not update the functionality in Visual Studio. Visual Studio developers have been working with the VS UI for a very long time, and we expect the context menus etc. to reflect the functionality of the project types and add ins. If, all of a sudden we are expected to be editing files like the project.json instead of using the UI, we need to be told about it. Otherwise, we'll continue to expect that the UI, and the project.json will have all of the functionality sync'd.

This has wasted a load of my time, and it will be wasting a load of other peoples' time who are trying to work with the newest toolset.

**Comment by MelbourneDeveloper** [comment]
Lastly, I'm being told elsewhere that the xproj format is going to be dumped, and I've also heard rumours that the project.json will be dumped. Is this true? Can we get some definitive answers on what is going on?

**Comment by MelbourneDeveloper** [comment]
Can we please get some proper documentation on the project.json format, and can this documentation be updated going in to future? What would be really good would be to get some intellisense information about the structures built in to Visual Studio so that we are not flying blind every time we need to change something in the project.json

**Comment by smbecker** [comment]
I personally like the project.json format but that is not a debate to have yet again as it has already been beaten to death.

You can find your project format msbuild questions in the blog posts below

https://blogs.msdn.microsoft.com/dotnet/2016/05/06/net-core-rc2-improvements-schedule-and-roadmap/
https://blogs.msdn.microsoft.com/dotnet/2016/07/15/net-core-roadmap/

**Comment by MelbourneDeveloper** [comment]
These blog posts give me no information whatsoever.

> I personally like the project.json format but that is not a debate to have yet again as it has already been beaten to death.

Really? I didn't hear about it. Where can I read this debate, and what was the result?

**Comment by MelbourneDeveloper** [comment]
What I am really asking for is what the plans are for the latest project formats.

Does xproj have a future? Will there be a project.json in future? Where is the long term documentation for these formats? What is the new csproj format going to look like? What are we supposed to use in the meantime?

**Comment by davidfowl** [comment]
> Does xproj have a future? Will there be a project.json in future? 

We're folding things back into csproj.

> Where is the long term documentation for these formats?

Not available yet,  we're actively working on it. Hopefully we'll have something to share soon.

> What are we supposed to use in the meantime?

Use xproj. We're also providing project conversion from xproj -> new csproj when it's ready.

**Comment by MelbourneDeveloper** [comment]
These are fair enough answers. But, my advice is please...

- Consolidate soon
- Test
- Inform the developers through Visual Studio (especially through context menus, and to a lesser extent, intellisense/intelliprompt doco)

**Comment by MelbourneDeveloper** [comment]
Right now, I need some information on how the copyToOutput structure works. One of the issues I'm up against is linking in .cs files from another project. Apparently we can't link files from other projects. Is that correct?

If not, I need to be able to copy files from another folder in to my .NET Core / ASP .NET Core projects. I can't figure out how it is supposed to work...

**Comment by davidfowl** [comment]
> Right now, I need some information on how the copyToOutput structure works. 

The docs for `project.json` are here https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json. 

Sounds like a workaround for the real solution thought.

> One of the issues I'm up against is linking in .cs files from another project. Apparently we can't link files from other projects. Is that correct?

Sure you can, example here https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/project.json#L13-L23.

**Comment by MelbourneDeveloper** [comment]
> The docs for project.json are here https://docs.microsoft.com/en-us/dotnet/articles/core/tools/project-json. 

You are right. There is documentation for the project.json, and it does include these new structures. I just hadn't realized because I was expecting the functionality to be embedded in Visual Studio, and up until this point, file inclusion etc. had been in the csproj file, in XML, so I'd never thought to look for this stuff in the project.json

> Sure you can, example here https://github.com/aspnet/EntityFramework/blob/dev/src/Microsoft.EntityFrameworkCore/project.json#L13-L23.

Hmm... while I've proven that this actually does work to an extent, the files don't show up in my Solution Explorer. So, it's pretty poor functionality from the Visual Studio point of view.

**Comment by MelbourneDeveloper** [comment]
So, basically, a fair few of my issues have been sorted out now. But, unfortunately, the problem doesn't end there. I'll start another issue to reflect the fact that Visual Studio doesn't show files in the solution explorer that are included in buildOptions\compile

**Comment by MelbourneDeveloper** [comment]
Is this repo the right place to be reporting this type of issue, or is there a better repo?

**Comment by MelbourneDeveloper** [comment]
But, what you've pointed out is overwhelmingly helpful. I've been screaming about the need for this kind of functionality in the xproj format for weeks.

**Comment by MelbourneDeveloper** [comment]
This new functionality works to an extent but how will the solution explorer display files that may be in a completely different folder? When is the Visual Studio functionality for all this going to be included?

**Comment by MelbourneDeveloper** [comment]
My project now compiles without manually copying files in from another project. But, the solution explorer is barren. There are no files there.

**Comment by davidfowl** [comment]
> This new functionality works to an extent but how will the solution explorer display files that may be in a completely different folder? When is the Visual Studio functionality for all this going to be included?

Are you editing those shared project files from multiple projects? Xproj won't show files included and its not going to be added as a feature since we're moving to msbuild and csproj again.

**Comment by MelbourneDeveloper** [comment]
So I keep hearing.

What's the long term plan then?

**Comment by mlorbetske** [comment]
Closing this thread since it hasn't been active in nearly a year.
