### ISSUE TITLE
Instrumentation Profiling: Analysis failed

### ISSUE THREAD

**Issue by davenewza** [aspnet/Tooling#725]
I am able to profile just fine using the CPU sampling profiling method, but when using Instrumentation, the report crashes. The performance ouput reads as follows:

> Profiling started.
> Data written to C:\Product\MyProject\MyProject.Api160803(8).vsp.
> Profiling finished.
> File contains no data buffers
> File contains no data buffers
> Analysis failed

See steps:

In the Performance Profiler, I am targeting 'Executable' and use the performance wizard to configure the type of profiling:

![image](https://cloud.githubusercontent.com/assets/6212830/17621822/5c59253c-6096-11e6-801e-777719126dbe.png)

I then select the project I want to profile:

![image](https://cloud.githubusercontent.com/assets/6212830/17621825/64519b5c-6096-11e6-8451-6cc5b329a45a.png)

**Note:** I am targeting .NET 4.5.2 and NOT the core libraries. I am using VS 2015 Update 3 (14.0.25425.01)

**Comment by mlorbetske** [comment]
@davenewza unfortunately, .NET Core projects currently don't work well (if at all) with the profiler. This is one of the reasons we're investing in moving .NET Core projects to csproj, it'll give us better ways of integrating with the other tools within Visual Studio. We're currently talking with the team that makes the profiler to make sure we work well together going forward.

**Comment by IEvangelist** [comment]
I am looking forward to when this is fixed. I'm hoping that when _Q4/Q1_ come around and we get our **RTM** update that this just works.  Here's to being an optimist!

**Comment by leonel7** [comment]
I agree.  It would be extremely helpful if this worked as it should or intended.  Thank you for the efforts.

**Comment by davenewza** [comment]
I assume this can be closed now that we have VS 2017 and all the supporting tooling for .NET Core.
