### ISSUE TITLE
Performance Profiler does not recognize projects as executables

### ISSUE THREAD

**Issue by oofpez** [aspnet/Tooling#726]
I have a solution built in aspnet core.

When using the Performance Wizard to do CPU sampling, on Page 2 of 4 the window to select an application to target has no options, and a message saying "No launchable projects availible to profile in the current solution"

However, multiple colleagues of mine with exactly the same solution are capable of doing CPU sampling on their machines.

![window](https://cloud.githubusercontent.com/assets/12951237/17623599/194b4012-60a1-11e6-9427-4185ba5ffa14.PNG)

**Comment by mlorbetske** [comment]
This is pretty similar (although not showing the same symptoms) to #725. Currently .NET Core projects don't work well with certain other tools in Visual Studio. As mentioned on the other issue, we're in contact with the team that makes the profiler and will be making sure that that scenario works as we move to using csproj projects for .NET Core.

Closing this issue for now, we can continue the discussion on the other issue if needed.
