### ISSUE TITLE
Restoring nuget packages takes a lot of time

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/Tooling#728]
![image](https://cloud.githubusercontent.com/assets/1798510/17643415/efacb866-6169-11e6-9580-e12b8a33165c.png)

**Comment by mlorbetske** [comment]
This appears to be NPM or Bower

**Comment by mlorbetske** [comment]
TFS Bug#252992

**Comment by jodavis** [comment]
@MaherJendoubi, can you share the contents of the "Bower/npm" Output Window Pane? I'm not sure from your screenshot which component is taking a long time.

Does the install eventually complete?

**Comment by mlorbetske** [comment]
Since there hasn't been a response here in quite some time, I'm closing this. If you're still seeing this behavior, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site
