### ISSUE TITLE
Manage Bower Packages: "No packages found" message missing

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#729]
I'm using VS 2015 Enterprise Update 3 with all of the latest patches and the .NET Core Preview 2 tooling. When searching for a Bower package in the "Manage Bower Packages" dialog, type something that will not be found. Notice that there's no message indicating that nothing was found:

![bower_dialog](https://cloud.githubusercontent.com/assets/10702007/17654225/5c961e52-6266-11e6-9845-7f4fc893966f.png)

This should behave the same way as the "Manage NuGet Packages" dialog. Notice the nice message outlined in the red box below.

![nuget_dialog](https://cloud.githubusercontent.com/assets/10702007/17654234/6eb2da80-6266-11e6-9bd1-02de24c8df0c.png)

**Comment by mlorbetske** [comment]
@madskristensen any ideas?

**Comment by mlorbetske** [comment]
Closing this as there hasn't been any activity in nearly a year, but this is being tracked by the feature team that owns that dialog as part of a broader set of improvements to that experience.
