### ISSUE TITLE
Tag Helpers coloring and intellisense dnx451 dependency

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#73]
Tag Helpers coloring and intellisense does not work on visual studio if project does not target dnx451

For example a project that only target dnxcore50 framework as below.

```
"frameworks": {
    "dnxcore50": {
      "dependencies": { }
    }
  }
```

**Comment by BillHiebert** [comment]
@ToddGrun @NTaylorMullen

**Comment by NTaylorMullen** [comment]
:+1: Bartmax, great find :smile:

**Comment by Bartmax** [comment]
hahaha it wasn't me. I had the problem, you @NTaylorMullen found it why. :)

**Comment by NTaylorMullen** [comment]
Pfff :smile:

**Comment by brentnewbury** [comment]
I had a similar problem to this in a blank website using beta5, but realised it was because I didn't add

```
   "dependencies": {
    "Microsoft.AspNet.Tooling.Razor": "1.0.0-beta5",
    ...
  }
```

For those wondering what [DevnerCoder09](http://xkcd.com/979/) saw.

**Comment by sayedihashimi** [comment]
TFS:151701
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
This should be fixed now
