### ISSUE TITLE
IISExpress fails to start when project name and directory are different

### ISSUE THREAD

**Issue by BrainCrumbz** [aspnet/Tooling#730]
There's a ready-made solution at https://github.com/BrainCrumbz/IISProblem showing this issue. 

## Steps to recreate solution (and problem)

1. Open VS 2015 Community Edition
2. Create new project and select *ASP.NET Core Web Application (.NET Core)* project type
3. Name solution as e.g. `BrainCrumbz.IISProblem`, name project as e.g. `BrainCrumbz.IISProblem.MyProject`
5. Select *Empty* web application type
6. Save all. Do not run, nor build, so not to create hidden `.vs\config\applicationhost.config` yet
7. Remove project
8. Rename **project** folder to e.g. just `MyProject`
9. Add back existing project from renamed folder
10. Add explicit project name, title and version in `project.json`:

  ```json
  "name": "BrainCrumbz.IISProblem.MyProject",
  "title": "BrainCrumbz.IISProblem.MyProject",
  "version": "0.0.0",
```
1. Make sure *IIS Express* profile is selected (the default)
2. Run in debug

## Expected

* VS stays running in debug mode. Browser shows *Hello world* text
* Windows Event Viewer, Applications log, shows a warning by *IIS Express*. We're seeing that on working web applications as well, it seems related to Bitdefender ([issue 309](https://github.com/aspnet/Tooling/issues/309) and [StackOverflow](http://stackoverflow.com/questions/34033654/asp-net-5-web-app-not-running-in-debug-mode-in-iis-express)) and it seems not having effects on this issue

> The directory specified for caching compressed content C:\Users\@@@USERNAME@@@\AppData\Local\Temp\iisexpress\IIS Temporary Compressed Files\Clr4IntegratedAppPool is invalid.  Static compression is being disabled

* Following warning, there's an Information event by *IIS Express AspNetCore Module* with success message:

> Process '10016' started successfully and is listening on port '11928'.

## Actual

* VS stops and leaves debug mode unexpectedly. Browser shows *Server unreachable* page
* Windows Event Viewer, Applications log, shows same warning as before
* Following warning, there's an Error event by *IIS Express AspNetCore Module*:

> Failed to start process with commandline '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\ProjectSystem\VSIISExeLauncher.exe" -debug -p "C:\Program Files\dotnet\dotnet.exe" -a "D:\WS\NET\ASP.NET-Core\BrainCrumbz.IISProblem\src\MyProject\bin\Debug\netcoreapp1.0\MyProject.dll" -pidFile "C:\Users\@@@USERNAME@@@\AppData\Local\Temp\tmpF450.tmp" -wd "D:\WS\NET\ASP.NET-Core\BrainCrumbz.IISProblem\src\MyProject"', ErrorCode = '0x80004005'.

## Environment

* Windows development machine
* Visual Studio 2015 Community Edition Version 14.0.25424.00 Update 3
* Microsoft .NET Core Tools (Preview 2) 14.1.20810.0
  * `dotnet --version` reports *1.0.0-preview2-003121*
  * Also installed brand new one, *DotNetCore.1.0.0-VS2015Tools.Preview2.0.1.exe*, with no improvement

## Notes

On our real-world project that first showed the issue, we've been able, after several trials with directory renaming and *project.json* `name` renaming, to get everything working back again, but at this point we're not sure how we got to that. During those changes we've taken care of renaming folder path in hidden *.vs\config\applicationhost.config* file. Now we're able to have a folder named differently than project (both in *.xproj* and *.json* files), and IIS runs correctly. 

**Edit**: Spoke too soon. After restarting VS, problem comes back again. In order to make it work, *.xproj* filename can be different, but *project.json* `name` property must be **the same as** folder name (or just remove that and leave the implicit default, I guess). Before restarting VS, when IISExpress seemed to run fine, VS showed "strange" issues with debugging files that had been recently modified. It complained that source file opened in VS did not match with the one actually running under debug.

**Comment by mlorbetske** [comment]
Hi @BrainCrumbz this issue should be fixed in the release where the .NET Core projects move to being csproj based. In that system, there will be a single, authoritative, way of determining what the primary output of a build is instead of the individual items that use the output attempting to determine what that name should be on their own.
