### ISSUE TITLE
Deprecated monikers

### ISSUE THREAD

**Issue by israelito3000** [aspnet/Tooling#733]
I still see "dnxcore50" when I create .NET Core Console Application:
"netcoreapp1.0": {
      "imports": "dnxcore50"
    }
dnxcore50 moniker are suppose to be deprecated so why?

**Comment by scottaddie** [comment]
@israelito3000 Out of curiosity, did you already install the [.NET Core Tooling Preview 2 for Visual Studio 2015](https://go.microsoft.com/fwlink/?LinkId=824849)? I do have that installed, and here's what I see in my `project.json`:
```json
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  }
```

**Comment by davidfowl** [comment]
It'll be all gone once tooling is RTM
