### ISSUE TITLE
IIS Debugging

### ISSUE THREAD

**Issue by Serjster** [aspnet/Tooling#734]
Is there a timeline for debugging straight from IIS... not using IIS Express. We have multi-project solutions (Web, API, etc.) that all need to be running at the same time. The current work around is to attach each project or load multiple instances of VS with the same solution... neither is ideal. It would be very helpful if we could run all of our apps in IIS and just debug whichever we are working in at the moment... like the good old days. Is this anywhere on the near horizon? If not, how can I help make it a higher priority?

**Comment by mlorbetske** [comment]
TFS#106198

**Comment by mlorbetske** [comment]
This feature has been added for Visual Studio 2017
