### ISSUE TITLE
Creating projects from templates doesn't install EF commands into PMC

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Tooling#737]
We've received multiple reports of that EF Core Package Manager Console commands are not available right after creating a new template.

> Update-Database : The term 'Update-Database' is not recognized as the name of a cmdlet, function, script file, or operable program.

The problem appears to be resolved by re-starting VS, editing project.json, and/or calling dotnet restore from the command line. 

These commands become available only when NuGet calls the install.ps1 or init.ps1 script from inside the Microsoft.EntityFrameworkCore.Tools package. My guess is that new templates are not running a NuGet restore correctly, which means install.ps1/init.ps1 are never called until the user triggers restore through some other method.

https://github.com/aspnet/EntityFramework/issues/6265
https://github.com/aspnet/EntityFramework.Docs/pull/229

**Comment by mlorbetske** [comment]
@abpiskunov any ideas?

**Comment by abpiskunov** [comment]
It has nothing to do with restore. Init script is executed separately after restore completed, we call nuget explicitly to run init script on all new packages. Will check with nuget team what might be wrong.

**Comment by mlorbetske** [comment]
Closing this in preference for tracking it as TFS 447525 (which implies that the issue where it wasn't getting installed at all has been resolved)
