### ISSUE TITLE
Unable to open Net Core project

### ISSUE THREAD

**Issue by bogdanim36** [aspnet/Tooling#738]
I have error trying open my .Net Core project:

> The project is configured to use .NET Core SDK versions 1.0.0.-preview2.003121 which is not installed or cannot be found...

dotnet --info return informations:

> .NET Command Line Tools (1.0.0-preview2-0003121).

I have o fresh windows 10 install, with VS 2015 Community Version 14.0.25425.01 Update 3.
I all ready tried with repairing Net Core tooling preview, an VC++ 2015.
I tried with dotnet restore - no success.

**Comment by bogdanim36** [comment]
I solved the problem this way:
I unistalled not only .NET Core Tooling Preview 2 (like first time), but also .NET Core SDK Preview 2.
I reinstalled Tooling preview 2.
Now it's seems to be everything ok. :)
Where dotnet command found it where is it C:\Program files\dotnet\dotnet.exe

**Comment by softlion** [comment]
Still does not work for me.

**Comment by manishsingh2061** [comment]
this link helped me lot. i thought it will help others too [Link]( http://errortroubleshooter.blogspot.com/2017/04/the-project-is-configured-to-use-net.html)
