### ISSUE TITLE
Add Reference to .NET 4.6.1 class library project from ASP.NET Core WebApp (.NET Framework) not working

### ISSUE THREAD

**Issue by ChristianSacramento** [aspnet/Tooling#741]
The reference not working.
The message is "Unable to resolve 'ClassLibraryFrameworkFull' for '.NETFramework,Version=v4.6.1'."

![endloadref](https://cloud.githubusercontent.com/assets/15038698/17832335/9276c4d8-6700-11e6-9cff-7a884953e2fa.png)

![projectfragmentlock](https://cloud.githubusercontent.com/assets/15038698/17832479/250ba464-6704-11e6-96c0-794f7dc3eb28.png)

![dotnetrestore](https://cloud.githubusercontent.com/assets/15038698/17832339/a66fd560-6700-11e6-84be-e9eb3334b090.png)

**Comment by davidfowl** [comment]
Using dotnet restore wont work unfortunately. When you xproj -> csproj you need to use nuget.exe restore and msbuild to build your projects. `dotnet build` and `dotnet restore` won't work anymore as they don't know anything about msbuild

**Comment by ChristianSacramento** [comment]
@davidfowl Ok.
I have create my nuget package library

![nuspec](https://cloud.githubusercontent.com/assets/15038698/17912628/ff1f12d4-6994-11e6-8064-1dc39e6a9751.png)

![addpkg](https://cloud.githubusercontent.com/assets/15038698/17912641/1063ba4a-6995-11e6-9d64-7905b11eb8be.png)

![whynotworkref](https://cloud.githubusercontent.com/assets/15038698/17912668/3f1f5510-6995-11e6-98a6-9096d3378a65.png)

but msbuild not working.
The message is "The name 'ClassLibraryFrameworkFull' does not exist in the current context"

**Comment by ChristianSacramento** [comment]
@davidfowl 

References: 
csproj ->xproj
xproj -> csproj
xproj -> csproj -> csproj -> xproj

with nuget packages (with dependency) and builds (it work).
Debug ok work.

thank you so much!!
