### ISSUE TITLE
Basic Nuget Update Failure

### ISSUE THREAD

**Issue by nullcat0** [aspnet/Tooling#742]
This is all without making code or reference changes.

VS2015 14.0.25425.01 Update 3

Go to File -> New -> Project.  Create a new Class Library (Package).

Initial project.json

>
{
  "version": "1.0.0-*",
  "description": "ClassLibrary2 Class Library",
  "authors": [ "me" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
  "frameworks": {
    "net451": { },
    "dotnet5.4": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1-beta-23516",
        "System.Collections": "4.0.11-beta-23516",
        "System.Linq": "4.0.1-beta-23516",
        "System.Runtime": "4.0.21-beta-23516",
        "System.Threading": "4.0.11-beta-23516"
      }
    }
  }
}

Right-click on the project, select Manage Nuget packages...   Go to the Updates screen.  Tick Select all packages and click Update.

End project.json

>
{
  "version": "1.0.0-*",
  "description": "ClassLibrary2 Class Library",
  "authors": [ "me" ],
  "tags": [ "" ],
  "projectUrl": "",
  "licenseUrl": "",
  "frameworks": {
    "net451": {
      "dependencies": {
        "Microsoft.CSharp": "4.0.1",
        "System.Collections": "4.0.11",
        "System.Linq": "4.1.0",
        "System.Runtime": "4.1.0",
        "System.Threading": "4.0.11"
      }
    },
    "dotnet5.4": {
      "dependencies": {
      }
    }
  }
}

Rebuild.

>
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.String' is not defined or imported	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.Object' is not defined or imported	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.Void' is not defined or imported	ClassLibrary2..NET Platform 5.4	
Error	CS1729	'object' does not contain a constructor that takes 0 arguments	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'System' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'AssemblyTitle' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.String' is not defined or imported	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'AssemblyDescription' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.String' is not defined or imported	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'AssemblyConfiguration' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.String' is not defined or imported	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'AssemblyCompany' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.String' is not defined or imported	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'AssemblyProduct' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.String' is not defined or imported	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'AssemblyCopyright' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.String' is not defined or imported	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'AssemblyTrademark' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.String' is not defined or imported	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'AssemblyCulture' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.String' is not defined or imported	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'ComVisible' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.Boolean' is not defined or imported	ClassLibrary2..NET Platform 5.4	
Error	CS0246	The type or namespace name 'Guid' could not be found (are you missing a using directive or an assembly reference?)	ClassLibrary2..NET Platform 5.4	
Error	CS0518	Predefined type 'System.String' is not defined or imported	ClassLibrary2..NET Platform 5.4	

These were all generated from the basic unmodified Class1.cs file.  Epic fail!

I'm guessing from the relocation of the dependencies from one framework to the other that the nuget manager is still trying to work with only the full .net framework, and doesn't play well with dotnetcore.

Also, I notice that if I try locating the dependencies lines back into the dotnet5.4 dependencies although they appear in the references section, they are missing all their child dependencies (is this due to changes in project.lock.json?), which I assume is why I still get these errors, due to a now missing implicit reference.

Having been playing around with VS2015, I have to say that the tooling support for dotnetcore in VS2015 seems rather premature for a paid product at the moment.

Regards,
Rob.

**Comment by mlorbetske** [comment]
Hi @nullcat0 are you using the latest version of the .NET Core tooling preview? If not, it's available here https://www.microsoft.com/net/core#windows but is not included as part of Visual Studio 2015 Update 3.

**Comment by nullcat0** [comment]
No, this was using VS2015 update 3 fresh install.

If there are additional tools required, should there not also be an "Install .NET Core SDK" project type in the project types selection window, like there is with Azure projects?  Otherwise you are allowing end-users to select a project type they are unable to work with by default.

Regards,
Rob.

**Comment by nullcat0** [comment]
Can confirm since installing the Tooling Preview, all the templates have been relabelled as .NET Core instead of DNX, and are using the netstandard1.6 moniker by default.  This seems to significantly stabilise the NuGet package management, as well as a number of reference incompatibility errors that occured under the default VS2015 install.

Again, strongly advise that there be some clearer indication to VS users that the tooling preview is in fact a pre-requisite to working with .NET Core.

Regards,
Rob.
