### ISSUE TITLE
VS2015 still locks up when changing project.json

### ISSUE THREAD

**Issue by nullcat0** [aspnet/Tooling#743]
I know this has been reported with previous versions of VS2015, but all those tickets were closed down.

VS2015 14.0.25425.01 Update 3  running on Windows 10 Pro

When making manual changes to project.json in a Class Library (Package) type project, upon saving the changes to a project.json, Visual Studio locks itself up indefinitely.  Attempting to close it just gives a messsage that Visual Studio is busy performing a task, and requires the process to be killed in Task Manager.

Regards,
Rob.

**Comment by akatz0813** [comment]
+1

**Comment by mlorbetske** [comment]
Are you seeing this in Visual Studio 2015 Update 3 or in Visual Studio 2015 Update 3 + .NET Core 1.0.0 - VS 2015 Tooling Preview 2?

**Comment by nullcat0** [comment]
It was without the Tooling Preview.  Since installing the preview, the project.json file has been far more stable.

As per comment on issue #742, the tooling kit should probably be made available as an "Install this required thing before using these project types" project type in VS out of the box.

Regards,
Rob.
