### ISSUE TITLE
Publish with FTP does not work

### ISSUE THREAD

**Issue by kurtdevocht** [aspnet/Tooling#748]
I want to publish an ASP.NET website:
  - right-click project > Publish...
  - In the dialog I select FPT as publish method

But it fails with the error message

"Unable to open the Web site 'ftp://xxxxx'. The components for communicating with FTP servers are not installed."

Already tried to repair VS, with no success... Should I reinstall some extension?

Environment:
Visual Studio Enterprise 2015 Version 14.0.25425.01 Update 3
+ Microsoft ASP.NET and Web Tools 14.1.20810.0
+ Microsoft ASP.NET Web Framework and Tools 5.2.40314.0

**Comment by mlorbetske** [comment]
@vijayrkn do we have a workaround for this?

**Comment by vijayrkn** [comment]
This means VC12 is not installed. Can you try installing VC12 ? This should fix the issue.

**Comment by kurtdevocht** [comment]
Great! After installing the 32-bit version of https://www.microsoft.com/en-us/download/details.aspx?id=40784 thing are up and running again! Thx!
