### ISSUE TITLE
VS2015/msbuild create different artifacts-structure than Sake/KoreBuild

### ISSUE THREAD

**Issue by Tasteful** [aspnet/Tooling#75]
When building solution from command line with the `Sake/KoreBuild` (`build.cmd`/`makefile.shade` from example https://github.com/aspnet/Identity) the artifacts are found directly below `artifacts/build`-folder. 

When building the same solution from VS2015RC the artifacts are placed in `artifacts/bin/{projectname}/{configuration}`-folder.

Desirable that the artifacts-structure will be the same independent of how the build is starting.

**Comment by sayedihashimi** [comment]
TFS:151700
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
@Tasteful if I'm following you the issue you are bringing up is that if you build the [Identity](https://github.com/aspnet/Identity) solution in VS versus running the build.cmd the outputs are in a different location.

To customize the output path for a dnx/asp.net 5 project you can edit the `OutputPath` property in the `.xproj` file. We haven't added any UI for this in VS yet but we will.

The particular issue you're bringing up I think will need to be discussed in the Identity repo. I'll go ahead and close this now, as it doesn't seem to be a generic tooling issue with ASP.NET 5. If it is please reopen with more details.
