### ISSUE TITLE
Nuget packages not overwrite old versions in csproj and xproj.

### ISSUE THREAD

**Issue by ChristianSacramento** [aspnet/Tooling#752]
Nuget packages not overwrite old versions in csproj and xproj.

**Comment by mlorbetske** [comment]
@ChristianSacramento can you elaborate on this? Is this that you using the NuGet package manager dialog and seeing that the package versions aren't being updated when applying an update? /cc @rrelyea

**Comment by ChristianSacramento** [comment]
@mlorbetske 
I have update my package nuget Library1.nupkg for my local nuget repository.
I have delete the references ClassLibrary2 and ClassLibrary3 from nuspec (Library1).
I install my new package changes (Library1.nupkg), but i see again the old references.

![reftest](https://cloud.githubusercontent.com/assets/15038698/18107838/eae70dec-6f09-11e6-8ba8-e98d4a937711.png)

**Comment by mlorbetske** [comment]
@ChristianSacramento could you check to see if the package you've changed exists at `%userprofile%\.nuget\packages` please? If it does, deleting the one in that location should force it to be obtained from you local feed again instead of from a cached location.

**Comment by ChristianSacramento** [comment]
@mlorbetske
It's Ok.
Thank you
