### ISSUE TITLE
ASP.NET Core Application missing models folders

### ISSUE THREAD

**Issue by wendyshen** [aspnet/Tooling#756]
ASP.NET Core Application missing models folders

**Comment by wendyshen** [comment]
Visual Studio 2015, 
new project -> Visual C# -> Web -> ASP.net Core Web Application (.NET Core) -> Web Application (Authentication is No Authentication) -> OK
there are folders of Controllers and Views, but Models folder is missing.

**Comment by mlorbetske** [comment]
This is currently by design since, when No Authentication is selected, no models are generated by the template
