### ISSUE TITLE
Failed to make the following project runnable

### ISSUE THREAD

**Issue by AndyCJ** [aspnet/Tooling#758]
I'm using: Microsoft .NET Core Tools (Preview 2).

I have an ASP.Net Core Web project which I've configured to run on the net452 framework.
That Web project references a .Net 4.5.2 Class Library project.
The Class Library has a nuget reference to the SQL Server Types native dll.

When building the Web project I get the following error message:
`Failed to make the following project runnable: WebCore451 (.NETFramework,Version=v4.5.2) reason: Could not find a part of the path 'D:\Other Code\Experiments\WebCore451\Dep\bin\packages\microsoft.sqlserver.types.11.0.2\nativebinaries\x64\msvcr100.dll'. WebCore451 C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Common.Targets 262`

The error message says it's looking for the path:
`D:\Other Code\Experiments\WebCore451\Dep\bin\packages\microsoft.sqlserver.types.11.0.2\nativebinaries\x64\msvcr100.dll`

The dll exists in the nuget package folders: `($solution)\packages\microsoft.sqlserver.types.11.0.2\nativebinaries\x64\msvcr100.dll`

And it also exists in the referenced project build output as it's copied on build:
`($project)\bin\($build)`

But neither of those match the path it's looking in.

**Comment by mlorbetske** [comment]
TFS Bug#260812

**Comment by jculverwell** [comment]
I have this issue as well.  Any workarounds?

**Comment by rmwever** [comment]
+1
I'm also experiencing this issue

**Comment by rmwever** [comment]
Found a workaround @jculverwell: 

For ASP.NET applications, add the following line of code to the Application_Start method in Global.asax.cs: 

    SqlServerTypes.Utilities.LoadNativeAssemblies(Server.MapPath("~/bin"));

**Comment by balachir** [comment]
Thanks for your feedback. This seems to be fixed now in the msbuild based tooling for ASP.NET Core projects that ships in Visual Studio 2017.
