### ISSUE TITLE
Host in Cloud silently fails if template dotnet SDK is not on the box.

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Tooling#765]
If you've cleaned up your box to only have a single dotnet SDK (one that does not match the one VS is configured to use) you can run into some problems with Host in Cloud.

**Repro Steps**:
1. File => New Web Application
2. Check host in cloud.
3. Update global.json to point to actual SDK installed on box.
4. Verify application builds/runs locally
5. Publish

The publish ends up pointing you to a site that says it's been created but nothing is available. On closer inspection of publish logs it looks like no MSDeploy task is happening. You can re-publish any number of times and the site still does not publish correctly (even though it says it succeeds).

You can work around this issue by creating a brand new site.

**Comment by mlorbetske** [comment]
@vijayrkn can you take a look?

**Comment by mlorbetske** [comment]
TFS Bug#260784

**Comment by mlorbetske** [comment]
Closing this since host in cloud has been removed for Visual Studio 2017
