### ISSUE TITLE
Produce output on build option hard to discover

### ISSUE THREAD

**Issue by danroth27** [aspnet/Tooling#77]
The new Class Library (Package) and Console Application (Package) templates don't produce packages on disk by default. To actually build a package you need to turn on the Produce output on build option:

![produce-output-on-build](https://cloud.githubusercontent.com/assets/1874516/7691127/e9604ad4-fd6c-11e4-858f-2632d11afd81.png)

This option is difficult to discover and it's not obvious that enabling it will result in a package being built. This problem is aggravated by the fact that DNX projects produce build outputs in a different folder (artifacts) than classic .NET projects.

**Comment by balachir** [comment]
TFS#1175324

**Comment by sayedihashimi** [comment]
We already have a backlog item to handle this.

**Comment by barrytang** [comment]
@rustd and @davidfowl, do we want to check this by default again for Dev14 RTM? Do we still have a perf issue?

**Comment by rustd** [comment]
No. We still have perf issues.

**Comment by barrytang** [comment]
@davidfowl, is the perf issue fixed?

**Comment by rustd** [comment]
@davidfowl ping?

**Comment by BillHiebert** [comment]
Not yet.

**Comment by balachir** [comment]
This is no longer applicable for dotnet-based projects in RC2.
