### ISSUE TITLE
Publish fails in VS 2015 due to broken dll interface

### ISSUE THREAD

**Issue by lukos** [aspnet/Tooling#777]
(Also raised on Connect) Right-click MVC project in "VS 2015 Update 3" and choose "Publish", sometimes crashes immediately, sometimes allows you to click through to the settings page for an App Services deployment. At this point, pressing Next or Publish causes the same crash: 

> Method not found: 'Boolean Microsoft.VisualStudio.Web.AzureAD.Contracts.IVsAzureADService.ProjectUsesAzureAD(System.String, System.String ByRef, Boolean ByRef, Boolean ByRef, Boolean ByRef, Boolean ByRef)'.

This method has been changed in Microsoft.VisualStudio.Web.AzureAD.Contracts.dll to take 5 boolean parameters but VS is still looking for the older method that only takes 4. I tried to replace the dll with the older version (12) but then VS complains that it can't find the correct version (14) of the DLL.

How has such a major mistake made it through testing and why does this not break for everyone trying to use Web Deploy for Azure App Services? I have uninstalled all VS products and reinstalled 2015 to make sure it wasn't a problem due to random versions of stuff built up over time, which has wasted an entire work day and hasn't fixed the problem.

**Comment by mlorbetske** [comment]
TFS Bug#265446

**Comment by mlorbetske** [comment]
@lukos could you paste in the contents of Help -> About from VS please? The "Copy Info" button should put everything on the clipboard

**Comment by lukos** [comment]
Microsoft Visual Studio Enterprise 2015
Version 14.0.25431.01 Update 3
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Architecture and Modeling Tools   00322-80000-00000-AA405
Microsoft Architecture and Modeling Tools
    
UML® and Unified Modeling Language™ are trademarks or registered trademarks of the Object Management Group, Inc. in the United States and other countries.

LightSwitch for Visual Studio 2015   00322-80000-00000-AA405
Microsoft LightSwitch for Visual Studio 2015

Visual Basic 2015   00322-80000-00000-AA405
Microsoft Visual Basic 2015

Visual C# 2015   00322-80000-00000-AA405
Microsoft Visual C# 2015

Visual C++ 2015   00322-80000-00000-AA405
Microsoft Visual C++ 2015

Application Insights Tools for Visual Studio Package   7.6.00907.1
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2015.1   14.1.20907.0
ASP.NET and Web Tools 2015.1

ASP.NET Web Frameworks and Tools 2012.2   4.1.41102.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.40314.0
For additional information, visit http://www.asp.net/

Azure App Service Tools v2.9.5   14.0.20810.0
Azure App Service Tools v2.9.5

Azure Data Lake Node   1.0
This package contains the Data Lake integration nodes for Server Explorer.

Azure Data Lake Tools for Visual Studio   2.1.0000.0
Microsoft Azure Data Lake Tools for Visual Studio

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Git Source Control Provider   1.6.5.1


JavaScript Language Service   2.0
JavaScript Language Service

JavaScript Project System   2.0
JavaScript Project System

Microsoft .NET Core Tools (Preview 2)   14.1.20907.0
Microsoft .NET Core Tools (Preview 2)

Microsoft Azure Hive Query Language Service   2.1.0000.0
Language service for Hive query

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio 2015 - v2.9.40715.2

NuGet Package Manager   3.5.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.60519.0
Microsoft SQL Server Data Tools

ToolWindowHostedEditor   1.0
Hosting json editor into a tool window

TypeScript   1.8.36.0
TypeScript tools for Visual Studio

**Comment by phenning** [comment]
@lukos Are you still running into a problem, or were you able to get this to work? I was unable to reproduce the problem you are experiencing when installing the 2.9.5 Azure SDK on VS 2015 Enterprise. Could you please run the VS Collect tool in order to gather the setup logs so we can see why the assemblies were not being updated on your machine?

You can find the collect tool here: https://www.microsoft.com/en-us/download/details.aspx?id=12493

Please upload the logs to the connect bug you opened so we can investigate more.

**Comment by lukos** [comment]
Yes, it still happens every time. I will upload the logs as requested.

**Comment by dustinbrooks** [comment]
Did you ever get a resolution for this? I'm having the same issue trying to publish (nothing even remotely related to Azure). I've tried reinstalling the Azure SDK and tools. I'm tempted to re-install visual studio, but that is painful and I'm not sure it will help.

**Comment by lukos** [comment]
It seems a long time ago now. I can't remember if I fixed it or at some point I did a full reinstall of Windows 10 when some other things starting going wrong as well. Sorry I can't remember exactly!

**Comment by mlorbetske** [comment]
Unfortunately, we still haven't been able to reproduce this. If anyone is still running in to it, please report the issue on the [Developer Community](http://developercommunity.visualstudio.com/) site where we'll be able to get more information to be able to help diagnose what's going on here.
