### ISSUE TITLE
Unable to start process

### ISSUE THREAD

**Issue by MaherJendoubi** [aspnet/Tooling#779]
![image](https://cloud.githubusercontent.com/assets/1798510/18608759/635f8ed4-7cf2-11e6-87be-22439d1c3aa1.png)

**Comment by mlorbetske** [comment]
If you open the Debug folder, is WebApplication1.exe present in a different path?

**Comment by MaherJendoubi** [comment]
@mlorbetske there is no Debug folder!

**Comment by MaherJendoubi** [comment]
there a bin folder but no WebApplication1.exe anywhere.

**Comment by mlorbetske** [comment]
could you add the contents of your project.json to this issue please?

**Comment by MaherJendoubi** [comment]
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.1",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0",
    "Microsoft.AspNetCore.Mvc": "1.0.1",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview2-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Routing": "1.0.1",
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",
    "Microsoft.Extensions.Configuration.Json": "1.0.0",
    "Microsoft.Extensions.Logging": "1.0.0",
    "Microsoft.Extensions.Logging.Console": "1.0.0",
    "Microsoft.Extensions.Logging.Debug": "1.0.0",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0"
  },

  "tools": {
    "BundlerMinifier.Core": "2.0.238",
    "Microsoft.AspNetCore.Razor.Tools": "1.0.0-preview2-final",
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.0-preview2-final"
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true
    }
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "**/*.cshtml",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "bower install", "dotnet bundle" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

**Comment by mlorbetske** [comment]
I see, it's looking for a project built with the `net452` framework (producing an exe) but it's supposed to be building for `netcoreapp1.0`. Is there a `webapplication1.dll` in the bin folder?

**Comment by MaherJendoubi** [comment]
no webapplication1.dll in the bin folder

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/18818761/bb8bd568-8382-11e6-98a1-69f59064c55c.png)

**Comment by MaherJendoubi** [comment]
![image](https://cloud.githubusercontent.com/assets/1798510/18818767/0bf0f3f8-8383-11e6-923d-cfcbf197fd48.png)

**Comment by MaherJendoubi** [comment]
@mlorbetske something magic happened to my Visual Studio IIS Express it works as a charm now don't know even why! Thanks a lot for the help 👍 👍 👍
