### ISSUE TITLE
Provide build warnings and squiggles in project.json to indicate that authors and description are required fields for NuGet packages

### ISSUE THREAD

**Issue by danroth27** [aspnet/Tooling#78]
By default the packages produced by the new Class Library (Package) and Console Application (Package) templates cannot be uploaded to nuget.org because they do not specify a description or an author in project.json. It would be great if you could get build warnings and squiggles to indicate this issue.

**Comment by sayedihashimi** [comment]
>It would be great if you could get build warnings and squiggles to indicate this issue.

Do you think that most projects will be published to nuget? If so then I agree otherwise it may be noise that most are not interested in.

**Comment by balachir** [comment]
TFS#1175326

**Comment by barrytang** [comment]
@danroth27, @davidfowl , @madskristensen told me that you guys own the project.json schema and have been updating it. Can you guys take care of this?
