### ISSUE TITLE
Problems after upgrading to latest VS2015 update 3 KB31655756

### ISSUE THREAD

**Issue by pantonis** [aspnet/Tooling#784]
After updating to latest update 3 KB31655756 I have following issue. Any assemblies that are used from nuget packages are not copied to bin/Debug They are being downloaded but not copied to the output

**Comment by mlorbetske** [comment]
Is this an ASP.Net Core project that you're getting this behavior with?

**Comment by pantonis** [comment]
I uninstall update and then reinstall and it works now
