### ISSUE TITLE
Does VS 2015 Tooling Preview 3 builds available?

### ISSUE THREAD

**Issue by DreamingDevs** [aspnet/Tooling#791]
Hi,
Currently the latest stable VS2015 Tooling is - **DotNetCore.1.0.1 - VS2015Tools.Preview2.0.2**.
Do we have nightly builds or latest bits for Preview 3 available in downloads?

I downloaded the latest Dotnet CLI **1.0.0-preview3-003686** from [https://github.com/dotnet/cli](https://github.com/dotnet/cli). I wanted to check if VS2015 preview2 tooling will work fine with Dotnet preview3 bits.
Thanks.

**Comment by sayedihashimi** [comment]
Hi @DreamingDevs we are working on preview3 tooling support currently. With that said if you update the version in `global.json` you should get some support. Things may not work exactly right until we release our tooling update for it, but give it a go and let us know if you find anything. Closing this now.
