### ISSUE TITLE
add reference command is not filtering non asp.net 5 projects 

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#8]
I suppose this is not an issue but just one thing still to be done, but if in the solution are present msbuild projects (asp.net 4 and class libraries) in the add reference dialog all the projects are shown,  selectable and I can add to an asp.net 5 project.
I added a class Library with an EF 6 model inside and I noticed that:
1. the program continues to run.
2. editor intellisense does not show any type present in the library.
3. If I explore the library using solution explorer shows a reference to entity framework 7.0.0.-beta 3.

**Comment by davidfowl** [comment]
You can add a reference to non ASP.NET 5 projects.

**Comment by lucamorelli** [comment]
yes, but I suppose I have to use the wrap command, to create the project.json, but if I add the project this way seems that the command is not executed, but just added the reference in the project.json

**Comment by davidfowl** [comment]
The wrap command happens on the fly. Tooling calls kpm wrap. Can you explain in further detail the exact steps.

**Comment by lucamorelli** [comment]
Hmm, I restarted from scratch and this time worked fine (I'll retry later to see if I can repro), but I have a few problems

1. I open my existing solution where I have the web apps and class libraries.
2.Add a webstarter application (framework 4.6). The project has been created at the solution level, without the src folder, and global.json isn't added.neither to the solution nor in the folder.
3. click in the asp.net 5 project, open the add reference dialog and see all the projects.
4. the reference is added, and yes, the wrap work is done and the project.json.
5. remove the reference to aspnetcore from the project.json
6. If I check in the solution explorer myLibrary shows a reference to ef 7.0.0-beta3 
![untitled](https://cloud.githubusercontent.com/assets/127777/6532094/4263e978-c43e-11e4-9360-ef950902e62e.png)

7.run the program this way and the program starts.
8. add this rown in the index action of the home controller var db = new TkSoplaLib.AdmModel.adminEntities(); and add a breakpoint at this point, so I can stop before the line is executed.
9.this is the error message

An unhandled exception occurred while processing the request.

FileNotFoundException: Could not load file or assembly 'EntityFramework, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies. The system cannot find the file specified.

TestApplication46.Controllers.HomeController.Index()

this happens before the program reach the breakpoint.

**Comment by lucamorelli** [comment]
Looks like that files create from the kpm wrap command are not added to the solution. The first effect is that the wrap command creates the global.json and the project.son in the wrap directory, but is not visible in the solution manager.
Enabling git source control the files are included in the commit (I have to try with TFVC), so the files are stored, but I don't know if this is good.

**Comment by sayedihashimi** [comment]
Should be working with RC2
