### ISSUE TITLE
Incorrect version number in known-issues.md

### ISSUE THREAD

**Issue by GregoryOtt** [aspnet/Tooling#801]
The version in the documentation ([known-issues.md](https://github.com/aspnet/Tooling/blob/master/known-issues.md)) and the version of the download binary are not the same.

![versioningpb](https://cloud.githubusercontent.com/assets/4428998/19073517/bb5e452a-8a3b-11e6-9021-16df45306ad3.png)

**Comment by markmnl** [comment]
Question is, where can we 003131 ???

**Comment by balachir** [comment]
Thanks for reporting this. We had an issue with the fwlinks being used for multiple things. I've updated known-issues.md now with the correct fwlinks for 003131.

**Comment by shaunluttin** [comment]
In other news, where can we get `"version": "1.0.0-preview2-003133"`? It seems to be jumping up in the `global.json`.

**Comment by GregoryOtt** [comment]
You can find 003133 at: https://go.microsoft.com/fwlink/?LinkID=827524
See known-issues.md history at: https://github.com/aspnet/Tooling/commit/e99bfac2653067381a1d6628cfb1c9c00b013663
