### ISSUE TITLE
Visual Studio Build or Rebuild with dotnet cli --framework specified (not all target frameworks) compilation

### ISSUE THREAD

**Issue by gencebay** [aspnet/Tooling#802]
How can I build or rebuild the solution (asp.net core apps and class libraries with target framework monikers are net46, netcoreapp1.0, netstandard1.6) from Visual Studio 2015 Update 3 like;

------ Rebuild All started: Project: Hosting, Configuration: Debug Any CPU ------
C:\Program Files\dotnet\dotnet.exe build "C:\projects\NetCore\src\Hosting" **--framework net46** --configuration Debug --no-dependencies --no-incremental

instead of

------ Rebuild All started: Project: Hosting, Configuration: Debug Any CPU ------
C:\Program Files\dotnet\dotnet.exe build "C:\projects\NetCore\src\Hosting" --configuration Debug --no-dependencies --no-incremental

I just want to use net46 runtime for now but I want to move as consistent with other

**Comment by mlorbetske** [comment]
Unfortunately, there isn't a way of specifying a subset of the specified (in project.json) target frameworks to build a project for from Visual Studio.

**Comment by gencebay** [comment]
I got it but need to improve compilation time so [encountered CLI performance issue](https://github.com/dotnet/cli/issues/2515)!
