### ISSUE TITLE
Create properties page for managing user secrets

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Tooling#804]
Currently VS tooling opens a raw text editor for "secrets.json" file. It would be nice to have a grid view (like a properties page) for editing.

 cref https://github.com/aspnet/Configuration/issues/514

**Comment by natemcmaster** [comment]
cc @abpiskunov

**Comment by sayedihashimi** [comment]
We are interested on offering this but the team has been busy with the .csproj related work.

**Comment by natemcmaster** [comment]
Yeah, I figured. Consider this a "nice to have" for now. "secrets.json" won't be changing in the near future.

**Comment by mlorbetske** [comment]
TFS Bug#275697

**Comment by natemcmaster** [comment]
Stale. Tracked internally.
