### ISSUE TITLE
Adding a new project to a solution unexpectedly adds the project under the src folder

### ISSUE THREAD

**Issue by danroth27** [aspnet/Tooling#81]
Create a new ASP.NET 5 Web Site
Right click on the solution and select Add -> New Project
Select Class Library (Package) and specify the location as Projects\WebApplication1\**test**

Expected result: 
- The project is created at Projects\WebApplication1\test
- The project is added to the solution under a test solution folder

Actual result: The project is added under the src solution folder
- The project is created at Projects\WebApplication1\test
- The project is added to the solution under the **src** solution folder

![wrong-folder](https://cloud.githubusercontent.com/assets/1874516/7714018/59d159c0-fe30-11e4-9df9-ed4fe6b733ea.png)

**Comment by sayedihashimi** [comment]
TFS:151698
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
We are removing this
