### ISSUE TITLE
unable to create new .net core projects

### ISSUE THREAD

**Issue by mani0070** [aspnet/Tooling#812]
![image](https://cloud.githubusercontent.com/assets/9861392/19377339/7ae0113c-91dd-11e6-8c40-f1e02d650481.png)

followed the instruction in below link it does not work

https://github.com/aspnet/Tooling/blob/master/known-issues.md#missing-sdk

**Comment by shababhussain** [comment]
I am having similar issue. 


C:\Program Files (x86)\Microsoft Visual Studio 14.0>dotnet --version
.NET Command Line Tools (1.0.0-beta-001598)

Product Information:
 Version:     1.0.0-beta-001598
 Commit Sha:  7582649f88

Runtime Environment:
 OS Name:     Windows
 OS Version:  6.3.9600
 OS Platform: Windows
 Runtime Id:  win81-x64

C:\Program Files (x86)\Microsoft Visual Studio 14.0>

**Comment by shababhussain** [comment]
My issue is resolved; wasted days on this. Here is what I did
1. Uninstall all older core sdk runtimes
2. Uninstall Microsoft Dotnet CLI for Windows (1.0.0.001598)
3. Reinstall the tooling and SDK as suggested in post at the top.
4. restart visual studio 

here is the thread that helped me. https://github.com/dotnet/cli/issues/3064

I uninstalled the CLI

**Comment by mani0070** [comment]
Thanks @shababhussain  

I have to do additional steps to get working on mine
1. Uninstall all the core related tools
<img width="479" alt="dotnetcoreerror" src="https://cloud.githubusercontent.com/assets/9861392/19402040/a67ca6b0-9256-11e6-8115-52b396322da8.PNG">
2. Clean up Path Variables and make sure the SDK version is only available path under the dotnet folder as shown below 
![image](https://cloud.githubusercontent.com/assets/9861392/19402073/e3d4a1a2-9256-11e6-83f8-e4eb52961ffd.png)
Restart the PC
Launch Visual studio . all worked

It was a mission to get this working .
