### ISSUE TITLE
Razor editor doesn't treat ~ in URLs as webroot

### ISSUE THREAD

**Issue by bojanrajkovic** [aspnet/Tooling#82]
When editing Razor views, ~ is resolved as the project root instead of the webroot, leading to lots of "path not found" annotations on paths that do actually exist.

**Comment by bojanrajkovic** [comment]
Huh, strange -- it seems to work if I have the `type="text/css"` attribute on `<link`> elements, but breaks without the attribute.

**Comment by sayedihashimi** [comment]
More details from @NotMyself at https://github.com/aspnet/Tooling/issues/114

@barrytang @mayurid @madskristensen is this a known issue?

**Comment by BillHiebert** [comment]
@ToddGrun

**Comment by barrytang** [comment]
@bojanrajkovic, I assume this happens when you run the page? If that's the case, then this is either a runtime issue or something to do with your app. Adding @NTaylorMullen as well.

**Comment by bojanrajkovic** [comment]
No, just in the editor--at runtime, it's fine.

**Comment by barrytang** [comment]
@vkichline, can you work with @bojanrajkovic and try to get a repro locally?

**Comment by barrytang** [comment]
TFS#1208596

**Comment by VanKichline** [comment]
Going bu the example in #114, this has been fixed:
![image](https://cloud.githubusercontent.com/assets/14066157/10147390/906f58fa-65e2-11e5-84eb-94632b8615f3.png)

**Comment by mlorbetske** [comment]
From the linked GitHub & TFS items, this appears to be fixed. If that's not the case, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site
