### ISSUE TITLE
(package.json) Namespaced packages do not display version & details on hover-over

### ISSUE THREAD

**Issue by MarkPieszak** [aspnet/Tooling#829]
(latest) VStudio 2015 Update **3**

![image](https://cloud.githubusercontent.com/assets/2574412/19649471/eadc6be0-99d3-11e6-9d8e-565003f9e2cd.png)

When hovering over Namespaced packages (@whatever/), version numbers and details are labeled as "Uknown".

Also intellisense comes out as "Unknown" as well when typing in the version area to the right.
![image](https://cloud.githubusercontent.com/assets/2574412/19649727/e3f93e56-99d4-11e6-81e8-a89cd21abeee.png)

**Comment by mlorbetske** [comment]
cc @madskristensen

**Comment by mlorbetske** [comment]
TFS Bug#362765

**Comment by MarkPieszak** [comment]
Great news! Thanks @mlorbetske

**Comment by mlorbetske** [comment]
I've just gotten word that this has been fixed for Visual Studio 2017.5
