### ISSUE TITLE
https exception when using UseBrowserLink extension

### ISSUE THREAD

**Issue by Eilon** [aspnet/Tooling#830]
_From @damienbod on October 9, 2016 8:26_

When I start an ASP.NET Core application using HTTPS (develop), I receive to following exception in the browser:

SEC7111: HTTPS security is compromised by http://localhost:28168/2d581390896c4191bba0e7f6b9141a8b/browserLink

The UseBrowserLink extension causes this exception.  Is it possible to use this with HTTPS?

```
if (env.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
    app.UseDatabaseErrorPage();
    // Does not work with HTTPS, browser exception
    //app.UseBrowserLink();
}
```

Greetings Damien

_Copied from original issue: aspnet/Home#1781_

**Comment by Eilon** [comment]
_From @MarcusPozzan on October 21, 2016 18:32_

Having same issue.
using identityserver4 as well - found this thread from their repo.

not sure how to change Browserlink extension to https - it looks like it is supposed to work. AND in previous versions of ASP.NET (4.5) it did work correctly as I have projects that work without incident with browserlink.
according to the documentation: [https://connect.microsoft.com/VisualStudio/feedback/details/808319/browser-link-does-not-work-when-ssl-enabled-is-set-to-true](url)

**Comment by Eilon** [comment]
@jodavis @barrytang

**Comment by TsengSR** [comment]
Any update on this?

**Comment by jodavis** [comment]
In VS 2017 RC, Browser Link should use an https link on pages that are requested by https on ASP.NET Core..
