### ISSUE TITLE
warning in cshtml for <a> taghelper with target attribute

### ISSUE THREAD

**Issue by wjzhou** [aspnet/Tooling#831]
The visual studio show a warning when using <a> taghelper with target attribute.

```
<a target="_blank" asp-action="...">
```

The warning description is: 
Attribute is allowed only when 'href' is present.

**Comment by mlorbetske** [comment]
cc @madskristensen

**Comment by cihadsevim** [comment]
Stilll going on.

**Comment by NTaylorMullen** [comment]
Duplicate of: https://github.com/aspnet/Razor/issues/1428
