### ISSUE TITLE
ASP.NET Core publish fails

### ISSUE THREAD

**Issue by softlion** [aspnet/Tooling#833]
I have this error when publishing:

> An error occurred while generating the publish appsettings file. System.ArgumentException: Invalid object passed in, ':' or '}' expected.

It happens when the file "appsettings.production.json" contains any json comment (lines starting with //).

**Comment by GuardRex** [comment]
Comments are not supported by the JSON spec and not supported in JSON files used by .NET Core. For example, see https://github.com/aspnet/Announcements/issues/24#issue-75734852.

**Comment by softlion** [comment]
Ok. This is crazy as it is supported in the base appsettings.json.

Note that even the json spec does not support it, javascript and all parsers do support it. And spec are there to be evolved. You can not go against the majority.
