### ISSUE TITLE
Refactor adds unneeded using when type is on same namespace.

### ISSUE THREAD

**Issue by Bartmax** [aspnet/Tooling#834]
I minor thing I just found.

When refactor suggests to change a mispelling/typo on some type, if the type lives in the same namespace that your corrent class, an unneeded using is added.

![image](https://cloud.githubusercontent.com/assets/3386797/19780331/0f4fcd6c-9c5b-11e6-8474-f6b06d746a0e.png)

it should suggest the change name only?

**Comment by miloush** [comment]
That's likely Roslyn issue, see https://github.com/dotnet/roslyn/issues/10912

**Comment by Bartmax** [comment]
yeah duped
