### ISSUE TITLE
VisualStudio Update 3 Can't See .Net Core Install

### ISSUE THREAD

**Issue by ShVerni** [aspnet/Tooling#840]
Hello,

After updating to VisualStudio Community to update 3 and the .Net Core Tooling 1.0.1 Preview 2.0.2, and removing the older .Net Core SDKs and Toolings, VisualStudio can't seem to find .Net Core and it can't open any of my ASP.Net solutions. Whenever I try I see this message:
![2](https://cloud.githubusercontent.com/assets/15352177/19913746/c828e07a-a07b-11e6-901f-0b8aa357fb97.PNG)

When I look in the Extensions and Updates portion of VisualStudio I see that .Net Core is not installed:
![one](https://cloud.githubusercontent.com/assets/15352177/19913771/fd5f17fa-a07b-11e6-9eb4-a7e3b52472b5.PNG)

However, I've downloaded and installed .Net Core several times:
![3](https://cloud.githubusercontent.com/assets/15352177/19913782/10e4f100-a07c-11e6-9291-2ea6812b2340.PNG)

I can see the ASP.Net Core templates in VisualStudio:
![4](https://cloud.githubusercontent.com/assets/15352177/19913887/d436c4bc-a07c-11e6-8283-caee9b15400a.PNG)

But when I try to create a new project I get this message:
![5](https://cloud.githubusercontent.com/assets/15352177/19913824/4f7c45d0-a07c-11e6-9309-ccb72a1fce73.PNG)

For reference, the .Net Core SDK is in what I think is the correct place:
![6](https://cloud.githubusercontent.com/assets/15352177/19913829/629a202e-a07c-11e6-957a-ca6afe26cecf.PNG)

I have tried repairing both the Tooling and VisualStudio installations, and uninstalled and reinstalled them as well after trying (probably unsuccessfully) to remove all vestiges of the VisualStudio installation using this tool: https://github.com/Microsoft/VisualStudioUninstaller

I also tried re-setting up the development environment using the `devenv /setup` command. On my other computer the update worked fine and all my projects open without issue. The project I'm working on can be found here: https://github.com/ShVerni/RoboRuckus

Any help on fixing my VisualStudio install would be greatly appreciated.

**Comment by mlorbetske** [comment]
Are you still experiencing this issue?

**Comment by ShVerni** [comment]
Hello,

Sorry for the delay, it's a busy time of year. But yes, I am still having this problem; I even tried updating to .Net Core Tooling 1.0.1 Preview 2.0.3 without success. At this point, I'm feeling like my best hope is to try the VisualStudio 2017 RC.

**Comment by mlorbetske** [comment]
@joeloff any ideas? It seems that the right stuff is marked as installed but the registration is not working correctly and `devenv /setup` didn't help

**Comment by ShVerni** [comment]
I gave up and just moved to VisualStudio 2017 RC, which is working.

**Comment by stevomccormack** [comment]
My PATH variables (unrelated to .NET Core) had errors - which prevented MS Visual Studio from loading .NET Core. Check your PATH environment variables for mistakes - any mistake in my case caused problem. The error was created with TypeScript add-on in Visual Studio. 

See https://www.rapidee.com for environment variable utility program - check for errors.

**Comment by ShVerni** [comment]
Thanks for the tip, if this happen again I'll definitely try that!
