### ISSUE TITLE
Known issues for ASP.NET Core support in Visual Studio 2015 - A new one?

### ISSUE THREAD

**Issue by ericwj** [aspnet/Tooling#854]
After installing both the x86 and the x64 SDK 1.0.0-preview2.1-003155 and opening Visual Studio 2015 for the first time for an existing 1.0.1 preview 2 project, I get the .NET Core SDK Not Found error dialog box as documented here [Known issues for ASP.NET Core support in Visual Studio 2015](https://github.com/aspnet/Tooling/blob/master/known-issues.md#missing-sdk).

The issue seems to be that I have the x86 edition of the preview 2 SDK installed but not the x64 one and installing the x64 edition of the preview 2.1 somehow breaks Visual Studio.

Installing the x64 edition of the preview 2 tooling fixes the issue. I might (didn't test) also have removed the x64 preview 2.1 SDK as for some reason I installed both x64 and x86 of the preview 2.1 SDK.

**Comment by mlorbetske** [comment]
Thanks for pointing this out, it has been added to the list of known issues https://github.com/aspnet/Tooling/blob/master/known-issues-vs2015.md

While this is discussed in the context of a side by side installation with Visual Studio 2017 RC, it applies in your case as well.
