### ISSUE TITLE
Visual Studio 2015 / Framework Switching Bug

### ISSUE THREAD

**Issue by Antaris** [aspnet/Tooling#855]
I seem to be encountering an issue with the Framework switcher in VS2015 for .NET Core projects.

![tooling-framework-switch-issue](https://cloud.githubusercontent.com/assets/255906/20242368/7c077886-a923-11e6-9f7d-d770868228f9.gif)

After changing the framework, I select back into the code editor, and the active framework switches back. This means:-
- I can't easily debug code targeting the other framework
- I can't use Visual Studio's unit test runner to execute unit tests targeting the other framework.

**Comment by mlorbetske** [comment]
Sorry you're running in to this, this is fixed in Visual Studio 2017 RC
