### ISSUE TITLE
Launching IISExpress + WebListener app silently crashes with no error

### ISSUE THREAD

**Issue by natemcmaster** [aspnet/Tooling#856]
IIS and WebListener are incompatible (cref https://github.com/aspnet/AspNetCoreModule/issues/23). When a user attempts to launch a project that that uses this incompatible combination with IIS Express, the app crashes without showing any kind of error.

Only evidence of failure is in the Windows application log.
Event Viewer > Windows Logs > Application
> Process was created with commandline '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\Common7\IDE\Extensions\Microsoft\Web Tools\ProjectSystem\VSIISExeLauncher.exe" -debug -p "C:\Program Files\dotnet\dotnet.exe" -a "C:\Users\namc\Downloads\sockets\bin\Debug\netcoreapp1.1\sockets.dll" -pidFile "C:\Users\namc\AppData\Local\Temp\tmpE6CC.tmp" -wd "C:\Users\namc\Downloads\sockets"' but did not listen on the given port '29729'

**Repro**
Create an ASP.NET Core project an use Microsoft.AspNetCore.Server.WebListener + Microsoft.AspNetCore.Server.IISIntegration
```c#
        public static void Main(string[] args)
        {
            var host = new WebHostBuilder()
                .UseWebListener()
                .UseIISIntegration()
                .UseStartup<Startup>()
                .Build();

            host.Run();
        }
```

**Comment by GuardRex** [comment]
We implicitly state that WebListener will not work with IIS in the Publish to IIS doc; however, an explicit statement either in the body of the doc or in the Common Errors section would probably be wise if the ANCM won't get this functionality any time soon. I'll add this to my upcoming tracking issue for doc changes for 1.1.

cc/ @shirhatti @Rick-Anderson @spboyer

**Comment by natemcmaster** [comment]
Closing as this bug is stale.
