### ISSUE TITLE
Error when adding nuget package dependencies in project.json

### ISSUE THREAD

**Issue by huytnd** [aspnet/Tooling#86]
I'm using VS2015RC, this error window appeared when typing the name of any nuget package, or pressing Ctrl + Spacebar to use Intellisense.
![vs2015rc_intellisense_1](https://cloud.githubusercontent.com/assets/2102905/7887485/a031d5ba-065b-11e5-91e9-0ae38c78c708.jpg)

**Comment by barrytang** [comment]
Opened an internal bug to track - TFS#1179936

**Comment by mlorbetske** [comment]
@huytnd what version of NuGet do you have installed?

**Comment by huytnd** [comment]
This is the version I'm using.
![ver](https://cloud.githubusercontent.com/assets/2102905/8096316/02f1b168-1000-11e5-8dbe-648e06ccb67a.jpg)
I have to downgrade to make it work. After updating to the current version of NPM, I can't use it. I wrote a blog post about it, and someone reported it here.
https://tndhuy.wordpress.com/2015/05/14/solved-nuget-package-management-problem-in-visual-studio-2015-rc/

**Comment by barrytang** [comment]
@mlorbetske fixed it now.
