### ISSUE TITLE
VS 2017 RC breaks VS 2015 Restore packages

### ISSUE THREAD

**Issue by jods4** [aspnet/Tooling#862]
.NET Core in VS 2017 RC is aweful as nothing seems to work but the worse part for me was that it broke my VS 2015, although the .net core SDK is supposed to work side-by-side.

After giving up on 2017, I reverted my projects to its 2015 state, removed the `.vs` folder and added a `global.json` file to indicate that I want to use the `preview-2` SDK.

Yet, when trying to restore packages, VS produces an error. Apparently the generated file inside `.vs` that is passed to `dotnet restore` is invalid (not sure why as I don't know what is expected in there).

I fixed the issue by completely uninstalling VS 2017.

**Comment by StefH** [comment]
Solved by https://github.com/aspnet/Tooling/blob/master/known-issues-vs2017.md#visual-studio-2015-fails-to-restore-nuget-packages-after-install-visual-studio-2017 ?

**Comment by jods4** [comment]
@StefH Thanks for the pointer. 
I guess MS is aware enough so I'll close this issue!

**Comment by Tochikoma** [comment]
I ran in to the same issue @jods4 . I found by installing the NET Core Tools preview 2 for Visual Studio 2015 meant that I didn't have to uninstall VS2017.

https://go.microsoft.com/fwlink/?LinkID=827546

or, can be found on the download list on this page:

https://www.microsoft.com/net/download/core
