### ISSUE TITLE
file grouping has gone in VS2017 RC

### ISSUE THREAD

**Issue by alanpurple** [aspnet/Tooling#871]
in vs 2015,    a.ts, a.js, a.module.ts, a.module.js, a.js.map, a.module.js.map,a.html,a.css were grouped and could be expanded.

that was very useful and nice to see

and it's gone in VS2017 RC, I don't see any possible reason.

**Comment by mlorbetske** [comment]
Sorry for the delay & to shift to a different issue - we're tracking this item as #889. The good news is that we're working on bringing back nesting right now.
