### ISSUE TITLE
No IntelliSense for COM reference assembly

### ISSUE THREAD

**Issue by pzgulyas** [aspnet/Tooling#873]
There is no intellisense for a COM assembly in VS 2017, but interestingly despite of that, it compiles and runs correctly. Also, adding a COM reference using VS 2017 UI adds a wrong line `<COMReference Include="pfcls.dll">` into the following (corrected) block in csproj:
```xml
  <ItemGroup>
    <COMReference Include="pfcls">
      <Guid>{176453F2-6934-4304-8C9D-126D98C1700E}</Guid>
      <VersionMajor>1</VersionMajor>
      <VersionMinor>0</VersionMinor>
      <Lcid>0</Lcid>
      <WrapperTool>tlbimp</WrapperTool>
      <Isolated>False</Isolated>
      <EmbedInteropTypes>True</EmbedInteropTypes>
    </COMReference>
  </ItemGroup>
```
The final dll name becomes Interop.pfcls.dll, so the added name is wrong anyway.

(Just for info: The example above shows a PTC Creo-Pro/Engineer CAD software VB.API interop reference)

**Comment by davidfowl** [comment]
Can you move this to https://github.com/dotnet/roslyn-project-system/issues. Assuming you are building a .NET Core based project?

**Comment by pzgulyas** [comment]
Yes, I am building a .NET Core based project. I will open as issue at the suggested location, thank's for your redirection to the correct location.

**Comment by mlorbetske** [comment]
Closing this one as it's being tracked by the project system
