### ISSUE TITLE
VS 2017 connection to Team Services is impossible with user's disabled regedit privileges

### ISSUE THREAD

**Issue by pzgulyas** [aspnet/Tooling#878]
This scenario is quite common in enterprise environments. The following error message appears:

Access to the registry key 'HKEY_CURRENT_USER\Software\Microsoft\VisualStudio\15.0_da219166\TeamExplorer\Connect\https://username.visualstudio.com/defaultcollection' is denied.

**Comment by mlorbetske** [comment]
TFS Bug#362070

**Comment by kaylangan** [comment]
Like much of Visual Studio, Team Explorer requires permissions to write to HKLM. This behavior is by design.
