### ISSUE TITLE
Not seeing .NET Core templates in VS 2017 RC

### ISSUE THREAD

**Issue by brgrz** [aspnet/Tooling#879]
I'm not seeing the .NET Core folder for Core templates when trying to create New Solution in Visual Studio 2017 Community RC.

I can confirm I installed the .NET Core and Docker workload (Preview) in VS installer.

**Comment by StefH** [comment]
On my system (VS 2015 and VS 2017 installed) I could solve this by reinstalling [.NET Core VS 2015 tooling](https://www.microsoft.com/net/core#windowsvs2015).

**Comment by brgrz** [comment]
Why would I need those? It's not mentioned here https://www.microsoft.com/net/core#windowsvs2017

**Comment by brgrz** [comment]
I've reformatted the VM I use for testing and installed the VS 2017 RC Professional version and the templates are there.

I guess it's an issue with Community version.

**Comment by davelobban** [comment]
I just installed 2017 RC Professional, selected Core and don't see any Core templates. In fact the only C# template of any type I have is "Shared Project"

**Comment by ardalis** [comment]
I'm looking for the Middleware template in Add New Item and it's nowhere to be found (in VS2017 RC). I'm guessing this is related to this issue. It doesn't make sense to me to install VS2015 tooling to add support to VS2017... Can someone confirm that's necessary?

**Comment by mlorbetske** [comment]
@joeloff any ideas?

**Comment by mlorbetske** [comment]
TFS Bug#362764

**Comment by rayc999** [comment]
Just installed VS 2017 Community and no templates. Not even the standard Web application templates, I was hoping to see the templates for .NET Core.

**Comment by barrytang** [comment]
Are you still experiencing this issue with the latest update to VS 2017 RC? You can download it from the following location:

https://www.visualstudio.com/vs/visual-studio-2017-rc/

If it does, could you please go to http://aka.ms/vscollect and send us the setup logs? Thanks!

**Comment by joeloff** [comment]
Logs would be useful. Nothing related to .NET Core is conditioned on the SKU type, but it's possible that something else in the setup engine failed and decided not to install certain packages and the logs will contain entries to show the decisions the engine made for all the packages.

**Comment by joeloff** [comment]
I'd definitely like to see the installation logs @brgrz 

I just did a clean install of the public RC, only selected the .NET Core / Docker preview workload and I'm seeing all the .NET Core templates in VS after install Community 2017 RC

**Comment by brgrz** [comment]
I'll try this again this weekend with the new RC bits that were published today and will let you know how it goes.

**Comment by brgrz** [comment]
This seems to be fixed in the latest RC bits.

**Comment by rodrigorf** [comment]
I had to install the SDK from this [link](https://github.com/dotnet/core/blob/master/release-notes/download-archives/2.0.0-preview2-download.md) and restart my pc, only modifing the VS2017 P3 installation didn't worked for me.

**Comment by joeloff** [comment]
@rodrigorf was this for the 2.0 templates? The 2.0 templates don't currently ship as part of VS and you have to install the SDK to obtain then.

**Comment by brgrz** [comment]
Hahaha, that's a good one, I lost track of .net core versioning.

**Comment by rodrigorf** [comment]
Exactly. I get it, some posts on the internet made me think the 2.0 templates would come together with Preview 3. Thanks @joeloff

**Comment by joeloff** [comment]
@rodrigorf you're welcome. Just curious, were these posts from the official dotnet site or other sources? If it's from the Microsoft sites, we should definitely try to address any ambiguity.

FYI @leecow

**Comment by rodrigorf** [comment]
@joeloff it was not an official site actually, its a independent blog(a famous one in brazil), the line that made me commit the error was like this: "_To build applications using ASP.NET Core 2.0, you need to install Visual Studio 2017 Preview 3._",  but never mentioned any manual SDK install. Its not wrong but incomplete. My bad!
