### ISSUE TITLE
Fail to get packages from myget.org

### ISSUE THREAD

**Issue by huytnd** [aspnet/Tooling#88]
I tried to get 'nightly build' packages from myget.org for my project, but failed. I'm using Vs2015RC.
![vs2015rc_nuget_2](https://cloud.githubusercontent.com/assets/2102905/7897146/2288122c-06fc-11e5-9b79-b4483a9cea2d.jpg)
My config
![vs2015rc_nuget_3](https://cloud.githubusercontent.com/assets/2102905/7897148/3ed40ca6-06fc-11e5-80f1-f55e9b3ef303.jpg)

**Comment by sayedihashimi** [comment]
@huytnd for the same project what is the result when you go to the command line and execute ```dnu restore```?

**Comment by huytnd** [comment]
Yes, failed too.
![vs2015rc_nuget_4](https://cloud.githubusercontent.com/assets/2102905/7898701/5abf62c2-0732-11e5-944b-3d5dd7adbfc4.jpg)

**Comment by sayedihashimi** [comment]
@davidfowl @glennc  thoughts?

@huytnd is the project.json file a valid json file? I noticed in the error screenshot above the error ```Invalid JSON end```

**Comment by huytnd** [comment]
Ok, I checked again, and the problem I met in the first comment is I didn't upgrade to the latest dnx version before declaring the latest dependency packages in project.json file. The problem I got in the second comment was my bad on missing a '}' at the end in project.json file. Now, I got all the packages I need.
