### ISSUE TITLE
commit afb0b1 renamed known-issues.md, but that file is linked from the error box in visual studio

### ISSUE THREAD

**Issue by Zazcallabah** [aspnet/Tooling#882]
The ".NET Core SDK Not Found" error messagebox ends with the text "To download the .NET Core SDK click here.", with a link to https://github.com/aspnet/Tooling/blob/master/known-issues.md#missing-sdk via a redirect from http://go.microsoft.com/fwlink/?LinkId=786989

This commit https://github.com/aspnet/Tooling/commit/afb0b1004f67aa2c601370a1d53c8cff7de1eec8 moved the file, so the link currently results in a 404.

**Comment by balachir** [comment]
I believe this is fixed now. I tried the fwlink http://go.microsoft.com/fwlink/?LinkId=786989 and it correctly takes me to https://github.com/aspnet/Tooling/blob/master/known-issues-vs2015.md#missing-sdk now
