### ISSUE TITLE
Typescript/js files not nested in ASPNETCORE project in VS17RC

### ISSUE THREAD

**Issue by gregoryagu** [aspnet/Tooling#887]
**TypeScript Version:**  2.1.1 

**Visual Studio 2017RC**

**ASPNETCORE Project**

**Expected behavior:**

test.js to be nested under test.ts.

**Actual behavior:**

test.js is at the same level as test.ts.

This works fine in VS15.

**REPRODUCE**

Create new ASPNETCORE project.

Add test.ts file.

Build

View generated test.js and test.js.map in project explorer at the same level as test.ts.

**Comment by aluanhaddad** [comment]
See #889

**Comment by mlorbetske** [comment]
Let's converge on #889 as @aluanhaddad suggested for tracking this
