### ISSUE TITLE
Wrong colorization of comments in Razor files when inline on a tag

### ISSUE THREAD

**Issue by javiercn** [aspnet/Tooling#891]
Repro steps:
Create a Razor file and paste the following contents.

The first comment will be colorized in green, the second one in red and blue.

@*style="list-style:none;list-style-type:none"*@
<ul class="list-inline list-unstyled" @*style="list-style:none;list-style-type:none"*@>

**Comment by javiercn** [comment]
![image](https://cloud.githubusercontent.com/assets/6995051/20949697/a3db530a-bbcf-11e6-8bc5-2098444316ca.png)

**Comment by NTaylorMullen** [comment]
This issue was moved to aspnet/Razor#883
