### ISSUE TITLE
Visual studio should be 64 bit

### ISSUE THREAD

**Issue by alanpurple** [aspnet/Tooling#896]
I write this here because I couldn't find elsewhere.

Many issues related to performance, crash.... everything is difficult because VS is still 32bit process.

It's time to move to the x64 Visual Studio

It's meant for all of us including MS developers.

**Comment by mlorbetske** [comment]
Hi @alanpurple, first off, thanks for taking the time to write, we appreciate it.

For this particular kind of feedback, the "Send Feedback" button in the upper right hand corner of Visual Studio (the "Provide a Suggestion" option on the menu that it opens specifically) will get your thoughts directed to the right people more directly. There's also a User Voice page that's being used to gather the amount of interest in a 64-bit version of Visual Studio & update people of any progress (https://visualstudio.uservoice.com/forums/121579-visual-studio/suggestions/2255687-make-vs-scalable-by-switching-to-64-bit).

More on the decision for 32-bit vs 64-bit for Visual Studio, here's a blog post (granted it's from 2009) discussing why a 64-bit version of VS hadn't been pursued https://blogs.msdn.microsoft.com/ricom/2009/06/10/visual-studio-why-is-there-no-64-bit-version-yet/
