### ISSUE TITLE
error upgrading vs to latest rc

### ISSUE THREAD

**Issue by lucamorelli** [aspnet/Tooling#899]
Hi, I'm trying to update the installation of vs 2015 rc, but the upgrade process fails. If I look in the log file I find 

`[29e8:0012][2016-12-13T14:16:02] Package 'Microsoft.VisualStudio.TypeScript.Sdk.2.1,version=2.1.61130.1' failed to install. MSI: C:\ProgramData\Microsoft\VisualStudio\Packages\Microsoft.VisualStudio.TypeScript.Sdk.2.1,version=2.1.61130.1\TypeScript_SDK.msi, Properties:  REBOOT=ReallySuppress ARPSYSTEMCOMPONENT=1 , Return code: 0, Details: A newer version of TypeScript Power Tool is already installed.
`

**Comment by nil4** [comment]
Same here. I previously installed TypeScript tools v2.1 for VS 2015, and I believe this error may be related.

**Comment by lucamorelli** [comment]
yes, I think so. the odd thing is that even uninstalling typescript 2.1 or the whole **typescript** directory in **microsfot sdks** directory solves the problem

**Comment by RichiCoder1** [comment]
Ditto. I had previously install TypeScript for VS 2015 also. Went through and had to manual find and remove the old power tool, but that fixed it.

**Comment by lucamorelli** [comment]
https://developercommunity.visualstudio.com/content/problem/6881/installation-fails-due-to-typescript-power-tools-a.html

another solution here, just one note: run the commands from cmd, not powershell

**Comment by mlorbetske** [comment]
TFS Bug#362762

**Comment by mlorbetske** [comment]
This should be fixed in the latest update to Visual Studio 2017 RC, please re-open the issue if you're still running in to this
