### ISSUE TITLE
design time host build fails with ImmutableArray<T> error

### ISSUE THREAD

**Issue by swaggerloaf** [aspnet/Tooling#9]
VS2015 CTP6
using latest nightly builds
started getting this msbuild error with latest aspnetvnext nightly builds
any idea on a workaround
If I comment out the DesignTimeHostBuild section I can compile app in VS2015 and it runs ok under k command.

<pre>
Severity	Code	Description	Project	File	Line	Column
Error		The design time host build failed with the following error: This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.	NeoSample	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AspNet\Microsoft.Web.AspNet.targets	135	5
</pre>

<pre>
c:\projects\2015\NeoSample-ASPNET5\src\NeoSample>kvm list

Active Version           Runtime Architecture Location                   Alias
------ -------           ------- ------------ --------                   -----
       1.0.0-beta3       clr     x64          C:\Users\Glenn\.k\runtimes
       1.0.0-beta3       clr     x86          C:\Users\Glenn\.k\runtimes
       1.0.0-beta3       coreclr x64          C:\Users\Glenn\.k\runtimes
       1.0.0-beta3       coreclr x86          C:\Users\Glenn\.k\runtimes
       1.0.0-beta4-11169 clr     x86          C:\Users\Glenn\.k\runtimes
       1.0.0-beta4-11169 coreclr x86          C:\Users\Glenn\.k\runtimes
       1.0.0-beta4-11181 clr     x86          C:\Users\Glenn\.k\runtimes
  *    1.0.0-beta4-11193 clr     x86          C:\Users\Glenn\.k\runtimes default
</pre>

**Comment by sayedihashimi** [comment]
Just so I understand you have VS2015 CTP6 and the latest nightlies of ASP.NET 5 are not working?

I'm guessing that is because we had to make changes in VS to accommodate some runtime change. The problem there is that VS builds are not available to the public.

@billhiebert do you know more about about the code changes?

**Comment by MattGal** [comment]
I hit this same issue today with an internal VS build from 3/2... rolling back to  1.0.0-beta4-11169 was the best workaround I've come up with, but it definitely needs to be understood/addressed

**Comment by davidfowl** [comment]
It's a bug we're working on.

**Comment by davidfowl** [comment]
This is fixed in the latest KRE. `kvm upgrade` and if you have existing projects, change the version in `global.json`.

**Comment by swaggerloaf** [comment]
using 1.0.0-beta4-11203 clr     x86   I no longer receive this error.

<pre>
c:\projects\2015\NeoSample-ASPNET5\src\NeoSample>kvm list

Active Version           Runtime Architecture Location                   Alias
------ -------           ------- ------------ --------                   -----
       1.0.0-beta3       clr     x64          C:\Users\Glenn\.k\runtimes
       1.0.0-beta3       clr     x86          C:\Users\Glenn\.k\runtimes
       1.0.0-beta3       coreclr x64          C:\Users\Glenn\.k\runtimes
       1.0.0-beta3       coreclr x86          C:\Users\Glenn\.k\runtimes
       1.0.0-beta4-11169 clr     x86          C:\Users\Glenn\.k\runtimes
       1.0.0-beta4-11169 coreclr x86          C:\Users\Glenn\.k\runtimes
       1.0.0-beta4-11181 clr     x86          C:\Users\Glenn\.k\runtimes
       1.0.0-beta4-11193 clr     x86          C:\Users\Glenn\.k\runtimes
  *    1.0.0-beta4-11203 clr     x86          C:\Users\Glenn\.k\runtimes default
</pre>

**Comment by sayedihashimi** [comment]
Ok closing
