### ISSUE TITLE
Changing target framework of wrapped csproj breaks errors

### ISSUE THREAD

**Issue by glennc** [aspnet/Tooling#90]
Create a web application and reference a csproj. Change the target framework of the csproj, from 4.5.2 to 4.5 for example. 

After this you will get errors in the error window for any usage of the referenced csproj, but the build will work and building from the command-line will work. I haven't dug into what exactly is causing this, but my assumption is that it is in tooling since the command line appears to work.

**Comment by muratg** [comment]
@ChengTian

**Comment by ChengTian** [comment]
I will have a look at this and check whether we should fix it in Tooling or DNX

**Comment by ChengTian** [comment]
Worked with @PradeepKadubandi to investigate this issue. Looks like the intellisense cannot find proper symbols in this case and that's why VS is showing errors. We can categorize this as a Tooling bug and keep it here.

**Comment by sayedihashimi** [comment]
TFS:149646
I've added this to our internal TFS, we will reply back here soon.

**Comment by sayedihashimi** [comment]
Should be fixed, closing.
