### ISSUE TITLE
Incorrect file name listed for NPM Restore On Save

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#903]
In VS 2017 RC, navigate to **Tools** --> **Options** --> **Projects and Solutions** --> **Web Package Management** --> **Package Restore**, and click the "Restore On Save" option under the "NPM" heading. The option's description appearing at the bottom of the dialog should reference `package.json`, not `packages.json`.

![npmpackagerestore](https://cloud.githubusercontent.com/assets/10702007/21211693/39e78a22-c24b-11e6-8757-24162c0e6983.png)

**Comment by mlorbetske** [comment]
TFS Bug#362036

**Comment by mlorbetske** [comment]
This should be fixed in the next release of Visual Studio 2017
