### ISSUE TITLE
Cookiecutter Recommended Feed URL should use HTTPS

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#904]
In VS 2017 RC, navigate to **Tools** --> **Options** --> **Cookiecutter** --> **General**. Notice that the value of the "Recommended Feed URL" box uses HTTP. This URL should use HTTPS instead.

![feedurl](https://cloud.githubusercontent.com/assets/10702007/21211786/20f2288c-c24c-11e6-8c83-669178cd252c.png)

**Comment by zooba** [comment]
Thanks, that's our issue. You can close it here.
