### ISSUE TITLE
Missing word in description for Enable ESLint option

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#905]
In VS 2017 RC, navigate to **Tools** --> **Options** --> **Text Editor** --> **JavaScript/TypeScript** --> **EsLint**. Click the "Enable ESLint" option, and view the description text at the bottom of the dialog. It's missing the word "for" in between the words "linter" and "JavaScript".

![eslint](https://cloud.githubusercontent.com/assets/10702007/21211906/26797f5c-c24d-11e6-8225-82667bc3a683.png)

**Comment by mlorbetske** [comment]
TFS Bug#362038

**Comment by mlorbetske** [comment]
The fix for this has been checked in and should be included in the next release of Visual Studio 2017
