### ISSUE TITLE
Setup Failed asp.net core 1.0.1 tools preview 2

### ISSUE THREAD

**Issue by mlorbetske** [aspnet/Tooling#910]
Move from https://github.com/dotnet/cli/issues/5073 on behalf of @umarsolehri 

Setup Failed
One or more issues caused the setup to fail.Please fix the issues and then retry setup.
For more information see the log file.
[d.txt](https://github.com/dotnet/cli/files/658886/d.txt)

**Comment by mlorbetske** [comment]
@joeloff can you take a look please?

**Comment by ImGonaRot** [comment]
I'm also getting Setup Failed. 
0x80070490 - Element not found.

[dd_DotNetCoreTools__20161221151851.txt](https://github.com/aspnet/Tooling/files/667311/dd_DotNetCoreTools__20161221151851.txt)

**Comment by umarsolehri** [comment]
https://www.microsoft.com/en-us/download/details.aspx?id=53840
install vc_redist, from above metioned link, my issue solved after this

**Comment by mlorbetske** [comment]
TFS Bug#362761

**Comment by mlorbetske** [comment]
Per our setup team, this is fixed in the latest updates to Visual Studio 2015. For those still impacted by this issue @umarsolehri's solution is the best one as it gets the registry keys that seem to be missing added correctly.
