### ISSUE TITLE
VS2015RC crashed while editing css file

### ISSUE THREAD

**Issue by huytnd** [aspnet/Tooling#92]
When I edited any css file that had at least 1 long line, VS2015RC crashed.
![crash](https://cloud.githubusercontent.com/assets/2102905/8020775/d0157a16-0caf-11e5-8bec-ee7589d65c93.jpg)

**Comment by sayedihashimi** [comment]
@huytnd is this still happening in VS2015 RTM?

**Comment by madskristensen** [comment]
@huytnd Do you have any extensions installed that might extend the CSS editor such as Web Essentials?
