### ISSUE TITLE
The migrated solution picks the wrong csproj file, not the migrated one

### ISSUE THREAD

**Issue by Tragetaschen** [aspnet/Tooling#923]
For my project, I had [forked](https://github.com/Tragetaschen/dbus-sharp) the original dbus-sharp project and added the necessary bits for `project.json`/`xproj` based VS integration. I have now tried to migrate this with the VS 2017 RC based tooling and it's stumbling over that project.

The fork is a submodule within my git repository and `global.json` points to that submodule's `src` folder and my solution points to the `xproj` in the [project's folder](https://github.com/Tragetaschen/dbus-sharp/tree/master/src/Dbus.Sharp).

After automatic migration in VS, there is a new `Dbus.Sharp.csproj` next to the old `xproj` that looks like the other migrated projects. However, the solution now points to the `dbus-daemon.csproj` instead of the migrated project.

When I remove the two "old" `csproj` files before attempting the migration, the solution migrates correctly.

**Comment by mlorbetske** [comment]
@srivatsn any thoughts on this?

**Comment by srivatsn** [comment]
@livarcocc and @333fred

**Comment by 333fred** [comment]
@Tragetaschen, are you using a specific branch? I cloned and looked at master, but it doesn't look like the solution file points to the xproj project files, but is pointing at the csproj files.

**Comment by Tragetaschen** [comment]
As said, that repository is a submodule in my private git repository. I'm referencing the xproj from a solution within that private repository. I'll try to create a public repository here on github with a similar setup and hopefully it shows the problem.

However, my thinking currently goes that it might be a simple 
```csharp
// instead of
Directory.FindFiles("...", "*.csproj").First();
// do
Path.ChangeExtension(Directory.FindFiles("...", "*.xproj").First(), ".csproj");
```

**Comment by Tragetaschen** [comment]
I just tried to reproduce it and couldn't ([Tragetaschen/aspnet-tooling-issue-923](https://github.com/Tragetaschen/aspnet-tooling-issue-923)). It also doesn't reproduce with my main project in the recent RC of Visual Studio 2017.

Yay?
