### ISSUE TITLE
Multiple publishes using msdeploy.exe causes directory repetition until file name is to long and crashes VS.

### ISSUE THREAD

**Issue by Tratcher** [aspnet/Tooling#927]
_From @ewhance on December 23, 2016 17:17_

I'm using Visual Studio Enterprise 2015, version 14.0.25431.01 Update 3 and a .net core project. The SDK does not change the result.

Steps to reproduce:
1. Create new .net core project.
2. Create custom publish target.
3. Default target location.
4. Default settings.
5. Publish.
6. Observe the added directories after the msdeploy execution: '\bin\Release\PublishOutput\'.
7. Publish again.
8. Observe that the msdeploy execution has now created another set of directories inside the first: '\bin\Release\PublishOutput\bin\Release\PublishOutput'
9. Repeat publish until file name becomes to long and crashes VS.

I also have found that even if I manually delete all of the published output as well as the publish profiles, the next publish still results in the same behavior. 

_Copied from original issue: aspnet/Home#1888_

**Comment by mlorbetske** [comment]
@vijayrkn do you know the settings that should be in project.json to prevent bin from being included in publish?

**Comment by vijayrkn** [comment]
I think it can be added to the PublishOptions exclude.  

```
  "publishOptions": {
    "exclude": [
      "bin\**",
      "obj\**",
    ]
  },
```

Even without these, the publish used to work in U3. It would be good to get a repro project to see what is causing the recursive copy. May be some custom pattern in publishOptions include could be causing this.

**Comment by ewhance** [comment]
I am using a new .net core project with all defaults. 

[SecondPublish.txt](https://github.com/aspnet/Tooling/files/685509/SecondPublish.txt)
[project.json.txt](https://github.com/aspnet/Tooling/files/685510/project.json.txt)

**Comment by ewhance** [comment]
The issue is resolved if the pattern "**/*.cshtml" is removed or replaced. I replaced it with "Views".

**Comment by derekpec** [comment]
I'm having the exact same issue (https://github.com/Microsoft/msbuild/issues/2185) and removing/replacing `**/*.cshtml` and/or adding `bin/**` to exclude section in project.json did not, unfortunately, fix it for me.
