### ISSUE TITLE
Unresolved dependency errors go to dnx.targets when clicked

### ISSUE THREAD

**Issue by glennc** [aspnet/Tooling#93]
I have an existing app that I was updating to Beta5. As I was doing this I had a period where some of my dependencies couldn't be resolved. When this happened the errors I had would direct me to the msbuild file instead of the project.json file where I had actually listed the dependency.

**Comment by sayedihashimi** [comment]
@glennc is this still an issue? If so do you have any repro steps?

**Comment by sayedihashimi** [comment]
Closing as no repro
