### ISSUE TITLE
Process remains open after closing VS2017 on csproj folder of a ASP.NET Core app

### ISSUE THREAD

**Issue by damienbod** [aspnet/Tooling#930]
When I start an ASP.NET Core application using IIS Express, and then close VS2017, the folder with the csproj file still has a process using it.

**Comment by mlorbetske** [comment]
TFS Bug#378954

**Comment by barrytang** [comment]
Hi, 

Can you find out what is locking the folder? You can do so by using the Process Monitor tool from Sysinternals:

https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx

Thanks!
Barry

**Comment by damienbod** [comment]
@barrytang thanks for the answer. This has not happened since I updated to RC3.

Thanks Damien
