### ISSUE TITLE
Changing 'Target framework' drop-down adds mysterious folder

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#935]
Using VS 2017 RC (build number 26020.00) on Windows 10, I see a strange folder appear in Solution Explorer when changing the **Target framework** drop-down value to **.NETCoreApp 1.1** in the project properties.

### Steps to Reproduce
1. **File** --> **New** --> **Project** --> **ASP.NET Core Web Application (.NET Core)** --> **Web Application** project template
2. Update all NuGet packages to latest stable versions via the Manage NuGet Packages dialog
3. Right-click project name in Solution Explorer, click **Properties**, change the **Target framework** drop-down value from **.NETCoreApp 1.0** to **.NETCoreApp 1.1**, and save the changes. Notice that the folder highlighted in the screenshot below appears in Solution Explorer:

![new_folder_defect](https://cloud.githubusercontent.com/assets/10702007/21722259/6e31d85c-d3f1-11e6-972e-1d1481f81654.png)

**Comment by D3MaxT** [comment]
If you update the Microsoft.DiaSymReader.Native package to the newer, unreleased (1.5.0-beta2-24728) version, that folder will go away once you close and reopen visual studio.

**Comment by mlorbetske** [comment]
This is fixed in the upcoming release of Visual Studio 2017
