### ISSUE TITLE
launch profiles with command name "Project" crash / don't work in VS 2017

### ISSUE THREAD

**Issue by EricBourland** [aspnet/Tooling#943]
Given this in launchsettings.json
```
"profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "http://localhost:49731",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "console": {
      "commandName": "Project",
      "launchUrl": "http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
```

The first profile will work correctly, the second one will crash when you try to debug the project and give this error in VS2017: 
![image](https://cloud.githubusercontent.com/assets/24632216/21957904/527427a8-da6f-11e6-9dc4-468bfbe9d898.png)

It also fails to attach the javascript debugger.

**Comment by EricBourland** [comment]
I figured out that this is happening because in the project properties window if you set the launch Url, it adds the launchUrl property to the profile, but this is incorrect. Instead it should add an "applicationUrl" property, so your launchsettings.json should look like this:

```
"profiles": {
    "IIS Express": {
      "commandName": "IISExpress",
      "launchBrowser": true,
      "launchUrl": "http://localhost:49731",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    },
    "console": {
      "commandName": "Project",
      "applicationUrl": "http://localhost:5000",
      "environmentVariables": {
        "ASPNETCORE_ENVIRONMENT": "Development"
      }
    }
  }
```

**Comment by mlorbetske** [comment]
TFS Bug#369165

**Comment by barrytang** [comment]
This is fixed in the upcoming update to the VS 2017 RC.
