### ISSUE TITLE
When generating the port for localhost exclude unsafe ports 

### ISSUE THREAD

**Issue by mjjames** [aspnet/Tooling#944]
At present unsafe ports can be generated as part of the application url within launchSettings.json . This then causes unsafe_port_error in chrome.

Ports which can't be used: http://superuser.com/questions/188058/which-ports-are-considered-unsafe-on-chrome

**Comment by mlorbetske** [comment]
TFS Bug#369164

**Comment by BillHiebert** [comment]
This will be fixed for the next tooling update.
