### ISSUE TITLE
Enter key doesn't work at the end of an @taghelper line in _ViewImports file.

### ISSUE THREAD

**Issue by srivatsn** [aspnet/Tooling#945]
_From @MarkMichaelis on January 16, 2017 21:42_

When working in a _ViewImports file, the ENTER key doesn't work at the end of the `@addTagHelper *, Microsoft.AspNetCore.Mvc.TagHelpers` line.

cc: @GrantErickson, @jinujoseph 

_Copied from original issue: dotnet/roslyn-project-system#1194_

**Comment by scottaddie** [comment]
It's worth noting that the ENTER key does work if you first hit the space bar at the end of the line. This seems to take the `@addTagHelper` line out of read-only mode.

**Comment by mlorbetske** [comment]
TFS Bug#369170

**Comment by NickCraver** [comment]
I didn't see this when searching, more info from my dupe here: https://github.com/aspnet/Razor/issues/1045

This is a weird one. The editor basically acts as if the enter key doesn't work immediately following this helper.

VS 2017 Build: 15.0.0+26288.0
Repo: https://github.com/MiniProfiler/dotnet/
File: [samples/Samples.AspNetCore/Views/Shared/_Layout.cshtml](https://github.com/MiniProfiler/dotnet/blob/4270b7fb8756a4284702d6f63069e7089945a428/samples/Samples.AspNetCore/Views/Shared/_Layout.cshtml)

When adding a directive like this (no quotes):
```c#
@addTagHelper *, MiniProfiler.AspNetCore.Mvc
```
If your cursor is at the end of the line right after the `c`, the enter key just doesn't work. It has no effect, no new line is inserted. The key command goes into a black hole of an uncaring cosmos never to return.

#### Workarounds
- Add a space, then hit enter
- Use the quoted form: `@addTagHelper "*, MiniProfiler.AspNetCore.Mvc"`

Apologies if this is a duplicate, I couldn't find anything on it and just came across it today.

**Comment by Roblinde** [comment]
Another workaround:
* just click on the next line. I always "exists" even though it's not always visible. 

It sure is annoying though.

**Comment by alexgav** [comment]
This is fixed. The fix will be in VS 2017 15.5
