### ISSUE TITLE
VS 2017 RC Icons for the ASP.NET Core Web Applications projects are showing as VB

### ISSUE THREAD

**Issue by NickCraver** [aspnet/Tooling#947]
In the VS 2017 RC, the icons in the project creation dialog for the **ASP.NET Core Web Applications** projects are showing as VB. Here's a screenshot:

<img width="989" alt="screen shot 2017-01-17 at 13 33 10" src="https://cloud.githubusercontent.com/assets/454813/22034654/ec613228-dcba-11e6-9dc0-dbbff91b0924.png">

cc @morrisjoe

**Comment by balachir** [comment]
I looked at it on Nick's machine now and it seems to be fixed on his machine, likely after he restarted VS. 

Following templates seemed to have a bad icon cached somewhere. 

![image](https://cloud.githubusercontent.com/assets/8246794/22044067/97344080-dcc7-11e6-8e4b-a71b0bc112dd.png)

**Comment by mlorbetske** [comment]
TFS Bug#369163
