### ISSUE TITLE
VS 2017 RC "Publish wwwroot" option doesn't work

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#949]
Create a new ASP.NET Core 1.1 Web Application targeting .NET Core using the project template in VS 2017 RC3. Create a new publish profile using a **Folder** publish target, right-click the **wwwroot** folder in Solution Explorer, and select the **Publish wwwroot** option from the context menu. The following error occurs:
![publish_wwwroot](https://cloud.githubusercontent.com/assets/10702007/22040600/3722d058-dcb8-11e6-927f-449e7f51d6c7.png)
@mlorbetske

**Comment by mlorbetske** [comment]
@vijayrkn any ideas?

**Comment by mlorbetske** [comment]
TFS Bug#369168

**Comment by mlorbetske** [comment]
This option is only available for Web Deploy based profiles, we'll hide the option from profile types where this action is not supported.
