### ISSUE TITLE
VS 2017 RC icons for the ASP.NET Core Web Application projects are clipped

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#953]
In VS 2017 RC3, go to **File** --> **New** --> **Project**. Select the Templates/Visual C#/Web node, and notice that the icons for the 2 ASP.NET Core project templates are clipped. I only see the very bottom portion of each icon:

![aspnetcore_icons](https://cloud.githubusercontent.com/assets/10702007/22044166/143f772a-dcc8-11e6-89c8-4ae123d937ca.png)

**Comment by mlorbetske** [comment]
@scottaddie does this still happen? If I recall correctly, this happened after doing an upgrade and then was resolved with `devenv /setup`, right?

**Comment by scottaddie** [comment]
@mlorbetske This doesn't happen in the latest version (15.0.26127.3).
