### ISSUE TITLE
Templates targeting .NET Framework should not include "System.Data"

### ISSUE THREAD

**Issue by davkean** [aspnet/Tooling#961]
System.Data is already being referenced by the default set of targets:
https://github.com/dotnet/sdk/blob/08fc30a4a6f7c304096721b5e45f3ba1c7f7b18f/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.BeforeCommon.targets#L82.

This is resulting in VSProject.References returning two System.Data's, one that is resolved and one that is not.

**Comment by mlorbetske** [comment]
This was fixed with https://github.com/aspnet/Templates/pull/796
