### ISSUE TITLE
vs2017 install/repair issue

### ISSUE THREAD

**Issue by jmurphzyo** [aspnet/Tooling#970]
When installing/repairing vs2017 and the users path contains a space the install will fail.

**Comment by mlorbetske** [comment]
TFS Bug#378786

**Comment by mlorbetske** [comment]
@jmurphzyo do you still see this behavior with the latest release of Visual Studio 2017 RC? If so, could you please run the log collection tool http://aka.ms/vscollect to help us further diagnose the issue

**Comment by jmurphzyo** [comment]
@mlorbetske yes the issue is still occurring. I have to log into the account I made just for the vs2017 install to do updates/repairs. If I attempt to do an update on the account with a space in the user path it's corrupting the entire install.

**Comment by mlorbetske** [comment]
For our setup team to properly investigate this, please run the http://aka.ms/vscollect tool, and send the logs to us by uploading to http://aka.ms/dev15logs.

**Comment by jmurphzyo** [comment]
@mlorbetske ok I send them over for you guys.

**Comment by jmurphzyo** [comment]
@mlorbetske Just did an update and it worked. I still haven't tried a fresh install but will close since it worked adding packages.

**Comment by mlorbetske** [comment]
Thanks @jmurphzyo, glad you're unblocked. Just so you know, the setup team is still analyzing the logs you provided to make sure this has been fixed.
