### ISSUE TITLE
Add Publishing to SFTP or rsync for linux

### ISSUE THREAD

**Issue by sayedihashimi** [aspnet/Tooling#98]
We should add support for publishing using SFTP / SSH to the VS publish dialog. This will help users get started with ASP.NET 5 and hosting on linux.

Here is the [proposed walk through](https://github.com/aspnet/Tooling/blob/master/specs/publish-to-linux-from-vs.pdf).

Would love to hear comments, especially those with Linux experience here.

**Comment by nosami** [comment]
This is great news. I tend to use ssh+rsync when deploying to linux. Works a treat :)

**Comment by sayedihashimi** [comment]
@nosami thanks for the comments. I'm investigating whether we should go with sftp or rsync. Did you have a chance to review the [walkthrough](https://dl.dropboxusercontent.com/u/40134810/ProjectK/publish-to-linux-from-vs.pdf)?

**Comment by nosami** [comment]
It shouldn't really be `SFTP/SSH`. It should be `SFTP/SCP` (Secure FTP and Secure CP [copy]). Both of these run over SSH (SSH is a pre-requisite).

`rsync` solves the incremental publish part. It just transfers the binary difference between what's local and what's remote. It can also handle permissions and ownership (whereas SCP can sometimes mess up ownership). It can run either over SSH or not. It should be a 3rd option.

Apart from that though, it looks great!

**Comment by nosami** [comment]
Thinking a bit more about this, I would probably just go with

- SFTP/SSH
- rsync/SSH

You might also want to allow the user to change the port that SSH is running on. It's a fairly common practice to change the port number from the default.

**Comment by davidjdriver** [comment]
The real problem is that there isn't a GOOD SSH/SFTP library in .net. However you decide to do it, you should push it over SSH. The remote before and after scripts are an interesting idea too.

**Comment by sayedihashimi** [comment]
@nosami "You might also want to allow the user to change the port that SSH is running on."

You're absolutely right. I've updated the [walkthrough](https://dl.dropboxusercontent.com/u/40134810/ProjectK/publish-to-linux-from-vs.pdf). Thanks for your input here. I appreciate it.

**Comment by ggrnd0** [comment]
> You might also want to allow the user to change the port that SSH is running on. It's a fairly common practice to change the port number from the default.

This is just childish pranks.

If you going to make good publishing tool you MUST provide fully support for ssh user configs `~/.ssh/config` !

**Comment by nosami** [comment]
I think anyone knowledgable enough to use ~/.ssh/config is unlikely to use this dialog in the first place :)

**Comment by ggrnd0** [comment]
I am not about dialog.
I am about full ssh support in comand line tools.

**Comment by sayedihashimi** [comment]
@ggrnd0 we are not the team that is working on the overall command line support for SSH. In the short term we are likely to use an open source SSH client that works on windows, most likely [OpenSSH](http://www.openssh.com/index.html). In the long term the PowerShell team is working on SSH support and we'll likely switch to use that when it's available. More info on that at http://blogs.msdn.com/b/powershell/archive/2015/06/03/looking-forward-microsoft-support-for-secure-shell-ssh.aspx.

I haven't had a chance to investigate ```rsync``` but it's on my list and we will not start the xplat publish support until that investigation is complete.

>No, it is a bad idea anyway. Especially with sudo.

That was just an example that I put in the mockups, perhaps it was a bad choice.

@ggrnd0 can you expand on why pre/post scripts over ssh is a bad idea?

**Comment by davidjdriver** [comment]
You really can't beat the asp.net guys up for not putting SSH into windows. It isn't their job. Also, if you don't want the pre and post deploy commands, just don't use them or script your own rsync deploy script.

**Comment by sayedihashimi** [comment]
Anyone aware of a good open source `rsync` client for windows?

**Comment by nosami** [comment]
Not open source, but source available from here https://acrosync.com/home.html

**Comment by nosami** [comment]
You could probably get GNU rsync running in conjunction with something like cygwin1.dll too

**Comment by nosami** [comment]
Maybe it is open source after all https://github.com/gilbertchen/acrosync-library ... no idea about that Reciprocal Public License though

**Comment by sayedihashimi** [comment]
Thanks @nosami I think the license for cygwin and acrosync will prohibit us from using those :(

**Comment by nosami** [comment]
Looks like you can purchase a license for acrosync.

**Comment by sayedihashimi** [comment]
@nosami I'm going to look into that but I'm guessing that license would be pretty expensive

**Comment by nosami** [comment]
From [Cygwin's license](https://www.cygwin.com/licensing.html)

"Red Hat permits programs whose sources are distributed under a license that complies with the Open Source Definition [See http://www.opensource.org/docs/osd/ for the precise Open Source Definition and a list of the licenses certified by OSI as conforming to that definition] to be linked with libcygwin.a/cygwin1.dll without libcygwin.a/cygwin1.dll itself causing the resulting program to be covered by the GNU GPL. This means that you can port an Open Source application to Cygwin (TM), and distribute that executable as if it didn't include a copy of libcygwin.a/cygwin1.dll linked into it... Red Hat sells a special Cygwin (TM) License for customers who are unable to provide their application in open source code form."

**Comment by nosami** [comment]
Hmm.. but rsync itself is GPL... so that definitely rules out the cygwin option.

**Comment by sayedihashimi** [comment]
I looked around for a good rsync open source client that works on windows that has a license that would work for us. I haven't found one yet.

For sftp Visual Studio already has a 3rd party component that it has licensed which we can use.

I think that we are going to implement sftp support first and then revisit rsync at a later time. Let me know if that would be a show stopper here.

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231279&fullScreen=false&_a=edit">231279</a>

**Comment by mlorbetske** [comment]
Since the discussion on this thread hasn't been updated in quite a while & we have the TFS issue tracking getting these options added, closing this issue.
