### ISSUE TITLE
VS 2017 RC3 Solution Explorer file nesting not persisting

### ISSUE THREAD

**Issue by srivatsn** [aspnet/Tooling#981]
_From @scottaddie on January 29, 2017 3:32_

Here are the steps to reproduce in VS 2017 RC3 (15.0.26127.0 D15REL):
1. Clone the following repo: https://github.com/scottaddie/TagHelpersDemo. This is an ASP.NET Core MVC project targeting .NET Core.
2. Open the solution in VS, right-click the project in Solution Explorer, and choose **Edit TagHelpersDemo.csproj** from the context menu.
3. Remove the **Compile** node (provided below) from the project file's **ItemGroup**, and save the f
```xml
<Compile Update="Views\Shared\Partials\CardViewModel.cs" DependentUpon="Views\Shared\Partials\_Card.cshtml" />
```
4. Add this **Compile** node back into the **ItemGroup**, and save the file. Notice that the **CardViewModel.cs** file is properly nested beneath **_Card.cshtml** in Solution Explorer.
5. Close the solution, and then reopen it in VS. Notice that the file nesting is no longer present in Solution Explorer.

_Copied from original issue: dotnet/roslyn-project-system#1366_

**Comment by srivatsn** [comment]
_From @abpiskunov on January 30, 2017 17:29_

@lifengl

**Comment by srivatsn** [comment]
The file nesting is implemented in the web tools extension. So moving to the web tools repo.

**Comment by abpiskunov** [comment]
this is either something new in CPS or again same issue with circular nestings , which CPS needs to handle. Circular nesting issue was moved to U1 in CPS. We need to create a separate bug and reference original github issue form core project system

**Comment by lifengl** [comment]
Missed this thread.  DependentUpon should not contain a path, it should contains only the file name inside the same folder.

**Comment by lifengl** [comment]
Also, not sure whether using DependentUpon as an attribute works well at this point.

**Comment by scottaddie** [comment]
@lifengl Is there a more reliable way to use _DependentUpon_ (e.g., as a child node of _Compile_)?

**Comment by lifengl** [comment]
The correct syntax is:
<Compile Update="Views\Shared\Partials\CardViewModel.cs" DependentUpon="_Card.cshtml" />

DependentUpon was interpreted in that folder, and relative/full path is not supported.  Only a file name can be used here.

Some of our logic might remove the rest, and uses the only file name part (which is incorrect, you can change to randomFolder\_card.cshtml but see the same behavior), but some are not .  For the project you provide, the defined behavior is that CardViewModel.cs should not be nested under _Card.cshtml.

**Comment by scottaddie** [comment]
I can confirm that the file nesting works reliably after switching to the `<Compile />` node provided above. I'm hoping that IntelliSense will eventually be provided, so that people know a full path isn't supported for `DependentUpon`.

**Comment by mlorbetske** [comment]
Glad to hear you got it working
