### ISSUE TITLE
VS 2017 RC3 crashes on using update from Solution-wide package management

### ISSUE THREAD

**Issue by glatzert** [aspnet/Tooling#983]
Trying to update packages via the solution-wide nuget package manager, will stop without further notice and keep VS non-responding.

I tried a smaller solution, where the update works, but with a mid-sized one (about 25-30 Projects) the update process will always make VS hang. Single projects will get the update, so if you restart multiple times and try again and again it will eventually work.

**Comment by davkean** [comment]
This issue was moved to NuGet/Home#4474
