### ISSUE TITLE
Cancelling "Browse With.." displays an error

### ISSUE THREAD

**Issue by davkean** [aspnet/Tooling#984]
1. Right-click on wwwroot
2. Click Browse with...
3. Click Cancel

Expected: Nothing I cancelled
Actual:
![image](https://cloud.githubusercontent.com/assets/1103906/22538586/92fa4a30-e967-11e6-9204-d6aa597a995f.png)

**Comment by mlorbetske** [comment]
TFS Bug#378598

**Comment by mlorbetske** [comment]
This has been fixed with CS#1648564
