### ISSUE TITLE
Browser Link Should Support Content Security Policy (CSP)

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Tooling#99]
<a href="http://rehansaeed.com/content-security-policy-for-asp-net-mvc/">Content Security Policy (CSP)</a> is a HTTP header that can be used to stop XSS attacks. You can find an example of an MVC 5 site making use of it using the <a href="https://visualstudiogallery.msdn.microsoft.com/6cf50a48-fc1e-4eaf-9e82-0b2a6705ca7d">ASP.NET MVC Boilerplate</a> project template. Edge will be supporting CSP and Chrome and Firefox already do.

Applying CSP to your site stops Browser link from working. Browser Link uses in-line scripts which are blocked by default in CSP. The scripts need to be moved to a separate file. 

Secondly, it would be nice if Browser Link amended the CSP HTTP header to enable itself to work but failing that we need an API we can call to get the browser link URL, so we can add it to the white-list of allowed content in the CSP header ourselves.

**Comment by BillHiebert** [comment]
@jodavis

**Comment by jodavis** [comment]
Copied to the backlog for Browser Link.

**Comment by sayedihashimi** [comment]
TFS Bug#<a href="https://devdiv.visualstudio.com/DefaultCollection/DevDiv/_workItems#id=231278&fullScreen=false&_a=edit">231278</a>

**Comment by mlorbetske** [comment]
Closing this one as it's been moved to https://developercommunity.visualstudio.com/content/problem/37049/browser-link-should-support-content-security-polic.html
