### ISSUE TITLE
Error	MSB6006	"tsc.exe"

### ISSUE THREAD

**Issue by joniLani** [aspnet/Tooling#996]
i'm trying to compile a simple project using angular 2 an VS but i have this problem

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB6006	"tsc.exe" exited with code 1.	OpenGameListWebApp	C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\TypeScript\Microsoft.TypeScript.targets	214

**Comment by mlorbetske** [comment]
@joniLani is there any additional information on why `tsc` failed in the output window?

**Comment by mlorbetske** [comment]
Closing this since we haven't heard back. If you're still experiencing this, please report the issue on the [developer community](https://developercommunity.visualstudio.com/) site
