### ISSUE TITLE
Manage Bower Packages: Include Prerelease checkbox not filtering

### ISSUE THREAD

**Issue by scottaddie** [aspnet/Tooling#997]
In VS 2017 RC4 (26206.0), create a new ASP.NET Core 1.1 app targeting .NET Core, using the Web Application template. Open the **Manage Bower Packages** dialog, click the **Installed** tab, and click the `bootstrap` package. Notice that the **Include Prerelease** checkbox isn't checked, yet there are prerelease versions of the package listed in the drop-down:

![bower_prerelease](https://cloud.githubusercontent.com/assets/10702007/22914757/03b81878-f238-11e6-9e72-bbe783380574.png)

These are clearly identified as Pre-release in the Bootstrap GitHub repo:

![bootstrap_prerelease](https://cloud.githubusercontent.com/assets/10702007/22914797/49b6acf4-f238-11e6-8dbe-710769ecfde1.png)

**Comment by mlorbetske** [comment]
@scottaddie is this the same as #975?

**Comment by scottaddie** [comment]
That does appear to be the same issue. Feel free to close this one.
